import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:logging/logging.dart';

// Import tables
import 'tables.dart';
import 'dev_agent_tables.dart';
import 'dev_agent_artifact_tables.dart';
import 'daos/ai_finance_dao.dart';
import 'daos/ai_purchase_dao.dart';
import 'daos/card_dao.dart';
import 'daos/search_dao.dart';
import 'daos/voice_call_dao.dart';

// Generated by drift_dev when running `dart run build_runner build`
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Tasks,
    KvStore,
    AgentActivityMessages,
    CardCache,
    SystemActions,
    ClarificationRequests,
    PersonaChatMessages,
    ConversationCaptureCursors,
    SharedLifeEventOperations,
    SharedLifeEntities,
    EntityEmbeddings,
    SharedLifeSummaries,
    UserNotifications,
    SystemMessageQueue,
    AiFinanceLedger,
    AiPurchaseLog,
    VoiceCallSessions,
    VoiceCallMessages,
    DevProjects,
    DevAgentRuns,
    DevAgentEvents,
    DevAgentApprovals,
    DevAgentArtifacts,
  ],
  daos: [CardDao, AiFinanceDao, AiPurchaseDao, VoiceCallDao],
)
class AppDatabase extends _$AppDatabase {
  final Logger _logger = Logger('AppDatabase');

  /// Lazy-initialized SearchDao for FTS5 full-text search.
  late final SearchDao searchDao = SearchDao(this);

  /// Set to true during onUpgrade when FTS tables are first created for an
  /// existing user. [MemexRouter._init] reads and clears this after services
  /// are ready so it can trigger a one-time full rebuild.
  bool _needsFtsRebuild = false;

  /// Whether a full FTS rebuild is needed (set during migration, cleared after rebuild).
  bool get needsFtsRebuild => _needsFtsRebuild;

  /// Clear the FTS rebuild flag after the rebuild has been triggered.
  void clearFtsRebuildFlag() => _needsFtsRebuild = false;

  /// Singleton pattern to ensure one DB connection
  static AppDatabase?
      _instance; // We will treat the current opened DB as singleton for the app lifecycle
  static AppDatabase get instance {
    if (_instance == null) {
      throw Exception(
          'Database not initialized. Call AppDatabase.init(userId) first.');
    }
    return _instance!;
  }

  static bool get isInitialized => _instance != null;

  /// Initialize the database for a specific user
  static Future<void> init(String userId) async {
    if (_instance != null) {
      await _instance!.close();
      _instance = null;
    }

    _instance = AppDatabase._(userId);
    await _instance!._configureConnection();
  }

  /// Private constructor
  AppDatabase._(String userId) : super(_openConnection(userId));

  @visibleForTesting
  static void setTestInstance(AppDatabase database) {
    _instance = database;
  }

  @visibleForTesting
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 29;

  Future<void> _configureConnection() async {
    await customStatement('PRAGMA busy_timeout = 5000');
    await customStatement('PRAGMA journal_mode = WAL');
  }

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
          // Create indices
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_at ON tasks(scheduled_at)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_type_biz_id ON tasks(type, biz_id)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_kv_bucket ON kv_store(bucket)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          await _createClarificationRequestIndices();
          await _createUserNotificationIndices();
          await _createSharedLifeMemoryIndices();
          await _createDevAgentIndices();
          // Create FTS5 virtual tables for full-text search
          await searchDao.createFtsTables();
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {
            await m.createTable(agentActivityMessages);
          }
          // Only add agent_id column if upgrading from version 2 to 3
          // If upgrading from version 1, the table was just created with all columns including agent_id
          if (from == 2 && to >= 3) {
            // Try to add the column, but ignore if it already exists
            try {
              await m.addColumn(
                  agentActivityMessages, agentActivityMessages.agentId);
            } catch (e) {
              // If column already exists (duplicate column error), ignore it
              final errorStr = e.toString().toLowerCase();
              if (errorStr.contains('duplicate column') ||
                  (errorStr.contains('sqlite') &&
                      errorStr.contains('agent_id'))) {
                _logger
                    .info('agent_id column already exists, skipping migration');
              } else {
                // Re-throw if it's a different error
                rethrow;
              }
            }
          }
          if (from < 4) {
            try {
              await m.addColumn(tasks, tasks.dependencies);
            } catch (e) {
              _logger.info(
                  'dependencies column might already exist, skipping: $e');
            }
          }
          if (from < 5) {
            await m.createTable(cardCache);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          }
          if (from < 7) {
            await m.createTable(systemActions);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          }
          if (from < 8) {
            try {
              await customStatement(
                  'ALTER TABLE card_cache DROP COLUMN is_draft');
            } catch (e) {
              _logger
                  .info('is_draft column may not exist or already dropped: $e');
            }
          }
          if (from < 9) {
            await m.createTable(personaChatMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_character ON persona_chat_messages(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_unread ON persona_chat_messages(character_id, is_read)');
          }
          if (from < 10) {
            // Create FTS5 virtual tables for full-text search.
            // Existing users upgrading to v10 need a full FTS rebuild
            // because their data was never indexed. We set a flag here
            // and MemexRouter._init() picks it up after all services are ready.
            await searchDao.createFtsTables();
            _needsFtsRebuild = true;
          }
          if (from < 11) {
            await _createClarificationRequestsTable(m);
          }
          if (from < 12) {
            await m.createTable(userNotifications);
            await _createUserNotificationIndices();
          }
          if (from < 13) {
            // Create FTS5 virtual tables for character world and timeline search.
            await searchDao.createCharacterFtsTables();
          }
          if (from < 14) {
            // Add messageType column to persona_chat_messages.
            try {
              await customStatement(
                  "ALTER TABLE persona_chat_messages ADD COLUMN message_type TEXT NOT NULL DEFAULT 'chat'");
            } catch (e) {
              _logger
                  .info('message_type column may already exist, skipping: $e');
            }
          }
          if (from < 15) {
            await m.createTable(systemMessageQueue);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_message_queue_status '
                'ON system_message_queue(status)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_message_queue_scheduled '
                'ON system_message_queue(scheduled_for)');
          }
          if (from < 16) {
            await m.createTable(aiFinanceLedger);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_finance_ledger_character '
                'ON ai_finance_ledger(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_finance_ledger_recorded_at '
                'ON ai_finance_ledger(recorded_at)');
          }
          if (from < 17) {
            await m.createTable(voiceCallSessions);
            await m.createTable(voiceCallMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_voice_call_sessions_character '
                'ON voice_call_sessions(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_voice_call_messages_session '
                'ON voice_call_messages(session_id)');
          }
          if (from < 18) {
            await m.createTable(aiPurchaseLog);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_purchase_log_character '
                'ON ai_purchase_log(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_purchase_log_created_at '
                'ON ai_purchase_log(created_at)');
          }
          if (from < 19) {
            await m.createTable(conversationCaptureCursors);
            await m.createTable(sharedLifeEventOperations);
            await m.createTable(sharedLifeEntities);
            await _createSharedLifeMemoryIndices();
          }
          if (from < 20) {
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('conversation_capture_baseline_reset_v1', 'pending', "
              "'conversation_capture', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 21) {
            // Add attachmentsJson column to persona_chat_messages.
            try {
              await customStatement(
                  'ALTER TABLE persona_chat_messages ADD COLUMN attachments_json TEXT');
            } catch (e) {
              _logger.info(
                  'attachments_json column may already exist, skipping: $e');
            }
          }
          if (from < 22) {
            // Create FTS5 virtual table for SharedLife entity search.
            await customStatement('''
              CREATE VIRTUAL TABLE IF NOT EXISTS shared_life_fts USING fts5(
                entity_id UNINDEXED,
                title,
                tags,
                summary,
                tokenize='unicode61'
              )
            ''');
            // Schedule a rebuild to backfill existing SharedLife entities.
            _needsFtsRebuild = true;
          }
          if (from < 23) {
            // Evidence model + domain fields on SharedLifeEventOperations
            const opTable = 'shared_life_event_operations';
            await _addColumnIfMissing(
                "$opTable ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'chat_message'");
            await _addColumnIfMissing('$opTable ADD COLUMN source_ref TEXT');
            await _addColumnIfMissing('$opTable ADD COLUMN raw_input TEXT');
            await _addColumnIfMissing(
                "$opTable ADD COLUMN primary_domain TEXT NOT NULL DEFAULT 'general'");
            await _addColumnIfMissing('$opTable ADD COLUMN facets TEXT');

            // Domain + event-time + emotion fields on SharedLifeEntities
            const entTable = 'shared_life_entities';
            await _addColumnIfMissing(
                "$entTable ADD COLUMN primary_domain TEXT NOT NULL DEFAULT 'general'");
            await _addColumnIfMissing('$entTable ADD COLUMN facets TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN occurred_at INTEGER');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN occurred_end_at INTEGER');
            await _addColumnIfMissing('$entTable ADD COLUMN valence REAL');
            await _addColumnIfMissing('$entTable ADD COLUMN arousal REAL');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1');

            // New tables
            await m.createTable(entityEmbeddings);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_entity_embeddings_updated '
                'ON entity_embeddings(updated_at)');
            await m.createTable(sharedLifeSummaries);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_summaries_domain_period '
                'ON shared_life_summaries(domain, period)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_summaries_stale '
                'ON shared_life_summaries(is_stale)');

            // Index for domain + time retrieval on entities
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_domain '
                'ON shared_life_entities(primary_domain, occurred_at)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_occurred '
                'ON shared_life_entities(occurred_at)');
          }
          if (from < 24) {
            // One-time data reset: clear tables contaminated by auto-capture.
            // Character YAML personas and API/LLM settings are preserved.
            // Character memory files (LTM/rolling context) are cleared via a
            // KvStore marker picked up by MemexRouter on next startup.
            await customStatement('DELETE FROM shared_life_entities');
            await customStatement('DELETE FROM shared_life_event_operations');
            await customStatement('DELETE FROM persona_chat_messages');
            await customStatement('DELETE FROM card_cache');
            await customStatement('DELETE FROM conversation_capture_cursors');
            try {
              await customStatement('DELETE FROM shared_life_fts');
            } catch (_) {}
            // Cancel pending capture tasks
            await customStatement(
              "UPDATE tasks SET status='completed', "
              "result='{\"discarded\":\"data_reset_v24\"}' "
              "WHERE type='conversation_capture_task' "
              "AND status IN ('pending','processing','retrying')",
            );
            // Marker for filesystem cleanup (character_memory dir)
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('character_memory_full_reset_v1', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 25) {
            // Marker for filesystem cleanup of Memex workspace directories
            // (Facts, Cards, KnowledgeInsights, PKM). Picked up by MemexRouter.
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('workspace_dirs_reset_v25', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 26) {
            // Schedule feature removed pending memory system rebuild.
            // Clear schedule-related data: system actions, clarification
            // requests, and the outbound message queue.
            await customStatement('DELETE FROM system_actions');
            await customStatement('DELETE FROM clarification_requests');
            await customStatement('DELETE FROM system_message_queue');
          }
          if (from < 27) {
            await _createDevAgentTables(m);
          }
          if (from < 28) {
            await m.createTable(devAgentArtifacts);
            await _createDevAgentArtifactIndices();
          }
          if (from < 29) {
            // Clear _System/memory/ (长期记忆 + 近期记忆 shown in settings).
            // Picked up by MemexRouter._resetSystemMemoryIfNeeded on next startup.
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('system_memory_reset_v29', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
        },
      );

  Future<void> _createClarificationRequestsTable(Migrator m) async {
    try {
      await m.createTable(clarificationRequests);
    } catch (e) {
      if (_isAlreadyExistsError(e, 'clarification_requests')) {
        _logger.info(
            'clarification_requests table already exists, skipping migration');
      } else {
        rethrow;
      }
    }
    await _createClarificationRequestIndices();
  }

  Future<void> _createClarificationRequestIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_status ON clarification_requests(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_fact_id ON clarification_requests(fact_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_dedupe ON clarification_requests(dedupe_key)');
  }

  Future<void> _createUserNotificationIndices() async {
    await customStatement(
        'CREATE UNIQUE INDEX IF NOT EXISTS idx_user_notifications_unique '
        'ON user_notifications(user_id, notification_type, subject_key)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_user_notifications_list '
        'ON user_notifications(user_id, notification_type, updated_at)');
  }

  Future<void> _createSharedLifeMemoryIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_shared_life_operations_entity '
        'ON shared_life_event_operations(entity_id, created_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_updated '
        'ON shared_life_entities(updated_at)');
  }

  Future<void> _createDevAgentTables(Migrator m) async {
    await m.createTable(devProjects);
    await m.createTable(devAgentRuns);
    await m.createTable(devAgentEvents);
    await m.createTable(devAgentApprovals);
    await m.createTable(devAgentArtifacts);
    await _createDevAgentIndices();
    await _createDevAgentArtifactIndices();
  }

  Future<void> _createDevAgentIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_project_status '
        'ON dev_agent_runs(project_id, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_started_at '
        'ON dev_agent_runs(started_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_events_run_ts '
        'ON dev_agent_events(run_id, ts)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_approvals_run_status '
        'ON dev_agent_approvals(run_id, status)');
  }

  Future<void> _createDevAgentArtifactIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_artifacts_run_kind '
        'ON dev_agent_artifacts(run_id, kind)');
  }

  bool _isAlreadyExistsError(Object error, String tableName) {
    final errorStr = error.toString().toLowerCase();
    return errorStr.contains(tableName) &&
        (errorStr.contains('already exists') ||
            errorStr.contains('duplicate table'));
  }

  Future<void> _addColumnIfMissing(String alterFragment) async {
    try {
      await customStatement('ALTER TABLE $alterFragment');
    } catch (e) {
      final msg = e.toString().toLowerCase();
      if (!msg.contains('duplicate column') &&
          !msg.contains('already exists')) {
        rethrow;
      }
    }
  }
}

/// Opens the connection using drift_flutter
QueryExecutor _openConnection(String userId) {
  final dbName = 'memex_local_$userId';

  return driftDatabase(name: dbName);
}
