import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:logging/logging.dart';

// Import tables
import 'tables.dart';
import 'dev_agent_tables.dart';
import 'dev_agent_artifact_tables.dart';
import 'comic_tables.dart';
import 'book_tables.dart';
import 'game_tables.dart';
import '../data/memory_v3/db/tables.dart' as memory_v3;
import 'daos/ai_finance_dao.dart';
import 'daos/ai_purchase_dao.dart';
import 'daos/card_dao.dart';
import 'daos/search_dao.dart';
import 'daos/voice_call_dao.dart';

// Generated by drift_dev when running `dart run build_runner build`
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Tasks,
    KvStore,
    AgentActivityMessages,
    CardCache,
    SystemActions,
    ClarificationRequests,
    PersonaChatMessages,
    SyncOutboxMessages,
    ConversationCaptureCursors,
    SharedLifeEventOperations,
    SharedLifeEntities,
    EntityEmbeddings,
    SharedLifeSummaries,
    UserNotifications,
    SystemMessageQueue,
    AiFinanceLedger,
    AiPurchaseLog,
    VoiceCallSessions,
    VoiceCallMessages,
    DevProjects,
    DevAgentRuns,
    DevAgentSessions,
    DevAgentSessionMessages,
    DevAgentToolBindings,
    DevAgentEvents,
    DevAgentApprovals,
    DevAgentArtifacts,
    // Memory V3 tables — see docs/memory-research/MEMORY_PROPOSAL_V3.md
    memory_v3.MemoryCards,
    memory_v3.MemoryCardSources,
    memory_v3.MemoryCardStructuredFields,
    memory_v3.MemoryCardRelations,
    memory_v3.MemoryCardAssets,
    memory_v3.MemoryFragments,
    memory_v3.MemoryEntities,
    memory_v3.MemoryEntityLinks,
    memory_v3.MemoryEpisodes,
    memory_v3.MemorySagas,
    memory_v3.MemorySagaSnapshots,
    memory_v3.Assets,
    memory_v3.AssetAnalysis,
    memory_v3.UserCorrections,
    memory_v3.MemoryCardOperations,
    memory_v3.MemoryRecallEvents,
    memory_v3.MemoryEmbeddings,
    memory_v3.ProjectMemoryItems,
    memory_v3.ProjectMemorySources,
    // Topic Thread tables — see docs/memory-research/TOPIC_THREAD_DESIGN.md
    memory_v3.TopicThreads,
    memory_v3.TopicThreadSessions,
    // Life Insights + User Rhythms + Growth Pacts — companion proactive care layer
    memory_v3.LifeInsights,
    memory_v3.UserRhythms,
    memory_v3.GrowthPacts,
    memory_v3.GrowthPactChecks,
    // Task Rooms (W5 AI Orchestration) — see docs/companion-first/W5_AI_ORCHESTRATION.md
    memory_v3.TaskRooms,
    memory_v3.TaskArtifacts,
    memory_v3.TaskDecisions,
    // Whiteboard production tables (W6 integration base) — see
    // WHITEBOARD_PARALLEL_DEVELOPMENT_CHARTER.md §2.3
    memory_v3.WhiteboardBoards,
    memory_v3.WhiteboardBoardItems,
    memory_v3.WhiteboardGroups,
    memory_v3.WhiteboardGroupMembers,
    memory_v3.WhiteboardEdges,
    memory_v3.WhiteboardSources,
    memory_v3.WhiteboardSourceVersions,
    memory_v3.WhiteboardCardExtras,
    // Comic co-reading tables — see docs/companion-first/COMIC_CO_READING_PLAN.md
    ComicMangas,
    ComicChapters,
    ComicPageScreenplays,
    ComicReadingProgress,
    ComicSyncCursor,
    // Book co-reading tables
    Books,
    BookChapters,
    BookReadingProgress,
    BookChapterNotes,
    BookAnnotations,
    CoReadingSessions,
    CoReadingSessionMessages,
    // Game tables — see lib/db/game_tables.dart
    GameDefinitions,
    GameSessions,
    GameMessages,
  ],
  daos: [CardDao, AiFinanceDao, AiPurchaseDao, VoiceCallDao],
)
class AppDatabase extends _$AppDatabase {
  final Logger _logger = Logger('AppDatabase');

  /// Lazy-initialized SearchDao for FTS5 full-text search.
  late final SearchDao searchDao = SearchDao(this);

  /// Set to true during onUpgrade when FTS tables are first created for an
  /// existing user. [MemexRouter._init] reads and clears this after services
  /// are ready so it can trigger a one-time full rebuild.
  bool _needsFtsRebuild = false;

  /// Whether a full FTS rebuild is needed (set during migration, cleared after rebuild).
  bool get needsFtsRebuild => _needsFtsRebuild;

  /// Clear the FTS rebuild flag after the rebuild has been triggered.
  void clearFtsRebuildFlag() => _needsFtsRebuild = false;

  /// Singleton pattern to ensure one DB connection
  static AppDatabase?
      _instance; // We will treat the current opened DB as singleton for the app lifecycle
  static AppDatabase get instance {
    if (_instance == null) {
      throw Exception(
          'Database not initialized. Call AppDatabase.init(userId) first.');
    }
    return _instance!;
  }

  static bool get isInitialized => _instance != null;

  /// Initialize the database for a specific user
  static Future<void> init(String userId) async {
    // Serialize concurrent inits for the same user. Startup calls this from
    // both MemexRouter._init and MainScreen's deferred block; without this
    // guard the two would close each other's half-open database mid-migration
    // and can leave the schema in a partial state (see v58 idempotent fix).
    if (_initInFlightUserId == userId && _initInFlight != null) {
      return _initInFlight!;
    }
    final future = _openForUser(userId);
    _initInFlightUserId = userId;
    _initInFlight = future;
    try {
      await future;
    } finally {
      if (identical(_initInFlight, future)) {
        _initInFlight = null;
        _initInFlightUserId = null;
      }
    }
  }

  static Future<void>? _initInFlight;
  static String? _initInFlightUserId;

  static Future<void> _openForUser(String userId) async {
    if (_instance != null) {
      await _instance!.close();
      _instance = null;
    }

    _instance = AppDatabase._(userId);
    await _instance!._configureConnection();
  }

  /// Private constructor
  AppDatabase._(String userId)
      : _testSchemaVersion = null,
        super(_openConnection(userId));

  @visibleForTesting
  static void setTestInstance(AppDatabase database) {
    _instance = database;
  }

  @visibleForTesting
  AppDatabase.forTesting(super.executor) : _testSchemaVersion = null;

  /// Private constructor for testing with custom schema version
  @visibleForTesting
  AppDatabase.private(super.executor, {int? schemaVersion})
      : _testSchemaVersion = schemaVersion;

  final int? _testSchemaVersion;

  @override
  int get schemaVersion => _testSchemaVersion ?? 59;

  Future<void> _configureConnection() async {
    await customStatement('PRAGMA busy_timeout = 5000');
    await customStatement('PRAGMA journal_mode = WAL');
  }

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
          // Create indices
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_at ON tasks(scheduled_at)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_type_biz_id ON tasks(type, biz_id)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_kv_bucket ON kv_store(bucket)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          await _createClarificationRequestIndices();
          await _createUserNotificationIndices();
          await _createSharedLifeMemoryIndices();
          await _createDevAgentIndices();
          await _createDevAgentSessionIndices();
          // Memory V3 indices (tables already created by createAll above)
          await _createMemoryV3Indices();
          // Task Room indices (W5 AI Orchestration)
          await _createTaskRoomIndices();
          // Whiteboard indices (W6 integration base)
          await _createWhiteboardIndices();
          // Comic co-reading indices
          await _createComicIndices();
          await _createCoReadingContinuityIndices();
          await _createBookAnnotationIndices();
          await _createPersonaChatSyncIndices();
          // Game indices
          await _createGameIndices();
          // Create FTS5 virtual tables for full-text search
          await searchDao.createFtsTables();
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {
            await m.createTable(agentActivityMessages);
          }
          // Only add agent_id column if upgrading from version 2 to 3
          // If upgrading from version 1, the table was just created with all columns including agent_id
          if (from == 2 && to >= 3) {
            // Try to add the column, but ignore if it already exists
            try {
              await m.addColumn(
                  agentActivityMessages, agentActivityMessages.agentId);
            } catch (e) {
              // If column already exists (duplicate column error), ignore it
              final errorStr = e.toString().toLowerCase();
              if (errorStr.contains('duplicate column') ||
                  (errorStr.contains('sqlite') &&
                      errorStr.contains('agent_id'))) {
                _logger
                    .info('agent_id column already exists, skipping migration');
              } else {
                // Re-throw if it's a different error
                rethrow;
              }
            }
          }
          if (from < 4) {
            try {
              await m.addColumn(tasks, tasks.dependencies);
            } catch (e) {
              _logger.info(
                  'dependencies column might already exist, skipping: $e');
            }
          }
          if (from < 5) {
            await m.createTable(cardCache);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          }
          if (from < 7) {
            await m.createTable(systemActions);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          }
          if (from < 8) {
            try {
              await customStatement(
                  'ALTER TABLE card_cache DROP COLUMN is_draft');
            } catch (e) {
              _logger
                  .info('is_draft column may not exist or already dropped: $e');
            }
          }
          if (from < 9) {
            await m.createTable(personaChatMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_character ON persona_chat_messages(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_unread ON persona_chat_messages(character_id, is_read)');
          }
          if (from < 10) {
            // Create FTS5 virtual tables for full-text search.
            // Existing users upgrading to v10 need a full FTS rebuild
            // because their data was never indexed. We set a flag here
            // and MemexRouter._init() picks it up after all services are ready.
            await searchDao.createFtsTables();
            _needsFtsRebuild = true;
          }
          if (from < 11) {
            await _createClarificationRequestsTable(m);
          }
          if (from < 12) {
            await m.createTable(userNotifications);
            await _createUserNotificationIndices();
          }
          if (from < 13) {
            // Create FTS5 virtual tables for character world and timeline search.
            await searchDao.createCharacterFtsTables();
          }
          if (from < 14) {
            // Add messageType column to persona_chat_messages.
            try {
              await customStatement(
                  "ALTER TABLE persona_chat_messages ADD COLUMN message_type TEXT NOT NULL DEFAULT 'chat'");
            } catch (e) {
              _logger
                  .info('message_type column may already exist, skipping: $e');
            }
          }
          if (from < 15) {
            await m.createTable(systemMessageQueue);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_message_queue_status '
                'ON system_message_queue(status)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_message_queue_scheduled '
                'ON system_message_queue(scheduled_for)');
          }
          if (from < 16) {
            await m.createTable(aiFinanceLedger);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_finance_ledger_character '
                'ON ai_finance_ledger(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_finance_ledger_recorded_at '
                'ON ai_finance_ledger(recorded_at)');
          }
          if (from < 17) {
            await m.createTable(voiceCallSessions);
            await m.createTable(voiceCallMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_voice_call_sessions_character '
                'ON voice_call_sessions(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_voice_call_messages_session '
                'ON voice_call_messages(session_id)');
          }
          if (from < 18) {
            await m.createTable(aiPurchaseLog);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_purchase_log_character '
                'ON ai_purchase_log(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_ai_purchase_log_created_at '
                'ON ai_purchase_log(created_at)');
          }
          if (from < 19) {
            await m.createTable(conversationCaptureCursors);
            await m.createTable(sharedLifeEventOperations);
            await m.createTable(sharedLifeEntities);
            await _createSharedLifeMemoryIndices();
          }
          if (from < 20) {
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('conversation_capture_baseline_reset_v1', 'pending', "
              "'conversation_capture', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 21) {
            // Add attachmentsJson column to persona_chat_messages.
            try {
              await customStatement(
                  'ALTER TABLE persona_chat_messages ADD COLUMN attachments_json TEXT');
            } catch (e) {
              _logger.info(
                  'attachments_json column may already exist, skipping: $e');
            }
          }
          if (from < 22) {
            // Create FTS5 virtual table for SharedLife entity search.
            await customStatement('''
              CREATE VIRTUAL TABLE IF NOT EXISTS shared_life_fts USING fts5(
                entity_id UNINDEXED,
                title,
                tags,
                summary,
                tokenize='unicode61'
              )
            ''');
            // Schedule a rebuild to backfill existing SharedLife entities.
            _needsFtsRebuild = true;
          }
          if (from < 23) {
            // Evidence model + domain fields on SharedLifeEventOperations
            const opTable = 'shared_life_event_operations';
            await _addColumnIfMissing(
                "$opTable ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'chat_message'");
            await _addColumnIfMissing('$opTable ADD COLUMN source_ref TEXT');
            await _addColumnIfMissing('$opTable ADD COLUMN raw_input TEXT');
            await _addColumnIfMissing(
                "$opTable ADD COLUMN primary_domain TEXT NOT NULL DEFAULT 'general'");
            await _addColumnIfMissing('$opTable ADD COLUMN facets TEXT');

            // Domain + event-time + emotion fields on SharedLifeEntities
            const entTable = 'shared_life_entities';
            await _addColumnIfMissing(
                "$entTable ADD COLUMN primary_domain TEXT NOT NULL DEFAULT 'general'");
            await _addColumnIfMissing('$entTable ADD COLUMN facets TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN occurred_at INTEGER');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN occurred_end_at INTEGER');
            await _addColumnIfMissing('$entTable ADD COLUMN valence REAL');
            await _addColumnIfMissing('$entTable ADD COLUMN arousal REAL');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1');

            // New tables
            await m.createTable(entityEmbeddings);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_entity_embeddings_updated '
                'ON entity_embeddings(updated_at)');
            await m.createTable(sharedLifeSummaries);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_summaries_domain_period '
                'ON shared_life_summaries(domain, period)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_summaries_stale '
                'ON shared_life_summaries(is_stale)');

            // Index for domain + time retrieval on entities
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_domain '
                'ON shared_life_entities(primary_domain, occurred_at)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_occurred '
                'ON shared_life_entities(occurred_at)');
          }
          if (from < 24) {
            // One-time data reset: clear tables contaminated by auto-capture.
            // Character YAML personas and API/LLM settings are preserved.
            // Character memory files (LTM/rolling context) are cleared via a
            // KvStore marker picked up by MemexRouter on next startup.
            await customStatement('DELETE FROM shared_life_entities');
            await customStatement('DELETE FROM shared_life_event_operations');
            await customStatement('DELETE FROM persona_chat_messages');
            await customStatement('DELETE FROM card_cache');
            await customStatement('DELETE FROM conversation_capture_cursors');
            try {
              await customStatement('DELETE FROM shared_life_fts');
            } catch (_) {}
            // Cancel pending capture tasks
            await customStatement(
              "UPDATE tasks SET status='completed', "
              "result='{\"discarded\":\"data_reset_v24\"}' "
              "WHERE type='conversation_capture_task' "
              "AND status IN ('pending','processing','retrying')",
            );
            // Marker for filesystem cleanup (character_memory dir)
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('character_memory_full_reset_v1', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 25) {
            // Marker for filesystem cleanup of Memex workspace directories
            // (Facts, Cards, KnowledgeInsights, PKM). Picked up by MemexRouter.
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('workspace_dirs_reset_v25', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 26) {
            // Schedule feature removed pending memory system rebuild.
            // Clear schedule-related data: system actions, clarification
            // requests, and the outbound message queue.
            await customStatement('DELETE FROM system_actions');
            await customStatement('DELETE FROM clarification_requests');
            await customStatement('DELETE FROM system_message_queue');
          }
          if (from < 27) {
            await _createDevAgentTables(m);
          }
          if (from < 28) {
            await m.createTable(devAgentArtifacts);
            await _createDevAgentArtifactIndices();
          }
          if (from < 29) {
            // Clear _System/memory/ (长期记忆 + 近期记忆 shown in settings).
            // Picked up by MemexRouter._resetSystemMemoryIfNeeded on next startup.
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('system_memory_reset_v29', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 30) {
            // Second full memory reset: clear any SharedLife data and character
            // memory files that accumulated after the v24 reset (e.g. from
            // CharacterContextCompressor checkpoint writes or stale AI tool calls).
            await customStatement('DELETE FROM shared_life_entities');
            await customStatement('DELETE FROM shared_life_event_operations');
            try {
              await customStatement('DELETE FROM shared_life_fts');
            } catch (_) {}
            // Re-issue filesystem reset markers so MemexRouter clears the dirs
            // again on next startup.
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('character_memory_full_reset_v1', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('system_memory_reset_v29', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 31) {
            // Third reset: clear records auto-generated before LifeMemoryCreate
            // trigger-phrase guard was added. Character memory also re-cleared.
            await customStatement('DELETE FROM shared_life_entities');
            await customStatement('DELETE FROM shared_life_event_operations');
            try {
              await customStatement('DELETE FROM shared_life_fts');
            } catch (_) {}
            await customStatement(
              "INSERT OR REPLACE INTO kv_store(key, value, bucket, updated_at) "
              "VALUES ('character_memory_full_reset_v1', 'pending', "
              "'data_reset', CAST(strftime('%s', 'now') AS INTEGER))",
            );
          }
          if (from < 32) {
            // Memory Card v1: add presentationJson column on SharedLifeEntities.
            try {
              await customStatement(
                  'ALTER TABLE shared_life_entities ADD COLUMN presentation_json TEXT');
            } catch (e) {
              _logger.info(
                  'presentation_json column may already exist, skipping: $e');
            }
          }
          if (from < 33) {
            await _addColumnIfMissing(
                'dev_agent_runs ADD COLUMN dev_session_id TEXT');
            await _createDevAgentSessionTables(m);
          }
          if (from < 34) {
            // Memory Card v2: emotion-coord confidence/evidence/override
            // plus the time-inference fields that were already declared as
            // reserved patch fields but had nowhere to land.
            const entTable = 'shared_life_entities';
            await _addColumnIfMissing(
                '$entTable ADD COLUMN emotion_confidence REAL');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN emotion_evidence TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN emotion_override TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN time_confidence REAL');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN time_source_text TEXT');
          }
          if (from < 35) {
            // Memory Card v3: place + droplet label.
            const entTable = 'shared_life_entities';
            await _addColumnIfMissing('$entTable ADD COLUMN place_name TEXT');
            await _addColumnIfMissing('$entTable ADD COLUMN place_lat REAL');
            await _addColumnIfMissing('$entTable ADD COLUMN place_lng REAL');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN droplet_label TEXT');
          }
          if (from < 36) {
            // Memory Card v4: source excerpts + structured fields +
            // soft related-memory references.
            const entTable = 'shared_life_entities';
            await _addColumnIfMissing(
                '$entTable ADD COLUMN source_excerpts TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN structured_fields TEXT');
            await _addColumnIfMissing(
                '$entTable ADD COLUMN related_memory_ids TEXT');
          }
          if (from < 37) {
            // Memory V3: new table family (memory_cards / Dreaming / Asset / 等)
            // See docs/memory-research/MEMORY_PROPOSAL_V3.md
            await _createMemoryV3Tables(m);
            // Ensure memory_v3_fts exists — createFtsTables is idempotent (IF NOT EXISTS)
            await searchDao.createFtsTables();
          }
          if (from < 38) {
            // Patch: ensure memory_v3_fts exists for installs that upgraded to
            // v37 before createFtsTables was included in that migration step.
            await searchDao.createFtsTables();
          }
          if (from < 40) {
            // Dreaming recall FTS5: index memory_episodes.narrative /
            // memory_fragments.content so queryRecentDreamingContext can rank
            // by bm25 instead of hand-rolled bigram scoring.
            // createFtsTables is idempotent (IF NOT EXISTS) and covers the new
            // memory_episodes_fts / memory_fragments_fts tables added in v40.
            await searchDao.createFtsTables();
            // Backfill is scheduled by DreamingOrchestratorServiceV3.init on
            // next startup — the migration itself has no access to tokenizers.
          }
          if (from < 41) {
            await _addColumnIfMissing(
              "memory_fragments ADD COLUMN event_time INTEGER",
            );
            // Backfill is done by DreamingOrchestratorServiceV3.init on next
            // startup — it resolves sourceMessageIds → min(timestamp).
          }
          if (from < 42) {
            await m.createTable(projectMemoryItems);
            await m.createTable(projectMemorySources);
            await _createProjectMemoryIndices();
            await searchDao.createFtsTables();
          }
          if (from < 43) {
            // Dev Room model switch: project default + session override + run
            // resolved model. All three columns are nullable; existing rows
            // keep NULL and the app falls back to opencode.jsonc / env.
            await _addColumnIfMissing(
              'dev_projects ADD COLUMN default_opencode_model TEXT',
            );
            await _addColumnIfMissing(
              'dev_agent_sessions ADD COLUMN default_model TEXT',
            );
            await _addColumnIfMissing(
              'dev_agent_runs ADD COLUMN model TEXT',
            );
          }
          if (from < 44) {
            // AiFinance transfer support: direction on transfer rows.
            //
            // This ALTER was originally appended to the v43 migration block in
            // commit 89b02f84 (2026-07-21), but v43 was already published and
            // applied to devices by commit 73041e19 (2026-07-20) — which only
            // added the dev-room model columns. Devices that had already
            // upgraded to v43 therefore never re-ran `if (from < 43)` and the
            // transfer_direction column was never created, causing every
            // card→ledger bridge INSERT to throw "no column named
            // transfer_direction". Bumping to v44 and moving the ALTER here
            // forces the column onto all upgraded devices. A defensive
            // `beforeOpen` check also backfills the column if it is still
            // missing for any reason (see the beforeOpen hook below).
            await _addColumnIfMissing(
              "ai_finance_ledger ADD COLUMN transfer_direction TEXT",
            );
          }
          if (from < 45) {
            // Comic co-reading: 5 new tables for manga library, chapters,
            // page screenplays, reading progress, and sync cursor.
            // See docs/companion-first/COMIC_CO_READING_PLAN.md
            await m.createTable(comicMangas);
            await m.createTable(comicChapters);
            await m.createTable(comicPageScreenplays);
            await m.createTable(comicReadingProgress);
            await m.createTable(comicSyncCursor);
            await _createComicIndices();
          }
          if (from < 46) {
            // Add commentsJson column to comic_chapters for reader comments
            await m.addColumn(comicChapters, comicChapters.commentsJson);
          }
          if (from < 47) {
            // Book co-reading: 4 new tables
            await m.createTable(books);
            await m.createTable(bookChapters);
            await m.createTable(bookReadingProgress);
            await m.createTable(bookChapterNotes);
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_book_chapters_book '
              'ON book_chapters (book_id, number)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_book_notes_book '
              'ON book_chapter_notes (book_id, chapter_number)',
            );
          }
          if (from < 48) {
            // Topic Thread: long-running topic tracking (Memory V3 facet 6).
            // See docs/memory-research/TOPIC_THREAD_DESIGN.md
            await m.createTable(topicThreads);
            await m.createTable(topicThreadSessions);
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_topic_threads_status '
              'ON topic_threads(status)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_topic_threads_last_discussed '
              'ON topic_threads(last_discussed_at)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_topic_thread_sessions_thread '
              'ON topic_thread_sessions(thread_id, occurred_at)',
            );
          }
          if (from < 49) {
            // Reading Intent: link books/manga to Topic Threads for co-reading routing.
            await _addColumnIfMissing(
              "books ADD COLUMN intents_json TEXT NOT NULL DEFAULT '[]'",
            );
            await _addColumnIfMissing(
              "comic_mangas ADD COLUMN intents_json TEXT NOT NULL DEFAULT '[]'",
            );
          }
          if (from < 50) {
            // Game feature: generic game definitions (character cards, scenarios, etc.)
            // and isolated game sessions. Completely isolated from companion memory —
            // GameMessages is never joined with PersonaChatMessages or SharedLife tables.
            await m.createTable(gameDefinitions);
            await m.createTable(gameSessions);
            await m.createTable(gameMessages);
            await _createGameIndices();
          }
          if (from < 51) {
            // Life Insights + User Rhythms + Growth Pacts — companion proactive
            // care layer. See lib/data/memory_v3/db/tables.dart sections 六/七/八.
            await m.createTable(lifeInsights);
            await m.createTable(userRhythms);
            await m.createTable(growthPacts);
            await m.createTable(growthPactChecks);
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_life_insights_domain_type_period '
              'ON life_insights(domain, insight_type, period, period_start)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_life_insights_updated '
              'ON life_insights(updated_at)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_user_rhythms_kind_valid '
              'ON user_rhythms(kind, valid_until)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_growth_pacts_status '
              'ON growth_pacts(status)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_growth_pacts_domain '
              'ON growth_pacts(domain, status)',
            );
            await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_growth_pact_checks_pact_time '
              'ON growth_pact_checks(pact_id, checked_at)',
            );
          }
          if (from < 39) {
            await _addColumnIfMissing(
              "memory_episodes ADD COLUMN topic_id TEXT NOT NULL DEFAULT '__ungrouped__'",
            );
            await customStatement(
              "INSERT OR IGNORE INTO memory_entities("
              "id, name, category, status, relationship_to_user, "
              "fragment_count, generated_by_version, user_corrected, "
              "schema_version"
              ") VALUES ("
              "'user_self', 'user_self', 'self', 'seed', 'self', "
              "0, 'migration.v39', 0, 1"
              ")",
            );
            await customStatement(
              "UPDATE memory_episodes "
              "SET topic_id = primary_entity_id "
              "WHERE topic_id = '__ungrouped__'",
            );
            await customStatement(
              "UPDATE memory_episodes "
              "SET primary_entity_id = 'user_self' "
              "WHERE primary_entity_id NOT IN ("
              "SELECT id FROM memory_entities"
              ")",
            );
          }
          if (from < 52) {
            // user_rhythms.exceptions_json — one-off cancellations
            // ("今天这节课不上了"), JSON array of yyyy-MM-dd dates.
            await _addColumnIfMissing(
              'user_rhythms ADD COLUMN exceptions_json TEXT',
            );
          }
          if (from < 53) {
            // Durable co-reading discussion boundaries. These soft-link the
            // shared chat messages to the exact book/manga chapter that
            // produced them, so later Topic Thread cleanup cannot absorb
            // unrelated companion chat.
            await m.createTable(coReadingSessions);
            await m.createTable(coReadingSessionMessages);
            await _createCoReadingContinuityIndices();
          }
          if (from < 54) {
            await m.createTable(bookAnnotations);
            await _createBookAnnotationIndices();
          }
          if (from < 55) {
            await _addColumnIfMissing(
              'persona_chat_messages ADD COLUMN sync_id TEXT',
            );
            await _addColumnIfMissing(
              'persona_chat_messages ADD COLUMN origin_device_id TEXT',
            );

            // Existing installations have one authoritative history at the
            // moment this migration lands. Give those rows deterministic IDs
            // without disturbing the local integer IDs still referenced by
            // Dreaming and co-reading. New writes use UUIDs in
            // PersonaChatService. Pre-v55 histories from multiple devices are
            // intentionally not auto-merged; one is selected as the initial
            // authority before incremental sync is enabled.
            await customStatement(
              "UPDATE persona_chat_messages "
              "SET sync_id = 'legacy-v55:' || id "
              "WHERE sync_id IS NULL OR sync_id = ''",
            );
            await customStatement(
              "UPDATE persona_chat_messages "
              "SET origin_device_id = 'legacy-authority' "
              "WHERE origin_device_id IS NULL OR origin_device_id = ''",
            );
            await _createPersonaChatSyncIndices();
          }
          if (from < 56) {
            // Phase 0 (CORE_SYNC_DATA_INVENTORY §7): give the four
            // message-evidence stores a stable cross-device reference column
            // alongside their legacy local int IDs. v55 already gave every
            // persona_chat_messages row a sync_id, so we backfill the new
            // columns from that mapping now. Per-domain dual-write and
            // read-prefers-stable land in follow-up commits; this step only
            // adds columns, backfills history and creates lookup indices.
            //
            // Each step is table-guarded: minimal/hand-built test databases
            // and any partial real install may not carry every table yet.
            await _addColumnIfTableExists(
              'shared_life_event_operations', 'source_sync_ids TEXT');
            await _addColumnIfTableExists(
              'memory_fragments', 'source_sync_ids TEXT');
            await _addColumnIfTableExists(
              'memory_recall_events', 'chat_message_sync_id TEXT');
            await _addColumnIfTableExists(
              'co_reading_session_messages', 'message_sync_id TEXT');
            await _addColumnIfTableExists(
              'memory_card_sources', 'source_sync_id TEXT');
            await _backfillStableMessageRefs();
            await _createStableMessageRefIndices();
          }
          if (from < 57) {
            // Phase 1 client side (CORE_API_V0): durable outbox for user chat
            // messages waiting to be submitted to the authority core. Written
            // in the same transaction as the chat row by PersonaChatService;
            // rows are removed once the core accepts the sync_id.
            await m.createTable(syncOutboxMessages);
            await _createSyncOutboxIndices();
          }
          if (from < 58) {
            // W5 AI Orchestration: Task Rooms + Artifacts + Decisions
            // See docs/companion-first/W5_AI_ORCHESTRATION.md
            //
            // Idempotent upgrade: a concurrent/interrupted v57→v58 upgrade can
            // leave the three tables created but the column or indices missing
            // while user_version still reports 57. Tolerate that by skipping
            // existing tables instead of failing on "already exists".
            await _createTableIfMissing(m, taskRooms, 'task_rooms');
            await _createTableIfMissing(m, taskArtifacts, 'task_artifacts');
            await _createTableIfMissing(m, taskDecisions, 'task_decisions');

            // Add taskRoomId to PersonaChatMessages BEFORE creating index
            await _addColumnIfMissing(
              'persona_chat_messages ADD COLUMN task_room_id TEXT',
            );

            // Now create indices (after column exists)
            await _createTaskRoomIndices();
          }
          if (from < 59) {
            // W6 integration base: whiteboard production table family.
            // See WHITEBOARD_PARALLEL_DEVELOPMENT_CHARTER.md §2.3 and
            // lib/data/memory_v3/db/tables.dart section 十.
            //
            // Idempotent like v58: an interrupted upgrade must not leave the
            // DB half-migrated. Fields first, indices after.
            await _createTableIfMissing(m, whiteboardBoards, 'whiteboard_boards');
            await _createTableIfMissing(
                m, whiteboardBoardItems, 'whiteboard_board_items');
            await _createTableIfMissing(
                m, whiteboardGroups, 'whiteboard_groups');
            await _createTableIfMissing(
                m, whiteboardGroupMembers, 'whiteboard_group_members');
            await _createTableIfMissing(m, whiteboardEdges, 'whiteboard_edges');
            await _createTableIfMissing(
                m, whiteboardSources, 'whiteboard_sources');
            await _createTableIfMissing(
                m, whiteboardSourceVersions, 'whiteboard_source_versions');
            await _createTableIfMissing(
                m, whiteboardCardExtras, 'whiteboard_card_extras');
            await _createWhiteboardIndices();
          }
        },
        beforeOpen: (OpeningDetails details) async {
          // Defensive backfill: some devices upgraded to v43 via the earlier
          // commit 73041e19 (which only added dev-room model columns) and
          // therefore never received the transfer_direction column that was
          // later appended to the same `if (from < 43)` block by 89b02d84.
          // The v44 migration should fix new upgrades, but this hook also
          // repairs already-broken databases on the next open — regardless
          // of their user_version — so existing installs self-heal without
          // needing a wipe/reinstall.
          try {
            final cols = await customSelect(
              'PRAGMA table_info(ai_finance_ledger)',
            ).get();
            final hasCol = cols.any((row) {
              final name = row.read<String>('name');
              return name == 'transfer_direction';
            });
            if (!hasCol) {
              await customStatement(
                'ALTER TABLE ai_finance_ledger ADD COLUMN transfer_direction TEXT',
              );
              _logger.info(
                  'beforeOpen: backfilled missing ai_finance_ledger.transfer_direction column');
            }
          } catch (e) {
            // Table may not exist on very old schemas; ignore — the v44
            // migration / createAll handles fresh table creation.
            _logger.warning('beforeOpen: transfer_direction backfill skipped: $e');
          }
        },
      );

  Future<void> _createMemoryV3Tables(Migrator m) async {
    // 用户确认资料层
    await m.createTable(memoryCards);
    await m.createTable(memoryCardSources);
    await m.createTable(memoryCardStructuredFields);
    await m.createTable(memoryCardRelations);
    await m.createTable(memoryCardAssets);
    // Dreaming 自动产物层
    await m.createTable(memoryFragments);
    await m.createTable(memoryEntities);
    await m.createTable(memoryEntityLinks);
    await m.createTable(memoryEpisodes);
    await m.createTable(memorySagas);
    await m.createTable(memorySagaSnapshots);
    // 原始资料与审计层
    await m.createTable(assets);
    await m.createTable(assetAnalysis);
    await m.createTable(userCorrections);
    await m.createTable(memoryCardOperations);
    // 索引 / 召回辅助
    await m.createTable(memoryRecallEvents);
    await m.createTable(memoryEmbeddings);
    await m.createTable(projectMemoryItems);
    await m.createTable(projectMemorySources);

    // Topic Thread tables
    await m.createTable(topicThreads);
    await m.createTable(topicThreadSessions);

    await _createMemoryV3Indices();
  }

  Future<void> _createMemoryV3Indices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_cards_scope_type '
        'ON memory_cards(memory_scope, type)');
    await customStatement('CREATE INDEX IF NOT EXISTS idx_memory_cards_updated '
        'ON memory_cards(updated_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_card_sources_kind '
        'ON memory_card_sources(source_kind)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_fragments_status '
        'ON memory_fragments(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_entities_status_category '
        'ON memory_entities(status, category)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_entity_links_entity '
        'ON memory_entity_links(entity_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_entity_links_source '
        'ON memory_entity_links(source_table, source_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_episodes_entity_status '
        'ON memory_episodes(primary_entity_id, status)');
    await customStatement('CREATE INDEX IF NOT EXISTS idx_memory_sagas_status '
        'ON memory_sagas(status)');
    await customStatement('CREATE INDEX IF NOT EXISTS idx_assets_type_created '
        'ON assets(asset_type, created_at)');
    await customStatement('CREATE INDEX IF NOT EXISTS idx_asset_analysis_asset '
        'ON asset_analysis(asset_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_user_corrections_target '
        'ON user_corrections(target_table, target_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_card_operations_card '
        'ON memory_card_operations(card_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_recall_events_target '
        'ON memory_recall_events(target_table, target_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_embeddings_updated '
        'ON memory_embeddings(updated_at)');
    await _createProjectMemoryIndices();
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_topic_threads_status '
        'ON topic_threads(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_topic_threads_last_discussed '
        'ON topic_threads(last_discussed_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_topic_thread_sessions_thread '
        'ON topic_thread_sessions(thread_id, occurred_at)');
  }

  Future<void> _createProjectMemoryIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_project_memory_project_status_time '
        'ON project_memory_items(project_id, status, occurred_at DESC)');
    await customStatement(
        'CREATE UNIQUE INDEX IF NOT EXISTS idx_project_memory_source_event '
        'ON project_memory_sources(source_event_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_project_memory_sources_item '
        'ON project_memory_sources(item_id)');
  }

  Future<void> _createComicIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_comic_chapters_manga_status '
        'ON comic_chapters(manga_id, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_comic_chapters_number '
        'ON comic_chapters(manga_id, chapter_number)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_comic_screenplay_chapter_page '
        'ON comic_page_screenplays(chapter_id, page_num)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_comic_mangas_status '
        'ON comic_mangas(status)');
  }

  Future<void> _createCoReadingContinuityIndices() async {
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_co_reading_sessions_work_status '
      'ON co_reading_sessions(work_type, work_id, status, started_at)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_co_reading_session_messages_session '
      'ON co_reading_session_messages(session_id, message_id)',
    );
  }

  Future<void> _createBookAnnotationIndices() async {
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_book_annotations_location '
      'ON book_annotations(book_id, chapter_number, start_offset)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_book_annotations_active '
      'ON book_annotations(book_id, deleted_at)',
    );
  }

  Future<void> _createPersonaChatSyncIndices() async {
    await customStatement(
      'CREATE UNIQUE INDEX IF NOT EXISTS idx_persona_chat_sync_id '
      'ON persona_chat_messages(sync_id) WHERE sync_id IS NOT NULL',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_persona_chat_origin_device '
      'ON persona_chat_messages(origin_device_id)',
    );
  }

  /// Backfills the v56 stable-reference columns from the integer IDs already
  /// stored alongside them, by joining through `persona_chat_messages.sync_id`.
  ///
  /// All four columns are nullable and start empty for new writes; this only
  /// repairs rows that predate dual-write. It is idempotent: rows already
  /// carrying a stable ref are left untouched.
  Future<void> _backfillStableMessageRefs() async {
    final idToSync = await _loadChatIdToSyncMap();
    if (idToSync.isEmpty) return;

    await _backfillJsonArrayRefs(
      table: 'shared_life_event_operations',
      idColumn: 'source_message_ids',
      syncColumn: 'source_sync_ids',
      idToSync: idToSync,
    );
    await _backfillJsonArrayRefs(
      table: 'memory_fragments',
      idColumn: 'source_message_ids',
      syncColumn: 'source_sync_ids',
      idToSync: idToSync,
    );
    await _backfillSingleIntRef(
      table: 'memory_recall_events',
      idColumn: 'chat_message_id',
      syncColumn: 'chat_message_sync_id',
      idToSync: idToSync,
    );
    await _backfillSingleIntRef(
      table: 'co_reading_session_messages',
      idColumn: 'message_id',
      syncColumn: 'message_sync_id',
      idToSync: idToSync,
    );
    await _backfillSingleIntRef(
      table: 'memory_card_sources',
      idColumn: 'source_ref',
      syncColumn: 'source_sync_id',
      idToSync: idToSync,
    );
  }

  Future<Map<int, String>> _loadChatIdToSyncMap() async {
    if (!await _tableExists('persona_chat_messages')) return const {};
    final rows = await customSelect(
      'SELECT id, sync_id FROM persona_chat_messages '
      "WHERE sync_id IS NOT NULL AND sync_id != ''",
    ).get();
    return {
      for (final row in rows) row.read<int>('id'): row.read<String>('sync_id'),
    };
  }

  Future<void> _backfillJsonArrayRefs({
    required String table,
    required String idColumn,
    required String syncColumn,
    required Map<int, String> idToSync,
  }) async {
    if (!await _tableExists(table)) return;
    final rows = await customSelect(
      'SELECT rowid, $idColumn AS ids FROM $table '
      "WHERE ($syncColumn IS NULL OR $syncColumn = '') "
      'AND $idColumn IS NOT NULL AND $idColumn != \'\'',
    ).get();
    for (final row in rows) {
      final idsRaw = row.read<String?>('ids');
      if (idsRaw == null || idsRaw.trim().isEmpty) continue;
      final intIds = _decodeIntList(idsRaw);
      if (intIds.isEmpty) continue;
      final syncIds = intIds
          .map((id) => idToSync[id])
          .whereType<String>()
          .toList();
      if (syncIds.isEmpty) continue;
      await customStatement(
        'UPDATE $table SET $syncColumn = ? WHERE rowid = ?',
        [jsonEncode(syncIds), row.read<int>('rowid')],
      );
    }
  }

  Future<void> _backfillSingleIntRef({
    required String table,
    required String idColumn,
    required String syncColumn,
    required Map<int, String> idToSync,
  }) async {
    if (!await _tableExists(table)) return;
    final rows = await customSelect(
      'SELECT rowid, $idColumn AS id FROM $table '
      "WHERE ($syncColumn IS NULL OR $syncColumn = '') "
      'AND $idColumn IS NOT NULL AND $idColumn != \'\'',
    ).get();
    for (final row in rows) {
      final idRaw = row.read<String?>('id');
      final intId = int.tryParse(idRaw ?? '');
      if (intId == null || intId <= 0) continue;
      final syncId = idToSync[intId];
      if (syncId == null) continue;
      await customStatement(
        'UPDATE $table SET $syncColumn = ? WHERE rowid = ?',
        [syncId, row.read<int>('rowid')],
      );
    }
  }

  List<int> _decodeIntList(String raw) {
    try {
      final decoded = jsonDecode(raw);
      if (decoded is List) {
        return decoded
            .map((e) => e is int ? e : int.tryParse('$e'))
            .whereType<int>()
            .where((id) => id > 0)
            .toList();
      }
    } catch (_) {
      // Malformed JSON - nothing to backfill.
    }
    return const [];
  }

  Future<void> _createStableMessageRefIndices() async {
    if (await _tableExists('memory_recall_events')) {
      await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_memory_recall_sync '
        'ON memory_recall_events(chat_message_sync_id) '
        'WHERE chat_message_sync_id IS NOT NULL',
      );
    }
    if (await _tableExists('co_reading_session_messages')) {
      await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_co_reading_session_messages_sync '
        'ON co_reading_session_messages(message_sync_id) '
        'WHERE message_sync_id IS NOT NULL',
      );
    }
  }

  Future<void> _createSyncOutboxIndices() async {
    // Submission batches read pending rows oldest-first per device.
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_sync_outbox_device_seq '
      'ON sync_outbox_messages(origin_device_id, origin_sequence)',
    );
  }

  Future<void> _createClarificationRequestsTable(Migrator m) async {
    try {
      await m.createTable(clarificationRequests);
    } catch (e) {
      if (_isAlreadyExistsError(e, 'clarification_requests')) {
        _logger.info(
            'clarification_requests table already exists, skipping migration');
      } else {
        rethrow;
      }
    }
    await _createClarificationRequestIndices();
  }

  Future<void> _createClarificationRequestIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_status ON clarification_requests(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_fact_id ON clarification_requests(fact_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_dedupe ON clarification_requests(dedupe_key)');
  }

  Future<void> _createUserNotificationIndices() async {
    await customStatement(
        'CREATE UNIQUE INDEX IF NOT EXISTS idx_user_notifications_unique '
        'ON user_notifications(user_id, notification_type, subject_key)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_user_notifications_list '
        'ON user_notifications(user_id, notification_type, updated_at)');
  }

  Future<void> _createSharedLifeMemoryIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_shared_life_operations_entity '
        'ON shared_life_event_operations(entity_id, created_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_shared_life_entities_updated '
        'ON shared_life_entities(updated_at)');
  }

  Future<void> _createDevAgentTables(Migrator m) async {
    await m.createTable(devProjects);
    await m.createTable(devAgentRuns);
    await m.createTable(devAgentEvents);
    await m.createTable(devAgentApprovals);
    await m.createTable(devAgentArtifacts);
    await _createDevAgentIndices();
    await _createDevAgentArtifactIndices();
  }

  Future<void> _createDevAgentIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_project_status '
        'ON dev_agent_runs(project_id, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_dev_session '
        'ON dev_agent_runs(dev_session_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_started_at '
        'ON dev_agent_runs(started_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_events_run_ts '
        'ON dev_agent_events(run_id, ts)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_approvals_run_status '
        'ON dev_agent_approvals(run_id, status)');
  }

  Future<void> _createDevAgentSessionTables(Migrator m) async {
    await _createTableIfMissing(m, devAgentSessions, 'dev_agent_sessions');
    await _createTableIfMissing(
        m, devAgentSessionMessages, 'dev_agent_session_messages');
    await _createTableIfMissing(
        m, devAgentToolBindings, 'dev_agent_tool_bindings');
    await _createDevAgentSessionIndices();
  }

  Future<void> _createDevAgentSessionIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_runs_dev_session '
        'ON dev_agent_runs(dev_session_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_sessions_project_status '
        'ON dev_agent_sessions(project_id, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_sessions_updated_at '
        'ON dev_agent_sessions(updated_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_session_messages_session_created '
        'ON dev_agent_session_messages(session_id, created_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_tool_bindings_character '
        'ON dev_agent_tool_bindings(character_id)');
  }

  Future<void> _createDevAgentArtifactIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_dev_agent_artifacts_run_kind '
        'ON dev_agent_artifacts(run_id, kind)');
  }

  Future<void> _createGameIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_sessions_definition_status '
        'ON game_sessions(definition_id, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_sessions_game_type '
        'ON game_sessions(game_type)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_sessions_last_played '
        'ON game_sessions(last_played_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_sessions_parent '
        'ON game_sessions(parent_session_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_messages_session_ts '
        'ON game_messages(session_id, timestamp)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_game_messages_type '
        'ON game_messages(session_id, message_type)');
  }

  Future<void> _createTaskRoomIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_task_rooms_status '
        'ON task_rooms(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_task_rooms_type '
        'ON task_rooms(task_type, status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_task_rooms_updated '
        'ON task_rooms(updated_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_task_artifacts_task '
        'ON task_artifacts(task_id, created_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_task_decisions_task '
        'ON task_decisions(task_id, decided_at)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_persona_chat_messages_task_room '
        'ON persona_chat_messages(task_room_id) '
        'WHERE task_room_id IS NOT NULL');
  }

  Future<void> _createWhiteboardIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_items_board '
        'ON whiteboard_board_items(board_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_groups_board '
        'ON whiteboard_groups(board_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_group_members_item '
        'ON whiteboard_group_members(item_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_edges_board '
        'ON whiteboard_edges(board_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_sources_canonical '
        'ON whiteboard_sources(provider, canonical_id) '
        'WHERE canonical_id IS NOT NULL');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_source_versions_source '
        'ON whiteboard_source_versions(source_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_whiteboard_card_extras_source '
        'ON whiteboard_card_extras(source_id) '
        'WHERE source_id IS NOT NULL');
  }

  Future<void> _createTableIfMissing(
    Migrator m,
    TableInfo<Table, dynamic> table,
    String tableName,
  ) async {
    try {
      await m.createTable(table);
    } catch (e) {
      if (_isAlreadyExistsError(e, tableName)) {
        _logger.info('$tableName table already exists, skipping migration');
      } else {
        rethrow;
      }
    }
  }

  bool _isAlreadyExistsError(Object error, String tableName) {
    final errorStr = error.toString().toLowerCase();
    return errorStr.contains(tableName) &&
        (errorStr.contains('already exists') ||
            errorStr.contains('duplicate table'));
  }

  Future<void> _addColumnIfMissing(String alterFragment) async {
    try {
      await customStatement('ALTER TABLE $alterFragment');
    } catch (e) {
      final msg = e.toString().toLowerCase();
      if (!msg.contains('duplicate column') &&
          !msg.contains('already exists')) {
        rethrow;
      }
    }
  }

  /// Like [_addColumnIfMissing] but first checks the table exists. Migration
  /// steps must tolerate minimal test databases and partial installs that do
  /// not yet carry every table.
  Future<void> _addColumnIfTableExists(
      String tableName, String columnDef) async {
    final exists = await customSelect(
      'SELECT name FROM sqlite_master WHERE type = \'table\' AND name = ?',
      variables: [Variable.withString(tableName)],
    ).getSingleOrNull();
    if (exists == null) return;
    await _addColumnIfMissing('$tableName ADD COLUMN $columnDef');
  }

  Future<bool> _tableExists(String tableName) async {
    final row = await customSelect(
      'SELECT name FROM sqlite_master WHERE type = \'table\' AND name = ?',
      variables: [Variable.withString(tableName)],
    ).getSingleOrNull();
    return row != null;
  }
}

/// Opens the connection using drift_flutter
QueryExecutor _openConnection(String userId) {
  final dbName = 'memex_local_$userId';

  return driftDatabase(name: dbName);
}
