import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,realpathSync,rmSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const local=name=>fileURLToPath(new URL(name,import.meta.url));
const source=local('./windows_text_gate_task_host_fault_retired.cs'),code=readFileSync(source,'utf8');
const deps=[local('./windows_text_gate_isolation_helper.cs'),local('./windows_text_gate_appid_startup_helper.cs'),local('../../tmp/p6-r7-review/native-appid-coordinator-candidate-15.cs'),local('../../tmp/p6-r7-review/native-appid-matrix-contract-01.cs'),local('./windows_text_gate_appid_matrix_native.cs'),local('../../tmp/p6-r7-review/native-task-executor-07.cs')];
const pins=['d22017641d9f8df750f6db7db9319b8c1930a726a8575ff1ffabfde0d5ffdcd8','c777023495ccdbf3b52663f49683f5d84dcfd03a36b3d280a75c925f37b7a1ea','c1f07e9487b8ce25d0acc2d5bbb03b69c975cbb7e448698d288ff6263cff9311','f70ffb86ce5efea2572532e1986f77dde9622893ad4b90a74f9ec40da5ba6774','f2d3b35a1e6d1763930ba7f9a82ab8dbb595e02d5d720216a0161dbce8a0d0ab','47d3da743598e17f92f2b3b7764226376097d015a7e337c3f27a9e7d8fbd5f92'];
const hash=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const csc=String.raw`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe`;
const harness=String.raw`
using System;using System.Collections.Generic;
namespace HereIAm.R7 {public static class TaskHostFaultRetiredPure {
 static int count;static void Check(bool ok){if(!ok)throw new Exception("pure_failed_"+count);count++;}static void Reject(Action action){bool failed=false;try{action();}catch{failed=true;}Check(failed);}
 static void History(string[] s){TaskHostFaultRetiredProgram.History(s[0],s[1],s[2],s[3],s[4],s[5]);}
 public static int Main(string[] args){
  var p=new Dictionary<string,object>{{"schema","p6_r7_task_owned_v2"},{"attempt_id",TaskHostFaultRetiredProgram.Attempt.ToString("D")},{"scope_id",TaskHostFaultRetiredProgram.Scope.ToString("D")},{"auth_mode","chatgpt"},{"home_class","dedicated_existing"},{"nonce",new string('a',64)},{"owner_pid",TaskHostFaultRetiredProgram.OwnerPid},{"owner_creation",TaskHostFaultRetiredProgram.OwnerCreation.ToString()},{"owner_sha256",TaskHostFaultRetiredProgram.ImageHash},{"owner_token_digest",new string('b',64)},{"cli_sha256",TaskHostFaultRetiredProgram.CliHash},{"broker_port",TaskHostFaultRetiredProgram.BrokerPort},{"phase","prepared"},{"child_pid",null},{"child_creation",null}};
  var s=new Dictionary<string,object>(p);s["phase"]="spawning";var b=new Dictionary<string,object>(p);b["phase"]="bound";b["child_pid"]=TaskHostFaultRetiredProgram.ChildPid;b["child_creation"]=TaskHostFaultRetiredProgram.ChildCreation.ToString();
  var receipt=TaskRecords.Receipt(p,"install",TaskHostFaultRetiredProgram.HelperPid,TaskHostFaultRetiredProgram.HelperCreation,TaskHostFaultRetiredProgram.BlobDigest,TaskHostFaultRetiredProgram.AssignedWeight);
  var ready=TaskRecords.Lease(p,"install",TaskHostFaultRetiredProgram.HelperPid,TaskHostFaultRetiredProgram.HelperCreation,new string('c',64));
  var records=new[]{p,s,b,receipt,ready,ready};var texts=new string[6];for(int i=0;i<6;i++)texts[i]=TaskJson.Json(records[i]);History(texts);Check(true);
  for(int r=0;r<6;r++){foreach(string field in new List<string>(records[r].Keys)){var bad=new Dictionary<string,object>(records[r]);bad.Remove(field);var changed=(string[])texts.Clone();changed[r]=TaskJson.Json(bad);Reject(delegate{History(changed);});bad=new Dictionary<string,object>(records[r]);bad[field]="invalid";changed=(string[])texts.Clone();changed[r]=TaskJson.Json(bad);Reject(delegate{History(changed);});}var extra=new Dictionary<string,object>(records[r]);extra["extra"]=true;var altered=(string[])texts.Clone();altered[r]=TaskJson.Json(extra);Reject(delegate{History(altered);});}
  foreach(string field in new[]{"nonce","owner_token_digest"}){var bad=new Dictionary<string,object>(b);bad[field]=new string('d',64);var changed=(string[])texts.Clone();changed[2]=TaskJson.Json(bad);Reject(delegate{History(changed);});}
  foreach(object weight in new object[]{null,-1,65536,32765,"32766"}){var bad=new Dictionary<string,object>(receipt);bad["assigned_weight"]=weight;var changed=(string[])texts.Clone();changed[3]=TaskJson.Json(bad);Reject(delegate{History(changed);});}
  var medium=new MediumIdentity{Type=1,Integrity=8192,ElevationType=3,Elevated=0,AppContainer=0,Authentication=1};var high=new MediumIdentity{Type=1,Integrity=12288,ElevationType=2,Elevated=1,AppContainer=0,Authentication=2};Check(!TaskHostFaultRetiredProgram.CallerAccepted(medium));Check(TaskHostFaultRetiredProgram.CallerAccepted(high));Check(!TaskHostFaultRetiredProgram.CallerAccepted(null));
  foreach(string field in new[]{"Type","Integrity","ElevationType","Elevated","AppContainer","Authentication"}){var bad=new MediumIdentity{Type=high.Type,Integrity=high.Integrity,ElevationType=high.ElevationType,Elevated=high.Elevated,AppContainer=high.AppContainer,Authentication=high.Authentication};var info=typeof(MediumIdentity).GetField(field,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);if(field=="Authentication")info.SetValue(bad,0UL);else info.SetValue(bad,field=="AppContainer"?1u:0u);Check(!TaskHostFaultRetiredProgram.CallerAccepted(bad));}
  foreach(uint pid in new[]{TaskHostFaultRetiredProgram.OwnerPid,TaskHostFaultRetiredProgram.ChildPid,TaskHostFaultRetiredProgram.HelperPid}){ulong created=12345;Check(TaskHostFaultRetiredProgram.Inactive(false,87,0,0,0,pid,created));Check(!TaskHostFaultRetiredProgram.Inactive(false,5,0,0,0,pid,created));Check(!TaskHostFaultRetiredProgram.Inactive(true,0,pid,created,258,pid,created));Check(TaskHostFaultRetiredProgram.Inactive(true,0,pid,created+1,258,pid,created));Check(TaskHostFaultRetiredProgram.Inactive(true,0,pid,created,0,pid,created));Check(!TaskHostFaultRetiredProgram.Inactive(true,0,pid+1,created,0,pid,created));Check(!TaskHostFaultRetiredProgram.Inactive(true,0,pid,created,0xffffffff,pid,created));}
  Check(TaskHostFaultRetiredProgram.ExactNames((string[])TaskHostFaultRetiredProgram.FixedNames.Clone()));for(int i=0;i<9;i++){var names=(string[])TaskHostFaultRetiredProgram.FixedNames.Clone();names[i]="unknown";Check(!TaskHostFaultRetiredProgram.ExactNames(names));names=(string[])TaskHostFaultRetiredProgram.FixedNames.Clone();names[i]="..\\"+names[i];Check(!TaskHostFaultRetiredProgram.ExactNames(names));}
  Check(TaskHostFaultRetiredProgram.PathIdle(false,258)&&TaskHostFaultRetiredProgram.PathIdle(true,0)&&!TaskHostFaultRetiredProgram.PathIdle(true,258)&&!TaskHostFaultRetiredProgram.PathIdle(false,0xffffffff));
  string actual=System.IO.File.ReadAllText(args[0]).Trim();TaskHostFaultRetiredProgram.CaptureHistory(actual);Check(true);var capture=TaskJson.Parse(actual);foreach(string key in new List<string>(capture.Keys)){var bad=new Dictionary<string,object>(capture);bad.Remove(key);Reject(delegate{TaskHostFaultRetiredProgram.CaptureHistory(TaskJson.Json(bad));});bad=new Dictionary<string,object>(capture);bad[key]="invalid";Reject(delegate{TaskHostFaultRetiredProgram.CaptureHistory(TaskJson.Json(bad));});}
  var order=new List<string>();int reads=0;Check(TaskHostFaultRetiredProgram.RemoveFixed(delegate{order.Add("read");return reads++==0?3:0;},delegate{order.Add("prove");},delegate{order.Add("begin");},delegate{order.Add("delete");},delegate{order.Add("commit");},delegate{order.Add("abort");}));Check(String.Join(",",order)=="prove,begin,prove,read,delete,prove,commit,prove,read");
  for(int failure=0;failure<9;failure++){int step=0,target=failure,readStep=0;bool mutation=false,committed=false,aborted=false;Action next=delegate{if(step++==target)throw new Exception("injected");};Reject(delegate{TaskHostFaultRetiredProgram.RemoveFixed(delegate{next();return readStep++==0?3:0;},delegate{next();},delegate{next();},delegate{next();mutation=true;},delegate{next();committed=true;},delegate{aborted=true;});});Check(!committed||failure>=7);Check(aborted==(failure>=2&&failure<=6));Check(!mutation||failure>=5);}
  foreach(int partial in new[]{-1,0,1,2,4}){bool touched=false;Reject(delegate{TaskHostFaultRetiredProgram.RemoveFixed(delegate{return partial;},delegate{},delegate{},delegate{touched=true;},delegate{},delegate{});});Check(!touched);}
  int abortedCount=0,closedCount=0;var retry=new TaskHostFaultRetiredResources(delegate(IntPtr h){return true;},delegate(IntPtr h){return ++abortedCount==1?5u:0u;},delegate(IntPtr h){closedCount++;return 0;});retry.Engine=new IntPtr(1);retry.Transaction=true;Check(!TaskHostFaultRetiredProgram.Finish(retry));Check(retry.Empty&&!retry.CloseSucceeded&&abortedCount==2&&closedCount==1);
  bool canClose=false;var retained=new TaskHostFaultRetiredResources(delegate(IntPtr h){return canClose;},delegate(IntPtr h){return 0;},delegate(IntPtr h){return 0;});retained.Handles.Own(new IntPtr(2));Check(!TaskHostFaultRetiredProgram.Finish(retained)&&!retained.Empty);canClose=true;Check(!TaskHostFaultRetiredProgram.Finish(retained)&&retained.Empty&&!retained.CloseSucceeded);
  int engineAttempts=0;var failedEngine=new TaskHostFaultRetiredResources(delegate(IntPtr h){return true;},delegate(IntPtr h){return 0;},delegate(IntPtr h){return ++engineAttempts==1?5u:0u;});failedEngine.Engine=new IntPtr(99);Check(!TaskHostFaultRetiredProgram.Finish(failedEngine)&&failedEngine.Empty&&engineAttempts==2);
  Console.WriteLine("{\"pure_assertions\":"+count+",\"native_executed\":false}");return 0;
 }
}}
`;
test('fixed host-fault retirement candidate compiles and stays non-executing in pure modes',async t=>{
 deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));const parent=local('../../tmp/p6-r7-helper/'),tmp=mkdtempSync(path.join(parent,'task-host-fault-retired-test-'));
 t.after(()=>{deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));const canonical=realpathSync(tmp);assert.equal(path.dirname(canonical),realpathSync(parent));assert.match(path.basename(canonical),/^task-host-fault-retired-test-/);rmSync(canonical,{recursive:true,force:true});});
 const exe=path.join(tmp,'retired.exe'),pure=path.join(tmp,'pure.exe'),harnessFile=path.join(tmp,'pure.cs');writeFileSync(harnessFile,harness);
 const compile=(main,out,extra=[])=>{const run=spawnSync(csc,['/nologo','/platform:x64','/warnaserror+','/target:exe','/reference:System.Web.Extensions.dll',`/main:${main}`,`/out:${out}`,...deps,source,...extra],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(run.status,0,run.stdout+run.stderr);};
 compile('HereIAm.R7.TaskHostFaultRetiredProgram',exe);compile('HereIAm.R7.TaskHostFaultRetiredPure',pure,[harnessFile]);
 await t.test('only exact four-key recovery and explicit guarded entries',()=>{
  assert.doesNotMatch(code,/FwpmFilterAdd|FwpmSubLayerAdd|FwpmEngineSetOption|FwpmNetEvent|ShellExecute|CreateProcess|TerminateProcess|TerminateJob|OpenJobObject|CreateDirectory|SetAccessControl|FileMode\.Create|WriteAll|WriteRecord|RunAs|Process\.Start|DedicatedHome/);
  for(const fragment of ['FwpmTransactionBegin0(resources.Engine,1)','if(apply&&before==3)','TaskBoundary.MakeRules(Scope,BrokerPort)','TaskBoundary.Key(Scope,"sublayer")','TaskBoundary.ExactFilter','TaskBoundary.ExactSublayer','TaskBoundary.ReadbackAllowed','OwnerInactive(resources);ImagesInactive(resources)','count<=8192','entries.Length==FixedNames.Length','CallerAccepted(current)','TaskRecords.VerifyReceipt','TaskRecords.Lease','CaptureHistory(evidence.Text(actual))','args.Length==1&&(args[0]=="--inspect"||args[0]=="--apply-cleanup")'])assert.ok(code.includes(fragment),fragment);
 });
 await t.test('default and malformed arguments never inspect/delete, history remains failed',()=>{
  for(const args of [[],['--plan'],['--self-test'],['--apply'],['--inspect','other'],['--apply-cleanup','other']]){
   const run=spawnSync(exe,args,{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,args.length===0||args.length===1&&['--plan','--self-test'].includes(args[0])?0:2,run.stdout+run.stderr);
   const r=JSON.parse(run.stdout);assert.equal(r.native_executed,false);assert.equal(r.cleanup_pending,true);assert.equal(r.historical_cleanup_pending,true);assert.equal(r.historical_host_fault_passed,false);assert.equal(r.recovery_pending,true);assert.equal(r.inspection_complete,false);assert.equal(r.exact_child_closed,null);assert.equal(r.job_active0,null);assert.equal(r.helper_actual_exit_verified,false);assert.equal(r.filters_deleted_count,0);assert.equal(r.sublayers_deleted_count,0);if(args[0]==='--self-test')process.stdout.write(`selftest_assertions=${r.pure_assertions}\n`);
  }
 });
 await t.test('synthetic relationships, retained identities, transaction failures and close failures reject',()=>{
  const run=spawnSync(pure,[local('../../tmp/p6-r7-review/native-host-fault-actual-02.json')],{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,0,run.stdout+run.stderr);const r=JSON.parse(run.stdout);assert.equal(r.native_executed,false);assert.ok(r.pure_assertions>=300);process.stdout.write(`pure_assertions=${r.pure_assertions}\n`);
 });
});
