// Read-only own-AppId WFP drop evidence. No option setters, subscriptions, or policy mutations.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Globalization;

namespace HereIAm.R7 {
    internal static class MatrixEventNative {
        [StructLayout(LayoutKind.Explicit,Size=88)]internal struct Header {
            [FieldOffset(0)]internal ulong Timestamp;[FieldOffset(8)]internal uint Flags;[FieldOffset(12)]internal uint Version;[FieldOffset(16)]internal byte Protocol;
            [FieldOffset(20)]internal uint Local4;[FieldOffset(36)]internal uint Remote4;[FieldOffset(52)]internal ushort LocalPort;[FieldOffset(54)]internal ushort RemotePort;[FieldOffset(56)]internal uint Scope;
            [FieldOffset(64)]internal Native.Blob App;[FieldOffset(80)]internal IntPtr User;
        }
        [StructLayout(LayoutKind.Explicit,Size=104)]internal struct Event { [FieldOffset(0)]internal Header Header;[FieldOffset(88)]internal uint Type;[FieldOffset(96)]internal IntPtr Detail; }
        [StructLayout(LayoutKind.Sequential)]internal struct Drop {internal ulong Filter;internal ushort Layer;}
        [StructLayout(LayoutKind.Sequential)]internal struct Template {internal ulong Start,End;internal uint Count;internal IntPtr Conditions;}
        [StructLayout(LayoutKind.Explicit,Size=72)]internal struct Layer {[FieldOffset(0)]internal Guid Key;[FieldOffset(64)]internal ushort Id;}
        [DllImport("fwpuclnt.dll")]internal static extern uint FwpmEngineGetOption0(IntPtr engine,int option,out IntPtr value);
        [DllImport("fwpuclnt.dll")]internal static extern uint FwpmNetEventCreateEnumHandle0(IntPtr engine,ref Template template,out IntPtr enumeration);
        [DllImport("fwpuclnt.dll")]internal static extern uint FwpmNetEventEnum0(IntPtr engine,IntPtr enumeration,uint requested,out IntPtr entries,out uint count);
        [DllImport("fwpuclnt.dll")]internal static extern uint FwpmNetEventDestroyEnumHandle0(IntPtr engine,IntPtr enumeration);
        [DllImport("fwpuclnt.dll")]internal static extern uint FwpmLayerGetByKey0(IntPtr engine,ref Guid key,out IntPtr layer);
        internal static void Layouts(){MatrixNetEvents.Need(IntPtr.Size==8&&Marshal.SizeOf(typeof(Header))==88&&Marshal.SizeOf(typeof(Event))==104&&Marshal.SizeOf(typeof(Drop))==16&&Marshal.SizeOf(typeof(Template))==32&&Marshal.SizeOf(typeof(Layer))==72&&Marshal.OffsetOf(typeof(Template),"Conditions").ToInt32()==24&&Marshal.OffsetOf(typeof(Drop),"Layer").ToInt32()==8);InspectionNative.Layouts();}
    }
    // Own only the resources returned by the read-only calls. A failed close remains a failure.
    internal sealed class MatrixEventApiError:Exception {internal readonly uint Status;internal MatrixEventApiError(uint status):base("matrix_event_api_failed"){Status=status;}}
    internal sealed class MatrixEventSession:IDisposable {
        internal IntPtr Engine,Enumeration;internal bool CloseSucceeded=true;internal uint? CloseStatus;
        readonly Func<IntPtr,IntPtr,uint> destroy;readonly Func<IntPtr,uint> close;
        internal MatrixEventSession():this(MatrixEventNative.FwpmNetEventDestroyEnumHandle0,Native.FwpmEngineClose0){}
        internal MatrixEventSession(Func<IntPtr,IntPtr,uint> destroyEnum,Func<IntPtr,uint> closeEngine){destroy=destroyEnum;close=closeEngine;}
        internal void Open(){MatrixNetEvents.Need(Engine==IntPtr.Zero);MatrixNetEvents.Status(Native.FwpmEngineOpen0(null,10,IntPtr.Zero,IntPtr.Zero,out Engine));MatrixNetEvents.Need(Engine!=IntPtr.Zero);}
        internal bool CloseVerified(){try{if(Enumeration!=IntPtr.Zero){uint status=destroy(Engine,Enumeration);if(status==0)Enumeration=IntPtr.Zero;else{CloseSucceeded=false;CloseStatus=status;}}}catch{CloseSucceeded=false;}try{if(Engine!=IntPtr.Zero&&Enumeration==IntPtr.Zero){uint status=close(Engine);if(status==0)Engine=IntPtr.Zero;else{CloseSucceeded=false;CloseStatus=status;}}}catch{CloseSucceeded=false;}return CloseSucceeded&&Engine==IntPtr.Zero&&Enumeration==IntPtr.Zero;}
        public void Dispose(){CloseVerified();}
    }
    internal sealed class MatrixEventProbe {internal string Role;internal IPAddress Local,Remote;internal ushort LocalPort,RemotePort;internal byte Protocol;internal ulong Start,End;}
    // Flat owned managed data, copied from WFP before the API result allocation is released.
    public sealed class MatrixDropObservation {
        public ulong Timestamp,FilterId;public uint Flags,Version,Scope;public byte Protocol;public ushort LocalPort,RemotePort,LayerId;public byte[] LocalAddress,RemoteAddress,AppId;
    }
    internal static class MatrixNetEvents {
        internal const string BindingSchema="matrix_own_drop_binding_v1",CaptureSchema="matrix_own_drop_capture_v1";
        const string BindingKeys="schema,attempt_id,scope_id,nonce,image_sha256,appid_blob_sha256,assigned_weight,deny4_filter_id,deny6_filter_id,deny4_layer_id,deny6_layer_id";
        static readonly List<MatrixEventSession> PendingSessions=new List<MatrixEventSession>();
        internal static int PendingSessionCount {get{lock(PendingSessions)return PendingSessions.Count;}}
        internal static void RetryPendingCloseOnly(){lock(PendingSessions){for(int round=0;round<2;round++)for(int i=PendingSessions.Count-1;i>=0;i--){MatrixEventSession held=PendingSessions[i];held.CloseVerified();if(held.Engine==IntPtr.Zero&&held.Enumeration==IntPtr.Zero)PendingSessions.RemoveAt(i);}}}
        internal static bool FinishSession(MatrixEventSession session){bool first=session.CloseVerified();if(!first&&(session.Engine!=IntPtr.Zero||session.Enumeration!=IntPtr.Zero)){lock(PendingSessions){if(!PendingSessions.Contains(session))PendingSessions.Add(session);}RetryPendingCloseOnly();}return first;}
        const string ProbeKeys="role,local_address,local_port,remote_address,remote_port,ip_protocol,started_filetime,finished_filetime";
        const string CaptureKeys="schema,attempt_id,nonce,binding_sha256,probes_sha256,capture_complete,all_roles_matched,collection_enabled,enumeration_exhausted,resources_closed,error_code,api_status,roles";
        internal static void Need(bool value){Guard.Require(value,"matrix_event_evidence_rejected");}
        internal static void Status(uint code){if(code!=0)throw new MatrixEventApiError(code);}
        internal static string HashBytes(byte[] bytes){using(SHA256 hash=SHA256.Create())return BitConverter.ToString(hash.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();}
        internal static string Hash(object value){string text=MatrixRecords.Json(value);Need(Encoding.UTF8.GetByteCount(text)<=16384);return HashBytes(Encoding.UTF8.GetBytes(text));}
        static void Keys(Dictionary<string,object> value,string keys){string[] names=keys.Split(',');Need(value!=null&&value.Count==names.Length);foreach(string name in names)Need(value.ContainsKey(name));}
        static ulong Decimal(object value){string text=value as string;ulong number;Need(text!=null&&UInt64.TryParse(text,NumberStyles.None,CultureInfo.InvariantCulture,out number));number=UInt64.Parse(text,CultureInfo.InvariantCulture);Need(number>0&&number.ToString(CultureInfo.InvariantCulture)==text);return number;}
        static uint Number(object value,uint maximum){Need(value is int||value is long||value is uint||value is ushort);long number=Convert.ToInt64(value,CultureInfo.InvariantCulture);Need(number>=0&&number<=maximum);return (uint)number;}
        static bool Boolean(object value){Need(value is bool);return (bool)value;}
        static void ValidateExpected(MatrixExpected e){Need(e!=null);MatrixRecords.ValidateOwned(MatrixRecords.Json(MatrixRecords.Owned(e,"prepared",null,null)),e);}
        internal static void ValidateBinding(MatrixExpected e,ushort weight,Dictionary<string,object> value){ValidateExpected(e);Keys(value,BindingKeys);Need(Object.Equals(value["schema"],BindingSchema)&&Object.Equals(value["attempt_id"],e.Attempt.ToString("D"))&&Object.Equals(value["scope_id"],MatrixContract.Scope(e.Attempt).ToString("D"))&&Object.Equals(value["nonce"],e.Nonce)&&Object.Equals(value["image_sha256"],e.ImageHash)&&Object.Equals(value["appid_blob_sha256"],e.BlobDigest)&&Number(value["assigned_weight"],65535)==weight);Need(Decimal(value["deny4_filter_id"])!=Decimal(value["deny6_filter_id"]));uint four=Number(value["deny4_layer_id"],65535),six=Number(value["deny6_layer_id"],65535);Need(four>0&&six>0&&four!=six);}
        static IPAddress Address(object raw){string text=raw as string;IPAddress address;Need(text!=null&&IPAddress.TryParse(text,out address));address=IPAddress.Parse(text);Need(address.ToString()==text&&(address.AddressFamily==AddressFamily.InterNetwork||address.AddressFamily==AddressFamily.InterNetworkV6)&&!address.IsIPv4MappedToIPv6);return address;}
        internal static MatrixEventProbe[] Probes(MatrixExpected e,object input){IList list=input as IList;Need(list!=null&&list.Count==8);MatrixEventProbe[] probes=new MatrixEventProbe[8];ulong first=UInt64.MaxValue,last=0;
            for(int i=0;i<8;i++){Dictionary<string,object> value=list[i] as Dictionary<string,object>;Keys(value,ProbeKeys);MatrixEventProbe probe=new MatrixEventProbe();probe.Role=value["role"] as string;Need(probe.Role==MatrixContract.Roles[i]);probe.Local=Address(value["local_address"]);probe.Remote=Address(value["remote_address"]);probe.LocalPort=(ushort)Number(value["local_port"],65535);probe.RemotePort=(ushort)Number(value["remote_port"],65535);probe.Protocol=(byte)Number(value["ip_protocol"],255);Need(probe.LocalPort>0&&probe.RemotePort>0&&probe.LocalPort!=probe.RemotePort&&probe.Protocol==(i%2==0?6:17)&&MatrixContract.SameAddress(probe.Local,probe.Remote)&&MatrixContract.TargetAllowed(probe.Role,probe.Remote,probe.RemotePort,new IPAddress[]{probe.Local},e.BrokerPort));probe.Start=Decimal(value["started_filetime"]);probe.End=Decimal(value["finished_filetime"]);Need(probe.Start>=e.OwnerCreation&&probe.Start>=last&&probe.Start<=probe.End&&probe.End-probe.Start<=50000000UL&&probe.End<=2650467743999999999UL);first=Math.Min(first,probe.Start);last=Math.Max(last,probe.End);probes[i]=probe;}
            Need(last-first<=300000000UL);return probes;
        }
        static byte[] AppId(MatrixExpected e){IntPtr allocation=IntPtr.Zero;try{Status(AppIdNative.FwpmGetAppIdFromFileName0(MatrixContract.ImageFor(e.Attempt),out allocation));byte[] result=CoordinatorBoundary.CopyBlob(allocation);Need(HashBytes(result)==e.BlobDigest);return result;}finally{if(allocation!=IntPtr.Zero)Native.FwpmFreeMemory0(ref allocation);}}
        static Dictionary<string,object> ReadBinding(IntPtr engine,MatrixExpected e,ushort weight,byte[] app){Guid scope=MatrixContract.Scope(e.Attempt),subkey=CoordinatorBoundary.Key(scope,"sublayer");Rule[] rules=MatrixContract.Rules(e.Attempt,e.BrokerPort);IntPtr allocation=IntPtr.Zero;try{Status(Native.FwpmSubLayerGetByKey0(engine,ref subkey,out allocation));Need(allocation!=IntPtr.Zero&&CoordinatorBoundary.ExactSublayer((Native.Sublayer)Marshal.PtrToStructure(allocation,typeof(Native.Sublayer)),subkey,weight));}finally{if(allocation!=IntPtr.Zero)Native.FwpmFreeMemory0(ref allocation);}
            ulong[] ids=new ulong[3];ushort[] layers=new ushort[3];for(int i=0;i<3;i++){Guid key=rules[i].Key;allocation=IntPtr.Zero;try{Status(InspectionNative.GetFilter(engine,ref key,out allocation));Need(allocation!=IntPtr.Zero);InspectionNative.Filter filter=(InspectionNative.Filter)Marshal.PtrToStructure(allocation,typeof(InspectionNative.Filter));Need(CoordinatorBoundary.ExactFilter(filter,rules[i],subkey,app)&&filter.Id!=0);ids[i]=filter.Id;}finally{if(allocation!=IntPtr.Zero)Native.FwpmFreeMemory0(ref allocation);}Guid layerKey=rules[i].Layer;allocation=IntPtr.Zero;try{Status(MatrixEventNative.FwpmLayerGetByKey0(engine,ref layerKey,out allocation));Need(allocation!=IntPtr.Zero);MatrixEventNative.Layer layer=(MatrixEventNative.Layer)Marshal.PtrToStructure(allocation,typeof(MatrixEventNative.Layer));Need(layer.Key==layerKey&&layer.Id!=0);layers[i]=layer.Id;}finally{if(allocation!=IntPtr.Zero)Native.FwpmFreeMemory0(ref allocation);}}
            Need(ids[0]!=ids[1]&&ids[0]!=ids[2]&&ids[1]!=ids[2]);Dictionary<string,object> binding=new Dictionary<string,object>{{"schema",BindingSchema},{"attempt_id",e.Attempt.ToString("D")},{"scope_id",scope.ToString("D")},{"nonce",e.Nonce},{"image_sha256",e.ImageHash},{"appid_blob_sha256",e.BlobDigest},{"assigned_weight",weight},{"deny4_filter_id",ids[1].ToString(CultureInfo.InvariantCulture)},{"deny6_filter_id",ids[2].ToString(CultureInfo.InvariantCulture)},{"deny4_layer_id",layers[1]},{"deny6_layer_id",layers[2]}};ValidateBinding(e,weight,binding);return binding;
        }
        internal static Dictionary<string,object> InstallBinding(MatrixExpected e,ushort weight,Action prove){ValidateExpected(e);Need(prove!=null);MatrixEventNative.Layouts();MatrixEventSession session=null;Dictionary<string,object> binding=null;bool closed=true;try{prove();byte[] app=AppId(e);session=new MatrixEventSession();session.Open();binding=ReadBinding(session.Engine,e,weight,app);prove();}finally{if(session!=null)closed=FinishSession(session);}Need(closed);return binding;}
        static Dictionary<string,object>[] Roles(int[] counts){Dictionary<string,object>[] roles=new Dictionary<string,object>[8];for(int i=0;i<8;i++)roles[i]=new Dictionary<string,object>{{"role",MatrixContract.Roles[i]},{"matched",counts[i]>0},{"matched_count",counts[i]}};return roles;}
        static bool Every(int[] counts){foreach(int count in counts)if(count==0)return false;return true;}
        internal static Dictionary<string,object> Capture(MatrixExpected e,ushort weight,Dictionary<string,object> binding,object input,Action prove){int error=1;uint? apiStatus=null;bool? enabled=null;bool exhausted=false,closed=true,verified=false;int[] counts=new int[8];string bindingHash=new string('0',64),probeHash=new string('0',64);MatrixEventSession session=null;
            try{ValidateBinding(e,weight,binding);MatrixEventProbe[] probes=Probes(e,input);Need(prove!=null);bindingHash=Hash(binding);probeHash=Hash(input);MatrixEventNative.Layouts();error=2;prove();byte[] app=AppId(e);session=new MatrixEventSession();session.Open();Need(MatrixRecords.Json(ReadBinding(session.Engine,e,weight,app))==MatrixRecords.Json(binding));error=3;IntPtr option=IntPtr.Zero;try{Status(MatrixEventNative.FwpmEngineGetOption0(session.Engine,0,out option));Need(option!=IntPtr.Zero);uint type=unchecked((uint)Marshal.ReadInt32(option)),value=unchecked((uint)Marshal.ReadInt32(option,8));Need(type==3&&value<=1);enabled=value==1;}finally{if(option!=IntPtr.Zero)Native.FwpmFreeMemory0(ref option);}Need(enabled==true);
                error=4;ulong start=UInt64.MaxValue,end=0;foreach(MatrixEventProbe probe in probes){start=Math.Min(start,probe.Start);end=Math.Max(end,probe.End);}using(Arena arena=new Arena()){Native.Condition[] conditions=new Native.Condition[]{new Native.Condition{Field=CoordinatorBoundary.AppId,Match=0,Value=new Native.Value{Type=12,Pointer=arena.Struct(new Native.Blob{Size=(uint)app.Length,Data=arena.Bytes(app)})}},new Native.Condition{Field=new Guid("206e9996-490e-40cf-b831-b38641eb6fcb"),Match=0,Value=new Native.Value{Type=3,Number=3}}};MatrixEventNative.Template template=new MatrixEventNative.Template{Start=start,End=end,Count=2,Conditions=arena.Array(conditions)};Status(MatrixEventNative.FwpmNetEventCreateEnumHandle0(session.Engine,ref template,out session.Enumeration));Need(session.Enumeration!=IntPtr.Zero);}
                error=5;for(int page=0;page<8;page++){IntPtr entries=IntPtr.Zero;uint count;try{Status(MatrixEventNative.FwpmNetEventEnum0(session.Engine,session.Enumeration,32,out entries,out count));Need(count<=32&&(count==0||entries!=IntPtr.Zero));for(int i=0;i<count;i++){IntPtr pointer=Marshal.ReadIntPtr(entries,i*8);Need(pointer!=IntPtr.Zero);MatrixDropObservation observation=ReadObservation(pointer);if(observation!=null)for(int row=0;row<8;row++)if(Matches(observation,probes[row],binding,app))counts[row]++;}if(count<32){exhausted=true;break;}}finally{if(entries!=IntPtr.Zero)Native.FwpmFreeMemory0(ref entries);}}Need(exhausted);error=6;Need(MatrixRecords.Json(ReadBinding(session.Engine,e,weight,app))==MatrixRecords.Json(binding));prove();verified=true;error=0;
            }catch(MatrixEventApiError failure){apiStatus=failure.Status;}catch{}finally{if(session!=null)closed=FinishSession(session);if(!closed){error=7;apiStatus=session==null?null:session.CloseStatus;}}
            bool complete=verified&&enabled==true&&exhausted&&closed;return new Dictionary<string,object>{{"schema",CaptureSchema},{"attempt_id",e==null?Guid.Empty.ToString("D"):e.Attempt.ToString("D")},{"nonce",e==null?null:e.Nonce},{"binding_sha256",bindingHash},{"probes_sha256",probeHash},{"capture_complete",complete},{"all_roles_matched",complete&&Every(counts)},{"collection_enabled",enabled.HasValue?(object)enabled.Value:null},{"enumeration_exhausted",exhausted},{"resources_closed",closed},{"error_code",error},{"api_status",apiStatus.HasValue?(object)apiStatus.Value:null},{"roles",Roles(counts)}};
        }
        static MatrixDropObservation ReadObservation(IntPtr pointer){MatrixEventNative.Event value=(MatrixEventNative.Event)Marshal.PtrToStructure(pointer,typeof(MatrixEventNative.Event));if(value.Type!=3)return null;Need(value.Detail!=IntPtr.Zero);MatrixEventNative.Header header=value.Header;Need(header.App.Size<=65536&&(header.App.Size==0||header.App.Data!=IntPtr.Zero));byte[] fixedEvent=new byte[104],drop=new byte[16],app=new byte[header.App.Size];Marshal.Copy(pointer,fixedEvent,0,104);Marshal.Copy(value.Detail,drop,0,16);if(app.Length>0)Marshal.Copy(header.App.Data,app,0,app.Length);return DecodeFixed(fixedEvent,drop,app);}
        internal static MatrixDropObservation DecodeFixed(byte[] bytes,byte[] drop,byte[] app){Need(BitConverter.IsLittleEndian&&bytes!=null&&bytes.Length==104&&drop!=null&&drop.Length==16&&app!=null&&app.Length<=65536&&BitConverter.ToUInt32(bytes,88)==3&&BitConverter.ToUInt32(bytes,64)==app.Length);byte[] local=new byte[16],remote=new byte[16],copy=(byte[])app.Clone();Array.Copy(bytes,20,local,0,16);Array.Copy(bytes,36,remote,0,16);return new MatrixDropObservation{Timestamp=BitConverter.ToUInt64(bytes,0),Flags=BitConverter.ToUInt32(bytes,8),Version=BitConverter.ToUInt32(bytes,12),Protocol=bytes[16],LocalAddress=local,RemoteAddress=remote,LocalPort=BitConverter.ToUInt16(bytes,52),RemotePort=BitConverter.ToUInt16(bytes,54),Scope=BitConverter.ToUInt32(bytes,56),AppId=copy,FilterId=BitConverter.ToUInt64(drop,0),LayerId=BitConverter.ToUInt16(drop,8)};}
        // IPv4 is compared as one host UINT32 (127.0.0.1 = 0x7f000001), IPv6 as 16 address bytes.
        // Header0 docs do not state IPv4 order explicitly; never accept both orders as a fallback.
        static bool AddressMatches(byte[] raw,IPAddress expected,uint version){if(raw==null||raw.Length!=16)return false;byte[] bytes=expected.GetAddressBytes();if(version==0){if(bytes.Length!=4)return false;uint number=(uint)(bytes[0]<<24|bytes[1]<<16|bytes[2]<<8|bytes[3]);return BitConverter.ToUInt32(raw,0)==number;}if(version!=1||bytes.Length!=16)return false;return CoordinatorBoundary.SameBytes(raw,bytes);}
        internal static bool Matches(MatrixDropObservation value,MatrixEventProbe probe,Dictionary<string,object> binding,byte[] app){bool ipv6=probe.Local.AddressFamily==AddressFamily.InterNetworkV6;uint required=0x13f;uint scope=ipv6?checked((uint)probe.Local.ScopeId):0;if(scope!=0)required|=0x80;return value!=null&&(value.Flags&required)==required&&value.Version==(ipv6?1u:0u)&&value.Timestamp>=probe.Start&&value.Timestamp<=probe.End&&value.Protocol==probe.Protocol&&value.LocalPort==probe.LocalPort&&value.RemotePort==probe.RemotePort&&((value.Flags&0x80)==0||value.Scope==scope)&&AddressMatches(value.LocalAddress,probe.Local,value.Version)&&AddressMatches(value.RemoteAddress,probe.Remote,value.Version)&&CoordinatorBoundary.SameBytes(value.AppId,app)&&value.FilterId==Decimal(binding[ipv6?"deny6_filter_id":"deny4_filter_id"])&&value.LayerId==Number(binding[ipv6?"deny6_layer_id":"deny4_layer_id"],65535);}
        internal static bool ValidateCapture(MatrixExpected e,ushort weight,Dictionary<string,object> binding,object probes,Dictionary<string,object> capture){ValidateBinding(e,weight,binding);Probes(e,probes);Keys(capture,CaptureKeys);Need(Object.Equals(capture["schema"],CaptureSchema)&&Object.Equals(capture["attempt_id"],e.Attempt.ToString("D"))&&Object.Equals(capture["nonce"],e.Nonce)&&Object.Equals(capture["binding_sha256"],Hash(binding))&&Object.Equals(capture["probes_sha256"],Hash(probes)));bool complete=Boolean(capture["capture_complete"]),all=Boolean(capture["all_roles_matched"]),exhausted=Boolean(capture["enumeration_exhausted"]),closed=Boolean(capture["resources_closed"]);object enabled=capture["collection_enabled"];Need(enabled==null||enabled is bool);uint error=Number(capture["error_code"],7);object api=capture["api_status"];Need(api==null||(Number(api,UInt32.MaxValue)>0&&error>=2));IList roles=capture["roles"] as IList;Need(roles!=null&&roles.Count==8);bool every=true;uint total=0;for(int i=0;i<8;i++){Dictionary<string,object> role=roles[i] as Dictionary<string,object>;Keys(role,"role,matched,matched_count");uint count=Number(role["matched_count"],256);bool matched=Boolean(role["matched"]);Need(Object.Equals(role["role"],MatrixContract.Roles[i])&&matched==(count>0));every=every&&matched;total+=count;}Need(total<=256);Need(complete==(error==0&&Object.Equals(enabled,true)&&exhausted&&closed)&&all==(complete&&every));return all;}
        // Validation still runs for a well-formed incomplete capture. No binding or endpoint data escapes.
        internal static Dictionary<string,object> SafeSummary(MatrixExpected e,ushort weight,Dictionary<string,object> binding,object probes,Dictionary<string,object> capture){ValidateCapture(e,weight,binding,probes,capture);IList input=capture["roles"] as IList;Dictionary<string,object>[] roles=new Dictionary<string,object>[8];for(int i=0;i<8;i++){Dictionary<string,object> row=(Dictionary<string,object>)input[i];roles[i]=new Dictionary<string,object>{{"role",MatrixContract.Roles[i]},{"matched",row["matched"]},{"matched_count",row["matched_count"]}};}return new Dictionary<string,object>{{"collection_enabled",capture["collection_enabled"]},{"enumeration_complete",capture["enumeration_exhausted"]},{"resources_closed",capture["resources_closed"]},{"error_stage",capture["error_code"]},{"api_status",capture["api_status"]},{"roles",roles}};}
    }
}
