// Explicit local diagnostic runtime. Compile with immutable v10/v11c/v15/contract01 and reviewed adapters/sockets.
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Text;
using System.Threading;
using System.Diagnostics;
using System.Web.Script.Serialization;
using Microsoft.Win32.SafeHandles;

namespace HereIAm.R7 {
    internal static class MatrixRuntimeCheck {
        internal static void Need(bool value){Guard.Require(value,"matrix_runtime_evidence_rejected");}
        internal static uint Number(object value){Need(value is int||value is long||value is uint);long n=Convert.ToInt64(value);Need(n>=0&&n<=UInt32.MaxValue);return (uint)n;}
        internal static ulong Time(object value){ulong result;string s=value as string;Need(s!=null&&UInt64.TryParse(s,out result));result=UInt64.Parse(s);Need(result>0&&result.ToString()==s);return result;}
        internal static void Keys(Dictionary<string,object> value,string keys){string[] names=keys.Split(',');Need(value!=null&&value.Count==names.Length);foreach(string name in names)Need(value.ContainsKey(name));}
        internal static MediumIdentity Token(IntPtr process){IntPtr token=IntPtr.Zero;MatrixNativeApi.Win(Native.OpenProcessToken(process,8,out token),"matrix_token_open_failed");try{return MediumIdentity.Read(token);}finally{bool closed=Native.CloseHandle(token);if(!closed)MatrixHandleLedger.AnyCloseFailure=true;MatrixNativeApi.Win(closed,"matrix_token_close_failed");}}
        internal static string Random(){byte[] bytes=new byte[32];using(System.Security.Cryptography.RandomNumberGenerator rng=System.Security.Cryptography.RandomNumberGenerator.Create())rng.GetBytes(bytes);return BitConverter.ToString(bytes).Replace("-","").ToLowerInvariant();}
    }
    // Only fresh attempt files are writable. Existing parents are admitted read-only with exact owner ACL.
    internal sealed class MatrixRuntimeFiles:IDisposable {
        readonly MatrixHandleLedger held=new MatrixHandleLedger();internal readonly string Directory,Image,Source;internal readonly Guid Attempt;internal readonly string User;bool disposed;
        internal MatrixRuntimeFiles(Guid attempt,string user,bool create){
            Attempt=attempt;User=user;Directory=MatrixContract.DirectoryFor(attempt);Image=MatrixContract.ImageFor(attempt);Source=MatrixNativeApi.SelfPath;
            try{Ancestors(Path.GetDirectoryName(Source));Pin(Source,false);Ancestors(Path.GetPathRoot(Directory));
                if(create){if(Absent(MatrixContract.Root))System.IO.Directory.CreateDirectory(MatrixContract.Root,Security(user));else VerifyAcl(MatrixContract.Root,user);Pin(MatrixContract.Root,true);MatrixRuntimeCheck.Need(Absent(Directory));System.IO.Directory.CreateDirectory(Directory,Security(user));}
                VerifyAcl(MatrixContract.Root,user);VerifyAcl(Directory,user);Pin(MatrixContract.Root,true);Pin(Directory,true);
                if(create){using(FileStream input=new FileStream(Source,FileMode.Open,FileAccess.Read,FileShare.Read))using(FileStream output=new FileStream(Image,FileMode.CreateNew,FileAccess.Write,FileShare.None)){MatrixNativeApi.VerifyPath(input.SafeFileHandle.DangerousGetHandle(),Source,false);MatrixNativeApi.VerifyPath(output.SafeFileHandle.DangerousGetHandle(),Image,false);input.CopyTo(output);output.Flush(true);}}
                Pin(Image,false);MatrixRuntimeCheck.Need(TokenProof.Hash(Source)==TokenProof.Hash(Image));
            }catch{held.Dispose();throw;}
        }
        static DirectorySecurity Security(string user){DirectorySecurity acl=new DirectorySecurity();acl.SetAccessRuleProtection(true,false);acl.SetOwner(new SecurityIdentifier(user));foreach(string sid in new string[]{user,"S-1-5-18","S-1-5-32-544"})acl.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));return acl;}
        internal static void VerifyAcl(string directory,string user){
            MatrixRuntimeCheck.Need((File.GetAttributes(directory)&FileAttributes.ReparsePoint)==0);DirectorySecurity acl=System.IO.Directory.GetAccessControl(directory,AccessControlSections.Owner|AccessControlSections.Access);
            MatrixRuntimeCheck.Need(acl.GetOwner(typeof(SecurityIdentifier)).Value==user&&acl.AreAccessRulesProtected);AuthorizationRuleCollection rules=acl.GetAccessRules(true,true,typeof(SecurityIdentifier));MatrixRuntimeCheck.Need(rules.Count==3);HashSet<string> wanted=new HashSet<string>(new string[]{user,"S-1-5-18","S-1-5-32-544"});foreach(FileSystemAccessRule rule in rules)MatrixRuntimeCheck.Need(wanted.Remove(rule.IdentityReference.Value)&&!rule.IsInherited&&rule.AccessControlType==AccessControlType.Allow&&rule.FileSystemRights==FileSystemRights.FullControl&&rule.InheritanceFlags==(InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit)&&rule.PropagationFlags==PropagationFlags.None);MatrixRuntimeCheck.Need(wanted.Count==0);
        }
        internal static bool Absent(string path){uint attributes=NeverSpawnedNative.GetFileAttributesW(path),error=unchecked((uint)Marshal.GetLastWin32Error());if(attributes==UInt32.MaxValue){MatrixRuntimeCheck.Need(error==2||error==3);return true;}MatrixRuntimeCheck.Need((attributes&0x400)==0);return false;}
        void Pin(string path,bool directory){IntPtr file=held.Own(Native.CreateFileW(path,directory?0x80u:0x80000000u,directory?3u:1u,IntPtr.Zero,3,0x00200000u|(directory?0x02000000u:0u),IntPtr.Zero));MatrixNativeApi.VerifyPath(file,path,directory);}
        void Ancestors(string directory){string full=MatrixNativeApi.Canonical(directory),root=Path.GetPathRoot(full),current=root;Pin(root,true);foreach(string part in full.Substring(root.Length).Split('\\')){if(part.Length==0)continue;current=Path.Combine(current,part);Pin(current,true);}}
        internal void Verify(){MatrixRuntimeCheck.Need(!disposed);VerifyAcl(MatrixContract.Root,User);VerifyAcl(Directory,User);MatrixRuntimeCheck.Need(TokenProof.Hash(Source)==TokenProof.Hash(Image));}
        internal string PathFor(string name){MatrixRuntimeCheck.Need(!disposed&&Array.IndexOf(new string[]{"prepared.json","spawning.json","bound.json","closed.json","install-ready.json","install-ack.json","install-receipt.json","install_rollback-receipt.json","cleanup-ready.json","cleanup-ack.json","cleanup-receipt.json","rollback-ready.json","rollback-ack.json","rollback-receipt.json","install-report.json","cleanup-report.json","rollback-report.json","probe-report.json","event-binding.json","event-probes.json","event-receipt.json"},name)>=0);return Path.Combine(Directory,name);}
        // Keep evidence read-locked for the remainder of this role, then reread under that lock.
        internal string ReadPinned(string name){Pin(PathFor(name),false);return Read(name);}
        internal void Write(string name,object value){Verify();string target=PathFor(name);MatrixRuntimeCheck.Need(Absent(target));byte[] bytes=Encoding.UTF8.GetBytes(MatrixRecords.Json(value));MatrixRuntimeCheck.Need(bytes.Length<=16384);using(FileStream file=new FileStream(target,FileMode.CreateNew,FileAccess.Write,FileShare.None)){MatrixNativeApi.VerifyPath(file.SafeFileHandle.DangerousGetHandle(),target,false);file.Write(bytes,0,bytes.Length);file.Flush(true);}}
        internal string Read(string name){Verify();string target=PathFor(name);using(FileStream file=new FileStream(target,FileMode.Open,FileAccess.Read,FileShare.Read)){MatrixNativeApi.VerifyPath(file.SafeFileHandle.DangerousGetHandle(),target,false);MatrixRuntimeCheck.Need(file.Length<=16384);byte[] bytes=new byte[(int)file.Length];int done=0;while(done<bytes.Length){int n=file.Read(bytes,done,bytes.Length-done);MatrixRuntimeCheck.Need(n>0);done+=n;}return new UTF8Encoding(false,true).GetString(bytes);}}
        internal static string WaitReadCore(Func<bool> absent,Func<string> read,int timeout){
            MatrixRuntimeCheck.Need(absent!=null&&read!=null&&timeout>0&&timeout<=30000);Stopwatch timer=Stopwatch.StartNew();
            while(timer.ElapsedMilliseconds<timeout){
                if(!absent()){try{string value=read();return timer.ElapsedMilliseconds<timeout?value:null;}catch(IOException failure){uint code=unchecked((uint)failure.HResult);if(code!=0x80070020u&&code!=0x80070021u)throw;}}
                int remaining=timeout-(int)timer.ElapsedMilliseconds;if(remaining>0)Thread.Sleep(Math.Min(20,remaining));
            }return null;
        }
        // File existence is not readiness: the exclusive writer must close before this strict read succeeds.
        internal string WaitRead(string name,int timeout){string target=PathFor(name);return WaitReadCore(delegate{return Absent(target);},delegate{return Read(name);},timeout);}
        internal bool CloseVerified(){disposed=true;return held.CloseAll();}public void Dispose(){CloseVerified();}
    }
    public static class MatrixRuntimePolicy {
        public static bool HelperAccepted(bool liveBound,bool exited,uint exit,bool receipt,bool handles){return liveBound&&exited&&exit==0&&receipt&&handles;}
        public static bool CleanupComplete(bool rules,bool helper,bool child,bool job,bool eof,bool drained,bool handles){return rules&&helper&&child&&job&&eof&&drained&&handles;}
        public static bool ProtocolLine(string line){return line!=null&&line.Length>0&&Encoding.UTF8.GetByteCount(line)<=8192&&line.IndexOf('\r')<0&&line.IndexOf('\n')<0;}
        public static bool EventGate(bool boundInstall,bool boundCleanup,bool allDrops,bool zeroReceives,bool windows){return boundInstall&&boundCleanup&&allDrops&&zeroReceives&&windows;}
    }
    internal sealed class MatrixRuntimePump {
        [DllImport("kernel32.dll",SetLastError=true)]static extern bool ReadFile(IntPtr file,byte[] data,uint count,out uint read,IntPtr overlapped);
        [DllImport("kernel32.dll",SetLastError=true)]static extern bool PeekNamedPipe(IntPtr pipe,IntPtr buffer,uint size,IntPtr read,out uint available,IntPtr left);
        readonly IntPtr handle;readonly List<byte> pending=new List<byte>();int total;internal bool Eof,Failed;
        internal MatrixRuntimePump(IntPtr pipe){handle=pipe;}
        internal string Line(int timeout){Stopwatch timer=Stopwatch.StartNew();while(timer.ElapsedMilliseconds<timeout){string line=Poll();if(line!=null)return line;MatrixRuntimeCheck.Need(!Eof&&!Failed);Thread.Sleep(10);}throw new BoundaryError("matrix_stdio_timeout");}
        internal string Poll(){try{int end=pending.IndexOf(10);if(end<0){uint available;bool peek=PeekNamedPipe(handle,IntPtr.Zero,0,IntPtr.Zero,out available,IntPtr.Zero);if(!peek){uint error=unchecked((uint)Marshal.GetLastWin32Error());MatrixRuntimeCheck.Need(error==109);Eof=true;MatrixRuntimeCheck.Need(pending.Count==0);return null;}if(available>0){byte[] bytes=new byte[Math.Min(available,4096)];uint read;MatrixNativeApi.Win(ReadFile(handle,bytes,(uint)bytes.Length,out read,IntPtr.Zero),"matrix_stdio_read_failed");total+=(int)read;MatrixRuntimeCheck.Need(total<=32768);for(int i=0;i<read;i++)pending.Add(bytes[i]);}end=pending.IndexOf(10);}if(end<0){MatrixRuntimeCheck.Need(pending.Count<=8192);return null;}byte[] value=pending.GetRange(0,end).ToArray();pending.RemoveRange(0,end+1);string result=new UTF8Encoding(false,true).GetString(value);MatrixRuntimeCheck.Need(MatrixRuntimePolicy.ProtocolLine(result));return result;}catch{Failed=true;throw;}}
        internal bool Drain(int timeout,bool requireEmpty){Stopwatch timer=Stopwatch.StartNew();try{while(!Eof&&timer.ElapsedMilliseconds<timeout){string line=Poll();if(line!=null&&requireEmpty)return false;Thread.Sleep(10);}return Eof&&!Failed&&pending.Count==0;}catch{return false;}}
        // One frame outstanding, with a response before the next send; frames fit the 4096-byte pipe capacity.
        internal static void Send(IntPtr pipe,object value){byte[] bytes=Encoding.UTF8.GetBytes(MatrixRecords.Json(value)+"\n");MatrixRuntimeCheck.Need(bytes.Length<=4096);uint written;MatrixNativeApi.Win(Native.WriteFile(pipe,bytes,(uint)bytes.Length,out written,IntPtr.Zero),"matrix_stdio_write_failed");MatrixRuntimeCheck.Need(written==bytes.Length);}
    }
    internal sealed class MatrixHelperProof:IDisposable {
        readonly MatrixHandleLedger handles=new MatrixHandleLedger();readonly MatrixRuntimeFiles files;readonly MatrixExpected expected;readonly string journalName,journalText;readonly bool prepared;IntPtr owner,job,child;internal readonly Dictionary<string,object> Journal;
        internal MatrixHelperProof(MatrixRuntimeFiles f,MatrixExpected e,string name){files=f;expected=e;journalName=name;journalText=f.Read(name);Journal=MatrixRecords.ValidateOwned(journalText,e);prepared=Object.Equals(Journal["phase"],"prepared");try{
            owner=handles.Own(Native.OpenProcess(0x1000|0x100000,false,e.OwnerPid));job=handles.Own(CoordinatorNative.OpenJobObjectW(4,false,MatrixNativeApi.JobName(e.Attempt)));
            if(!prepared)child=handles.Own(Native.OpenProcess(0x1000|0x100000,false,MatrixRuntimeCheck.Number(Journal["child_pid"])));Prove();
        }catch{handles.Dispose();throw;}}
        internal void Prove(){files.Verify();MatrixRuntimeCheck.Need(files.Read(journalName)==journalText);MatrixRuntimeCheck.Need(Native.WaitForSingleObject(owner,0)==258&&CoordinatorNative.GetProcessId(owner)==expected.OwnerPid&&TokenProof.Creation(owner)==expected.OwnerCreation);TokenProof.Image(owner,files.Source);MediumIdentity token=MatrixRuntimeCheck.Token(owner),current=MatrixRuntimeCheck.Token(Native.GetCurrentProcess());MatrixRuntimeCheck.Need(token.IsMedium&&MatrixNativeIdentity.Digest(token)==expected.OwnerTokenDigest&&current.User==token.User&&current.Session==token.Session);
            Native.ExtendedLimit limits;MatrixNativeApi.Win(CoordinatorJobNative.QueryLimits(job,9,out limits,144,IntPtr.Zero),"matrix_helper_limit_query_failed");MatrixRuntimeCheck.Need(CoordinatorJobNative.Exact(limits));Native.JobAccounting accounting;MatrixNativeApi.Win(Native.QueryInformationJobObject(job,1,out accounting,48,IntPtr.Zero),"matrix_helper_job_query_failed");MatrixRuntimeCheck.Need(accounting.Active==0&&(prepared?accounting.Total==0:accounting.Total==1));
            if(!prepared){MatrixRuntimeCheck.Need(Object.Equals(Journal["phase"],"closed")&&child!=IntPtr.Zero&&Native.WaitForSingleObject(child,0)==0&&CoordinatorNative.GetProcessId(child)==MatrixRuntimeCheck.Number(Journal["child_pid"])&&TokenProof.Creation(child)==MatrixRuntimeCheck.Time(Journal["child_creation"]));bool member;MatrixNativeApi.Win(Native.IsProcessInJob(child,job,out member),"matrix_helper_child_job_failed");MatrixRuntimeCheck.Need(member);}
        }
        internal bool CloseVerified(){return handles.CloseAll();}public void Dispose(){CloseVerified();}
    }
    internal sealed class MatrixHelperRun {
        internal bool Launched,LiveBound,Exited,Receipt,HandlesClosed,Rollback,EventMatched,EventCapturePresent;internal uint? Exit;internal ushort? Weight;
        // Observation-only fields. None participates in Accepted, cleanup, or event admission.
        internal bool LaunchAttempted,LaunchReturned,ProcessHandleObserved,ReadyWaitAttempted,ExitWaitAttempted,ReceiptReadAttempted,HandlesCloseAttempted;
        internal uint? LaunchError,ExitWaitResult;internal bool? ReadyObserved;
        internal string EventBinding;internal Dictionary<string,object> EventSummary;
        internal bool Accepted {get{return MatrixRuntimePolicy.HelperAccepted(LiveBound,Exited,Exit.HasValue?Exit.Value:UInt32.MaxValue,Receipt,HandlesClosed);}}
    }
    public static class MatrixRuntimeProgram {
        static readonly List<Socket> failedSockets=new List<Socket>();static Guid runningAttempt;
        [DllImport("kernel32.dll",SetLastError=true)]static extern IntPtr GetStdHandle(int kind);
        static Dictionary<string,object> Message(string kind,string nonce){return new Dictionary<string,object>{{"kind",kind},{"nonce",nonce}};}
        static Dictionary<string,object> ReadMessage(MatrixRuntimePump pump,string kind,string nonce,string keys){Dictionary<string,object> value=MatrixRecords.Parse(pump.Line(30000));MatrixRuntimeCheck.Keys(value,keys);MatrixRuntimeCheck.Need(Object.Equals(value["kind"],kind)&&Object.Equals(value["nonce"],nonce));return value;}
        static Dictionary<string,object> EventRecord(MatrixExpected e,string kind,uint pid,ulong created,object value){return new Dictionary<string,object>{{"schema","matrix_runtime_event_"+kind+"_v2"},{"attempt_id",e.Attempt.ToString("D")},{"nonce",e.Nonce},{"helper_pid",pid},{"helper_creation",created.ToString()},{"value",value}};}
        static Dictionary<string,object> EventValue(string text,MatrixExpected e,string kind,uint pid,ulong created){Dictionary<string,object> record=MatrixRecords.Parse(text);MatrixRuntimeCheck.Keys(record,"schema,attempt_id,nonce,helper_pid,helper_creation,value");MatrixRuntimeCheck.Need(Object.Equals(record["schema"],"matrix_runtime_event_"+kind+"_v2")&&Object.Equals(record["attempt_id"],e.Attempt.ToString("D"))&&Object.Equals(record["nonce"],e.Nonce)&&MatrixRuntimeCheck.Number(record["helper_pid"])==pid&&MatrixRuntimeCheck.Time(record["helper_creation"])==created);Dictionary<string,object> value=record["value"] as Dictionary<string,object>;MatrixRuntimeCheck.Need(value!=null);return value;}
        static object ProbeValues(string text,MatrixExpected e){Dictionary<string,object> record=MatrixRecords.Parse(text);MatrixRuntimeCheck.Keys(record,"schema,attempt_id,nonce,rows");MatrixRuntimeCheck.Need(Object.Equals(record["schema"],"matrix_runtime_event_probes_v2")&&Object.Equals(record["attempt_id"],e.Attempt.ToString("D"))&&Object.Equals(record["nonce"],e.Nonce));return record["rows"];}
        static Dictionary<string,object> EventDiagnostic(MatrixHelperRun install,MatrixHelperRun cleanup,bool probesReady){
            bool binding=install!=null&&install.Accepted&&install.EventBinding!=null,admitted=cleanup!=null&&cleanup.Accepted,present=admitted&&cleanup.EventCapturePresent,validated=admitted&&cleanup.EventSummary!=null;
            return new Dictionary<string,object>{{"diagnostic_only",true},{"binding_verified",binding},{"probes_available",probesReady},{"capture_present",present},{"capture_validated",validated},{"integration_stage",!binding?1:!probesReady?2:!admitted?3:!present?4:!validated?5:0},{"capture_summary",validated?cleanup.EventSummary:null}};
        }
        static Dictionary<string,object> HelperDiagnostic(MatrixHelperRun value){
            return new Dictionary<string,object>{{"schema","matrix_helper_diagnostic_v1"},{"diagnostic_only",true},{"invoked",value!=null},
                {"launch_attempted",value==null?null:(object)value.LaunchAttempted},{"launch_returned",value==null?null:(object)value.LaunchReturned},
                {"launched",value!=null&&value.LaunchReturned?(object)value.Launched:null},{"launch_error",value!=null&&value.LaunchReturned&&!value.Launched&&value.LaunchError.HasValue?(object)value.LaunchError.Value:null},
                {"process_handle_observed",value!=null&&value.LaunchReturned?(object)value.ProcessHandleObserved:null},
                {"ready_wait_attempted",value==null?null:(object)value.ReadyWaitAttempted},{"ready_observed",value!=null&&value.ReadyWaitAttempted&&value.ReadyObserved.HasValue?(object)value.ReadyObserved.Value:null},
                {"live_bound",value==null?null:(object)value.LiveBound},{"exit_wait_attempted",value==null?null:(object)value.ExitWaitAttempted},
                {"exit_wait_result",value!=null&&value.ExitWaitAttempted&&value.ExitWaitResult.HasValue?(object)value.ExitWaitResult.Value:null},
                {"actual_exited",value!=null&&value.Exited?(object)true:null},{"actual_exit",value!=null&&value.Exited&&value.Exit.HasValue?(object)value.Exit.Value:null},
                {"receipt_read_attempted",value==null?null:(object)value.ReceiptReadAttempted},{"receipt",value!=null&&value.ReceiptReadAttempted?(object)value.Receipt:null},
                {"handles_close_attempted",value==null?null:(object)value.HandlesCloseAttempted},{"handles_closed",value!=null&&value.HandlesCloseAttempted?(object)value.HandlesClosed:null}};
        }
        static void SocketSend(Socket socket,byte[] bytes){int offset=0;while(offset<bytes.Length){int n=socket.Send(bytes,offset,bytes.Length-offset,SocketFlags.None);MatrixRuntimeCheck.Need(n>0);offset+=n;}}
        static void SocketReceive(Socket socket,byte[] expected){byte[] bytes=new byte[expected.Length];int offset=0;while(offset<bytes.Length){int n=socket.Receive(bytes,offset,bytes.Length-offset,SocketFlags.None);MatrixRuntimeCheck.Need(n>0);offset+=n;}MatrixRuntimeCheck.Need(CoordinatorBoundary.SameBytes(bytes,expected));}
        static bool CloseSocket(Socket value){if(value==null)return true;try{value.Close();failedSockets.Remove(value);return true;}catch{if(!failedSockets.Contains(value))failedSockets.Add(value);return false;}}
        static void RetrySocketCloses(){foreach(Socket value in failedSockets.ToArray())CloseSocket(value);}
        static void Diagnostic(MatrixRuntimeFiles files,string name,int stage,bool completed){if(files==null)return;try{files.Write(name,new Dictionary<string,object>{{"stage",stage},{"completed",completed},{"error_code",completed?0:1}});}catch{}}
        static Socket Accept(TcpListener listener,int timeout){Stopwatch timer=Stopwatch.StartNew();while(timer.ElapsedMilliseconds<timeout){if(listener.Pending()){Socket socket=listener.AcceptSocket();try{socket.SendTimeout=2000;socket.ReceiveTimeout=2000;return socket;}catch{if(!CloseSocket(socket))MatrixHandleLedger.AnyCloseFailure=true;throw;}}Thread.Sleep(10);}throw new BoundaryError("matrix_broker_timeout");}
        static int Probe(Guid id){
            MatrixRuntimeFiles files=null;MatrixHandleLedger handles=new MatrixHandleLedger();Socket socket=null;bool success=false,closed=true;int stage=1;
            try{MediumIdentity current=MatrixRuntimeCheck.Token(Native.GetCurrentProcess());MatrixRuntimeCheck.Need(current.IsMedium);files=new MatrixRuntimeFiles(id,current.User,false);MatrixExpected e=Expected(files);MatrixRuntimeCheck.Need(MatrixNativeIdentity.Digest(current)==e.OwnerTokenDigest);Dictionary<string,object> bound=MatrixRecords.ValidateOwned(files.Read("bound.json"),e);MatrixRuntimeCheck.Need(Object.Equals(bound["phase"],"bound")&&MatrixRuntimeCheck.Number(bound["child_pid"])==CoordinatorNative.GetProcessId(Native.GetCurrentProcess())&&MatrixRuntimeCheck.Time(bound["child_creation"])==TokenProof.Creation(Native.GetCurrentProcess()));IntPtr job=handles.Own(CoordinatorNative.OpenJobObjectW(4,false,MatrixNativeApi.JobName(id)));bool member;MatrixNativeApi.Win(Native.IsProcessInJob(Native.GetCurrentProcess(),job,out member),"matrix_probe_job_failed");MatrixRuntimeCheck.Need(member);IntPtr owner=handles.Own(Native.OpenProcess(0x1000|0x100000,false,e.OwnerPid));MatrixRuntimeCheck.Need(Native.WaitForSingleObject(owner,0)==258&&CoordinatorNative.GetProcessId(owner)==e.OwnerPid&&TokenProof.Creation(owner)==e.OwnerCreation&&MatrixNativeIdentity.Digest(MatrixRuntimeCheck.Token(owner))==e.OwnerTokenDigest);
                stage=2;MatrixRuntimePump input=new MatrixRuntimePump(GetStdHandle(-10));IntPtr output=GetStdHandle(-11);MatrixRuntimePump.Send(output,Message("ready",e.Nonce));Dictionary<string,object> broker=ReadMessage(input,"broker",e.Nonce,"kind,nonce,port,marker");MatrixRuntimeCheck.Need(MatrixRuntimeCheck.Number(broker["port"])==e.BrokerPort);string marker=broker["marker"] as string;MatrixRuntimeCheck.Need(marker!=null&&marker.Length==64);byte[] payload=Encoding.ASCII.GetBytes(marker);socket=new Socket(AddressFamily.InterNetwork,SocketType.Stream,ProtocolType.Tcp);socket.SendTimeout=2000;socket.ReceiveTimeout=2000;IAsyncResult connect=socket.BeginConnect(IPAddress.Loopback,e.BrokerPort,null,null);try{MatrixRuntimeCheck.Need(connect.AsyncWaitHandle.WaitOne(5000));socket.EndConnect(connect);}finally{connect.AsyncWaitHandle.Close();}SocketSend(socket,payload);SocketReceive(socket,payload);closed=CloseSocket(socket)&&closed;socket=null;MatrixRuntimePump.Send(output,Message("broker_done",e.Nonce));stage=3;
                for(int index=0;index<8;index++){Dictionary<string,object> command=ReadMessage(input,"row",e.Nonce,"kind,nonce,index,challenge");MatrixRuntimeCheck.Need(MatrixRuntimeCheck.Number(command["index"])==index);Dictionary<string,object> challenge=command["challenge"] as Dictionary<string,object>;MatrixRuntimeCheck.Need(challenge!=null&&Object.Equals(challenge["role"],MatrixContract.Roles[index]));Dictionary<string,object> response=Message("row_outcome",e.Nonce);response["index"]=index;response["row"]=MatrixSocketFixtures.Probe(challenge,e.BrokerPort);MatrixRuntimePump.Send(output,response);}ReadMessage(input,"finish",e.Nonce,"kind,nonce");files.Verify();MatrixRuntimePump.Send(output,Message("done",e.Nonce));success=true;
            }catch{}finally{closed=CloseSocket(socket)&&closed;RetrySocketCloses();closed=handles.CloseAll()&&closed;Diagnostic(files,"probe-report.json",stage,success&&closed);if(files!=null)closed=files.CloseVerified()&&closed;}return success&&closed&&!MatrixHandleLedger.AnyCloseFailure?0:5;
        }
        static Dictionary<string,object> Base(string mode){return new Dictionary<string,object>{{"schema","p6_r7_appid_matrix_runtime_v2"},{"mode",mode},{"runtime_implemented",true},{"native_executed",false},{"cleanup_pending",false},{"matrix_passed",false},{"all_own_filter_drops_matched",false},{"event_matrix_passed",false},{"production_isolation_passed",false},{"human_gate_passed",false},{"real_upstream_requests",0},{"model_turns_requested",0}};}
        const string PublicReportKeys="schema,mode,runtime_implemented,native_executed,cleanup_pending,matrix_passed,all_own_filter_drops_matched,event_matrix_passed,production_isolation_passed,human_gate_passed,real_upstream_requests,model_turns_requested,attempt_id,failure_stage,rows,all_negative_roles_blocked,event_probe_windows_verified,zero_receives_verified,event_diagnostic,fixture_ready,owned_peer_admitted,wrong_peer_rejected,marker_round_trip,normal_child_exit0,no_child_created,no_job_created,exact_child_closed,job_active0,stdio_eof,socket_drain,post_pin,helper_actual_closed,rules_postabsence,all_handles_closed,install_diagnostic,cleanup_diagnostic";
        // Public projection may contain event_diagnostic -> capture_summary -> roles -> role.
        // Its bounded depth is intentionally separate from strict, canonical on-disk records.
        internal static string PublicMatrixReportJson(Dictionary<string,object> report){
            MatrixRuntimeCheck.Keys(report,PublicReportKeys);MatrixRuntimeCheck.Need(Object.Equals(report["schema"],"p6_r7_appid_matrix_runtime_v2")&&Object.Equals(report["mode"],"apply_local_matrix"));
            string text=new JavaScriptSerializer{MaxJsonLength=16384,RecursionLimit=6}.Serialize(report);MatrixRuntimeCheck.Need(Encoding.UTF8.GetByteCount(text)<=16384);return text;
        }
        static Dictionary<string,object> StartReport(){Dictionary<string,object> report=Base("apply_local_matrix");report["native_executed"]=true;report["cleanup_pending"]=true;report["failure_stage"]=0;report["rows"]=null;return report;}
        internal static MatrixExpected Expected(MatrixRuntimeFiles files){Dictionary<string,object> j=MatrixRecords.Parse(files.Read("prepared.json"));MatrixExpected e=new MatrixExpected{Attempt=files.Attempt,Nonce=j["nonce"] as string,OwnerHash=j["coordinator_sha256"] as string,ImageHash=j["image_sha256"] as string,OwnerTokenDigest=j["coordinator_token_digest"] as string,OwnerPid=MatrixRuntimeCheck.Number(j["coordinator_pid"]),OwnerCreation=MatrixRuntimeCheck.Time(j["coordinator_creation"]),BrokerPort=(int)MatrixRuntimeCheck.Number(j["broker_port"])};using(CoordinatorBoundary boundary=new CoordinatorBoundary(MatrixContract.Scope(e.Attempt),e.BrokerPort,files.Image))e.BlobDigest=boundary.BlobDigest;MatrixRecords.ValidateOwned(MatrixRecords.Json(j),e);MatrixRuntimeCheck.Need(TokenProof.Hash(files.Source)==e.OwnerHash&&TokenProof.Hash(files.Image)==e.ImageHash);return e;}
        static Dictionary<string,object> Lease(MatrixExpected e,string action,uint pid,ulong created,string digest){return new Dictionary<string,object>{{"schema","matrix_helper_lease_v1"},{"attempt",e.Attempt.ToString("D")},{"scope",MatrixContract.Scope(e.Attempt).ToString("D")},{"nonce",e.Nonce},{"action",action},{"helper_pid",pid},{"helper_creation",created.ToString()},{"helper_token_digest",digest},{"helper_sha256",e.OwnerHash}};}
        static int Helper(Guid id,string action){
            MatrixRuntimeFiles files=null;MatrixHelperProof proof=null;MatrixRuleAdapter rules=null;MatrixExpected expected=null;Dictionary<string,object> journal=null,eventCapture=null;string receiptAction=action=="rollback"?"install_rollback":action;ushort? weight=null;bool completed=false,rolledBack=false,closed=true;int stage=1;
            try{MediumIdentity current=MatrixRuntimeCheck.Token(Native.GetCurrentProcess());MatrixRuntimeCheck.Need(current.Type==1&&current.Elevated==1&&current.ElevationType==2&&current.AppContainer==0);files=new MatrixRuntimeFiles(id,current.User,false);expected=Expected(files);proof=new MatrixHelperProof(files,expected,action=="cleanup"?"closed.json":"prepared.json");journal=proof.Journal;uint pid=CoordinatorNative.GetProcessId(Native.GetCurrentProcess());ulong created=TokenProof.Creation(Native.GetCurrentProcess());Dictionary<string,object> lease=Lease(expected,action,pid,created,MatrixNativeIdentity.Digest(current));files.Write(action+"-ready.json",lease);MatrixRuntimeCheck.Need(files.WaitRead(action+"-ack.json",30000)==MatrixRecords.Json(lease));proof.Prove();rules=new MatrixRuleAdapter(expected,proof.Prove);
                stage=2;if(action=="install"){
                    rules.Install(files.Read("prepared.json"));
                    // Event collection is optional evidence. Its failure never changes rule ownership or cleanup.
                    try{MatrixRuntimeCheck.Need(rules.AssignedWeight.HasValue);Dictionary<string,object> binding=MatrixNetEvents.InstallBinding(expected,rules.AssignedWeight.Value,proof.Prove);MatrixNetEvents.ValidateBinding(expected,rules.AssignedWeight.Value,binding);files.Write("event-binding.json",EventRecord(expected,"binding",pid,created,binding));files.ReadPinned("event-binding.json");}catch{}
                }else{
                    Dictionary<string,object> install=MatrixRecords.Parse(files.Read("install-receipt.json"));weight=checked((ushort)MatrixRuntimeCheck.Number(install["assigned_sublayer_weight"]));MatrixRecords.ValidateReceipt(MatrixRecords.Json(install),expected,MatrixRecords.ValidateOwned(files.Read("prepared.json"),expected),"install",MatrixRuntimeCheck.Number(install["helper_pid"]),MatrixRuntimeCheck.Time(install["helper_creation"]),weight);
                    if(action=="cleanup"){
                        try{string bindingText=files.ReadPinned("event-binding.json"),probeText=files.ReadPinned("event-probes.json");Dictionary<string,object> binding=EventValue(bindingText,expected,"binding",MatrixRuntimeCheck.Number(install["helper_pid"]),MatrixRuntimeCheck.Time(install["helper_creation"]));MatrixNetEvents.ValidateBinding(expected,weight.Value,binding);object probes=ProbeValues(probeText,expected);Action eventProof=delegate{proof.Prove();MatrixRuntimeCheck.Need(files.Read("event-binding.json")==bindingText&&files.Read("event-probes.json")==probeText);};eventCapture=MatrixNetEvents.Capture(expected,weight.Value,binding,probes,eventProof);eventProof();}catch{eventCapture=null;}
                        rules.Cleanup(files.Read("closed.json"),weight.Value);
                    }else rules.RollbackPrepared(files.Read("prepared.json"),weight);
                }
                proof.Prove();weight=rules.AssignedWeight;completed=action=="install"||rules.PostAbsence;
            }catch{if(action=="install"&&rules!=null&&rules.RollbackVerified&&expected!=null&&journal!=null){rolledBack=true;receiptAction="install_rollback";weight=rules.AssignedWeight;}}
            finally{if(rules!=null){try{rules.Dispose();}catch{closed=false;}}if(proof!=null)closed=proof.CloseVerified()&&closed;}
            try{if((completed||rolledBack)&&closed&&!MatrixHandleLedger.AnyCloseFailure){stage=3;files.Write((action=="rollback"?"rollback":receiptAction)+"-receipt.json",MatrixRecords.Receipt(expected,journal,receiptAction,CoordinatorNative.GetProcessId(Native.GetCurrentProcess()),TokenProof.Creation(Native.GetCurrentProcess()),weight));if(completed&&action=="cleanup"&&eventCapture!=null){try{files.Write("event-receipt.json",EventRecord(expected,"capture",CoordinatorNative.GetProcessId(Native.GetCurrentProcess()),TokenProof.Creation(Native.GetCurrentProcess()),eventCapture));}catch{}}}else completed=rolledBack=false;}catch{completed=rolledBack=false;}finally{Diagnostic(files,action+"-report.json",stage,completed&&closed);if(files!=null)closed=files.CloseVerified()&&closed;}
            closed=closed&&!MatrixHandleLedger.AnyCloseFailure;return completed&&closed?0:rolledBack&&closed?3:4;
        }
        static MatrixHelperRun Invoke(MatrixRuntimeFiles files,MatrixExpected expected,string action,ushort? assigned,string eventBinding=null,string eventProbes=null){
            MatrixHelperRun result=new MatrixHelperRun();MatrixHandleLedger handles=new MatrixHandleLedger();try{files.Verify();CoordinatorNative.ShellInfo shell=new CoordinatorNative.ShellInfo{Size=(uint)Marshal.SizeOf(typeof(CoordinatorNative.ShellInfo)),Mask=0x40|0x100|0x400,Verb="runas",File=files.Source,Parameters="--matrix-helper "+expected.Attempt.ToString("D")+" "+action,Directory=files.Directory,Show=0};result.LaunchAttempted=true;bool launched=CoordinatorNative.ShellExecuteExW(ref shell);uint error=unchecked((uint)Marshal.GetLastWin32Error());result.LaunchReturned=true;result.Launched=launched;result.LaunchError=launched?(uint?)null:error;result.ProcessHandleObserved=shell.Process!=IntPtr.Zero;if(shell.Process!=IntPtr.Zero)handles.Own(shell.Process);Guard.Win32(launched,error,"matrix_helper_launch_failed");MatrixRuntimeCheck.Need(shell.Process!=IntPtr.Zero);uint pid=CoordinatorNative.GetProcessId(shell.Process);ulong created=TokenProof.Creation(shell.Process);result.ReadyWaitAttempted=true;string readyText=files.WaitRead(action+"-ready.json",30000);bool ready=readyText!=null;result.ReadyObserved=ready;MatrixRuntimeCheck.Need(ready);MatrixRuntimeCheck.Need(Native.WaitForSingleObject(shell.Process,0)==258);TokenProof.Image(shell.Process,files.Source);MediumIdentity token=MatrixRuntimeCheck.Token(shell.Process),owner=MatrixRuntimeCheck.Token(Native.GetCurrentProcess());MatrixRuntimeCheck.Need(token.Type==1&&token.Elevated==1&&token.ElevationType==2&&token.AppContainer==0&&token.User==owner.User&&token.Session==owner.Session);Dictionary<string,object> lease=Lease(expected,action,pid,created,MatrixNativeIdentity.Digest(token));MatrixRuntimeCheck.Need(readyText==MatrixRecords.Json(lease));files.Verify();result.LiveBound=true;files.Write(action+"-ack.json",lease);
                result.ExitWaitAttempted=true;uint waited=Native.WaitForSingleObject(shell.Process,30000);result.ExitWaitResult=waited;MatrixRuntimeCheck.Need(waited==0&&CoordinatorNative.GetProcessId(shell.Process)==pid&&TokenProof.Creation(shell.Process)==created);uint exit;MatrixNativeApi.Win(Native.GetExitCodeProcess(shell.Process,out exit),"matrix_helper_exit_failed");result.Exited=true;result.Exit=exit;files.Verify();string receiptAction=action=="rollback"?"install_rollback":action;string receiptName=action=="rollback"?"rollback":action;if(action=="install"&&exit==3){receiptAction="install_rollback";receiptName="install_rollback";result.Rollback=true;}MatrixRuntimeCheck.Need(exit==0||result.Rollback);result.ReceiptReadAttempted=true;Dictionary<string,object> receipt=MatrixRecords.Parse(files.Read(receiptName+"-receipt.json"));object raw=receipt["assigned_sublayer_weight"];result.Weight=raw==null?(ushort?)null:checked((ushort)MatrixRuntimeCheck.Number(raw));if(assigned.HasValue)MatrixRuntimeCheck.Need(result.Weight==assigned);MatrixRecords.ValidateReceipt(MatrixRecords.Json(receipt),expected,MatrixRecords.ValidateOwned(files.Read(action=="cleanup"?"closed.json":"prepared.json"),expected),receiptAction,pid,created,result.Weight);result.Receipt=true;
                // Only an actual bound helper exit plus the original rule receipt can admit event files.
                try{
                    if(action=="install"&&exit==0&&result.Weight.HasValue){string text=files.ReadPinned("event-binding.json");Dictionary<string,object> binding=EventValue(text,expected,"binding",pid,created);MatrixNetEvents.ValidateBinding(expected,result.Weight.Value,binding);result.EventBinding=text;}
                    if(action=="cleanup"&&eventBinding!=null&&eventProbes!=null&&result.Weight.HasValue){MatrixRuntimeCheck.Need(files.Read("event-binding.json")==eventBinding&&files.Read("event-probes.json")==eventProbes);Dictionary<string,object> envelope=MatrixRecords.Parse(eventBinding);Dictionary<string,object> binding=EventValue(eventBinding,expected,"binding",MatrixRuntimeCheck.Number(envelope["helper_pid"]),MatrixRuntimeCheck.Time(envelope["helper_creation"]));Dictionary<string,object> capture=EventValue(files.ReadPinned("event-receipt.json"),expected,"capture",pid,created);result.EventCapturePresent=true;object probes=ProbeValues(eventProbes,expected);result.EventMatched=MatrixNetEvents.ValidateCapture(expected,result.Weight.Value,binding,probes,capture);result.EventSummary=MatrixNetEvents.SafeSummary(expected,result.Weight.Value,binding,probes,capture);}
                }catch{result.EventBinding=null;result.EventMatched=false;result.EventSummary=null;}
            }catch{}finally{result.HandlesCloseAttempted=true;result.HandlesClosed=handles.CloseAll();}return result;
        }
        static int Coordinator(){
            Dictionary<string,object> report=StartReport();Guid id=Guid.NewGuid();runningAttempt=id;report["attempt_id"]=id.ToString("D");int stage=0;MatrixRuntimeFiles files=null;MatrixPinnedAttempt pin=null;MatrixOwnedProbe child=null;MatrixOwnedPipes pipes=null;MatrixSocketFixtures fixtures=null;TcpListener broker=null;Socket accepted=null,outsider=null;MatrixRuntimePump stdout=null,stderr=null;MatrixExpected expected=null;MatrixHelperRun install=null,cleanup=null;bool owned=false,wrong=false,marker=false,normal=false,stdio=false,job0=false,exactChild=false,postpin=false,drained=false,fixtureDrainEvidence=false,closed=true,removed=false,helperclosed=true,protocol=false,fixtureReady=false,rulesPossiblyPresent=false;bool noChild=true,jobConstructionAttempted=false,probeWindows=true,zeroReceives=false;string eventProbes=null;ushort? weight=null;
            try{stage=1;MatrixRuntimeCheck.Need(IntPtr.Size==8);MediumIdentity owner=MatrixRuntimeCheck.Token(Native.GetCurrentProcess());MatrixRuntimeCheck.Need(owner.IsMedium);files=new MatrixRuntimeFiles(id,owner.User,true);broker=new TcpListener(IPAddress.Loopback,0);broker.Server.ExclusiveAddressUse=true;broker.Start(2);int port=((IPEndPoint)broker.LocalEndpoint).Port;stage=2;fixtures=new MatrixSocketFixtures(port);fixtureReady=fixtures.Ready;MatrixRuntimeCheck.Need(fixtureReady);
                string hash=TokenProof.Hash(files.Source),digest;using(CoordinatorBoundary boundary=new CoordinatorBoundary(MatrixContract.Scope(id),port,files.Image))digest=boundary.BlobDigest;expected=new MatrixExpected{Attempt=id,Nonce=MatrixRuntimeCheck.Random(),OwnerHash=hash,ImageHash=hash,OwnerTokenDigest=MatrixNativeIdentity.Digest(owner),OwnerPid=CoordinatorNative.GetProcessId(Native.GetCurrentProcess()),OwnerCreation=TokenProof.Creation(Native.GetCurrentProcess()),BrokerPort=port,BlobDigest=digest};files.Write("prepared.json",MatrixRecords.Owned(expected,"prepared",null,null));pin=new MatrixPinnedAttempt(expected,files.Read("prepared.json"));jobConstructionAttempted=true;child=new MatrixOwnedProbe(pin);stage=3;rulesPossiblyPresent=true;install=Invoke(files,expected,"install",null);helperclosed=install.Exited&&install.HandlesClosed;if(install.Rollback&&install.Receipt&&helperclosed){removed=true;rulesPossiblyPresent=false;}MatrixRuntimeCheck.Need(install.Accepted);weight=install.Weight;MatrixRuntimeCheck.Need(weight.HasValue);stage=4;
                files.Write("spawning.json",MatrixRecords.Owned(expected,"spawning",null,null));pipes=new MatrixOwnedPipes();stdout=new MatrixRuntimePump(pipes.OutputReader);stderr=new MatrixRuntimePump(pipes.ErrorReader);child.CreateSuspended(pipes);noChild=false;files.Write("bound.json",MatrixRecords.Owned(expected,"bound",child.ChildPid,child.ChildCreation));child.Resume();ReadMessage(stdout,"ready",expected.Nonce,"kind,nonce");Native.JobAccounting active=child.QueryJob();MatrixRuntimeCheck.Need(active.Active==1&&active.Total==1);stage=5;
                outsider=new Socket(AddressFamily.InterNetwork,SocketType.Stream,ProtocolType.Tcp);outsider.Connect(IPAddress.Loopback,port);accepted=Accept(broker,2000);wrong=!child.AdmitBrokerPeer(accepted);closed=CloseSocket(accepted)&&closed;accepted=null;closed=CloseSocket(outsider)&&closed;outsider=null;MatrixRuntimeCheck.Need(wrong&&closed);
                string markerValue=MatrixRuntimeCheck.Random();Dictionary<string,object> command=Message("broker",expected.Nonce);command["port"]=port;command["marker"]=markerValue;MatrixRuntimePump.Send(pipes.InputWriter,command);accepted=Accept(broker,5000);owned=child.AdmitBrokerPeer(accepted);MatrixRuntimeCheck.Need(owned);byte[] bytes=Encoding.ASCII.GetBytes(markerValue);SocketReceive(accepted,bytes);SocketSend(accepted,bytes);closed=CloseSocket(accepted)&&closed;accepted=null;ReadMessage(stdout,"broker_done",expected.Nonce,"kind,nonce");marker=true;stage=6;
                Dictionary<string,object>[] challenges=fixtures.Challenges();MatrixRuntimeCheck.Need(challenges.Length==8);List<Dictionary<string,object>> outcomes=new List<Dictionary<string,object>>();
                for(int index=0;index<8;index++){
                    Dictionary<string,object> challenge=challenges[index];MatrixRuntimeCheck.Need(Object.Equals(challenge["role"],MatrixContract.Roles[index]));Dictionary<string,object> row=Message("row",expected.Nonce);row["index"]=index;row["challenge"]=challenge;ulong before=MatrixSocketFixtures.NowFileTime();MatrixRuntimePump.Send(pipes.InputWriter,row);Dictionary<string,object> response=ReadMessage(stdout,"row_outcome",expected.Nonce,"kind,nonce,index,row");ulong after=MatrixSocketFixtures.NowFileTime();MatrixRuntimeCheck.Need(MatrixRuntimeCheck.Number(response["index"])==index);Dictionary<string,object> outcome=response["row"] as Dictionary<string,object>;MatrixRuntimeCheck.Need(outcome!=null&&Object.Equals(outcome["role"],MatrixContract.Roles[index])&&Object.Equals(outcome["marker"],challenge["marker"]));probeWindows=MatrixSocketFixtures.ValidateProbeWindow(challenge,outcome,before,after)&&probeWindows;outcomes.Add(outcome);
                }
                fixtures.Complete(outcomes.ToArray());
                if(probeWindows&&install.EventBinding!=null){try{Dictionary<string,object> evidence=new Dictionary<string,object>{{"schema","matrix_runtime_event_probes_v2"},{"attempt_id",id.ToString("D")},{"nonce",expected.Nonce},{"rows",fixtures.EventProbes()}};files.Write("event-probes.json",evidence);eventProbes=files.ReadPinned("event-probes.json");MatrixRuntimeCheck.Need(eventProbes==MatrixRecords.Json(evidence));}catch{eventProbes=null;}}
                MatrixRuntimePump.Send(pipes.InputWriter,Message("finish",expected.Nonce));ReadMessage(stdout,"done",expected.Nonce,"kind,nonce");protocol=true;normal=child.WaitForExit(5000);stage=7;
            }catch{report["failure_stage"]=stage;}
            finally{
                // Every branch reaches real owned cleanup; unknown proofs remain pending.
                closed=CloseSocket(accepted)&&closed;closed=CloseSocket(outsider)&&closed;
                if(child!=null){noChild=!child.ChildCreated;try{child.StopAndObserve();job0=child.JobZeroProven;exactChild=noChild?job0&&child.LastAccounting.HasValue&&child.LastAccounting.Value.Total==0:child.ExitIdentityProven;normal=normal&&child.ExitBeforeTermination==0;}catch{job0=exactChild=false;}}
                else{job0=true;exactChild=true;}
                if(pipes!=null){try{closed=pipes.CloseChildEndsForCleanup()&&closed;}catch{closed=false;}}
                if(stdout!=null&&stderr!=null)stdio=stdout.Drain(5000,true)&stderr.Drain(5000,true);else stdio=noChild;
                try{if(pin!=null)pin.Verify();if(files!=null)files.Verify();postpin=files!=null;}catch{postpin=false;}
                try{drained=fixtures==null||fixtures.DrainVerified();fixtureDrainEvidence=fixtures!=null&&drained;if(!rulesPossiblyPresent&&noChild&&!fixtureReady)drained=true;if(broker!=null){int extras=0;while(broker.Pending()&&extras<16){Socket extra=broker.AcceptSocket();closed=CloseSocket(extra)&&closed;extras++;}drained=drained&&extras==0&&!broker.Pending();}}catch{drained=false;}
                if(rulesPossiblyPresent&&helperclosed&&job0&&exactChild&&expected!=null&&weight.HasValue){try{if(noChild){cleanup=Invoke(files,expected,"rollback",weight);}else{files.Write("closed.json",MatrixRecords.Owned(expected,"closed",child.ChildPid,child.ChildCreation));cleanup=Invoke(files,expected,"cleanup",weight,install.EventBinding,eventProbes);}removed=cleanup.Accepted;helperclosed=helperclosed&&cleanup.Exited&&cleanup.HandlesClosed;}catch{removed=false;}}
                else if(!rulesPossiblyPresent)removed=true;
                if(child!=null){try{if(removed){closed=(noChild?child.CloseNeverCreated(true):child.CloseAfterVerifiedRulesRemoval(true))&&closed;}else{child.Dispose();closed=child.HandlesClosed&&closed;}}catch{closed=false;try{child.Dispose();}catch{}}}
                if(pipes!=null)closed=pipes.CloseVerified()&&closed;if(pin!=null)closed=pin.CloseVerified()&&closed;
                if(fixtures!=null){report["rows"]=fixtures.Rows();report["all_negative_roles_blocked"]=fixtures.AllNegativeBlocked;zeroReceives=fixtures.ZeroReceivesVerified;closed=fixtures.CloseVerified()&&closed;}else report["all_negative_roles_blocked"]=false;
                if(broker!=null)closed=CloseSocket(broker.Server)&&closed;RetrySocketCloses();if(files!=null)closed=files.CloseVerified()&&closed;
            }
            closed=closed&&!MatrixHandleLedger.AnyCloseFailure;bool clean=MatrixRuntimePolicy.CleanupComplete(removed,helperclosed,exactChild,job0,stdio,drained,closed);bool allDrops=cleanup!=null&&cleanup.Accepted&&cleanup.EventMatched;bool eventEvidence=MatrixRuntimePolicy.EventGate(install!=null&&install.Accepted&&install.EventBinding!=null,cleanup!=null&&cleanup.Accepted,allDrops,zeroReceives,protocol&&probeWindows);bool passed=fixtureReady&&protocol&&normal&&owned&&wrong&&marker&&postpin&&clean&&eventEvidence;report["all_own_filter_drops_matched"]=allDrops;report["event_matrix_passed"]=passed;report["event_probe_windows_verified"]=protocol&&probeWindows;report["zero_receives_verified"]=zeroReceives;report["event_diagnostic"]=EventDiagnostic(install,cleanup,eventProbes!=null);
            report["fixture_ready"]=fixtureReady;report["owned_peer_admitted"]=owned;report["wrong_peer_rejected"]=wrong;report["marker_round_trip"]=marker;report["normal_child_exit0"]=normal;report["no_child_created"]=noChild;report["no_job_created"]=child!=null?(object)false:jobConstructionAttempted?null:(object)true;report["exact_child_closed"]=noChild?null:(object)exactChild;report["job_active0"]=child==null?null:(object)job0;report["stdio_eof"]=pipes==null?null:(object)stdio;report["socket_drain"]=fixtures==null?null:(object)fixtureDrainEvidence;report["post_pin"]=postpin;report["helper_actual_closed"]=install==null?null:(object)helperclosed;report["rules_postabsence"]=install==null?null:(object)removed;report["all_handles_closed"]=closed;report["cleanup_pending"]=!clean;report["matrix_passed"]=passed;report["install_diagnostic"]=HelperDiagnostic(install);report["cleanup_diagnostic"]=HelperDiagnostic(cleanup);Console.WriteLine(PublicMatrixReportJson(report));return passed?0:2;
        }
        static Dictionary<string,object> SyntheticPublicReport(bool fixtureReady){
            Dictionary<string,object> report=StartReport();report["cleanup_pending"]=!fixtureReady;report["matrix_passed"]=fixtureReady;report["all_own_filter_drops_matched"]=fixtureReady;report["event_matrix_passed"]=fixtureReady;report["all_negative_roles_blocked"]=false;report["attempt_id"]="11111111-1111-4111-8111-111111111111";
            List<object> rows=new List<object>(),roles=new List<object>();for(int i=0;i<8;i++){rows.Add(new Dictionary<string,object>{{"role",MatrixContract.Roles[i]},{"fixture_status","ready"},{"fixture_available",fixtureReady},{"local_address_verified",fixtureReady},{"host_positive",fixtureReady},{"host_drain_complete",fixtureReady},{"operation_completed",fixtureReady},{"socket_error",10035},{"accepted_connections",0},{"received_datagrams",0},{"received_bytes",0},{"listener_drain_complete",fixtureReady},{"outcome","incomplete"}});roles.Add(new Dictionary<string,object>{{"role",MatrixContract.Roles[i]},{"matched",fixtureReady},{"matched_count",fixtureReady?1:0}});}if(fixtureReady)report["rows"]=rows;
            Dictionary<string,object> summary=new Dictionary<string,object>{{"collection_enabled",true},{"enumeration_complete",true},{"resources_closed",true},{"error_stage",0},{"api_status",null},{"roles",roles}};
            report["event_probe_windows_verified"]=fixtureReady;report["zero_receives_verified"]=fixtureReady;
            report["fixture_ready"]=fixtureReady;report["owned_peer_admitted"]=fixtureReady;report["wrong_peer_rejected"]=fixtureReady;report["marker_round_trip"]=fixtureReady;report["normal_child_exit0"]=fixtureReady;report["no_child_created"]=!fixtureReady;report["no_job_created"]=!fixtureReady;report["exact_child_closed"]=fixtureReady?(object)true:null;report["job_active0"]=fixtureReady?(object)true:null;report["stdio_eof"]=fixtureReady?(object)true:null;report["socket_drain"]=fixtureReady?(object)true:null;report["post_pin"]=fixtureReady;report["helper_actual_closed"]=fixtureReady?(object)true:null;report["rules_postabsence"]=fixtureReady?(object)true:null;report["all_handles_closed"]=true;
            MatrixHelperRun helper=new MatrixHelperRun{LaunchAttempted=true,LaunchReturned=true,Launched=true,ProcessHandleObserved=true,ReadyWaitAttempted=true,ReadyObserved=true,LiveBound=true,ExitWaitAttempted=true,ExitWaitResult=0,Exited=true,Exit=0,ReceiptReadAttempted=true,Receipt=true,HandlesCloseAttempted=true,HandlesClosed=true};helper.EventBinding="synthetic";helper.EventCapturePresent=true;helper.EventSummary=summary;MatrixHelperRun observed=fixtureReady?helper:null;report["event_diagnostic"]=EventDiagnostic(observed,observed,fixtureReady);report["install_diagnostic"]=HelperDiagnostic(observed);report["cleanup_diagnostic"]=HelperDiagnostic(observed);return report;
        }
        static int SelfTest(){
            int assertions=0;for(int bits=0;bits<128;bits++){bool got=MatrixRuntimePolicy.CleanupComplete((bits&1)!=0,(bits&2)!=0,(bits&4)!=0,(bits&8)!=0,(bits&16)!=0,(bits&32)!=0,(bits&64)!=0);MatrixRuntimeCheck.Need(got==(bits==127));assertions++;}for(int bits=0;bits<32;bits++){bool got=MatrixRuntimePolicy.HelperAccepted((bits&1)!=0,(bits&2)!=0,(bits&4)!=0?0u:1u,(bits&8)!=0,(bits&16)!=0);MatrixRuntimeCheck.Need(got==(bits==31));assertions++;}foreach(string bad in new string[]{null,"","a\nb","a\rb",new string('x',8193)}){MatrixRuntimeCheck.Need(!MatrixRuntimePolicy.ProtocolLine(bad));assertions++;}MatrixRuntimeCheck.Need(MatrixRuntimePolicy.ProtocolLine("{}"));assertions++;
            for(int bits=0;bits<32;bits++){MatrixRuntimeCheck.Need(MatrixRuntimePolicy.EventGate((bits&1)!=0,(bits&2)!=0,(bits&4)!=0,(bits&8)!=0,(bits&16)!=0)==(bits==31));assertions++;}
            MatrixExpected expected=new MatrixExpected{Attempt=new Guid("11111111-1111-4111-8111-111111111111"),Nonce=new string('a',64)};
            Dictionary<string,object> value=new Dictionary<string,object>{{"fixed",true}};
            MatrixRuntimeCheck.Need(Object.Equals(EventValue(MatrixRecords.Json(EventRecord(expected,"binding",7,9,value)),expected,"binding",7,9)["fixed"],true));assertions++;
            foreach(string field in new string[]{"schema","attempt_id","nonce","helper_pid","helper_creation","value","extra"}){Dictionary<string,object> record=EventRecord(expected,"binding",7,9,value);record[field]=field=="helper_pid"?(object)8:field=="helper_creation"?(object)"10":field=="value"?(object)false:"PRIVATE";bool rejected=false;try{EventValue(MatrixRecords.Json(record),expected,"binding",7,9);}catch{rejected=true;}MatrixRuntimeCheck.Need(rejected);assertions++;}
            Dictionary<string,object> absent=HelperDiagnostic(null);MatrixRuntimeCheck.Keys(absent,"schema,diagnostic_only,invoked,launch_attempted,launch_returned,launched,launch_error,process_handle_observed,ready_wait_attempted,ready_observed,live_bound,exit_wait_attempted,exit_wait_result,actual_exited,actual_exit,receipt_read_attempted,receipt,handles_close_attempted,handles_closed");assertions++;MatrixRuntimeCheck.Need(Object.Equals(absent["invoked"],false));assertions++;
            foreach(string field in new string[]{"launch_attempted","launch_returned","launched","launch_error","process_handle_observed","ready_wait_attempted","ready_observed","live_bound","exit_wait_attempted","exit_wait_result","actual_exited","actual_exit","receipt_read_attempted","receipt","handles_close_attempted","handles_closed"}){MatrixRuntimeCheck.Need(absent[field]==null);assertions++;}
            MatrixHelperRun observation=new MatrixHelperRun{HandlesCloseAttempted=true,HandlesClosed=true};Dictionary<string,object> projection=HelperDiagnostic(observation);MatrixRuntimeCheck.Need(Object.Equals(projection["invoked"],true)&&Object.Equals(projection["launch_attempted"],false)&&projection["launched"]==null&&projection["ready_observed"]==null&&projection["actual_exited"]==null&&Object.Equals(projection["handles_closed"],true));assertions++;
            observation.LaunchAttempted=observation.LaunchReturned=true;observation.LaunchError=1223;projection=HelperDiagnostic(observation);MatrixRuntimeCheck.Need(Object.Equals(projection["launched"],false)&&Object.Equals(projection["launch_error"],1223u)&&projection["actual_exit"]==null&&projection["receipt"]==null);assertions++;
            observation.Launched=observation.ProcessHandleObserved=observation.ReadyWaitAttempted=true;observation.LaunchError=null;observation.ReadyObserved=false;projection=HelperDiagnostic(observation);MatrixRuntimeCheck.Need(Object.Equals(projection["ready_observed"],false)&&Object.Equals(projection["exit_wait_attempted"],false)&&projection["actual_exited"]==null);assertions++;
            observation.ReadyObserved=true;observation.LiveBound=observation.ExitWaitAttempted=true;observation.ExitWaitResult=258;projection=HelperDiagnostic(observation);MatrixRuntimeCheck.Need(Object.Equals(projection["exit_wait_result"],258u)&&projection["actual_exited"]==null&&projection["actual_exit"]==null&&projection["receipt"]==null);assertions++;
            observation.ExitWaitResult=0;observation.Exited=observation.ReceiptReadAttempted=true;observation.Exit=0;projection=HelperDiagnostic(observation);MatrixRuntimeCheck.Need(Object.Equals(projection["actual_exited"],true)&&Object.Equals(projection["actual_exit"],0u)&&Object.Equals(projection["receipt"],false));assertions++;
            observation.Receipt=true;MatrixRuntimeCheck.Need(observation.Accepted);observation.LaunchAttempted=observation.LaunchReturned=observation.ReadyWaitAttempted=observation.ExitWaitAttempted=observation.ReceiptReadAttempted=observation.HandlesCloseAttempted=false;MatrixRuntimeCheck.Need(observation.Accepted);assertions++;
            Dictionary<string,object> complete=SyntheticPublicReport(true);bool legacyRejected=false;try{MatrixRecords.Json(complete);}catch{legacyRejected=true;}MatrixRuntimeCheck.Need(legacyRejected);assertions++;string projected=PublicMatrixReportJson(complete);Dictionary<string,object> parsed=new JavaScriptSerializer{MaxJsonLength=16384,RecursionLimit=6}.DeserializeObject(projected) as Dictionary<string,object>;MatrixRuntimeCheck.Keys(parsed,PublicReportKeys);Dictionary<string,object> eventDiagnostic=parsed["event_diagnostic"] as Dictionary<string,object>,summary=eventDiagnostic==null?null:eventDiagnostic["capture_summary"] as Dictionary<string,object>;System.Collections.IList projectedRoles=summary==null?null:summary["roles"] as System.Collections.IList;MatrixRuntimeCheck.Need(projectedRoles!=null&&projectedRoles.Count==8&&Encoding.UTF8.GetByteCount(projected)<=16384&&!projected.Contains("PRIVATE"));assertions++;
            Dictionary<string,object> beforeFixture=SyntheticPublicReport(false);MatrixRuntimeCheck.Need(beforeFixture["rows"]==null&&MatrixRuntimeCheck.Number(beforeFixture["failure_stage"])==0&&Object.Equals(beforeFixture["fixture_ready"],false));string incomplete=PublicMatrixReportJson(beforeFixture);Dictionary<string,object> incompleteParsed=new JavaScriptSerializer{MaxJsonLength=16384,RecursionLimit=6}.DeserializeObject(incomplete) as Dictionary<string,object>;MatrixRuntimeCheck.Need(incompleteParsed["rows"]==null&&Object.Equals(incompleteParsed["fixture_ready"],false));assertions++;
            Dictionary<string,object> report=Base("self_test");report["assertions_passed"]=assertions;Console.WriteLine(MatrixRecords.Json(report));return 0;
        }
        [STAThread]public static int Main(string[] args){bool actual=false;try{if(args.Length==0||args.Length==1&&args[0]=="--plan"){Console.WriteLine(MatrixRecords.Json(Base("plan")));return 0;}if(args.Length==1&&args[0]=="--self-test")return SelfTest();if(args.Length==1&&args[0]=="--apply-local-appid-matrix"){actual=true;return Coordinator();}Guid id;if(args.Length==2&&args[0]=="--matrix-probe"&&Guid.TryParseExact(args[1],"D",out id)&&id!=Guid.Empty){actual=true;return Probe(id);}if(args.Length==3&&args[0]=="--matrix-helper"&&Guid.TryParseExact(args[1],"D",out id)&&id!=Guid.Empty&&(args[2]=="install"||args[2]=="cleanup"||args[2]=="rollback")){actual=true;return Helper(id,args[2]);}}catch{}Dictionary<string,object> rejected=Base("rejected");rejected["native_executed"]=actual;rejected["cleanup_pending"]=actual;if(actual){rejected["failure_stage"]=99;if(runningAttempt!=Guid.Empty)rejected["attempt_id"]=runningAttempt.ToString("D");}Console.WriteLine(MatrixRecords.Json(rejected));return 2;}
    }
}
