import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,realpathSync,rmSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const local=name=>fileURLToPath(new URL(name,import.meta.url));
const source=local('./windows_text_gate_appid_matrix_inspect.cs'),code=readFileSync(source,'utf8');
const deps=[local('./windows_text_gate_isolation_helper.cs'),local('./windows_text_gate_appid_startup_helper.cs'),local('../../tmp/p6-r7-review/native-appid-coordinator-candidate-15.cs'),local('../../tmp/p6-r7-review/native-appid-matrix-contract-01.cs'),local('./windows_text_gate_appid_matrix_native.cs')];
const pins=['d22017641d9f8df750f6db7db9319b8c1930a726a8575ff1ffabfde0d5ffdcd8','c777023495ccdbf3b52663f49683f5d84dcfd03a36b3d280a75c925f37b7a1ea','c1f07e9487b8ce25d0acc2d5bbb03b69c975cbb7e448698d288ff6263cff9311','f70ffb86ce5efea2572532e1986f77dde9622893ad4b90a74f9ec40da5ba6774','f2d3b35a1e6d1763930ba7f9a82ab8dbb595e02d5d720216a0161dbce8a0d0ab'];
const hash=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const csc=String.raw`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe`;
const historicalFile=local('../../tmp/p6-r7-review/native-appid-matrix-runtime-actual-02.json');
assert.equal(hash(historicalFile),'767e40d8646cb432ba10c555c6884ba13364a9636c34455e6c1616fc1435e031');
const historical=readFileSync(historicalFile,'utf8').trimEnd();
const literal=value=>'@"'+value.replaceAll('"','""')+'"';
const harness=String.raw`
using System;using System.Collections;using System.Collections.Generic;
namespace HereIAm.R7 {public static class MatrixInspectPureHarness {
 static int count;static void Check(bool condition){if(!condition)throw new Exception("pure_failed_"+count);count++;}static void Reject(Action action){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected);}
 static MatrixExpected Expected(){return new MatrixExpected{Attempt=MatrixInspectProgram.Attempt,Nonce=new string('a',64),ImageHash=MatrixInspectProgram.ImageHash,OwnerHash=MatrixInspectProgram.ImageHash,OwnerTokenDigest=new string('b',64),BlobDigest=new string('0',64),OwnerPid=MatrixInspectProgram.OwnerPid,OwnerCreation=MatrixInspectProgram.OwnerCreation,BrokerPort=MatrixInspectProgram.BrokerPort};}
 public static int Main(){string original=ORIGINAL;MatrixExpected e=Expected();Dictionary<string,object> journal=MatrixRecords.Owned(e,"prepared",null,null);string prepared=MatrixRecords.Json(journal);Check(MatrixInspectProgram.History(prepared,original).Attempt==e.Attempt);
  var medium=new MediumIdentity{Type=1,Integrity=8192,ElevationType=3,Elevated=0,AppContainer=0,Authentication=1};var high=new MediumIdentity{Type=1,Integrity=12288,ElevationType=2,Elevated=1,AppContainer=0,Authentication=2};Check(MatrixInspectProgram.CallerAccepted(medium,false));Check(!MatrixInspectProgram.CallerAccepted(medium,true));Check(MatrixInspectProgram.CallerAccepted(high,true));Check(!MatrixInspectProgram.CallerAccepted(high,false));Check(!MatrixInspectProgram.CallerAccepted(null,true));foreach(string field in new[]{"Type","Integrity","ElevationType","Elevated","AppContainer","Authentication"}){var bad=new MediumIdentity{Type=high.Type,Integrity=high.Integrity,ElevationType=high.ElevationType,Elevated=high.Elevated,AppContainer=high.AppContainer,Authentication=high.Authentication};var info=typeof(MediumIdentity).GetField(field,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);if(field=="Authentication")info.SetValue(bad,0UL);else info.SetValue(bad,field=="AppContainer"?1u:0u);Check(!MatrixInspectProgram.CallerAccepted(bad,true));}
  foreach(string key in new List<string>(journal.Keys)){Dictionary<string,object> bad=new Dictionary<string,object>(journal);bad.Remove(key);Reject(delegate{MatrixInspectProgram.History(MatrixRecords.Json(bad),original);});}
  foreach(string key in new string[]{"schema","attempt_id","scope_id","image_sha256","coordinator_sha256","coordinator_pid","coordinator_creation","broker_port","phase","child_pid","child_creation","child_token_digest"}){Dictionary<string,object> bad=new Dictionary<string,object>(journal);bad[key]="untrusted";Reject(delegate{MatrixInspectProgram.History(MatrixRecords.Json(bad),original);});}
  Dictionary<string,object> report=MatrixRecords.Parse(original);foreach(string key in new string[]{"schema","mode","attempt_id","failure_stage","runtime_implemented","native_executed","cleanup_pending","fixture_ready","no_child_created","job_active0","socket_drain","post_pin","all_handles_closed","matrix_passed","all_own_filter_drops_matched","event_matrix_passed","production_isolation_passed","human_gate_passed","all_negative_roles_blocked","event_probe_windows_verified","zero_receives_verified","owned_peer_admitted","wrong_peer_rejected","marker_round_trip","normal_child_exit0","no_job_created","helper_actual_closed","rules_postabsence","exact_child_closed","stdio_eof","real_upstream_requests","model_turns_requested","rows"}){Dictionary<string,object> bad=new Dictionary<string,object>(report);bad.Remove(key);Reject(delegate{MatrixInspectProgram.History(prepared,MatrixRecords.Json(bad));});}
  Dictionary<string,object> cancel=new Dictionary<string,object>(report);cancel["win32_error"]=1223;Reject(delegate{MatrixInspectProgram.History(prepared,MatrixRecords.Json(cancel));});
  string[] forbidden={"spawning.json","bound.json","closed.json","install-ready.json","install-ack.json","install-receipt.json","install_rollback-receipt.json","cleanup-ready.json","cleanup-ack.json","cleanup-receipt.json","rollback-ready.json","rollback-ack.json","rollback-receipt.json","install-report.json","cleanup-report.json","rollback-report.json","probe-report.json","event-binding.json","event-probes.json","event-receipt.json"};foreach(string name in forbidden)Check(!MatrixInspectProgram.ExactNames(new string[]{"matrix-probe.exe","prepared.json",name}));Check(!MatrixInspectProgram.ExactNames(new string[]{"prepared.json","prepared.json"}));Check(!MatrixInspectProgram.ExactNames(new string[]{"..\\prepared.json","matrix-probe.exe"}));
  Check(!MatrixInspectProgram.Complete(true,true,true,true,true,3,0,true,true,true,true));Check(!MatrixInspectProgram.Complete(true,true,true,true,true,4,0,true,false,true,true));Check(MatrixInspectProgram.PathIdle(false,258)&&MatrixInspectProgram.PathIdle(true,0)&&!MatrixInspectProgram.PathIdle(true,258)&&!MatrixInspectProgram.PathIdle(false,0xffffffff));
  int aborted=0,engineClosed=0;MatrixInspectResources retry=new MatrixInspectResources(delegate(IntPtr h){return true;},delegate(IntPtr h){aborted++;return aborted==1?5u:0u;},delegate(IntPtr h){engineClosed++;return 0;});retry.Engine=new IntPtr(1);retry.Transaction=true;Check(!MatrixInspectProgram.Finish(retry));Check(retry.Empty&&!retry.CloseSucceeded&&aborted==2&&engineClosed==1&&retry.CloseError==5u);
  bool canClose=false;MatrixInspectResources retained=new MatrixInspectResources(delegate(IntPtr h){return canClose;},delegate(IntPtr h){return 0;},delegate(IntPtr h){return 0;});retained.Handles.Own(new IntPtr(2));Check(!MatrixInspectProgram.Finish(retained)&&!retained.Empty&&retained.Handles.Owns(new IntPtr(2)));canClose=true;Check(!MatrixInspectProgram.Finish(retained)&&retained.Empty&&!retained.CloseSucceeded);
  Console.WriteLine("{\"pure_assertions\":"+count+",\"native_executed\":false}");return 0;
 }
}}
`.replace('ORIGINAL',literal(historical));

test('fixed never-started matrix inspector: compile and pure checks only',async t=>{
 deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));const parent=local('../../tmp/p6-r7-helper/'),tmp=mkdtempSync(path.join(parent,'matrix-inspect-test-'));
 t.after(()=>{deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));assert.equal(hash(historicalFile),'767e40d8646cb432ba10c555c6884ba13364a9636c34455e6c1616fc1435e031');const canonical=realpathSync(tmp);assert.equal(path.dirname(canonical),realpathSync(parent));assert.match(path.basename(canonical),/^matrix-inspect-test-/);rmSync(canonical,{recursive:true,force:true});});
 await t.test('fixed scope and read-only API boundary',()=>{
  assert.doesNotMatch(code,/FwpmFilterAdd|FwpmFilterDelete|FwpmSubLayerAdd|FwpmSubLayerDelete|FwpmTransactionCommit|FwpmEngineSetOption|FwpmNetEvent|ShellExecute|CreateProcess|TerminateProcess|TerminateJob|CreateDirectory|SetAccessControl|FileMode\.Create|WriteAll|WriteRecord|RunAs|Process\.Start/);
  assert.ok(code.includes('FwpmTransactionBegin0(resources.Engine,1)'));assert.ok(code.includes('MatrixContract.Rules(Attempt,BrokerPort)'));assert.ok(code.includes('CoordinatorBoundary.Key(MatrixContract.Scope(Attempt),"sublayer")'));assert.ok(code.includes('CreateToolhelp32Snapshot(2,0)'));assert.ok(code.includes('count<=8192'));assert.ok(code.includes('MatrixNativeIdentity.Digest(current)==expected.OwnerTokenDigest'));assert.ok(code.includes('resources.Handles.Own(process)'));assert.ok(code.includes('MatrixNativeApi.VerifyPath'));
  for(const pin of ['74fe88f74597e31ebd2af6dca727ae8ab458a5363977b514a48023b790bd803d','767e40d8646cb432ba10c555c6884ba13364a9636c34455e6c1616fc1435e031','eb039cb1778f0b56e322ca97feeeea6d7675efecc7a8a9de3b4eb377e0f3462a'])assert.ok(code.includes(pin));
 });
 const exe=path.join(tmp,'inspect.exe'),pure=path.join(tmp,'pure.exe'),harnessFile=path.join(tmp,'pure.cs');writeFileSync(harnessFile,harness);
 const compile=(main,out,extra=[])=>{const run=spawnSync(csc,['/nologo','/platform:x64','/warnaserror+','/target:exe','/reference:System.Web.Extensions.dll',`/main:${main}`,`/out:${out}`,...deps,source,...extra],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(run.status,0,run.stdout+run.stderr);};
 compile('HereIAm.R7.MatrixInspectProgram',exe);compile('HereIAm.R7.MatrixInspectPureHarness',pure,[harnessFile]);
 await t.test('plan/selftest/rejected arguments never execute inspection or claim history closed',()=>{for(const args of [[],['--plan'],['--self-test'],['--inspect-never-started-fixed','unexpected'],['--apply'],['--inspect-never-started-fixed','56e435bd-05cb-4569-b86d-ba884d2eb717']]){const run=spawnSync(exe,args,{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,args.length===0||args.length===1&&['--plan','--self-test'].includes(args[0])?0:2,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.native_executed,false);assert.equal(result.cleanup_pending,true);assert.equal(result.inspection_complete,false);assert.equal(result.exact_child_closed,null);assert.equal(result.job_active0,null);assert.equal(result.helper_launch_error_known,false);assert.equal(result.filters_deleted_count,0);assert.equal(result.sublayers_deleted_count,0);assert.equal(result.production_isolation_passed,false);if(args[0]==='--self-test'){assert.equal(result.pure_assertions,1027);process.stdout.write(`selftest_assertions=${result.pure_assertions}\n`);}}});
 await t.test('historical no-child, pending policy, wrong scope, post-start files and retained close negatives',()=>{const run=spawnSync(pure,[],{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,0,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.native_executed,false);assert.ok(result.pure_assertions>=85);process.stdout.write(`pure_assertions=${result.pure_assertions}\n`);});
 await t.test('SDK proves native snapshot layout and read-only transaction constant without execution',()=>{
  const cpp='#include <windows.h>\n#include <tlhelp32.h>\n#include <fwpmu.h>\n#include <stddef.h>\nstatic_assert(sizeof(PROCESSENTRY32W)==568,"size");\nstatic_assert(offsetof(PROCESSENTRY32W,th32ProcessID)==8,"pid");\nstatic_assert(offsetof(PROCESSENTRY32W,th32DefaultHeapID)==16,"heap");\nstatic_assert(offsetof(PROCESSENTRY32W,szExeFile)==44,"name");\nstatic_assert(TH32CS_SNAPPROCESS==2,"snapshot");\nstatic_assert(FWPM_TXN_READ_ONLY==1,"readOnly");\n';
  const file=path.join(tmp,'abi.cpp'),obj=path.join(tmp,'abi.obj');writeFileSync(file,cpp);const vc=String.raw`C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.50.35717`,sdk=String.raw`C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0`;
  const run=spawnSync(path.join(vc,'bin','Hostx64','x64','cl.exe'),['/nologo','/c','/TP','/W4','/WX',`/I${path.join(vc,'include')}`,...['ucrt','shared','um'].map(p=>`/I${path.join(sdk,p)}`),`/Fo${obj}`,file],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(run.status,0,run.stdout+run.stderr);
 });
});
