// Standalone, Medium witness. No CLI/network/WFP/helper implementation.
// Default is plan; only explicit apply starts the witness-owned Node target.
using System;using System.IO;using System.Text;using System.Collections.Generic;using System.Collections.Concurrent;using System.Diagnostics;using System.Globalization;using System.Runtime.InteropServices;using System.Security.Cryptography;using System.Threading.Tasks;using System.Web.Script.Serialization;
namespace HereIAm.R7.InflightHostFault {
internal static class Check {
 internal static void Need(bool ok){if(!ok)throw new InvalidOperationException("host_fault_unconfirmed");}
 internal static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=16384,RecursionLimit=16};
 internal static Dictionary<string,object> Parse(string s){Need(s!=null&&s.Length<=16384);new Syntax(s).Run();var d=Json.DeserializeObject(s) as Dictionary<string,object>;Need(d!=null);return d;}
 internal static void Keys(Dictionary<string,object>d,string names){string[] a=names.Split(',');Need(d!=null&&d.Count==a.Length);foreach(string k in a)Need(d.ContainsKey(k));}
 internal static bool Eq(object a,object b){return Object.Equals(a,b);}
 internal static int Num(object n){Need(n is int);return(int)n;}
 internal static ulong Time(object n){ulong v;Need(n is string&&UInt64.TryParse((string)n,NumberStyles.None,CultureInfo.InvariantCulture,out v)&&v>0&&v.ToString(CultureInfo.InvariantCulture)==(string)n);return UInt64.Parse((string)n,CultureInfo.InvariantCulture);}
 internal static bool Hex(object s){return s is string&&System.Text.RegularExpressions.Regex.IsMatch((string)s,"^[A-Fa-f0-9]{64}$");}
 internal static bool HashEq(object a,object b){return Hex(a)&&Hex(b)&&String.Equals((string)a,(string)b,StringComparison.OrdinalIgnoreCase);}
 internal static Guid Id(object s){Guid id;Need(s is string&&Guid.TryParseExact((string)s,"D",out id)&&id!=Guid.Empty&&id.ToString("D")== (string)s);return Guid.Parse((string)s);}
 internal static string Scope(Guid id){using(var sha=SHA256.Create()){byte[] b=sha.ComputeHash(Encoding.ASCII.GetBytes("HereIAm.P6R7.TaskExecutorV1/"+id.ToString("N")));byte[] g=new byte[16];Array.Copy(b,g,16);return new Guid(g).ToString("D");}}
 internal static readonly string Facts="process_close_observed,job_empty_verified,stdio_eof_verified,rules_absent_verified,handles_closed_verified,helper_exits_verified";
 internal static readonly string Binding="attempt_id,scope_id,nonce,auth_mode,home_class,owner_pid,owner_creation,owner_sha256,cli_sha256,broker_port";
 internal const string Cli="3D6CA7085C932B62EF4EE4877E92F15B050FB94B2EB8E6C10A346A06248C6004";
 internal static void Ready(Dictionary<string,object> r){Keys(r,"schema,attempt_id,child_pid,child_creation,cli_sha256,broker_port,http_created,no_model,default_three_pipes");Need(Eq(r["schema"],"p6_r7_host_fault_ready_v1"));Id(r["attempt_id"]);Need(Num(r["child_pid"])>0);Time(r["child_creation"]);Need(String.Equals((string)r["cli_sha256"],Cli,StringComparison.OrdinalIgnoreCase)&&Num(r["broker_port"])>0&&Num(r["broker_port"])<=65535&&Eq(r["http_created"],true)&&Eq(r["no_model"],true)&&Eq(r["default_three_pipes"],true));}
 internal static void KilledExit(uint exit){Need(exit==77);}
 internal static bool SafeId(object value){return value is string&&System.Text.RegularExpressions.Regex.IsMatch((string)value,@"\A[a-zA-Z0-9_-]{1,128}\z");}
 internal static Dictionary<string,object> Initial(Dictionary<string,object> r){Keys(r,"schema,native_ready,local_session_id,execution_epoch,provider_thread_id");Need(Eq(r["schema"],"p6_r7_inflight_initial_v1"));foreach(string key in new[]{"local_session_id","execution_epoch","provider_thread_id"})Need(SafeId(r[key]));var ready=r["native_ready"] as Dictionary<string,object>;Ready(ready);return ready;}
 internal static void Inflight(Dictionary<string,object> r,Dictionary<string,object> initial){var ready=Initial(initial);Keys(r,"schema,attempt_id,local_session_id,execution_epoch,provider_thread_id,local_turn_id,provider_turn_id,start_command_id,turn_start_dispatched,exchange_entered,exchange_settled,response_released,terminal_observed,text_observed,upstream_attempts,default_three_pipes,snapshot_claim");Need(Eq(r["schema"],"p6_r7_inflight_ready_v1")&&Eq(r["attempt_id"],ready["attempt_id"]));Same(r,initial,"local_session_id,execution_epoch,provider_thread_id");Need(SafeId(r["local_turn_id"])&&SafeId(r["provider_turn_id"])&&Num(r["start_command_id"])==1&&Eq(r["turn_start_dispatched"],true)&&Num(r["exchange_entered"])==1&&Eq(r["exchange_settled"],false)&&Eq(r["response_released"],false)&&Eq(r["terminal_observed"],false)&&Eq(r["text_observed"],false)&&Num(r["upstream_attempts"])==1&&Eq(r["default_three_pipes"],true)&&Eq(r["snapshot_claim"],"local_exchange_pending_at_ready"));}
 internal static void Journal(Dictionary<string,object> j,Dictionary<string,object> r,string hash,string phase){Keys(j,"schema,"+Binding+",owner_token_digest,phase,child_pid,child_creation");Need(Eq(j["schema"],"p6_r7_task_owned_v2")&&Eq(j["attempt_id"],r["attempt_id"])&&Eq(j["scope_id"],Scope(Id(r["attempt_id"])))&&Hex(j["nonce"])&&Hex(j["owner_token_digest"])&&Eq(j["auth_mode"],"chatgpt")&&Eq(j["home_class"],"dedicated_existing")&&HashEq(j["owner_sha256"],hash)&&HashEq(j["cli_sha256"],Cli)&&Num(j["owner_pid"])>0&&Eq(j["broker_port"],r["broker_port"])&&Eq(j["phase"],phase));Time(j["owner_creation"]);if(phase=="prepared")Need(j["child_pid"]==null&&j["child_creation"]==null);else Need(Eq(j["child_pid"],r["child_pid"])&&Eq(j["child_creation"],r["child_creation"])&&!Eq(j["child_pid"],j["owner_pid"]));}
 internal static void Same(Dictionary<string,object>a,Dictionary<string,object>b,string keys){foreach(string k in keys.Split(','))Need(Eq(a[k],b[k]));}
 internal static void Final(Dictionary<string,object> f,Dictionary<string,object>b,uint exit){Keys(f,"schema,"+Binding+",child_pid,child_creation,started,close_command_id,shutdown_trigger,operation_failed,stdout_final_emit_succeeded,receipt,requires_actual_exit_0_or_3,receipt_write_state");Need(Eq(f["schema"],"p6_r7_task_final_receipt_v1"));Same(f,b,Binding+",child_pid,child_creation");Need(exit==3&&Eq(f["started"],true)&&Num(f["close_command_id"])==0&&Eq(f["shutdown_trigger"],"input_eof")&&Eq(f["operation_failed"],true)&&Eq(f["stdout_final_emit_succeeded"],false)&&Eq(f["requires_actual_exit_0_or_3"],true)&&Eq(f["receipt_write_state"],"pending_actual_exit_commit"));var r=f["receipt"] as Dictionary<string,object>;Keys(r,Facts+",cleanup_pending");foreach(string k in Facts.Split(','))Need(Eq(r[k],true));Need(Eq(r["cleanup_pending"],false));}
 // Strict JSON preflight rejects duplicate decoded keys, malformed tokens and depth.
 sealed class Syntax{readonly string s;int p;internal Syntax(string s){this.s=s;}void White(){while(p<s.Length&&" \r\n\t".IndexOf(s[p])>=0)p++;}char Take(){Need(p<s.Length);return s[p++];}string Str(){int start=p;Need(Take()=='"');while(true){char c=Take();Need(c>=32);if(c=='"')break;if(c=='\\'){c=Take();if(c=='u'){for(int i=0;i<4;i++)Need(Uri.IsHexDigit(Take()));}else Need("\"\\/bfnrt".IndexOf(c)>=0);}}return Json.Deserialize<string>(s.Substring(start,p-start));}void Value(int depth){Need(depth<=16);White();Need(p<s.Length);char c=s[p];if(c=='{'){p++;White();var keys=new HashSet<string>(StringComparer.Ordinal);if(p<s.Length&&s[p]=='}'){p++;return;}while(true){White();Need(keys.Add(Str()));White();Need(Take()==':');Value(depth+1);White();char sep=Take();if(sep=='}')return;Need(sep==',');}}if(c=='['){p++;White();if(p<s.Length&&s[p]==']'){p++;return;}while(true){Value(depth+1);White();char sep=Take();if(sep==']')return;Need(sep==',');}}if(c=='"'){Str();return;}var m=System.Text.RegularExpressions.Regex.Match(s.Substring(p),"^(?:true|false|null|-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)");Need(m.Success);p+=m.Length;}internal void Run(){Value(0);White();Need(p==s.Length);}}
}
internal static class Win {
 [StructLayout(LayoutKind.Sequential)]internal struct FileInfo{internal uint Attr,CTLow,CTHigh,ATLow,ATHigh,WTLow,WTHigh,Volume,SizeHigh,SizeLow,Links,IndexHigh,IndexLow;}
 [StructLayout(LayoutKind.Sequential)]struct FT{internal uint Low,High;}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]internal static extern IntPtr CreateFileW(string p,uint access,uint share,IntPtr security,uint disposition,uint flags,IntPtr template);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool CloseHandle(IntPtr h);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool GetFileInformationByHandle(IntPtr h,out FileInfo info);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern uint GetFinalPathNameByHandleW(IntPtr h,StringBuilder s,uint n,uint f);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool ReadFile(IntPtr h,byte[]b,uint n,out uint got,IntPtr o);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool SetFilePointerEx(IntPtr h,long offset,out long actual,uint method);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern IntPtr OpenProcess(uint access,bool inherit,uint pid);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern uint GetProcessId(IntPtr h);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetProcessTimes(IntPtr h,out FT c,out FT e,out FT k,out FT u);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool QueryFullProcessImageNameW(IntPtr h,uint f,StringBuilder s,ref uint n);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern uint WaitForSingleObject(IntPtr h,uint ms);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool GetExitCodeProcess(IntPtr h,out uint exit);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool TerminateProcess(IntPtr h,uint code);
 [DllImport("kernel32.dll")]internal static extern IntPtr GetCurrentProcess();
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool DuplicateHandle(IntPtr sourceProcess,IntPtr source,IntPtr targetProcess,out IntPtr target,uint access,bool inherit,uint options);
 [DllImport("kernel32.dll")]internal static extern IntPtr GetStdHandle(int number);
 [DllImport("kernel32.dll")]internal static extern uint GetFileType(IntPtr handle);
 [DllImport("kernel32.dll",SetLastError=true)]internal static extern bool PeekNamedPipe(IntPtr pipe,IntPtr buffer,uint bytes,IntPtr read,out uint available,IntPtr left);
 internal static string Canonical(string p){Check.Need(Path.IsPathRooted(p));string f=Path.GetFullPath(p);Check.Need(f==p&&!f.StartsWith(@"\\"));return f.TrimEnd('\\');}
 internal static void File(IntPtr h,string p,bool directory){FileInfo f;Check.Need(GetFileInformationByHandle(h,out f)&&(f.Attr&0x400)==0&&((f.Attr&0x10)!=0)==directory);var b=new StringBuilder(32768);uint n=GetFinalPathNameByHandleW(h,b,32768,0);Check.Need(n>0&&n<32768);string got=b.ToString();if(got.StartsWith(@"\\?\"))got=got.Substring(4);Check.Need(String.Equals(Canonical(got),Canonical(p),StringComparison.OrdinalIgnoreCase));}
 internal static ulong Creation(IntPtr h){FT c,e,k,u;Check.Need(GetProcessTimes(h,out c,out e,out k,out u));return((ulong)c.High<<32)|c.Low;}
 internal static bool ProcessState(bool identity,uint wait,bool alive){return identity&&wait==(alive?258u:0u);}
 internal static uint Process(IntPtr h,uint pid,ulong creation,string image,bool alive){
  Check.Need(h!=IntPtr.Zero&&ProcessState(GetProcessId(h)==pid&&Creation(h)==creation,WaitForSingleObject(h,0),alive));
  if(alive){var b=new StringBuilder(32768);uint n=32768;Check.Need(QueryFullProcessImageNameW(h,0,b,ref n)&&String.Equals(Canonical(b.ToString()),Canonical(image),StringComparison.OrdinalIgnoreCase));return 259;}
  // The same retained handle is signaled and identity-bound. Windows may reject
  // QueryFullProcessImageNameW after exit (dummy observed ERROR_GEN_FAILURE 31).
  // The caller retains and rehashes the image pinned before exit instead.
  uint exit;Check.Need(GetExitCodeProcess(h,out exit));return exit;
 }
 internal static bool Absent(string path){IntPtr h=CreateFileW(path,0x80,3,IntPtr.Zero,3,0x00200000,IntPtr.Zero);int error=Marshal.GetLastWin32Error();if(h!=IntPtr.Zero&&h!=new IntPtr(-1)){Check.Need(CloseHandle(h));return false;}return error==2;}
}
internal sealed class Pins {
 readonly List<IntPtr> handles=new List<IntPtr>();internal bool Closed=true;
 internal IntPtr Open(string p,bool directory){p=Path.GetFullPath(p);IntPtr h=Win.CreateFileW(p,directory?0x80u:0x80000000u,directory?3u:1u,IntPtr.Zero,3,0x02200000,IntPtr.Zero);Check.Need(h!=IntPtr.Zero&&h!=new IntPtr(-1));handles.Add(h);Win.File(h,p,directory);return h;}
 internal void Ancestors(string p){string f=Path.GetFullPath(p),root=Path.GetPathRoot(f),at=root;Open(root,true);foreach(string part in f.Substring(root.Length).Split('\\')){if(part.Length==0)continue;at=Path.Combine(at,part);Open(at,true);}}
 internal IntPtr Pin(string p){Ancestors(Path.GetDirectoryName(p));return Open(p,false);}
 internal string Hash(IntPtr h){long at;Check.Need(Win.SetFilePointerEx(h,0,out at,0));using(var sha=SHA256.Create()){byte[]b=new byte[65536];uint n;while(true){Check.Need(Win.ReadFile(h,b,(uint)b.Length,out n,IntPtr.Zero));if(n==0)break;sha.TransformBlock(b,0,(int)n,null,0);}sha.TransformFinalBlock(new byte[0],0,0);return BitConverter.ToString(sha.Hash).Replace("-","");}}
 internal Dictionary<string,object> Read(string path){IntPtr h=Pin(path);Win.FileInfo info;Check.Need(Win.GetFileInformationByHandle(h,out info)&&info.SizeHigh==0&&info.SizeLow>0&&info.SizeLow<=16384);byte[]b=new byte[info.SizeLow];uint n;Check.Need(Win.ReadFile(h,b,(uint)b.Length,out n,IntPtr.Zero)&&n==b.Length);Win.File(h,path,false);return Check.Parse(new UTF8Encoding(false,true).GetString(b));}
 internal string Text(IntPtr h){long at;Check.Need(Win.SetFilePointerEx(h,0,out at,0));Win.FileInfo info;Check.Need(Win.GetFileInformationByHandle(h,out info)&&info.SizeHigh==0&&info.SizeLow>0&&info.SizeLow<=1048576);byte[]b=new byte[info.SizeLow];uint n;Check.Need(Win.ReadFile(h,b,(uint)b.Length,out n,IntPtr.Zero)&&n==b.Length);return new UTF8Encoding(false,true).GetString(b);}
 internal bool Close(){for(int i=handles.Count-1;i>=0;i--){if(handles[i]==IntPtr.Zero)continue;if(Win.CloseHandle(handles[i]))handles[i]=IntPtr.Zero;else Closed=false;}return Closed;}
}
public static class Program {
 sealed class Closure {
  readonly Dictionary<string,IntPtr> handles=new Dictionary<string,IntPtr>(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,string> hashes=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);readonly Pins pins;
  internal Closure(Pins pins,string manifest,string entry){this.pins=pins;var m=pins.Read(manifest);Check.Keys(m,"schema,files");Check.Need(Check.Eq(m["schema"],"p6_r7_host_fault_closure_v1")&&m["files"] is object[]);var files=(object[])m["files"];Check.Need(files.Length>0&&files.Length<=64);string root=Path.GetDirectoryName(entry);foreach(object value in files){var f=value as Dictionary<string,object>;Check.Keys(f,"path,sha256");string path=f["path"] as string;Check.Need(path!=null&&Path.GetFullPath(path)==path&&String.Equals(Path.GetDirectoryName(path),root,StringComparison.OrdinalIgnoreCase)&&Path.GetExtension(path)==".mjs"&&Check.Hex(f["sha256"])&&!handles.ContainsKey(path));handles.Add(path,pins.Pin(path));hashes.Add(path,((string)f["sha256"]).ToUpperInvariant());}Verify();var reached=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var pending=new Queue<string>();pending.Enqueue(entry);while(pending.Count>0){string path=pending.Dequeue();if(!reached.Add(path))continue;Check.Need(handles.ContainsKey(path));string source=pins.Text(handles[path]);Check.Need(!System.Text.RegularExpressions.Regex.IsMatch(source,@"\b(?:import|require)\s*\("));foreach(System.Text.RegularExpressions.Match match in System.Text.RegularExpressions.Regex.Matches(source,"(?:^|\\n)\\s*(?:import|export)\\s+(?:[^;]*?\\s+from\\s+)?['\"]([^'\"]+)['\"]")){string spec=match.Groups[1].Value;if(spec.StartsWith("node:",StringComparison.Ordinal))continue;Check.Need(spec.StartsWith("./",StringComparison.Ordinal)&&spec.EndsWith(".mjs",StringComparison.Ordinal));string dependency=Path.GetFullPath(Path.Combine(root,spec));Check.Need(handles.ContainsKey(dependency));pending.Enqueue(dependency);}}Check.Need(reached.Count==handles.Count);}
  internal void Verify(){foreach(var item in handles)Check.Need(pins.Hash(item.Value)==hashes[item.Key]);}
 }
 static string Quote(string value){Check.Need(value!=null&&value.IndexOf('"')<0&&value.IndexOf('\r')<0&&value.IndexOf('\n')<0&&!value.EndsWith("\\"));return "\""+value+"\"";}
 sealed class Reader {
  readonly BlockingCollection<string> lines=new BlockingCollection<string>(4);readonly Task task;internal bool Fault,HadBytes;
  internal Reader(StreamReader reader,bool discard){task=Task.Run(delegate{try{var b=new StringBuilder();while(true){int c=reader.Read();if(c<0)break;HadBytes=true;if(discard)continue;Check.Need(b.Length<8192);if(c=='\n'){Check.Need(lines.TryAdd(b.ToString()));b.Clear();}else b.Append((char)c);}Check.Need(discard||b.Length==0);}catch{Fault=true;}finally{lines.CompleteAdding();}});}
  internal string Next(int milliseconds){string value;Check.Need(lines.TryTake(out value,milliseconds));return value;}
  internal bool Join(){return task.Wait(5000)&&!Fault;}
 }
 static bool GracefulLine(string line){if(line==null)return false;if(line.EndsWith("\r",StringComparison.Ordinal))line=line.Substring(0,line.Length-1);return line=="{\"type\":\"graceful\"}";}
 static bool Graceful(Process node,int ms){try{node.StandardInput.NewLine="\n";node.StandardInput.WriteLine("{\"type\":\"graceful\"}");node.StandardInput.Flush();return node.WaitForExit(ms)&&node.ExitCode==0;}catch{return false;}}
 static bool NeedsRetention(bool nodeExited,bool nativeHeld,bool nativeExited){return !nodeExited||(nativeHeld&&!nativeExited);}
 static bool AttentionNotice(Action write){try{write();return true;}catch{return false;}}
 static void RetainUntilExited(Process node,IntPtr native){
  AttentionNotice(delegate{Console.WriteLine("{\"schema\":\"p6_r7_host_fault_attention_v1\",\"needs_attention\":true,\"handles_retained\":true}");});
  IntPtr input=Win.GetStdHandle(-10);var buffer=new StringBuilder();
  while(true){bool nodeExited=node==null||node.HasExited;bool nativeExited=native==IntPtr.Zero||Win.WaitForSingleObject(native,0)==0;if(!NeedsRetention(nodeExited,native!=IntPtr.Zero,nativeExited))return;
   uint available;if(Win.GetFileType(input)==3&&Win.PeekNamedPipe(input,IntPtr.Zero,0,IntPtr.Zero,out available,IntPtr.Zero)&&available>0){byte[]b=new byte[Math.Min(available,256)];uint n;if(Win.ReadFile(input,b,(uint)b.Length,out n,IntPtr.Zero)){for(int i=0;i<n;i++){char c=(char)b[i];if(c=='\n'){if(GracefulLine(buffer.ToString())&&!nodeExited)Graceful(node,180000);buffer.Clear();}else if(buffer.Length<256)buffer.Append(c);}}}
   System.Threading.Thread.Sleep(100);
  }
 }
 static Dictionary<string,object> Report(){return new Dictionary<string,object>{{"schema","p6_r7_inflight_host_fault_witness_v1"},{"actual_native",false},{"passed",false},{"requires_actual_witness_exit_0",true},{"receipt_write_state","pending_actual_witness_exit_commit"},{"node_binding_verified",false},{"native_binding_verified",false},{"node_killed",false},{"native_exit_code",null},{"final_binding_verified",false},{"input_eof_observed",false},{"stdout_final_failed",false},{"cleanup_pending",true},{"native_cleanup_pending",true},{"graceful_fallback_confirmed",false},{"witness_handles_closed",false},{"held_process_handles_closed",false},{"file_handles_closed",false},{"reader_tasks_joined",false},{"managed_streams_disposed",false},{"code","host_fault_unconfirmed"},{"production_isolation_passed",false},{"human_gate_passed",false}};}
 static Dictionary<string,string> FilterEnvironment(System.Collections.IDictionary source){var result=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var allowed=new HashSet<string>(("SystemRoot,WINDIR,COMSPEC,PATHEXT,PATH,USERPROFILE,LOCALAPPDATA,TEMP,TMP,SYSTEMDRIVE,HTTP_PROXY,HTTPS_PROXY,NO_PROXY,ALL_PROXY").Split(','),StringComparer.OrdinalIgnoreCase);foreach(System.Collections.DictionaryEntry entry in source){string key=entry.Key as string,value=entry.Value as string;if(key!=null&&value!=null&&allowed.Contains(key))result[key]=value;}return result;}
 static void ApplyEnvironment(ProcessStartInfo info){var filtered=FilterEnvironment(Environment.GetEnvironmentVariables());info.EnvironmentVariables.Clear();foreach(var entry in filtered)info.EnvironmentVariables[entry.Key]=entry.Value;Check.Need(!info.EnvironmentVariables.ContainsKey("NODE_OPTIONS")&&!info.EnvironmentVariables.ContainsKey("NODE_PATH"));}
 static int Run(string[]args){Check.Need(args.Length==9&&args[0]=="--apply-inflight-host-fault");string nodePath=Path.GetFullPath(args[1]),target=Path.GetFullPath(args[3]),nativePath=Path.GetFullPath(args[5]),reportPath=Path.GetFullPath(args[7]),manifest=Path.GetFullPath(args[8]);Check.Need(nodePath==args[1]&&target==args[3]&&nativePath==args[5]&&reportPath==args[7]&&manifest==args[8]&&Check.Hex(args[2])&&Check.Hex(args[4])&&Check.Hex(args[6]));string nodeHash=args[2].ToUpperInvariant(),targetHash=args[4].ToUpperInvariant(),nativeHash=args[6].ToUpperInvariant();
  var result=Report();result["prekill_snapshot"]=null;result["ready_received_to_kill_call_ms"]=null;result["temporal_claim"]="ready_snapshot_then_held_kill_non_atomic";result["remote_running_at_kill"]=null;result["remote_computation_stopped"]=null;result["remote_billing_stopped"]=null;result["upstream_socket_abort_observed"]=null;result["broker_drained_after_kill"]=null;result["provider_terminal_after_kill"]=null;result["restart_resume_verified"]=false;result["native_receipt"]=null;result["native_shutdown_trigger"]=null;result["failure_stage"]=null;string stage="preflight";Process node=null;IntPtr native=IntPtr.Zero,child=IntPtr.Zero,nodeHandle=IntPtr.Zero;Reader stdout=null,stderr=null;bool killed=false,good=false;var pins=new Pins();
  using(var output=new FileStream(reportPath,FileMode.CreateNew,FileAccess.Write,FileShare.Read)){
   try{
    stage="source_closure";IntPtr nfile=pins.Pin(nodePath),tfile=pins.Pin(target),efile=pins.Pin(nativePath);Check.Need(pins.Hash(nfile)==nodeHash&&pins.Hash(tfile)==targetHash&&pins.Hash(efile)==nativeHash);var closure=new Closure(pins,manifest,target);
    var info=new ProcessStartInfo{FileName=nodePath,Arguments="--use-env-proxy "+Quote(target)+" --inflight-host-fault-target "+Quote(nativePath)+" "+args[6].ToLowerInvariant(),WorkingDirectory=Path.GetDirectoryName(target),UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true};
    ApplyEnvironment(info);
    stage="node_start";node=Process.Start(info);Check.Need(node!=null);Check.Need(Win.DuplicateHandle(Win.GetCurrentProcess(),node.Handle,Win.GetCurrentProcess(),out nodeHandle,0x00101001,false,0));uint nodePid=(uint)node.Id;ulong nodeCreation=Win.Creation(nodeHandle);Win.Process(nodeHandle,nodePid,nodeCreation,nodePath,true);result["node_binding_verified"]=true;result["node_pid"]=nodePid;result["node_creation"]=nodeCreation.ToString(CultureInfo.InvariantCulture);
    // stderr is drained but never copied to a report. Native pipes are owned only by Node.
    stderr=new Reader(node.StandardError,true);stdout=new Reader(node.StandardOutput,false);
    stage="http_ready";var initial=Check.Parse(stdout.Next(180000));var ready=Check.Initial(initial);Guid attempt=Check.Id(ready["attempt_id"]);result["attempt_id"]=attempt.ToString("D");
    stage="journal_binding";string dir=Path.Combine(@"D:\HereIAm-P6-R7-Task-Executor",attempt.ToString("N"));var prepared=pins.Read(Path.Combine(dir,"prepared.json"));var bound=pins.Read(Path.Combine(dir,"bound.json"));Check.Journal(prepared,ready,nativeHash,"prepared");Check.Journal(bound,ready,nativeHash,"bound");Check.Same(prepared,bound,Check.Binding+",owner_token_digest");
    stage="native_binding";uint ownerPid=(uint)Check.Num(bound["owner_pid"]);ulong ownerCreation=Check.Time(bound["owner_creation"]);native=Win.OpenProcess(0x00101000,false,ownerPid);Check.Need(native!=IntPtr.Zero);Win.Process(native,ownerPid,ownerCreation,nativePath,true);result["native_binding_verified"]=true;result["actual_native"]=true;result["native_pid"]=ownerPid;result["native_creation"]=ownerCreation.ToString(CultureInfo.InvariantCulture);
    stage="child_binding";string childImage=Path.Combine(dir,"codex.exe");IntPtr cfile=pins.Pin(childImage);Check.Need(pins.Hash(cfile)==Check.Cli);uint childPid=(uint)Check.Num(bound["child_pid"]);ulong childCreation=Check.Time(bound["child_creation"]);child=Win.OpenProcess(0x00101000,false,childPid);Check.Need(child!=IntPtr.Zero);Win.Process(child,childPid,childCreation,childImage,true);Check.Need(Win.Absent(Path.Combine(dir,"final-receipt.json")));
    // Last checks occur on retained process handles and held immutable images.
    Win.Process(nodeHandle,nodePid,nodeCreation,nodePath,true);Win.Process(native,ownerPid,ownerCreation,nativePath,true);Win.Process(child,childPid,childCreation,childImage,true);closure.Verify();Check.Need(pins.Hash(nfile)==nodeHash&&pins.Hash(efile)==nativeHash&&pins.Hash(tfile)==targetHash&&pins.Hash(cfile)==Check.Cli);
    stage="turn_start";node.StandardInput.NewLine="\n";node.StandardInput.WriteLine("{\"type\":\"start_turn\"}");node.StandardInput.Flush();
    stage="inflight_ready";string inflightLine=stdout.Next(180000);var readyAge=Stopwatch.StartNew();var inflight=Check.Parse(inflightLine);Check.Inflight(inflight,initial);result["prekill_snapshot"]=inflight;
    // The old three native pipes remain exclusively owned by Node. No remote
    // execution claim is made across this non-atomic readiness/kill window.
    Win.Process(nodeHandle,nodePid,nodeCreation,nodePath,true);Win.Process(native,ownerPid,ownerCreation,nativePath,true);Win.Process(child,childPid,childCreation,childImage,true);Check.Need(Win.Absent(Path.Combine(dir,"final-receipt.json")));
    stage="kill";Check.Need(readyAge.ElapsedMilliseconds<=1000);result["ready_received_to_kill_call_ms"]=readyAge.ElapsedMilliseconds;Check.Need(Win.TerminateProcess(nodeHandle,77));killed=true;result["node_killed"]=true;Check.Need(Win.WaitForSingleObject(nodeHandle,10000)==0);
    stage="native_exit";Check.Need(Win.WaitForSingleObject(native,180000)==0);uint exit=Win.Process(native,ownerPid,ownerCreation,nativePath,false);result["native_exit_code"]=exit;uint nodeExit=Win.Process(nodeHandle,nodePid,nodeCreation,nodePath,false);result["node_exit_code"]=nodeExit;Check.KilledExit(nodeExit);result["child_exit_code"]=Win.Process(child,childPid,childCreation,childImage,false);closure.Verify();Check.Need(pins.Hash(nfile)==nodeHash&&pins.Hash(efile)==nativeHash&&pins.Hash(cfile)==Check.Cli);
    stage="final_receipt";var final=pins.Read(Path.Combine(dir,"final-receipt.json"));string trigger=final["shutdown_trigger"] as string;result["native_shutdown_trigger"]=trigger=="input_eof"||trigger=="close_command"||trigger=="operation_failure"?trigger:"unknown";result["input_eof_observed"]=Check.Eq(final["shutdown_trigger"],"input_eof");result["stdout_final_failed"]=Check.Eq(final["stdout_final_emit_succeeded"],false);Check.Final(final,bound,exit);result["native_receipt"]=final["receipt"];result["final_binding_verified"]=true;result["native_cleanup_pending"]=false;good=true;
   }catch{good=false;result["failure_stage"]=stage;}
   finally{
    // Never use a timeout as permission to kill an unverified or unknown owner.
    if(node!=null&&!killed){bool graceful=Graceful(node,180000);result["graceful_fallback_confirmed"]=graceful;if(!graceful)RetainUntilExited(node,native);}
    if(node!=null&&(!node.HasExited||(native!=IntPtr.Zero&&Win.WaitForSingleObject(native,0)!=0)))RetainUntilExited(node,native);
    if(native!=IntPtr.Zero&&Win.WaitForSingleObject(native,0)==0){uint observedExit;if(Win.GetExitCodeProcess(native,out observedExit))result["native_exit_code"]=observedExit;}
    bool stdoutJoined=stdout==null||stdout.Join(),stderrJoined=stderr==null||stderr.Join();bool joined=stdoutJoined&&stderrJoined;result["reader_tasks_joined"]=joined;good=good&&joined&&(stderr==null||!stderr.HadBytes);
    bool rawClosed=true;foreach(IntPtr h in new[]{native,child,nodeHandle})if(h!=IntPtr.Zero&&!Win.CloseHandle(h)){rawClosed=false;Win.CloseHandle(h);}result["held_process_handles_closed"]=rawClosed;good=good&&rawClosed;
    bool closed=pins.Close();if(!closed)pins.Close();result["file_handles_closed"]=closed;result["witness_handles_closed"]=closed&&rawClosed;good=good&&closed;
    bool disposed=true;if(node!=null){try{node.StandardInput.Dispose();node.StandardOutput.Dispose();node.StandardError.Dispose();node.Dispose();}catch{disposed=false;}}result["managed_streams_disposed"]=disposed;good=good&&disposed;
    result["cleanup_pending"]=!Check.Eq(result["native_cleanup_pending"],false)||!rawClosed||!closed||!joined||!disposed;
    if(!good&&result["failure_stage"]==null)result["failure_stage"]="post_close";
    result["passed"]=good;result["code"]=good?null:"host_fault_unconfirmed";
    byte[] bytes=Encoding.UTF8.GetBytes(Check.Json.Serialize(result)+"\n");output.Write(bytes,0,bytes.Length);output.Flush(true);
   }
  }Console.WriteLine(Check.Json.Serialize(result));return good?0:2;
 }
 static int tests;static void Test(bool value){Check.Need(value);tests++;}static void Reject(Action action){bool rejected=false;try{action();}catch{rejected=true;}Test(rejected);}
 static int SelfTest(){
  Test(Win.ProcessState(true,258,true));Test(Win.ProcessState(true,0,false));Test(!Win.ProcessState(true,258,false));Test(!Win.ProcessState(true,0,true));Test(!Win.ProcessState(false,0,false));Test(!Win.ProcessState(false,258,true));Test(!Win.ProcessState(true,UInt32.MaxValue,false));
  Check.Parse("{\"x\":1}");foreach(string bad in new[]{"{\"x\":1,\"\\u0078\":2}","{\"x\":01}","{\"x\":NaN}","{\"x\":1,}","{\"x\":{\"a\":1,\"a\":2}}"})Reject(delegate{Check.Parse(bad);});
  var env=new System.Collections.Hashtable{{"NODE_OPTIONS","--import unverified.mjs"},{"NODE_PATH","unverified"},{"OPENAI_API_KEY","not inherited"},{"SystemRoot","synthetic"},{"https_proxy","synthetic proxy"}};var filtered=FilterEnvironment(env);Test(filtered.Count==2&&filtered.ContainsKey("SystemRoot")&&filtered.ContainsKey("HTTPS_PROXY")&&!filtered.ContainsKey("NODE_OPTIONS")&&!filtered.ContainsKey("NODE_PATH"));
  Test(NeedsRetention(false,false,false));Test(NeedsRetention(false,true,false));Test(NeedsRetention(true,true,false));Test(!NeedsRetention(true,true,true));Test(!NeedsRetention(true,false,false));
  Test(!AttentionNotice(delegate{throw new IOException("synthetic output failure");}));Test(NeedsRetention(false,true,false));
  Test(GracefulLine("{\"type\":\"graceful\"}"));Test(GracefulLine("{\"type\":\"graceful\"}\r"));foreach(string invalid in new[]{" {\"type\":\"graceful\"}","{\"type\":\"graceful\"} ","{\"type\":\"graceful\"}\r\r","{\"type\":\"kill\"}","{\"type\":\"graceful\",\"pid\":123}"})Test(!GracefulLine(invalid));int retryFrames=0;foreach(string frame in "{\"type\":\"graceful\"}\r\n{\"type\":\"graceful\"}\n".Split('\n'))if(GracefulLine(frame))retryFrames++;Test(retryFrames==2);
  string id="11111111-2222-4333-8444-555555555555",hash=new string('a',64);var ready=new Dictionary<string,object>{{"schema","p6_r7_host_fault_ready_v1"},{"attempt_id",id},{"child_pid",456},{"child_creation","1234567891"},{"cli_sha256",Check.Cli.ToLowerInvariant()},{"broker_port",32123},{"http_created",true},{"no_model",true},{"default_three_pipes",true}};Check.Ready(ready);tests++;
  Check.KilledExit(77);tests++;foreach(uint nodeExit in new uint[]{0,1,3,259})Reject(delegate{Check.KilledExit(nodeExit);});
  var initial=new Dictionary<string,object>{{"schema","p6_r7_inflight_initial_v1"},{"native_ready",ready},{"local_session_id",id},{"execution_epoch",id},{"provider_thread_id",id}};Check.Initial(initial);tests++;
  var inflight=new Dictionary<string,object>{{"schema","p6_r7_inflight_ready_v1"},{"attempt_id",id},{"local_session_id",id},{"execution_epoch",id},{"provider_thread_id",id},{"local_turn_id",id},{"provider_turn_id",id},{"start_command_id",1},{"turn_start_dispatched",true},{"exchange_entered",1},{"exchange_settled",false},{"response_released",false},{"terminal_observed",false},{"text_observed",false},{"upstream_attempts",1},{"default_three_pipes",true},{"snapshot_claim","local_exchange_pending_at_ready"}};Check.Inflight(inflight,initial);tests++;
  foreach(string key in new[]{"exchange_settled","response_released","terminal_observed","text_observed"}){inflight[key]=true;Reject(delegate{Check.Inflight(inflight,initial);});inflight[key]=false;}
  foreach(string key in new[]{"turn_start_dispatched","default_three_pipes"}){inflight[key]=false;Reject(delegate{Check.Inflight(inflight,initial);});inflight[key]=true;}
  foreach(string key in new[]{"start_command_id","exchange_entered","upstream_attempts"}){inflight[key]=2;Reject(delegate{Check.Inflight(inflight,initial);});inflight[key]=1;}
  foreach(string key in new[]{"attempt_id","local_session_id","execution_epoch","provider_thread_id"}){inflight[key]="other";Reject(delegate{Check.Inflight(inflight,initial);});inflight[key]=id;}
  inflight["provider_turn_id"]="identifier\n";Reject(delegate{Check.Inflight(inflight,initial);});inflight["provider_turn_id"]=id;inflight["extra"]=true;Reject(delegate{Check.Inflight(inflight,initial);});inflight.Remove("extra");
  var prepared=new Dictionary<string,object>{{"schema","p6_r7_task_owned_v2"},{"attempt_id",id},{"scope_id",Check.Scope(Guid.Parse(id))},{"nonce",new string('b',64)},{"auth_mode","chatgpt"},{"home_class","dedicated_existing"},{"owner_pid",123},{"owner_creation","1234567890"},{"owner_sha256",hash},{"cli_sha256",Check.Cli.ToLowerInvariant()},{"broker_port",32123},{"owner_token_digest",new string('c',64)},{"phase","prepared"},{"child_pid",null},{"child_creation",null}};
  var bound=new Dictionary<string,object>(prepared);bound["phase"]="bound";bound["child_pid"]=456;bound["child_creation"]="1234567891";Check.Journal(prepared,ready,hash.ToUpperInvariant(),"prepared");Check.Journal(bound,ready,hash.ToUpperInvariant(),"bound");tests+=2;
  var final=new Dictionary<string,object>{{"schema","p6_r7_task_final_receipt_v1"},{"child_pid",456},{"child_creation","1234567891"},{"started",true},{"close_command_id",0},{"shutdown_trigger","input_eof"},{"operation_failed",true},{"stdout_final_emit_succeeded",false},{"requires_actual_exit_0_or_3",true},{"receipt_write_state","pending_actual_exit_commit"}};foreach(string key in Check.Binding.Split(','))final[key]=bound[key];var receipt=new Dictionary<string,object>{{"cleanup_pending",false}};foreach(string key in Check.Facts.Split(','))receipt[key]=true;final["receipt"]=receipt;Check.Final(final,bound,3);tests++;
  foreach(uint exit in new uint[]{0,4,259})Reject(delegate{Check.Final(final,bound,exit);});foreach(string key in Check.Facts.Split(',')){receipt[key]=false;Reject(delegate{Check.Final(final,bound,3);});receipt[key]=true;}final["owner_creation"]="1234567892";Reject(delegate{Check.Final(final,bound,3);});final["owner_creation"]=bound["owner_creation"];final["shutdown_trigger"]="operation_failure";Reject(delegate{Check.Final(final,bound,3);});
  using(var sha=SHA256.Create()){byte[] input=Encoding.ASCII.GetBytes("abc");sha.TransformBlock(input,0,3,null,0);sha.TransformFinalBlock(new byte[0],0,0);Test(BitConverter.ToString(sha.Hash).Replace("-","")=="BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD");}
  Console.WriteLine("{\"schema\":\"p6_r7_inflight_host_fault_witness_plan_v1\",\"mode\":\"self_test\",\"actual_native\":false,\"checks\":"+tests+"}");return 0;
 }
 public static int Main(string[]args){try{if(args.Length==0||args.Length==1&&args[0]=="--plan"){Console.WriteLine("{\"schema\":\"p6_r7_inflight_host_fault_witness_plan_v1\",\"actual_native\":false}");return 0;}if(args.Length==1&&args[0]=="--self-test")return SelfTest();return Run(args);}catch{Console.WriteLine("{\"schema\":\"p6_r7_inflight_host_fault_witness_plan_v1\",\"actual_native\":false,\"code\":\"host_fault_rejected\"}");return 2;}}
}
}
