import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,realpathSync,rmSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const local=name=>fileURLToPath(new URL(name,import.meta.url));
const source=local('./windows_text_gate_appid_matrix_retired_cleanup.cs'),code=readFileSync(source,'utf8');
const deps=[local('./windows_text_gate_isolation_helper.cs'),local('./windows_text_gate_appid_startup_helper.cs'),local('../../tmp/p6-r7-review/native-appid-coordinator-candidate-15.cs'),local('../../tmp/p6-r7-review/native-appid-matrix-contract-01.cs'),local('./windows_text_gate_appid_matrix_native.cs')];
const pins=['d22017641d9f8df750f6db7db9319b8c1930a726a8575ff1ffabfde0d5ffdcd8','c777023495ccdbf3b52663f49683f5d84dcfd03a36b3d280a75c925f37b7a1ea','c1f07e9487b8ce25d0acc2d5bbb03b69c975cbb7e448698d288ff6263cff9311','f70ffb86ce5efea2572532e1986f77dde9622893ad4b90a74f9ec40da5ba6774','f2d3b35a1e6d1763930ba7f9a82ab8dbb595e02d5d720216a0161dbce8a0d0ab'];
const hash=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const csc=String.raw`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe`;
const harness=String.raw`
using System;using System.Collections;using System.Collections.Generic;
namespace HereIAm.R7 {public static class MatrixRetiredCleanupPureHarness {
 static int count;static void Check(bool condition){if(!condition)throw new Exception("pure_failed_"+count);count++;}static void Reject(Action action){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected);}
 static void History(string[] v){MatrixRetiredCleanupProgram.History(v[0],v[1],v[2],v[3]);}
 public static int Main(string[] args){var e=new MatrixExpected{Attempt=MatrixRetiredCleanupProgram.Attempt,Nonce=new string('a',64),ImageHash=MatrixRetiredCleanupProgram.ImageHash,OwnerHash=MatrixRetiredCleanupProgram.ImageHash,OwnerTokenDigest=new string('b',64),BlobDigest=new string('c',64),OwnerPid=MatrixRetiredCleanupProgram.OwnerPid,OwnerCreation=MatrixRetiredCleanupProgram.OwnerCreation,BrokerPort=MatrixRetiredCleanupProgram.BrokerPort};
  var p=MatrixRecords.Owned(e,"prepared",null,null);var b=MatrixRecords.Owned(e,"bound",303,404);var c=MatrixRecords.Owned(e,"closed",303,404);var receipt=MatrixRecords.Receipt(e,p,"install",505,606,32766);
  var records=new[]{p,b,c,receipt};var texts=new string[4];for(int i=0;i<4;i++)texts[i]=MatrixRecords.Json(records[i]);History(texts);Check(true);
  for(int r=0;r<4;r++)foreach(string field in new List<string>(records[r].Keys)){var bad=new Dictionary<string,object>(records[r]);bad.Remove(field);var altered=(string[])texts.Clone();altered[r]=MatrixRecords.Json(bad);Reject(delegate{History(altered);});bad=new Dictionary<string,object>(records[r]);bad[field]="invalid";altered[r]=MatrixRecords.Json(bad);Reject(delegate{History(altered);});}
  for(int r=0;r<4;r++){var bad=new Dictionary<string,object>(records[r]);bad["extra"]=true;var altered=(string[])texts.Clone();altered[r]=MatrixRecords.Json(bad);Reject(delegate{History(altered);});}
  foreach(var wrong in new[]{MatrixRecords.Owned(e,"bound",304,404),MatrixRecords.Owned(e,"bound",303,405),MatrixRecords.Owned(e,"closed",303,404),MatrixRecords.Owned(e,"spawning",null,null)}){var altered=(string[])texts.Clone();altered[1]=MatrixRecords.Json(wrong);Reject(delegate{History(altered);});}
  foreach(object weight in new object[]{null,-1,65536,"32766"}){var bad=new Dictionary<string,object>(receipt);bad["assigned_sublayer_weight"]=weight;var altered=(string[])texts.Clone();altered[3]=MatrixRecords.Json(bad);Reject(delegate{History(altered);});}
  var medium=new MediumIdentity{Type=1,Integrity=8192,ElevationType=3,Elevated=0,AppContainer=0,Authentication=1};var high=new MediumIdentity{Type=1,Integrity=12288,ElevationType=2,Elevated=1,AppContainer=0,Authentication=2};Check(!MatrixRetiredCleanupProgram.CallerAccepted(medium));Check(MatrixRetiredCleanupProgram.CallerAccepted(high));Check(!MatrixRetiredCleanupProgram.CallerAccepted(null));
  foreach(string field in new[]{"Type","Integrity","ElevationType","Elevated","AppContainer","Authentication"}){var bad=new MediumIdentity{Type=high.Type,Integrity=high.Integrity,ElevationType=high.ElevationType,Elevated=high.Elevated,AppContainer=high.AppContainer,Authentication=high.Authentication};var info=typeof(MediumIdentity).GetField(field,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);if(field=="Authentication")info.SetValue(bad,0UL);else info.SetValue(bad,field=="AppContainer"?1u:0u);Check(!MatrixRetiredCleanupProgram.CallerAccepted(bad));}
  Check(MatrixRetiredCleanupProgram.ExactNames((string[])MatrixRetiredCleanupProgram.FixedNames.Clone()));Check(!MatrixRetiredCleanupProgram.ExactNames(null));Check(!MatrixRetiredCleanupProgram.ExactNames(new string[]{"prepared.json","matrix-probe.exe"}));
  for(int i=0;i<15;i++){var names=(string[])MatrixRetiredCleanupProgram.FixedNames.Clone();names[i]="unknown.json";Check(!MatrixRetiredCleanupProgram.ExactNames(names));names=(string[])MatrixRetiredCleanupProgram.FixedNames.Clone();names[i]="..\\"+names[i];Check(!MatrixRetiredCleanupProgram.ExactNames(names));}
  var duplicate=(string[])MatrixRetiredCleanupProgram.FixedNames.Clone();duplicate[1]=duplicate[0];Check(!MatrixRetiredCleanupProgram.ExactNames(duplicate));
  Check(!MatrixRetiredCleanupProgram.Complete(true,true,true,true,true,false,true,true));Check(MatrixRetiredCleanupProgram.PathIdle(false,258)&&MatrixRetiredCleanupProgram.PathIdle(true,0)&&!MatrixRetiredCleanupProgram.PathIdle(true,258)&&!MatrixRetiredCleanupProgram.PathIdle(false,0xffffffff));
  int aborted=0,engineClosed=0;var retry=new MatrixRetiredCleanupResources(delegate(IntPtr h){return true;},delegate(IntPtr h){aborted++;return aborted==1?5u:0u;},delegate(IntPtr h){engineClosed++;return 0;});retry.Engine=new IntPtr(1);retry.Transaction=true;Check(!MatrixRetiredCleanupProgram.Finish(retry));Check(retry.Empty&&!retry.CloseSucceeded&&aborted==2&&engineClosed==1&&retry.CloseError==5u);
  bool canClose=false;var retained=new MatrixRetiredCleanupResources(delegate(IntPtr h){return canClose;},delegate(IntPtr h){return 0;},delegate(IntPtr h){return 0;});retained.Handles.Own(new IntPtr(2));Check(!MatrixRetiredCleanupProgram.Finish(retained)&&!retained.Empty&&retained.Handles.Owns(new IntPtr(2)));canClose=true;Check(!MatrixRetiredCleanupProgram.Finish(retained)&&retained.Empty&&!retained.CloseSucceeded);
  string actual=System.IO.File.ReadAllText(args[0]).Trim(),capture=System.IO.File.ReadAllText(args[1]).Trim();MatrixRetiredCleanupProgram.CaptureHistory(actual,capture);Check(true);
  var captures=new[]{MatrixRecords.Parse(actual),MatrixRecords.Parse(capture)};for(int r=0;r<2;r++)foreach(string key in new List<string>(captures[r].Keys)){var bad=new Dictionary<string,object>(captures[r]);bad.Remove(key);string changed=MatrixRecords.Json(bad);int index=r;Reject(delegate{MatrixRetiredCleanupProgram.CaptureHistory(index==0?changed:actual,index==1?changed:capture);});bad=new Dictionary<string,object>(captures[r]);bad[key]="invalid";changed=MatrixRecords.Json(bad);Reject(delegate{MatrixRetiredCleanupProgram.CaptureHistory(index==0?changed:actual,index==1?changed:capture);});}
  var order=new List<string>();int reads=0;bool removed=MatrixRetiredCleanupProgram.RemoveFixed(delegate{order.Add("read");return reads++==0?3:0;},delegate{order.Add("prove");},delegate{order.Add("begin");},delegate{order.Add("delete");},delegate{order.Add("commit");},delegate{order.Add("abort");});Check(removed&&String.Join(",",order)=="prove,begin,prove,read,delete,prove,commit,prove,read");
  for(int failure=0;failure<9;failure++){int step=0;int target=failure;bool mutation=false,committedPure=false,abortedPure=false;Action next=delegate{if(step++==target)throw new Exception("injected");};int readStep=0;Reject(delegate{MatrixRetiredCleanupProgram.RemoveFixed(delegate{next();return readStep++==0?3:0;},delegate{next();},delegate{next();},delegate{next();mutation=true;},delegate{next();committedPure=true;},delegate{abortedPure=true;});});Check(!committedPure||failure>=7);Check(abortedPure==(failure>=2&&failure<=6));Check(!mutation||failure>=5);}
  foreach(int countBefore in new[]{-1,0,1,2,4}){bool touched=false;Reject(delegate{MatrixRetiredCleanupProgram.RemoveFixed(delegate{return countBefore;},delegate{},delegate{},delegate{touched=true;},delegate{},delegate{});});Check(!touched);}
  bool postCommit=false;Reject(delegate{MatrixRetiredCleanupProgram.RemoveFixed(delegate{return 3;},delegate{},delegate{},delegate{},delegate{postCommit=true;},delegate{});});Check(postCommit);
  int closeAttempts=0;var closeRetry=new MatrixRetiredCleanupResources(delegate(IntPtr h){return true;},delegate(IntPtr h){return 0;},delegate(IntPtr h){return ++closeAttempts==1?5u:0u;});closeRetry.Engine=new IntPtr(99);Check(!MatrixRetiredCleanupProgram.Finish(closeRetry)&&closeRetry.Empty&&!closeRetry.CloseSucceeded&&closeAttempts==2);
  Console.WriteLine("{\"pure_assertions\":"+count+",\"native_executed\":false}");return 0;
 }
}}
`;
test('fixed retired-attempt cleanup: compile and pure checks only',async t=>{
 deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));const parent=local('../../tmp/p6-r7-helper/'),tmp=mkdtempSync(path.join(parent,'matrix-retired-cleanup-test-'));
 t.after(()=>{deps.forEach((f,i)=>assert.equal(hash(f),pins[i]));const canonical=realpathSync(tmp);assert.equal(path.dirname(canonical),realpathSync(parent));assert.match(path.basename(canonical),/^matrix-retired-cleanup-test-/);rmSync(canonical,{recursive:true,force:true});});
 await t.test('fixed retired scope and only exact removal surface',()=>{
  assert.doesNotMatch(code,/FwpmFilterAdd|FwpmSubLayerAdd|FwpmEngineSetOption|FwpmNetEvent|ShellExecute|CreateProcess|TerminateProcess|TerminateJob|CreateDirectory|SetAccessControl|FileMode\.Create|WriteAll|WriteRecord|RunAs|Process\.Start/);
  for(const fragment of ['FwpmTransactionBegin0(resources.Engine,1)','MatrixContract.Rules(Attempt,BrokerPort)','CoordinatorBoundary.Key(MatrixContract.Scope(Attempt),"sublayer")','CoordinatorBoundary.ExactFilter','CoordinatorBoundary.ExactSublayer','CoordinatorBoundary.ReadbackAllowed','CreateToolhelp32Snapshot(2,0)','count<=8192','CallerAccepted(current)','MatrixRecords.ValidateReceipt','entries.Length==FixedNames.Length','resources.Handles.Own(process)','MatrixNativeApi.VerifyPath','if(before==3)','RemoveFixed(read,prove','CaptureHistory(evidence.Text(actual),evidence.Text(capture))'])assert.ok(code.includes(fragment),fragment);
  for(const pin of ['28e6b32b-9ad0-4be3-b04b-b1c22767d943','73f7a5990914be21032028cc88a6692e03cdd6f343858508218dba6bf45f0de6','d076c12c324f5f15b30309eb12ae8a7c3ac09ac74addb2059920f4edfa2bf2d1','77a547c3844846172e0aa90636264cfde6421ab3c7b11aa5ba6e6e19bf41cbe7','f891c10462003a99aa175783402d7d13a3d3da39328733fae611cc97b93ddf8e','06b0e49b125d9b8c6f596bc0c21bbd9600557c2988c5eccf667190165687e099','b0b9b0d7d211407a7a62252ede236fcbc120c25cd974d8e800eaf63f951122ab'])assert.ok(code.includes(pin));
 });
 const exe=path.join(tmp,'inspect.exe'),pure=path.join(tmp,'pure.exe'),harnessFile=path.join(tmp,'pure.cs');writeFileSync(harnessFile,harness);
 const compile=(main,out,extra=[])=>{const run=spawnSync(csc,['/nologo','/platform:x64','/warnaserror+','/target:exe','/reference:System.Web.Extensions.dll',`/main:${main}`,`/out:${out}`,...deps,source,...extra],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(run.status,0,run.stdout+run.stderr);};
 compile('HereIAm.R7.MatrixRetiredCleanupProgram',exe);compile('HereIAm.R7.MatrixRetiredCleanupPureHarness',pure,[harnessFile]);
 await t.test('pure modes and rejected arguments never claim lost actual exit',()=>{for(const args of [[],['--plan'],['--self-test'],['--apply'],['--inspect-never-started-fixed'],['--inspect-never-started-fixed-elevated-readonly'],['--cleanup-fixed-retired-matrix-attempt','unexpected']]){const run=spawnSync(exe,args,{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,args.length===0||args.length===1&&['--plan','--self-test'].includes(args[0])?0:2,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.schema,'p6_r7_matrix_fixed_retired_cleanup_v1');assert.equal(result.native_executed,false);assert.equal(result.cleanup_pending,true);assert.equal(result.inspection_complete,false);assert.equal(result.exact_child_closed,null);assert.equal(result.job_active0,null);assert.equal(result.helper_actual_exit_verified,false);assert.equal(result.historical_records_consistent,false);assert.equal(result.filters_deleted_count,0);assert.equal(result.sublayers_deleted_count,0);assert.equal(result.production_isolation_passed,false);if(args[0]==='--self-test'){assert.equal(result.pure_assertions,259);process.stdout.write(`selftest_assertions=${result.pure_assertions}\n`);}}});
 await t.test('record relationships, exact names, caller identity and failed-close negatives',()=>{const run=spawnSync(pure,[local('../../tmp/p6-r7-review/native-appid-matrix-runtime-actual-04.json'),local('../../tmp/p6-r7-review/native-appid-matrix-runtime-capture-04.json')],{encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(run.status,0,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.native_executed,false);assert.ok(result.pure_assertions>=180);process.stdout.write(`pure_assertions=${result.pure_assertions}\n`);});
 await t.test('SDK compile proves snapshot layout and read-only preflight constant',()=>{
  const cpp='#include <windows.h>\n#include <tlhelp32.h>\n#include <fwpmu.h>\n#include <stddef.h>\nstatic_assert(sizeof(PROCESSENTRY32W)==568,"size");\nstatic_assert(offsetof(PROCESSENTRY32W,th32ProcessID)==8,"pid");\nstatic_assert(offsetof(PROCESSENTRY32W,th32DefaultHeapID)==16,"heap");\nstatic_assert(offsetof(PROCESSENTRY32W,szExeFile)==44,"name");\nstatic_assert(TH32CS_SNAPPROCESS==2,"snapshot");\nstatic_assert(FWPM_TXN_READ_ONLY==1,"readOnly");\n';
  const file=path.join(tmp,'abi.cpp'),obj=path.join(tmp,'abi.obj');writeFileSync(file,cpp);const vc=String.raw`C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.50.35717`,sdk=String.raw`C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0`;
  const run=spawnSync(path.join(vc,'bin','Hostx64','x64','cl.exe'),['/nologo','/c','/TP','/W4','/WX',`/I${path.join(vc,'include')}`,...['ucrt','shared','um'].map(p=>`/I${path.join(sdk,p)}`),`/Fo${obj}`,file],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(run.status,0,run.stdout+run.stderr);
 });
});
