/// Anonymous Bilibili platform subtitle transport.
///
/// Follows the narrow public-player request chain used by a normal Bilibili
/// page: BV identity -> public metadata -> player subtitle list -> short-lived
/// BCC payload. It never sends or reads cookies, downloads video media, or
/// exposes the signed subtitle URL returned by the platform.
library;

import 'dart:convert';

import '../player_adapter.dart';
import 'bilibili_safe_http_transport.dart';

enum BilibiliTimedTextFailureKind {
  invalidVideo,
  noTrack,
  needsAuthorization,
  network,
  parserFailure,
  responseTooLarge,
}

class BilibiliTimedTextResult {
  const BilibiliTimedTextResult({this.track, this.error, this.failureKind});

  final TimedTextTrack? track;
  final String? error;
  final BilibiliTimedTextFailureKind? failureKind;

  bool get isSuccess => track != null;
}

class _BilibiliSubtitleDescriptor {
  const _BilibiliSubtitleDescriptor({
    required this.language,
    required this.url,
    required this.isAutoGenerated,
  });

  final String language;
  final Uri url;
  final bool isAutoGenerated;
}

class _BilibiliJsonFetchResult {
  const _BilibiliJsonFetchResult({this.payload, this.failure});

  final Object? payload;
  final BilibiliTimedTextResult? failure;
}

class _BilibiliBccParseResult {
  const _BilibiliBccParseResult({
    this.cues = const [],
    this.limitExceeded = false,
  });

  final List<TimedTextCue> cues;
  final bool limitExceeded;
}

/// Fetches platform-provided captions without a login session.
class BilibiliTimedTextService {
  BilibiliTimedTextService({
    BilibiliHttpTransport? transport,
    this.preferredLanguage = 'zh',
    this.metadataMaxBytes = 512 * 1024,
    this.playerMaxBytes = 1024 * 1024,
    this.bccMaxBytes = 8 * 1024 * 1024,
    this.maxCueCount = 20000,
    this.maxCueTextChars = 8000,
    this.maxTotalTextChars = 2000000,
  })  : assert(metadataMaxBytes > 0),
        assert(playerMaxBytes > 0),
        assert(bccMaxBytes > 0),
        assert(maxCueCount > 0),
        assert(maxCueTextChars > 0),
        assert(maxTotalTextChars > 0),
        transport = transport ?? BilibiliSafeHttpTransport();

  final BilibiliHttpTransport transport;
  final String preferredLanguage;
  final int metadataMaxBytes;
  final int playerMaxBytes;
  final int bccMaxBytes;
  final int maxCueCount;
  final int maxCueTextChars;
  final int maxTotalTextChars;

  bool _disposed = false;
  int _lifecycleEpoch = 0;

  String? extractBvid(String? value) {
    if (value == null || value.trim().isEmpty) return null;
    return RegExp(r'BV[0-9A-Za-z]{10}').firstMatch(value.trim())?.group(0);
  }

  Future<BilibiliTimedTextResult> fetchForVideo(
    String videoIdOrUrl, {
    required String sourceId,
    String? sourceVersionId,
  }) async {
    final bvid = extractBvid(videoIdOrUrl);
    if (bvid == null) {
      return const BilibiliTimedTextResult(
        error: '来源无效：无法识别哔哩哔哩 BV 号',
        failureKind: BilibiliTimedTextFailureKind.invalidVideo,
      );
    }
    if (_disposed) return _disposedResult;
    final epoch = _lifecycleEpoch;
    final referer = 'https://www.bilibili.com/video/$bvid';

    final metadataFetch = await _getJson(
      Uri.https('api.bilibili.com', '/x/web-interface/view', {'bvid': bvid}),
      referer: referer,
      maxBytes: metadataMaxBytes,
      stage: '视频元数据',
    );
    if (!_isCurrent(epoch)) return _disposedResult;
    if (metadataFetch.failure != null) return metadataFetch.failure!;
    final metadata = metadataFetch.payload;
    if (metadata is! Map<String, dynamic>) {
      return _parserFailure('视频元数据格式无法识别');
    }

    final metadataCode = _intValue(metadata['code']);
    if (metadataCode == null) {
      return _parserFailure('视频元数据缺少 code');
    }
    if (metadataCode != 0) {
      final message = _apiMessage(metadata);
      if (metadataCode == -400 ||
          metadataCode == -404 ||
          metadataCode == 62002) {
        return BilibiliTimedTextResult(
          error: '来源无效：${message ?? '平台未找到该视频'}',
          failureKind: BilibiliTimedTextFailureKind.invalidVideo,
        );
      }
      return BilibiliTimedTextResult(
        error: '地区或权限限制：${message ?? '平台未提供视频元数据'}',
        failureKind: BilibiliTimedTextFailureKind.needsAuthorization,
      );
    }

    final data = metadata['data'];
    if (data is! Map<String, dynamic>) {
      return _parserFailure('视频元数据缺少 data');
    }
    final aid = _intValue(data['aid']);
    final cid = _selectCid(data, videoIdOrUrl);
    if (aid == null || aid <= 0 || cid == null || cid <= 0) {
      return _parserFailure('视频元数据缺少 aid / cid');
    }

    final playerFetch = await _getJson(
      Uri.https('api.bilibili.com', '/x/player/wbi/v2', {
        'aid': '$aid',
        'bvid': bvid,
        'cid': '$cid',
      }),
      referer: referer,
      maxBytes: playerMaxBytes,
      stage: '字幕轨清单',
    );
    if (!_isCurrent(epoch)) return _disposedResult;
    if (playerFetch.failure != null) return playerFetch.failure!;
    final player = playerFetch.payload;
    if (player is! Map<String, dynamic>) {
      return _parserFailure('字幕轨清单格式无法识别');
    }

    final playerCode = _intValue(player['code']);
    if (playerCode == null) {
      return _parserFailure('字幕轨清单缺少 code');
    }
    if (playerCode != 0) {
      return BilibiliTimedTextResult(
        error: '地区或权限限制：${_apiMessage(player) ?? '平台未提供字幕轨'}',
        failureKind: BilibiliTimedTextFailureKind.needsAuthorization,
      );
    }

    final playerData = player['data'];
    if (playerData is! Map<String, dynamic>) {
      return _parserFailure('字幕轨清单缺少 data');
    }
    final subtitle = playerData['subtitle'];
    if (subtitle is! Map<String, dynamic>) {
      return const BilibiliTimedTextResult(
        error: '无字幕轨：当前视频未公开平台字幕，可导入 SRT / VTT',
        failureKind: BilibiliTimedTextFailureKind.noTrack,
      );
    }
    final needsLogin = subtitle['need_login_subtitle'] == true;
    final rawDescriptors = subtitle['subtitles'];
    final descriptors = _parseDescriptors(rawDescriptors);
    if (descriptors.isEmpty) {
      if (rawDescriptors is List && rawDescriptors.isNotEmpty) {
        return _parserFailure('字幕轨地址格式无法识别或来源不受信任');
      }
      return BilibiliTimedTextResult(
        error: needsLogin
            ? '匿名不可见：平台标记字幕需要登录权限；本应用不读取 Cookie，可导入 SRT / VTT'
            : '无字幕轨：当前视频未向匿名访问者公开字幕，可导入 SRT / VTT',
        failureKind: needsLogin
            ? BilibiliTimedTextFailureKind.needsAuthorization
            : BilibiliTimedTextFailureKind.noTrack,
      );
    }

    final chosen = _pickDescriptor(descriptors);
    final payloadFetch = await _getJson(
      chosen.url,
      referer: referer,
      maxBytes: bccMaxBytes,
      stage: '字幕内容',
    );
    if (!_isCurrent(epoch)) return _disposedResult;
    if (payloadFetch.failure != null) return payloadFetch.failure!;
    final parsed = _parseBcc(payloadFetch.payload, language: chosen.language);
    if (parsed.limitExceeded) {
      return _sizeFailure('字幕 cue 或文本');
    }
    final cues = parsed.cues;
    if (cues.isEmpty) {
      return _parserFailure('字幕内容为空或 bcc JSON 格式已变更');
    }

    final safeLanguage = chosen.language.replaceAll(
      RegExp(r'[^0-9A-Za-z_-]'),
      '_',
    );
    return BilibiliTimedTextResult(
      track: TimedTextTrack(
        trackId: 'bili_${bvid}_$safeLanguage',
        sourceId: sourceId,
        sourceVersionId: sourceVersionId,
        sourceKind: TimedTextSourceKind.platform,
        language: chosen.language,
        format: 'bcc-json',
        reliability: chosen.isAutoGenerated
            ? TimedTextReliability.partial
            : TimedTextReliability.reliable,
        rightsPolicy: 'bilibili platform captions',
        cues: cues,
      ),
    );
  }

  List<TimedTextCue> parseBcc(Object? payload, {String language = 'zh'}) {
    return _parseBcc(payload, language: language).cues;
  }

  _BilibiliBccParseResult _parseBcc(
    Object? payload, {
    String language = 'zh',
  }) {
    try {
      final decoded = payload is String ? jsonDecode(payload) : payload;
      if (decoded is! Map<String, dynamic>) {
        return const _BilibiliBccParseResult();
      }
      final body = decoded['body'];
      if (body is! List) return const _BilibiliBccParseResult();
      if (body.length > maxCueCount) {
        return const _BilibiliBccParseResult(limitExceeded: true);
      }
      final cues = <TimedTextCue>[];
      var totalTextChars = 0;
      for (final item in body) {
        if (item is! Map<String, dynamic>) continue;
        final from = item['from'];
        final to = item['to'];
        final content = item['content'];
        if (from is! num || to is! num || content is! String) continue;
        final text = content.trim();
        if (text.length > maxCueTextChars ||
            totalTextChars + text.length > maxTotalTextChars) {
          return const _BilibiliBccParseResult(limitExceeded: true);
        }
        final startMs = (from * 1000).round();
        final endMs = (to * 1000).round();
        if (startMs < 0 || endMs <= startMs || text.isEmpty) continue;
        totalTextChars += text.length;
        cues.add(
          TimedTextCue(
            cueId: 'cue_${language}_${cues.length + 1}',
            startMs: startMs,
            endMs: endMs,
            text: text,
          ),
        );
      }
      return _BilibiliBccParseResult(cues: cues);
    } catch (_) {
      return const _BilibiliBccParseResult();
    }
  }

  Future<_BilibiliJsonFetchResult> _getJson(
    Uri uri, {
    required String referer,
    required int maxBytes,
    required String stage,
  }) async {
    BilibiliHttpFetchResult result;
    try {
      result = await transport.getText(
        uri,
        headers: {
          'Accept': 'application/json, text/plain, */*',
          'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.6',
          'Referer': referer,
        },
        maxBytes: maxBytes,
      );
    } catch (_) {
      return _BilibiliJsonFetchResult(failure: _networkFailure(stage));
    }
    if (!result.isSuccess || result.body == null) {
      return _BilibiliJsonFetchResult(
        failure: _mapHttpFailure(result, stage),
      );
    }
    try {
      return _BilibiliJsonFetchResult(payload: jsonDecode(result.body!));
    } catch (_) {
      return _BilibiliJsonFetchResult(
        failure: _parserFailure('$stage不是有效 JSON'),
      );
    }
  }

  static BilibiliTimedTextResult _mapHttpFailure(
    BilibiliHttpFetchResult result,
    String stage,
  ) =>
      switch (result.failureKind) {
        BilibiliHttpFailureKind.accessRestricted => BilibiliTimedTextResult(
            error: '地区或权限限制：无法读取 Bilibili $stage',
            failureKind: BilibiliTimedTextFailureKind.needsAuthorization,
          ),
        BilibiliHttpFailureKind.responseTooLarge => _sizeFailure(stage),
        BilibiliHttpFailureKind.redirectRejected ||
        BilibiliHttpFailureKind.tooManyRedirects ||
        BilibiliHttpFailureKind.invalidResponse =>
          _parserFailure('Bilibili $stage安全请求失败：${result.message ?? '响应无效'}'),
        BilibiliHttpFailureKind.network || null => _networkFailure(stage),
      };

  static int? _selectCid(Map<String, dynamic> data, String videoRef) {
    var pageNumber = 1;
    final uri = Uri.tryParse(videoRef);
    final parsedPage = int.tryParse(uri?.queryParameters['p'] ?? '');
    if (parsedPage != null && parsedPage > 0) pageNumber = parsedPage;
    final pages = data['pages'];
    if (pages is List && pages.isNotEmpty) {
      Map<String, dynamic>? selected;
      for (final page in pages) {
        if (page is Map<String, dynamic> &&
            _intValue(page['page']) == pageNumber) {
          selected = page;
          break;
        }
      }
      selected ??= pages.first is Map<String, dynamic>
          ? pages.first as Map<String, dynamic>
          : null;
      final pageCid = selected == null ? null : _intValue(selected['cid']);
      if (pageCid != null) return pageCid;
    }
    return _intValue(data['cid']);
  }

  static List<_BilibiliSubtitleDescriptor> _parseDescriptors(Object? value) {
    if (value is! List) return const [];
    final tracks = <_BilibiliSubtitleDescriptor>[];
    for (final item in value) {
      if (item is! Map<String, dynamic>) continue;
      final language = item['lan'];
      final rawUrl = item['subtitle_url'];
      if (language is! String || language.isEmpty || rawUrl is! String) {
        continue;
      }
      final normalized = rawUrl.startsWith('//') ? 'https:$rawUrl' : rawUrl;
      final uri = Uri.tryParse(normalized);
      if (uri == null || !BilibiliSafeHttpTransport.isAllowedUri(uri)) {
        continue;
      }
      tracks.add(
        _BilibiliSubtitleDescriptor(
          language: language,
          url: uri,
          isAutoGenerated:
              language.toLowerCase().startsWith('ai-') || item['type'] == 1,
        ),
      );
    }
    return tracks;
  }

  _BilibiliSubtitleDescriptor _pickDescriptor(
    List<_BilibiliSubtitleDescriptor> tracks,
  ) {
    final preferred = preferredLanguage.toLowerCase();
    final languageMatches = tracks.where((track) {
      final language = track.language.toLowerCase();
      return language == preferred ||
          language.startsWith('$preferred-') ||
          language == 'ai-$preferred';
    }).toList();
    final candidates = languageMatches.isEmpty ? tracks : languageMatches;
    return candidates.firstWhere(
      (track) => !track.isAutoGenerated,
      orElse: () => candidates.first,
    );
  }

  static int? _intValue(Object? value) => value is num ? value.toInt() : null;

  static String? _apiMessage(Map<String, dynamic> payload) {
    final message = payload['message'] ?? payload['msg'];
    return message is String && message.trim().isNotEmpty
        ? message.trim()
        : null;
  }

  static BilibiliTimedTextResult _networkFailure(String stage) =>
      BilibiliTimedTextResult(
        error: '网络失败：无法读取 Bilibili $stage',
        failureKind: BilibiliTimedTextFailureKind.network,
      );

  static BilibiliTimedTextResult _parserFailure(String detail) =>
      BilibiliTimedTextResult(
        error: '解析器失效：$detail',
        failureKind: BilibiliTimedTextFailureKind.parserFailure,
      );

  static BilibiliTimedTextResult _sizeFailure(String stage) =>
      BilibiliTimedTextResult(
        error: '响应过大：Bilibili $stage超过安全预算',
        failureKind: BilibiliTimedTextFailureKind.responseTooLarge,
      );

  static const _disposedResult = BilibiliTimedTextResult(
    error: '字幕请求已结束',
    failureKind: BilibiliTimedTextFailureKind.network,
  );

  bool _isCurrent(int epoch) => !_disposed && epoch == _lifecycleEpoch;

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _lifecycleEpoch++;
    transport.dispose();
  }
}
