/// YouTube platform subtitle auto-fetch (timedtext) — runtime implementation.
///
/// Fetches the caption track list from the watch page's
/// `ytInitialPlayerResponse` (the officially embedded player response), picks
/// the best language match, then fetches the signed `baseUrl` as JSON3 and
/// parses it into [TimedTextCue]s.
///
/// **Honesty contract**: any failure — network error, bot-block, CORS,
/// missing captions, empty track — returns an honest [YouTubeTimedTextResult]
/// with `track == null` and a human-readable [YouTubeTimedTextResult.error].
/// The service never fabricates cues or claims support that did not load. The
/// UI shows "需要字幕" plus this reason until a real track is loaded (either
/// auto-fetched or user-imported SRT/VTT).
///
/// **Compliance**: only uses YouTube's public watch page and its signed
/// public caption endpoints. No downloads of the video, no DRM / login /
/// payment bypass — captions are only available for tracks the platform
/// itself exposes.
///
/// Auto-generated (ASR) tracks are marked [TimedTextReliability.partial];
/// manually authored tracks are [TimedTextReliability.reliable].
library;

import 'dart:convert';

import '../player_adapter.dart';
import 'timedtext_transport.dart';

/// One caption track discovered on the YouTube watch page.
class YouTubeCaptionTrack {
  final String languageCode;
  final String? displayName;
  final String baseUrl;
  final bool isAutoGenerated;

  const YouTubeCaptionTrack({
    required this.languageCode,
    this.displayName,
    required this.baseUrl,
    this.isAutoGenerated = false,
  });

  String get selectionKey => baseUrl;

  String get label {
    final name = displayName?.trim();
    final kind = isAutoGenerated ? '自动生成' : '人工字幕';
    return '${name?.isNotEmpty == true ? name : languageCode} · $kind';
  }
}

/// User-visible failure buckets for platform caption discovery/loading.
enum YouTubeTimedTextFailureKind {
  invalidVideo,
  noTrack,
  accessRestricted,
  network,
  parserFailure,
}

/// The result of a subtitle auto-fetch attempt.
///
/// Either [track] (loaded, usable platform track) or [error] (honest reason
/// why no track could be loaded). Never both.
class YouTubeTimedTextResult {
  final TimedTextTrack? track;
  final String? error;
  final YouTubeTimedTextFailureKind? failureKind;
  final List<YouTubeCaptionTrack> availableTracks;
  final YouTubeCaptionTrack? selectedTrack;

  const YouTubeTimedTextResult({
    this.track,
    this.error,
    this.failureKind,
    this.availableTracks = const [],
    this.selectedTrack,
  });

  bool get isSuccess => track != null;
}

/// Fetches and parses YouTube platform subtitles for a video.
class YouTubeTimedTextService {
  final TimedTextTransport transport;

  /// Preferred language code for track selection (e.g. 'zh' or 'en').
  /// Falls back to English, then to the first available track.
  final String preferredLanguage;

  /// Optional custom timeout for the track-list / cue fetches.
  final Duration timeout;

  YouTubeTimedTextService({
    TimedTextTransport? transport,
    this.preferredLanguage = 'zh',
    this.timeout = const Duration(seconds: 8),
  }) : transport = transport ?? HttpTimedTextTransport();

  /// Extracts an 11-character YouTube video ID from a URL or raw ID.
  ///
  /// Returns null when [videoIdOrUrl] is not a recognizable YouTube video
  /// reference.
  String? extractVideoId(String? videoIdOrUrl) {
    final url = videoIdOrUrl;
    if (url == null || url.isEmpty) return null;
    if (RegExp(r'^[a-zA-Z0-9_-]{11}$').hasMatch(url)) return url;
    final watchMatch = RegExp(r'[?&]v=([a-zA-Z0-9_-]{11})').firstMatch(url);
    if (watchMatch != null) return watchMatch.group(1);
    final shortMatch = RegExp(r'youtu\.be/([a-zA-Z0-9_-]{11})').firstMatch(url);
    if (shortMatch != null) return shortMatch.group(1);
    final embedMatch = RegExp(r'embed/([a-zA-Z0-9_-]{11})').firstMatch(url);
    if (embedMatch != null) return embedMatch.group(1);
    final shortsMatch = RegExp(r'shorts/([a-zA-Z0-9_-]{11})').firstMatch(url);
    if (shortsMatch != null) return shortsMatch.group(1);
    return null;
  }

  /// Attempts to auto-fetch platform subtitles for [videoIdOrUrl].
  ///
  /// Returns a successful result with a [TimedTextTrack] (sourceKind
  /// `platform`) when captions exist and could be loaded; otherwise an honest
  /// error result. Never throws — all failures are captured in [error].
  Future<YouTubeTimedTextResult> fetchForVideo(
    String videoIdOrUrl, {
    required String sourceId,
    String? sourceVersionId,
  }) async {
    final videoId = extractVideoId(videoIdOrUrl);
    if (videoId == null) {
      return const YouTubeTimedTextResult(
        error: '无法识别 YouTube 视频 ID，自动获取字幕失败',
        failureKind: YouTubeTimedTextFailureKind.invalidVideo,
      );
    }

    final discovery = await _discoverTracks(videoId);
    final tracks = discovery.tracks;
    if (tracks.isEmpty) return discovery.failure!;

    final chosen = _pickTrack(tracks);
    if (chosen == null) {
      return YouTubeTimedTextResult(
        error: '字幕轨解析器未能选择可用轨道',
        failureKind: YouTubeTimedTextFailureKind.parserFailure,
        availableTracks: tracks,
      );
    }

    return fetchTrack(
      chosen,
      sourceId: sourceId,
      sourceVersionId: sourceVersionId,
      availableTracks: tracks,
    );
  }

  /// Loads one explicitly selected track discovered for the current video.
  Future<YouTubeTimedTextResult> fetchTrack(
    YouTubeCaptionTrack chosen, {
    required String sourceId,
    String? sourceVersionId,
    List<YouTubeCaptionTrack> availableTracks = const [],
  }) async {
    String? raw;
    try {
      raw = await _fetchTrackPayload(chosen).timeout(timeout);
    } catch (_) {
      raw = null;
    }
    if (raw == null) {
      return YouTubeTimedTextResult(
        error: '网络失败：无法读取字幕轨 ${chosen.languageCode}',
        failureKind: YouTubeTimedTextFailureKind.network,
        availableTracks: availableTracks,
        selectedTrack: chosen,
      );
    }
    final cues = parseJson3(raw, language: chosen.languageCode);
    if (cues.isEmpty) {
      return YouTubeTimedTextResult(
        error: '解析器失效：字幕轨 ${chosen.languageCode} 返回了无法识别或为空的内容',
        failureKind: YouTubeTimedTextFailureKind.parserFailure,
        availableTracks: availableTracks,
        selectedTrack: chosen,
      );
    }
    final providerVideoId =
        Uri.tryParse(chosen.baseUrl)?.queryParameters['v'] ?? sourceId;
    final trackSuffix = providerVideoId.length > 6
        ? providerVideoId.substring(0, 6)
        : providerVideoId;

    return YouTubeTimedTextResult(
      track: TimedTextTrack(
        trackId: 'yt_${chosen.languageCode}_$trackSuffix',
        sourceId: sourceId,
        sourceVersionId: sourceVersionId,
        sourceKind: TimedTextSourceKind.platform,
        language: chosen.languageCode,
        format: 'json3',
        reliability: chosen.isAutoGenerated
            ? TimedTextReliability.partial
            : TimedTextReliability.reliable,
        rightsPolicy: 'youtube public captions',
        cues: cues,
      ),
      availableTracks: availableTracks,
      selectedTrack: chosen,
    );
  }

  Future<_YouTubeTrackDiscovery> _discoverTracks(String videoId) async {
    var receivedPage = false;
    var sawParserShape = false;
    var sawRestriction = false;
    for (final url in [
      'https://www.youtube.com/watch?v=$videoId',
      'https://www.youtube.com/embed/$videoId',
    ]) {
      String? html;
      try {
        html = await transport.getText(url).timeout(timeout);
      } catch (_) {
        html = null;
      }
      if (html == null || html.trim().isEmpty) continue;
      receivedPage = true;
      sawRestriction = sawRestriction || _looksAccessRestricted(html);
      sawParserShape = sawParserShape || html.contains('"captionTracks"');
      final parsed = parseTrackList(html);
      if (parsed != null && parsed.isNotEmpty) {
        return _YouTubeTrackDiscovery(tracks: parsed);
      }
    }
    if (!receivedPage) {
      return const _YouTubeTrackDiscovery(
        failure: YouTubeTimedTextResult(
          error: '网络失败：无法读取 YouTube 字幕清单（含网络、超时或跨域限制）',
          failureKind: YouTubeTimedTextFailureKind.network,
        ),
      );
    }
    if (sawRestriction) {
      return const _YouTubeTrackDiscovery(
        failure: YouTubeTimedTextResult(
          error: '地区或权限限制：平台未向当前访问环境提供字幕轨',
          failureKind: YouTubeTimedTextFailureKind.accessRestricted,
        ),
      );
    }
    if (sawParserShape) {
      return const _YouTubeTrackDiscovery(
        failure: YouTubeTimedTextResult(
          error: '解析器失效：YouTube 页面包含字幕结构，但当前解析器无法识别',
          failureKind: YouTubeTimedTextFailureKind.parserFailure,
        ),
      );
    }
    return const _YouTubeTrackDiscovery(
      failure: YouTubeTimedTextResult(
        error: '无字幕轨：该视频没有向平台播放器公开 CC 字幕',
        failureKind: YouTubeTimedTextFailureKind.noTrack,
      ),
    );
  }

  static bool _looksAccessRestricted(String html) {
    final lower = html.toLowerCase();
    return lower.contains('login_required') ||
        lower.contains('age_check_required') ||
        lower.contains('region') && lower.contains('restrict') ||
        lower.contains('not available in your country') ||
        lower.contains('sign in to confirm');
  }

  /// Parses `captionTracks` from a watch/embed page's player response.
  ///
  /// Works on the raw HTML without depending on the full
  /// `ytInitialPlayerResponse` JSON: the `captionTracks` array itself is
  /// valid JSON. Returns null when the page has no captions or the structure
  /// is unrecognized (e.g. bot-blocked page).
  List<YouTubeCaptionTrack>? parseTrackList(String html) {
    final match =
        RegExp(r'"captionTracks":\s*(\[.*?\])', dotAll: true).firstMatch(html);
    if (match == null) return null;
    try {
      final raw = jsonDecode(match.group(1)!) as List<dynamic>;
      final tracks = <YouTubeCaptionTrack>[];
      for (final item in raw) {
        final map = item as Map<String, dynamic>;
        final baseUrl = map['baseUrl'] as String?;
        if (baseUrl == null || baseUrl.isEmpty) continue;
        final lang = map['languageCode'] as String? ?? '';
        if (lang.isEmpty) continue;
        final nameMap = map['name'] as Map<String, dynamic>?;
        tracks.add(YouTubeCaptionTrack(
          languageCode: lang,
          displayName: nameMap?['simpleText'] as String?,
          baseUrl: baseUrl,
          isAutoGenerated: map['kind'] == 'asr',
        ));
      }
      return tracks.isEmpty ? null : tracks;
    } catch (_) {
      return null;
    }
  }

  /// Picks the best track: preferred language, then English, then first.
  YouTubeCaptionTrack? _pickTrack(List<YouTubeCaptionTrack> tracks) {
    for (final t in tracks) {
      if (t.languageCode == preferredLanguage ||
          t.languageCode
              .toLowerCase()
              .startsWith('${preferredLanguage.toLowerCase()}-')) {
        return t;
      }
    }
    for (final t in tracks) {
      if (t.languageCode.toLowerCase().startsWith('en')) return t;
    }
    return tracks.first;
  }

  /// Fetches a track's cues from its signed `baseUrl` (JSON3 format).
  ///
  /// Returns an empty list when the fetch fails or the payload has no usable
  /// events.
  Future<String?> _fetchTrackPayload(YouTubeCaptionTrack track) async {
    final sep = track.baseUrl.contains('?') ? '&' : '?';
    final url = '${track.baseUrl}${sep}fmt=json3';
    return transport.getText(url);
  }

  /// Parses a YouTube JSON3 caption payload into cues.
  ///
  /// Handles multi-segment lines (`tOffsetMs`) and missing durations (cue
  /// ends at the next cue's start; the last cue gets a 2s fallback).
  /// Exposed for testing; returns an empty list on malformed input.
  List<TimedTextCue> parseJson3(String raw, {String language = 'unknown'}) {
    try {
      final decoded = jsonDecode(raw) as Map<String, dynamic>;
      final events = decoded['events'] as List<dynamic>? ?? const [];
      final cues = <TimedTextCue>[];
      for (var i = 0; i < events.length; i++) {
        final ev = events[i];
        if (ev is! Map<String, dynamic>) continue;
        final startNum = ev['tStartMs'] ?? ev['aStartMs'];
        if (startNum is! num) continue;
        final startMs = startNum.toInt();
        final durNum = ev['dDurationMs'] ?? ev['tDurationMs'];
        final segs = ev['segs'];
        var text = '';
        if (segs is List) {
          for (final seg in segs) {
            if (seg is! Map<String, dynamic>) continue;
            final offset = (seg['tOffsetMs'] as num?)?.toInt() ?? 0;
            if (offset > 0) text += '\n';
            text += seg['utf8'] as String? ?? '';
          }
        }
        if (text.trim().isEmpty) continue;
        int endMs;
        if (durNum is num && durNum > 0) {
          endMs = startMs + durNum.toInt();
        } else if (i + 1 < events.length) {
          final next = events[i + 1];
          final nextStart = next is Map<String, dynamic>
              ? (next['tStartMs'] ?? next['aStartMs'])
              : null;
          endMs = nextStart is num ? nextStart.toInt() : startMs + 2000;
        } else {
          endMs = startMs + 2000;
        }
        cues.add(TimedTextCue(
          cueId: 'cue_${language}_${i + 1}',
          startMs: startMs,
          endMs: endMs,
          text: text,
        ));
      }
      return cues;
    } catch (_) {
      return const [];
    }
  }

  /// Closes the underlying transport (no-op for injected fakes without one).
  void dispose() {
    final t = transport;
    if (t is HttpTimedTextTransport) t.dispose();
  }
}

class _YouTubeTrackDiscovery {
  const _YouTubeTrackDiscovery({this.tracks = const [], this.failure});

  final List<YouTubeCaptionTrack> tracks;
  final YouTubeTimedTextResult? failure;
}
