library;

import 'dart:collection';
import 'dart:convert';

import 'package:crypto/crypto.dart';

import 'package:memex/data/whiteboard/domain_commands/whiteboard_domain_command_executor.dart';
import 'package:memex/data/whiteboard/whiteboard_drift_store.dart';
import 'package:memex/data/workbench_ai/search/workbench_runtime_search_tool.dart'
    show WorkbenchRuntimeToolResult;
import 'package:memex/data/workbench_ai/whiteboard_workbench_coordinator.dart';
import 'package:memex/data/workbench_ai/whiteboard_workbench_surface.dart';
import 'package:memex/db/app_database.dart';
import 'package:memex/domain/whiteboard/domain_command.dart';
import 'package:memex/domain/whiteboard/domain_command_receipt.dart';
import 'package:memex/domain/workbench_ai/permissions/whiteboard_permission_broker.dart';

class WhiteboardRuntimeTurnAuthorization {
  const WhiteboardRuntimeTurnAuthorization({
    required this.conversationId,
    required this.characterId,
    required this.userAuthorizationMessageId,
    required this.allowedCapabilities,
    this.surfaceOwner,
    this.boardId,
    this.boardName,
    this.selectedItemIds = const {},
    this.selectedCardIds = const {},
    this.expectedSnapshotHash,
    this.unavailableReason,
  });

  final String conversationId;
  final String characterId;
  final String userAuthorizationMessageId;
  final Object? surfaceOwner;
  final String? boardId;
  final String? boardName;
  final Set<String> selectedItemIds;
  final Set<String> selectedCardIds;
  final Set<WhiteboardWriteCapability> allowedCapabilities;
  final String? expectedSnapshotHash;
  final String? unavailableReason;

  bool get available =>
      surfaceOwner != null &&
      boardId != null &&
      expectedSnapshotHash != null &&
      unavailableReason == null;

  String toPromptBlock() {
    if (!available) {
      return '当前白板写工具不可用：${unavailableReason ?? 'whiteboard_unavailable'}。'
          '不要改用浏览器工具、模拟点击或声称已操作白板。';
    }
    final capabilities =
        allowedCapabilities.map((value) => value.wireName).toList()..sort();
    final items = selectedItemIds.toList()..sort();
    final cards = selectedCardIds.toList()..sort();
    return '当前打开白板：$boardName；宿主持有 board scope。'
        '本轮只授权：${capabilities.join(', ')}；'
        '选中 item ids：${items.join(', ')}；'
        '对应 card ids：${cards.join(', ')}。'
        '明确白板写请求必须调用 '
        '${WorkbenchRuntimeWhiteboardDomainTool.toolName}，不要调用浏览器工具；'
        '不要在参数里提供 board、授权、hash、turn 或消息证据。';
  }
}

/// Runtime adapter for the six frozen provider-neutral DomainCommands.
///
/// Provider payloads describe only the requested command data. Board scope,
/// selected targets, baseline hash, actor turn, authorization and message
/// evidence are captured and enforced by the desktop host.
class WorkbenchRuntimeWhiteboardDomainTool {
  WorkbenchRuntimeWhiteboardDomainTool({
    required WhiteboardDriftStore store,
    required WhiteboardWorkbenchCoordinator coordinator,
    required WhiteboardWorkbenchSurfaceController surfaceController,
  })  : _store = store,
        _coordinator = coordinator,
        _surfaceController = surfaceController;

  factory WorkbenchRuntimeWhiteboardDomainTool.production() =>
      WorkbenchRuntimeWhiteboardDomainTool(
        store: WhiteboardDriftStore(AppDatabase.instance),
        coordinator: WhiteboardWorkbenchCoordinator.instance,
        surfaceController: WhiteboardWorkbenchSurfaceController.instance,
      );

  static const toolName = 'whiteboard_domain_commands';

  static const toolDefinition = <String, dynamic>{
    'name': toolName,
    'description':
        'Apply only the user-authorized create/edit-body/set-labels/move/'
            'resize/remove-placement operations to the currently open '
            'Here I am whiteboard. Removing a placement never deletes a card.',
    'input_schema': {
      'type': 'object',
      'additionalProperties': false,
      'required': ['commands'],
      'properties': {
        'commands': {
          'type': 'array',
          'minItems': 1,
          'maxItems': 64,
          'items': {
            'description': 'Exactly one of the six supported command shapes. '
                'New card and placement ids are generated by the host.',
            'oneOf': [
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind'],
                'properties': {
                  'kind': {'const': 'create_card'},
                  'title': {'type': 'string'},
                  'body': {'type': 'string'},
                  'labels': {
                    'type': 'array',
                    'items': {'type': 'string'},
                  },
                  'x': {'type': 'number'},
                  'y': {'type': 'number'},
                  'width': {'type': 'number', 'exclusiveMinimum': 0},
                  'height': {'type': 'number', 'exclusiveMinimum': 0},
                },
              },
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind', 'card_id', 'body'],
                'properties': {
                  'kind': {'const': 'edit_card_body'},
                  'card_id': {'type': 'string', 'minLength': 1},
                  'body': {'type': 'string'},
                },
              },
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind', 'card_id', 'labels'],
                'properties': {
                  'kind': {'const': 'set_card_labels'},
                  'card_id': {'type': 'string', 'minLength': 1},
                  'labels': {
                    'type': 'array',
                    'items': {'type': 'string'},
                  },
                },
              },
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind', 'item_id', 'x', 'y'],
                'properties': {
                  'kind': {'const': 'move_placement'},
                  'item_id': {'type': 'string', 'minLength': 1},
                  'x': {'type': 'number'},
                  'y': {'type': 'number'},
                },
              },
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind', 'item_id', 'width', 'height'],
                'properties': {
                  'kind': {'const': 'resize_placement'},
                  'item_id': {'type': 'string', 'minLength': 1},
                  'width': {'type': 'number', 'exclusiveMinimum': 0},
                  'height': {'type': 'number', 'exclusiveMinimum': 0},
                },
              },
              {
                'type': 'object',
                'additionalProperties': false,
                'required': ['kind', 'item_id'],
                'properties': {
                  'kind': {'const': 'remove_placement'},
                  'item_id': {'type': 'string', 'minLength': 1},
                },
              },
            ],
          },
        },
      },
    },
  };

  final WhiteboardDriftStore _store;
  final WhiteboardWorkbenchCoordinator _coordinator;
  final WhiteboardWorkbenchSurfaceController _surfaceController;
  final Map<String, Future<WorkbenchRuntimeToolResult>> _inflight = {};
  final LinkedHashMap<String, WorkbenchRuntimeToolResult> _completed =
      LinkedHashMap();

  static const _maxCompletedInvocations = 128;

  Map<String, dynamic> get dynamicToolDefinition =>
      WorkbenchRuntimeWhiteboardDomainTool.toolDefinition;

  Future<WhiteboardRuntimeTurnAuthorization?> prepareAuthorization({
    required String conversationId,
    required String characterId,
    required String userText,
    required String? userAuthorizationMessageId,
  }) async {
    final capabilities = _capabilitiesFromExplicitRequest(userText);
    if (capabilities.isEmpty) return null;
    final evidence = userAuthorizationMessageId?.trim();
    if (evidence == null || evidence.isEmpty) {
      return WhiteboardRuntimeTurnAuthorization(
        conversationId: conversationId,
        characterId: characterId,
        userAuthorizationMessageId: 'missing',
        allowedCapabilities: capabilities,
        unavailableReason: 'authorization_evidence_missing',
      );
    }
    final surface = _surfaceController.current;
    if (surface == null) {
      return WhiteboardRuntimeTurnAuthorization(
        conversationId: conversationId,
        characterId: characterId,
        userAuthorizationMessageId: evidence,
        allowedCapabilities: capabilities,
        unavailableReason: 'whiteboard_not_open',
      );
    }
    try {
      if (!await surface.flush()) {
        return _unavailable(
          conversationId,
          characterId,
          evidence,
          capabilities,
          'whiteboard_save_failed',
        );
      }
      final loaded = await _store.load(surface.boardId);
      final snapshot = loaded.snapshot;
      final current = _surfaceController.current;
      if (!loaded.isSuccess ||
          snapshot == null ||
          current == null ||
          !identical(current.owner, surface.owner) ||
          current.boardId != surface.boardId) {
        return _unavailable(
          conversationId,
          characterId,
          evidence,
          capabilities,
          'whiteboard_surface_changed',
        );
      }
      final selectedItems = Set<String>.unmodifiable(surface.selectedItemIds);
      final selectedCards = Set<String>.unmodifiable(
        snapshot.boardItems
            .where((item) =>
                item.boardId == surface.boardId &&
                selectedItems.contains(item.itemId))
            .map((item) => item.cardId),
      );
      var boardName = surface.boardId;
      for (final board in snapshot.boards) {
        if (board.boardId == surface.boardId) {
          boardName = board.name;
          break;
        }
      }
      return WhiteboardRuntimeTurnAuthorization(
        conversationId: conversationId,
        characterId: characterId,
        userAuthorizationMessageId: evidence,
        surfaceOwner: surface.owner,
        boardId: surface.boardId,
        boardName: boardName,
        selectedItemIds: selectedItems,
        selectedCardIds: selectedCards,
        allowedCapabilities: capabilities,
        expectedSnapshotHash:
            WhiteboardDomainCommandExecutor.snapshotHash(snapshot),
      );
    } catch (_) {
      return _unavailable(
        conversationId,
        characterId,
        evidence,
        capabilities,
        'whiteboard_scope_unavailable',
      );
    }
  }

  Future<WorkbenchRuntimeToolResult> invoke(
    Object? arguments, {
    required WhiteboardRuntimeTurnAuthorization authorization,
    required String runtimeTurnId,
    required bool Function() isCancelled,
  }) async {
    if (!authorization.available) {
      return _failure(
          authorization.unavailableReason ?? 'whiteboard_unavailable');
    }
    if (isCancelled()) return _failure('runtime_interrupted');
    final surface = _surfaceController.current;
    if (surface == null ||
        !identical(surface.owner, authorization.surfaceOwner) ||
        surface.boardId != authorization.boardId) {
      return _failure('whiteboard_surface_changed');
    }
    surface.setInteractionLocked(true);
    try {
      final parsed = _parseBatch(
        arguments,
        authorization: authorization,
        runtimeTurnId: runtimeTurnId,
      );
      if (parsed is String) return _failure(parsed, invalid: true);
      if (isCancelled()) return _failure('runtime_interrupted');
      final current = _surfaceController.current;
      if (current == null ||
          !identical(current.owner, authorization.surfaceOwner) ||
          current.boardId != authorization.boardId) {
        return _failure('whiteboard_surface_changed');
      }
      final batch = parsed as WhiteboardDomainCommandBatch;
      return await _executeIdempotently(
        batch,
        authorization: authorization,
        runtimeTurnId: runtimeTurnId,
        isCancelled: isCancelled,
      );
    } catch (_) {
      return _failure('whiteboard_tool_failed');
    } finally {
      final current = _surfaceController.current;
      if (current != null &&
          identical(current.owner, authorization.surfaceOwner) &&
          current.boardId == authorization.boardId) {
        try {
          await current.reload();
        } catch (_) {
          // The Domain receipt remains authoritative even if visual refresh
          // fails. The route exposes its own reload error and can retry.
        }
      }
      try {
        surface.setInteractionLocked(false);
      } catch (_) {
        // A disposed/switching surface cannot invalidate a committed receipt.
      }
    }
  }

  Future<WorkbenchRuntimeToolResult> _executeIdempotently(
    WhiteboardDomainCommandBatch batch, {
    required WhiteboardRuntimeTurnAuthorization authorization,
    required String runtimeTurnId,
    required bool Function() isCancelled,
  }) async {
    final operationId = batch.operationBatchId;
    final completed = _completed.remove(operationId);
    if (completed != null) {
      _completed[operationId] = completed;
      return completed;
    }
    final existing = _inflight[operationId];
    if (existing != null) return existing;
    final operation = () async {
      final grant = _coordinator.authorizeRuntimeDomainCommands(
        batch: batch,
        runtimeTurnId: runtimeTurnId,
        userAuthorizationMessageId: authorization.userAuthorizationMessageId,
      );
      if (isCancelled()) return _failure('runtime_interrupted');
      final receipt = await _coordinator.executeRuntimeDomainCommands(
        characterId: authorization.characterId,
        batch: batch,
        authorizationId: grant.authorizationId,
        runtimeTurnId: runtimeTurnId,
        userAuthorizationMessageId: authorization.userAuthorizationMessageId,
      );
      return WorkbenchRuntimeToolResult(
        success: receipt.status == WhiteboardDomainCommandStatus.applied,
        text: jsonEncode(receipt.toJson()),
      );
    }();
    _inflight[operationId] = operation;
    try {
      final result = await operation;
      if (result.success) {
        _completed[operationId] = result;
        while (_completed.length > _maxCompletedInvocations) {
          _completed.remove(_completed.keys.first);
        }
      }
      return result;
    } finally {
      _inflight.remove(operationId);
    }
  }

  Object _parseBatch(
    Object? arguments, {
    required WhiteboardRuntimeTurnAuthorization authorization,
    required String runtimeTurnId,
  }) {
    if (arguments is! Map) return 'invalid_whiteboard_request';
    final payload = Map<String, dynamic>.from(arguments);
    if (payload.length != 1 || payload['commands'] is! List) {
      return 'invalid_whiteboard_request';
    }
    final rawCommands = payload['commands'] as List;
    if (rawCommands.isEmpty ||
        rawCommands.length > WhiteboardDomainCommandExecutor.hardMaxCommands) {
      return 'invalid_whiteboard_request';
    }
    final canonical = jsonEncode(_canonicalJson(payload));
    final seed = sha256
        .convert(utf8.encode(
          '${authorization.conversationId}|$runtimeTurnId|'
          '${authorization.userAuthorizationMessageId}|$canonical',
        ))
        .toString();
    final allowedItems = {...authorization.selectedItemIds};
    final allowedCards = {...authorization.selectedCardIds};
    final commands = <WhiteboardDomainCommand>[];
    for (var index = 0; index < rawCommands.length; index++) {
      final raw = rawCommands[index];
      if (raw is! Map) return 'invalid_whiteboard_request';
      final command = Map<String, dynamic>.from(raw);
      final kind = command['kind'];
      final capability = _capabilityForKind(kind);
      if (capability == null ||
          !authorization.allowedCapabilities.contains(capability)) {
        return 'whiteboard_capability_denied';
      }
      final commandId = 'command:${seed.substring(0, 20)}:$index';
      switch (kind) {
        case 'create_card':
          if (!_onlyKeys(command, const {
            'kind',
            'title',
            'body',
            'labels',
            'x',
            'y',
            'width',
            'height',
          })) {
            return 'invalid_whiteboard_request';
          }
          final cardId = 'card:${seed.substring(0, 24)}:$index';
          final itemId = 'item:${seed.substring(0, 24)}:$index';
          final labels = _stringList(command['labels']);
          if (labels == null) return 'invalid_whiteboard_request';
          commands.add(CreateCardCommand(
            commandId: commandId,
            cardId: cardId,
            itemId: itemId,
            title: _optionalString(command['title']) ?? '',
            body: _optionalString(command['body']) ?? '',
            labels: labels,
            x: _number(command['x'], 0),
            y: _number(command['y'], 0),
            width: _number(command['width'], 260),
            height: _number(command['height'], 200),
          ));
          allowedCards.add(cardId);
          allowedItems.add(itemId);
          continue;
        case 'edit_card_body':
          if (!_onlyKeys(command, const {'kind', 'card_id', 'body'})) {
            return 'invalid_whiteboard_request';
          }
          final cardId = _requiredString(command['card_id']);
          final body = command['body'];
          if (cardId == null ||
              body is! String ||
              !allowedCards.contains(cardId)) {
            return 'whiteboard_target_outside_scope';
          }
          commands.add(EditCardBodyCommand(
            commandId: commandId,
            cardId: cardId,
            body: body,
          ));
          continue;
        case 'set_card_labels':
          if (!_onlyKeys(command, const {'kind', 'card_id', 'labels'})) {
            return 'invalid_whiteboard_request';
          }
          final cardId = _requiredString(command['card_id']);
          final labels = _stringList(command['labels']);
          if (cardId == null ||
              labels == null ||
              !allowedCards.contains(cardId)) {
            return 'whiteboard_target_outside_scope';
          }
          commands.add(SetCardLabelsCommand(
            commandId: commandId,
            cardId: cardId,
            labels: labels,
          ));
          continue;
        case 'move_placement':
          if (!_onlyKeys(command, const {'kind', 'item_id', 'x', 'y'})) {
            return 'invalid_whiteboard_request';
          }
          final itemId = _requiredString(command['item_id']);
          if (itemId == null || !allowedItems.contains(itemId)) {
            return 'whiteboard_target_outside_scope';
          }
          commands.add(MovePlacementCommand(
            commandId: commandId,
            itemId: itemId,
            x: _requiredNumber(command['x']),
            y: _requiredNumber(command['y']),
          ));
          continue;
        case 'resize_placement':
          if (!_onlyKeys(command, const {
            'kind',
            'item_id',
            'width',
            'height',
          })) {
            return 'invalid_whiteboard_request';
          }
          final itemId = _requiredString(command['item_id']);
          if (itemId == null || !allowedItems.contains(itemId)) {
            return 'whiteboard_target_outside_scope';
          }
          commands.add(ResizePlacementCommand(
            commandId: commandId,
            itemId: itemId,
            width: _requiredNumber(command['width']),
            height: _requiredNumber(command['height']),
          ));
          continue;
        case 'remove_placement':
          if (!_onlyKeys(command, const {'kind', 'item_id'})) {
            return 'invalid_whiteboard_request';
          }
          final itemId = _requiredString(command['item_id']);
          if (itemId == null || !allowedItems.contains(itemId)) {
            return 'whiteboard_target_outside_scope';
          }
          commands.add(RemovePlacementCommand(
            commandId: commandId,
            itemId: itemId,
          ));
          continue;
      }
    }
    return WhiteboardDomainCommandBatch(
      operationBatchId: 'batch:${seed.substring(0, 28)}',
      boardId: authorization.boardId!,
      expectedSnapshotHash: authorization.expectedSnapshotHash,
      commands: commands,
    );
  }

  WhiteboardRuntimeTurnAuthorization _unavailable(
    String conversationId,
    String characterId,
    String evidence,
    Set<WhiteboardWriteCapability> capabilities,
    String reason,
  ) =>
      WhiteboardRuntimeTurnAuthorization(
        conversationId: conversationId,
        characterId: characterId,
        userAuthorizationMessageId: evidence,
        allowedCapabilities: capabilities,
        unavailableReason: reason,
      );

  WorkbenchRuntimeToolResult _failure(String code, {bool invalid = false}) =>
      WorkbenchRuntimeToolResult(
        success: false,
        text: jsonEncode({
          'status': invalid ? 'invalid_request' : 'rejected',
          'error_code': code,
        }),
      );
}

Set<WhiteboardWriteCapability> _capabilitiesFromExplicitRequest(String text) {
  final normalized = text.trim().toLowerCase();
  if (normalized.isEmpty ||
      !(normalized.contains('白板') || normalized.contains('卡片'))) {
    return const {};
  }
  if (_containsNegatedWhiteboardWrite(normalized)) return const {};
  final result = <WhiteboardWriteCapability>{};
  if (RegExp(r'新建|创建|添加.*卡片|加一张').hasMatch(normalized)) {
    result.add(WhiteboardWriteCapability.createCard);
  }
  if (RegExp(r'编辑|修改|改写|正文|内容').hasMatch(normalized)) {
    result.add(WhiteboardWriteCapability.editCardBody);
  }
  if (normalized.contains('标签')) {
    result.add(WhiteboardWriteCapability.setCardLabels);
  }
  if (RegExp(r'移动|挪动|位置|移到|放到').hasMatch(normalized)) {
    result.add(WhiteboardWriteCapability.movePlacement);
  }
  if (RegExp(r'缩放|放大|缩小|尺寸|大小').hasMatch(normalized)) {
    result.add(WhiteboardWriteCapability.resizePlacement);
  }
  if (RegExp(r'从白板移除|移出白板|移除摆放|拿出白板').hasMatch(normalized)) {
    result.add(WhiteboardWriteCapability.removePlacement);
  }
  return Set.unmodifiable(result);
}

bool _containsNegatedWhiteboardWrite(String text) => RegExp(
      r'(?:不要|别|不许|禁止|请勿|无需|不用|不能|不可以|不准)'
      r'.{0,24}'
      r'(?:新建|创建|添加|编辑|修改|改写|正文|内容|标签|移动|挪动|'
      r'移到|放到|缩放|放大|缩小|尺寸|大小|移除|移出|拿出)',
    ).hasMatch(text);

WhiteboardWriteCapability? _capabilityForKind(Object? kind) => switch (kind) {
      'create_card' => WhiteboardWriteCapability.createCard,
      'edit_card_body' => WhiteboardWriteCapability.editCardBody,
      'set_card_labels' => WhiteboardWriteCapability.setCardLabels,
      'move_placement' => WhiteboardWriteCapability.movePlacement,
      'resize_placement' => WhiteboardWriteCapability.resizePlacement,
      'remove_placement' => WhiteboardWriteCapability.removePlacement,
      _ => null,
    };

bool _onlyKeys(Map<String, dynamic> value, Set<String> allowed) =>
    value.keys.every(allowed.contains) && value['kind'] is String;

String? _requiredString(Object? value) =>
    value is String && value.trim().isNotEmpty ? value : null;

String? _optionalString(Object? value) {
  if (value == null) return null;
  if (value is! String) throw const FormatException('Expected string');
  return value;
}

List<String>? _stringList(Object? value) {
  if (value == null) return const [];
  if (value is! List || value.any((item) => item is! String)) return null;
  return List<String>.unmodifiable(value.cast<String>());
}

double _requiredNumber(Object? value) {
  if (value is! num || !value.isFinite) {
    throw const FormatException('Expected finite number');
  }
  return value.toDouble();
}

double _number(Object? value, double fallback) =>
    value == null ? fallback : _requiredNumber(value);

Object? _canonicalJson(Object? value) {
  if (value is Map) {
    final keys = value.keys.map((key) => key.toString()).toList()..sort();
    return {for (final key in keys) key: _canonicalJson(value[key])};
  }
  if (value is List) return value.map(_canonicalJson).toList();
  return value;
}
