import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:memex/data/services/custom_agent_config_service.dart';
import 'package:memex/data/services/file_system_service.dart';
import 'package:memex/utils/logger.dart';

class WereadSyncService {
  static final _logger = getLogger('WereadSync');

  static const _gatewayUrl = 'https://i.weread.qq.com/api/agent/gateway';

  /// Fetch WeRead reading data and write to local files so the insight agent
  /// can discover and analyze it alongside other workspace data.
  ///
  /// Returns true if data was synced successfully, false if WeRead is not
  /// configured or the sync failed.  Never throws — failures are logged and
  /// swallowed so insight generation is never blocked.
  static Future<bool> syncIfConfigured(String userId) async {
    final configs = await CustomAgentConfigService.instance.loadAll(userId);
    final wereadCfg = configs.where((c) => c.agentName == 'weread').firstOrNull;
    if (wereadCfg == null) {
      _logger.info('WeRead not configured, skipping sync');
      return false;
    }

    final sp = wereadCfg.systemPrompt ?? '';
    final keyMatch = RegExp(r'wrk-[A-Za-z0-9]+').firstMatch(sp);
    if (keyMatch == null) {
      _logger.warning('WeRead API key not found in config');
      return false;
    }
    final apiKey = keyMatch.group(0)!;

    final fileService = FileSystemService.instance;
    final dirPath =
        '${fileService.getUserSettingsPath(userId)}/external_data/weread';
    final dir = Directory(dirPath);
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    final dio = Dio();
    dio.options.connectTimeout = const Duration(seconds: 30);
    dio.options.receiveTimeout = const Duration(seconds: 30);

    try {
      final response = await dio.post(
        _gatewayUrl,
        data: {'api_name': '/shelf/sync', 'skill_version': '1.0.3'},
        options: Options(
          headers: {
            'Authorization': 'Bearer $apiKey',
            'Content-Type': 'application/json',
          },
        ),
      );

      if (response.statusCode != 200) {
        _logger.warning(
            'WeRead shelf sync returned ${response.statusCode}');
        return false;
      }

      final shelfData = response.data;
      if (shelfData == null) {
        _logger.warning('WeRead shelf sync returned null data');
        return false;
      }

      // Write raw shelf data for reference
      File('$dirPath/shelf_data.json')
          .writeAsStringSync(const JsonEncoder.withIndent('  ').convert(shelfData));

      // Build and write human-readable summary for the insight agent
      final summary = _buildSummary(shelfData);
      File('$dirPath/reading_summary.md').writeAsStringSync(summary);

      _logger.info('WeRead data synced to $dirPath');
      return true;
    } on DioException catch (e) {
      _logger.warning('WeRead sync network error: ${e.message}');
      return false;
    } catch (e) {
      _logger.warning('WeRead sync unexpected error: $e');
      return false;
    }
  }

  /// Build a markdown summary of WeRead reading data for the insight agent.
  ///
  /// The output is designed to be read by the KnowledgeInsightAgent via its
  /// existing file tools (Read, Grep).  It surfaces reading patterns, current
  /// books, and statistics that the agent can correlate with other life data.
  static String _buildSummary(dynamic shelfData) {
    final buf = StringBuffer();
    buf.writeln('# WeRead Reading Data');
    buf.writeln();
    buf.writeln(
        'This file is auto-generated by WeReadSyncService before each insight refresh.');
    buf.writeln(
        'It summarizes the user\'s reading activity from WeRead (微信读书).');
    buf.writeln();

    // Try to extract book list from various possible structures
    List<dynamic>? books;

    if (shelfData is Map) {
      // Common patterns: {"books": [...]}, {"data": {"books": [...]}}, etc.
      books = _extractList(shelfData, ['books', 'bookList', 'items', 'data']);
      if (books == null && shelfData.containsKey('data')) {
        final inner = shelfData['data'];
        if (inner is Map) {
          books = _extractList(inner, ['books', 'bookList', 'items']);
        }
      }
    }

    if (books == null || books.isEmpty) {
      buf.writeln('_No books found in shelf data. Raw data is in shelf_data.json._');
      return buf.toString();
    }

    // Statistics
    int totalBooks = books.length;
    int currentlyReading = 0;
    int finished = 0;
    final reading = <Map<String, dynamic>>[];
    final recent = <Map<String, dynamic>>[];

    for (final b in books) {
      if (b is! Map) continue;
      final progress = _numVal(b, ['progress', 'readingProgress', 'percent']) ?? 0;
      final status = _strVal(b, ['readingStatus', 'status', 'shelf']);

      if (progress > 0 && progress < 1.0) {
        currentlyReading++;
        reading.add(b as Map<String, dynamic>);
      } else if (progress >= 1.0 || status == 'finished' || status == 'read') {
        finished++;
      }

      // Recently updated books (last 30 days)
      final updateTime = _numVal(b, ['updateTime', 'update_time', 'lastReadTime']);
      if (updateTime != null && updateTime > 0) {
        final nowMs = DateTime.now().millisecondsSinceEpoch;
        // updateTime might be in seconds or milliseconds
        final updateMs = updateTime > 1e12 ? updateTime : updateTime * 1000;
        if (nowMs - updateMs < 30 * 24 * 3600 * 1000) {
          recent.add(b as Map<String, dynamic>);
        }
      }
    }

    buf.writeln('## Reading Statistics');
    buf.writeln();
    buf.writeln('- **Total books on shelf**: $totalBooks');
    buf.writeln('- **Currently reading**: $currentlyReading');
    buf.writeln('- **Finished**: $finished');
    buf.writeln('- **Recently active (30 days)**: ${recent.length}');
    buf.writeln();

    // Currently reading
    if (reading.isNotEmpty) {
      buf.writeln('## Currently Reading');
      buf.writeln();
      for (final b in reading) {
        _writeBookEntry(buf, b);
      }
    }

    // Recently finished
    final recentlyFinished = recent
        .where((b) =>
            (_numVal(b, ['progress', 'readingProgress']) ?? 0) >= 1.0)
        .toList();
    if (recentlyFinished.isNotEmpty) {
      buf.writeln('## Recently Finished');
      buf.writeln();
      for (final b in recentlyFinished) {
        _writeBookEntry(buf, b);
      }
    }

    // Recently active but not currently reading
    final recentOther = recent
        .where((b) =>
            (_numVal(b, ['progress', 'readingProgress']) ?? 0) > 0 &&
            (_numVal(b, ['progress', 'readingProgress']) ?? 0) < 1.0 &&
            !reading.contains(b))
        .toList();
    if (recentOther.isNotEmpty) {
      buf.writeln('## Recently Active (Not Currently Reading)');
      buf.writeln();
      for (final b in recentOther) {
        _writeBookEntry(buf, b);
      }
    }

    // All books summary
    if (books.length > 10) {
      buf.writeln('## All Books (Condensed)');
      buf.writeln();
      for (final b in books) {
        if (b is! Map) continue;
        final title = _strVal(b, ['title', 'bookName', 'name']) ?? 'Unknown';
        final author = _strVal(b, ['author', 'authors']);
        final progress = _numVal(b, ['progress', 'readingProgress']);
        final pct = progress != null ? '${(progress * 100).toStringAsFixed(0)}%' : '?%';
        buf.write('- **$title**');
        if (author != null) buf.write(' — $author');
        buf.writeln(' ($pct)');
      }
    }

    return buf.toString();
  }

  static void _writeBookEntry(StringBuffer buf, Map<String, dynamic> b) {
    final title = _strVal(b, ['title', 'bookName', 'name']) ?? 'Unknown';
    final author = _strVal(b, ['author', 'authors']);
    final cover = _strVal(b, ['cover', 'coverUrl', 'image']);
    final progress = _numVal(b, ['progress', 'readingProgress']);
    final chapterTitle = _strVal(b, ['chapterTitle', 'chapter_title', 'currentChapter']);
    final updateTime = _numVal(b, ['updateTime', 'update_time', 'lastReadTime']);

    buf.writeln('### $title');
    buf.writeln();
    if (author != null) buf.writeln('- **Author**: $author');
    if (cover != null) buf.writeln('- **Cover**: $cover');
    if (progress != null) {
      buf.writeln('- **Progress**: ${(progress * 100).toStringAsFixed(1)}%');
    }
    if (chapterTitle != null) buf.writeln('- **Current Chapter**: $chapterTitle');
    if (updateTime != null && updateTime > 0) {
      final dt = DateTime.fromMillisecondsSinceEpoch(
        (updateTime > 1e12 ? updateTime : updateTime * 1000).toInt(),
      );
      buf.writeln('- **Last Read**: ${dt.toIso8601String()}');
    }

    // Notes / highlights if present
    final notes = b['notes'];
    if (notes is List && notes.isNotEmpty) {
      buf.writeln('- **Notes**: ${notes.length} highlights');
      for (final n in notes.take(5)) {
        if (n is Map) {
          final text = _strVal(n, ['text', 'content', 'markText']);
          if (text != null) buf.writeln('  - "$text"');
        }
      }
    }

    buf.writeln();
  }

  // -- Helpers --

  static List<dynamic>? _extractList(Map data, List<String> keys) {
    for (final key in keys) {
      final val = data[key];
      if (val is List) return val;
    }
    return null;
  }

  static String? _strVal(Map data, List<String> keys) {
    for (final key in keys) {
      final val = data[key];
      if (val is String && val.isNotEmpty) return val;
    }
    return null;
  }

  static double? _numVal(Map data, List<String> keys) {
    for (final key in keys) {
      final val = data[key];
      if (val is num) return val.toDouble();
    }
    return null;
  }
}
