import { assertDomainSchemaReady } from './domain_schema.mjs';
import { createHmac, createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';

export const DOMAIN_POLICY = Object.freeze({version:'domain-policy-v1',intentTtl:60*86400000,reminderAge:7*86400000,futureSkew:300000,outboxItems:5000,outboxBytes:50000000,maxOpBytes:262144,maxRecordBytes:262144,pageLimit:100,maxPageLimit:500,maxResponseBytes:2097152,feedRetention:60*86400000,activeConsumer:90*86400000,snapshotTtl:900000,bodyQuota:268435456,snapshotQuota:4,restoreWindow:30*86400000,terminalRetention:30*86400000,runtimeConsumerEntries:1024,runtimeDomainEntries:8192,runtimeBytes:8388608});
const levels={agent_inferred:1,import:2,user_direct:3,user_via_agent:3};
const actions={create:'create',patch:'patch',status:'status',ack_capture:'ack',delete:'delete',restore:'restore',merge:'merge',purge:'purge'};
const common=['domain_protocol_version','core_instance_id','op_id','schema_version','kind','id','base_revision','created_at','expires_at','actor','authorization_ref','epoch','fencing_token'];
const specific={create:['data','provenance'],patch:['patch','confirm_fields'],status:['patch'],ack_capture:['processor','disposition'],delete:['permanent'],restore:[],purge:[],merge:['target_id','target_base_revision','target_data','reference_updates']};
export class DomainError extends Error { constructor(code,status=400,details={}){super(code);this.code=code;this.status=status;this.details=details;} }
const fail=(code,status=400,details={})=>{throw new DomainError(code,status,details);};
const plain=x=>x!==null&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;
export const canonicalJSON=x=>JSON.stringify(sort(x));
function sort(x){if(Array.isArray(x))return x.map(sort);if(plain(x))return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])]));return x;}
const bytes=x=>Buffer.byteLength(JSON.stringify(x),'utf8');
const clone=x=>structuredClone(x);
function frozenCopy(value){const freeze=x=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};return freeze(clone(value));}
const eq=(a,b)=>canonicalJSON(a)===canonicalJSON(b);
const json=x=>JSON.parse(x);
const hash=x=>createHash('sha256').update(typeof x==='string'?x:canonicalJSON(x)).digest('hex');
const identifier=x=>typeof x==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_.:-]{0,199}$/.test(x);
const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
function strict(o,keys){if(!plain(o)||Object.keys(o).some(k=>!keys.includes(k)))fail('invalid_request');}
function time(x){if(typeof x!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(x)||!Number.isFinite(Date.parse(x))||new Date(x).toISOString()!==x)fail('invalid_request');return Date.parse(x);}
function response(fn){try{return fn();}catch(e){if(e instanceof DomainError)return {status:e.status,body:{error:{code:e.code,retryable:[429,503].includes(e.status)},...e.details}};throw e;}}

/** Local administrative methods require a trusted host. No constructor migration or default domain. */
export class DomainStore {
 constructor(db,{nodeId,cursorSecret,clock=()=>Date.now(),verifyAuthorization=null,dedupHooks={},domainHooks={},verifyLegacyAdoption=null,testOnlyFault=null}={}){
  this.db=db;this.nodeId=nodeId;this.secret=cursorSecret;this.clock=clock;this.verifyAuthorization=verifyAuthorization;this.dedupHooks=dedupHooks;this.domainHooks=domainHooks;this.verifyLegacyAdoption=verifyLegacyAdoption;this.fault=testOnlyFault;
  if(!nodeId||!cursorSecret)throw new DomainError('schema_not_ready',503);
  this.ready();
 }
 now(){const n=this.clock();return n instanceof Date?n.getTime():typeof n==='string'?Date.parse(n):n;}
 iso(n=this.now()){return new Date(n).toISOString();}
 ready(){
  if(this.inHostHook)fail('schema_not_ready',503);
  if(this.integrityFailure)fail('core_not_ready',503);
  try{assertDomainSchemaReady(this.db);const node=this.db.prepare("SELECT value FROM core_metadata WHERE key='node_id'").get()?.value??null;const secret=this.db.prepare("SELECT value FROM core_metadata WHERE key='cursor_secret'").get()?.value??null;const hasActivity=!!this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='activity_metadata'").get();const role=hasActivity?(this.db.prepare("SELECT value FROM activity_metadata WHERE key='database_role'").get()?.value??null):null;
   if(hasActivity&&role!=='live')fail('backup_activation_unsupported',503);if(!node||!secret)fail('core_not_ready',503);if(node!==this.nodeId||secret!==this.secret)fail('core_identity_mismatch',503);const binding={node,secret,hasActivity,role};if(this.integrityBinding&&!eq(this.integrityBinding,binding))fail('core_not_ready',503);this.integrityBinding??=binding;
  }catch(e){this.integrityFailure=true;if(e instanceof DomainError)throw e;fail('schema_not_ready',503);}
 }
 tx(fn){this.db.exec('BEGIN IMMEDIATE');let committed=false;try{const out=fn();this.fault?.('before_commit');this.db.exec('COMMIT');committed=true;this.fault?.('after_commit');return out;}catch(e){if(!committed)this.db.exec('ROLLBACK');throw e;}}
 mac(x){return createHmac('sha256',this.secret).update(canonicalJSON(x)).digest('hex');}
 recoveryMetadata(ns,principal,domain,opId,digest,result,metadata){
  const recovery_rows=(metadata.targets??[]).map(target=>{const row=this.db.prepare('SELECT * FROM domain_records WHERE namespace=? AND domain=? AND id=?').get(ns,domain,target.id);if(!row||row.revision!==target.revision)fail('core_not_ready',503);return {id:row.id,revision:row.revision,row_auth:this.mac({format:'domain-record-result-v1',...row})};});
  const unsigned={...metadata,recovery_rows};
  return {...unsigned,recovery_auth:this.mac({format:'domain-operation-recovery-v1',namespace:ns,principal_id:principal,domain,op_id:opId,request_digest:digest,result,metadata:unsigned})};
 }

 seal(x){return Buffer.from(canonicalJSON(x)).toString('base64url')+'.'+this.mac(x);}
 unseal(s){try{if(typeof s!=='string'||s.length>8192)fail('resync_required',409);const [b,m,...extra]=s.split('.');const x=json(Buffer.from(b,'base64url').toString());const expected=this.mac(x);if(extra.length||typeof m!=='string'||m.length!==expected.length||!timingSafeEqual(Buffer.from(m),Buffer.from(expected)))fail('resync_required',409);return x;}catch{fail('resync_required',409);}}
 registerDomain(domain,schema,{mode='off',policyVersion=DOMAIN_POLICY.version,requiredHooksVersion=null,serverDerivedFields=[]}={}){
  this.ready();if(!identifier(domain)||!plain(schema)||!Number.isSafeInteger(schema.version)||schema.version<1||!plain(schema.fields))fail('invalid_request');
  strict(schema,['version','fields','groups','statusFields','referenceFields','processors','dedupFields','immediateDeleteSources']);
  const groups=new Set();for(const [f,s] of Object.entries(schema.fields)){if(!identifier(f))fail('invalid_request');strict(s,['type','nullable','required','enum']);if(!['string','number','integer','boolean','object','array'].includes(s.type))fail('invalid_request');}
  for(const fs of Object.values(schema.groups??{})){if(!Array.isArray(fs)||fs.length<2)fail('invalid_request');for(const f of fs){if(!schema.fields[f]||groups.has(f))fail('invalid_request');groups.add(f);}}
  for(const f of [...schema.statusFields??[],...schema.referenceFields??[],...schema.dedupFields??[],...Object.values(schema.processors??{}).flat()])if(!schema.fields[f])fail('invalid_request');
  if(requiredHooksVersion!==null&&!identifier(requiredHooksVersion))fail('invalid_request');
  if(!Array.isArray(serverDerivedFields)||new Set(serverDerivedFields).size!==serverDerivedFields.length||serverDerivedFields.some(f=>!schema.fields[f])||(serverDerivedFields.length&&!requiredHooksVersion))fail('invalid_request');
  if(!['off','shadow','frozen','authoritative'].includes(mode))fail('invalid_request');
  if(this.db.prepare('SELECT 1 FROM domain_registry WHERE domain=?').get(domain))fail('domain_already_registered',409);
  this.db.prepare('INSERT INTO domain_registry(domain,mode,frozen_from,schema_json,policy_version) VALUES(?,?,?,?,?)').run(domain,mode,null,canonicalJSON({definition:schema,requiredHooksVersion,serverDerivedFields,runtime:{watermarks:{},highwaters:{},issued:{},acks:{}}}),policyVersion);
 }
 setMode(domain,mode){this.ready();const d=this.domain(domain);if(!['off','shadow','frozen','authoritative'].includes(mode))fail('invalid_request');if(d.mode==='shadow'&&mode==='authoritative')fail('freeze_required',409);this.db.prepare('UPDATE domain_registry SET mode=?,frozen_from=? WHERE domain=?').run(mode,mode==='frozen'?(d.mode==='frozen'?d.frozen_from:d.mode):null,domain);this.db.prepare('DELETE FROM domain_snapshots WHERE domain=?').run(domain);}
 domain(domain){const r=this.db.prepare('SELECT * FROM domain_registry WHERE domain=?').get(domain);if(!r)fail('not_found',404);const j=json(r.schema_json);return {...r,schema:j.definition,runtime:j.runtime,requiredHooksVersion:j.requiredHooksVersion??null,serverDerivedFields:j.serverDerivedFields??[]};}
 // Host hooks are synchronous policy code. They receive immutable copies and no DB/write capability.
 hooks(d){
  if(!d.requiredHooksVersion)return null;
  const h=this.domainHooks[d.domain];
  if(!h||h.version!==d.requiredHooksVersion||typeof h.authorizeOperation!=='function'||typeof h.validateTransition!=='function'||(d.serverDerivedFields.length&&typeof h.deriveFields!=='function'))fail('schema_not_ready',503);
  return h;
 }
 callHost(fn,context){
  if(typeof fn!=='function'||this.inHostHook)fail('schema_not_ready',503);
  this.inHostHook=true;
  try{const out=fn(context);if(out&&typeof out.then==='function'){Promise.resolve(out).catch(()=>{});fail('schema_not_ready',503);}return clone(out);}
  catch{fail('schema_not_ready',503);}finally{this.inHostHook=false;}
 }
 hookContext(p,d,ns,raw,{current=null,next=null,phase='submit',operation=null,operationOrigin='public_intent',adoption=null}={}){
  const immutable=frozenCopy({principal:p,domain:d.domain,kind:raw?.kind??operation?.kind,request:raw??null,current,next,phase,operation,operationOrigin,adoption,now:this.iso()});
  return Object.freeze({...immutable,lookupRecord:(domain,id)=>{
   if(!identifier(domain)||!identifier(id))return null;
   const target=this.domain(domain);this.hooks(target);const visible=target.mode==='frozen'?target.frozen_from:target.mode;
   if(visible==='off'||(visible==='shadow'?'shadow':'production')!==ns||!p.scopes.includes(`${domain}:${ns==='shadow'?'shadow_read':'read'}`))return null;
   const r=this.businessView?.namespace===ns&&this.businessView.domain===domain&&this.businessView.records.has(id)?this.businessView.records.get(id):this.load(ns,domain,id);return r&&this.allowed(p,r)?frozenCopy(this.publicRecord(r)):null;
  },matchesOperationValue:(field,value)=>!!operation?.field_value_hmacs?.[field]&&operation.field_value_hmacs[field]===this.mac(value)});
 }
 authorizeBusiness(p,d,ns,raw,extra={}){
  const h=this.hooks(d);if(!h)return;
  const result=this.callHost(h.authorizeOperation,this.hookContext(p,d,ns,raw,extra));
  if(result===false)fail('scope_forbidden',403);if(result!==true)fail('schema_not_ready',503);
 }
 derivedPatch(p,d,ns,raw,r){
  const h=this.hooks(d);if(raw.kind!=='status'||levels[raw.actor]!==3||!d.serverDerivedFields.length)return {};
  const result=this.callHost(h.deriveFields,this.hookContext(p,d,ns,raw,{current:r,next:{...r,data:{...r.data,...raw.patch}}}));
  if(!plain(result)||Object.keys(result).some(f=>!d.serverDerivedFields.includes(f)||Object.hasOwn(raw.patch,f)))fail('schema_not_ready',503);
  try{this.validateData(d.schema,{...raw.patch,...result});}catch{fail('schema_not_ready',503);}
  this.pendingDerivedFields=Object.keys(result);return result;
 }
 referenceList(value){
  if(!Array.isArray(value)||bytes(value)>DOMAIN_POLICY.maxOpBytes)fail('schema_not_ready',503);
  const unique=new Map();for(const ref of value){if(!plain(ref)||Object.keys(ref).some(k=>!['domain','id'].includes(k))||!identifier(ref.domain)||!identifier(ref.id))fail('schema_not_ready',503);unique.set(canonicalJSON([ref.domain,ref.id]),{domain:ref.domain,id:ref.id});}
  return [...unique.values()].sort((a,b)=>{const left=canonicalJSON(a),right=canonicalJSON(b);return left<right?-1:left>right?1:0;});
 }
 validateBusiness(p,d,ns,raw,current,next,extra={}){
  const h=this.hooks(d);if(!h)return;
  const result=this.callHost(h.validateTransition,this.hookContext(p,d,ns,raw,{current,next,...extra}));
  if(result===true)return;if(result===false)fail('invalid_request');
  if(!plain(result)||Object.keys(result).some(k=>!['valid','code','derived_refs'].includes(k))||typeof result.valid!=='boolean')fail('schema_not_ready',503);
  if(!result.valid){if(Object.hasOwn(result,'derived_refs')||!['invalid_request','stale_base','reference_conflict','user_conflict'].includes(result.code))fail('schema_not_ready',503);fail(result.code,result.code==='invalid_request'?400:409);}
  if(Object.hasOwn(result,'code'))fail('schema_not_ready',503);
  if(Object.hasOwn(result,'derived_refs')){
   if(raw.kind!=='ack_capture'&&extra.operationOrigin!=='local_adoption')fail('schema_not_ready',503);
   this.pendingDerivedRefs=this.referenceList(result.derived_refs);
   const prior=this.historicalDerivedRefs(ns,d.domain,raw.id);if(bytes([...prior,...this.pendingDerivedRefs])>DOMAIN_POLICY.maxOpBytes)fail('domain_capacity_exceeded',429);
  }
 }
 historicalDerivedRefs(ns,domain,id){
  const refs=[];for(const row of this.db.prepare('SELECT op_meta_json FROM domain_ops WHERE namespace=? AND domain=?').all(ns,domain)){const m=json(row.op_meta_json);if(m.id===id&&['accepted','shadow_staged'].includes(m.outcome))refs.push(...m.derived_refs??[]);}
  return this.referenceList(refs);
 }
 replayBusiness(p,d,ns,meta){
  this.hooks(d);
  if(meta.operation_origin==='local_adoption'&&!p.import_sources?.includes(meta.adoption?.sourceKind))fail('actor_not_authorized',403);
  if((meta.derived_fields?.length??0)>0&&(meta.kind!=='status'||levels[meta.actor]!==3||meta.derived_hooks_version!==d.requiredHooksVersion||meta.derived_fields.some(f=>!d.serverDerivedFields.includes(f))))fail('scope_forbidden',403);
  this.authorizeBusiness(p,d,ns,null,{phase:'lookup',operation:meta,operationOrigin:meta.operation_origin??'public_intent',adoption:meta.adoption??null});
 }
 saveRuntime(d){
  const completed=Object.values(d.runtime.completed_snapshots??{});const keys=new Set([...Object.keys(d.runtime.issued),...completed.map(entry=>entry.key)]);let entries=Object.keys(d.runtime.acks).length;
  for(const key of keys){const issued=(d.runtime.issued[key]??[]).length,done=completed.filter(entry=>entry.key===key).length;if(issued>DOMAIN_POLICY.runtimeConsumerEntries||done>DOMAIN_POLICY.runtimeConsumerEntries)fail('domain_capacity_exceeded',429);entries+=issued+done;}
  const serialized=canonicalJSON({definition:d.schema,requiredHooksVersion:d.requiredHooksVersion,serverDerivedFields:d.serverDerivedFields,runtime:d.runtime});if(entries>DOMAIN_POLICY.runtimeDomainEntries||Buffer.byteLength(serialized)>DOMAIN_POLICY.runtimeBytes)fail('domain_capacity_exceeded',429);
  const prior=Number(this.db.prepare('SELECT length(CAST(schema_json AS BLOB)) n FROM domain_registry WHERE domain=?').get(d.domain)?.n??0);const growth=Math.max(0,Buffer.byteLength(serialized)-prior);for(const ns of ['production','shadow'])this.checkCapacity(ns,d.domain,growth);this.db.prepare('UPDATE domain_registry SET schema_json=? WHERE domain=?').run(serialized,d.domain);
 }
 pruneRuntime(d){const cutoff=this.now()-DOMAIN_POLICY.activeConsumer;for(const [key,issued] of Object.entries(d.runtime.issued)){const kept=issued.filter(entry=>time(entry.at)>=cutoff);if(kept.length)d.runtime.issued[key]=kept;else delete d.runtime.issued[key];}for(const [id,entry] of Object.entries(d.runtime.completed_snapshots??{}))if(time(entry.at)<cutoff)delete d.runtime.completed_snapshots[id];for(const [key,entry] of Object.entries(d.runtime.acks))if(time(entry.at)<cutoff)delete d.runtime.acks[key];}

 configurePrincipal(config,{token=randomBytes(32).toString('base64url')}={}){this.ready();
  strict(config,['principal_id','device_id','installation_id','scopes','actors','trusted_interactive','origins','record_ids','fields','processor','import_sources','expires_at','origin_device_only']);
  for(const key of ['principal_id','device_id','installation_id'])if(!identifier(config[key]))fail('invalid_request');
  if(!Array.isArray(config.scopes)||!Array.isArray(config.actors)||config.actors.some(a=>!levels[a])||config.scopes.some(s=>typeof s!=='string'||!s.includes(':')))fail('invalid_request');
  if(config.expires_at)time(config.expires_at);if(typeof token!=='string'||token.length<24)fail('invalid_request');
  return this.tx(()=>{const prior=this.db.prepare('SELECT generation FROM domain_principals WHERE principal_id=?').get(config.principal_id);const generation=(prior?.generation??0)+1;this.db.prepare('INSERT INTO domain_principals(principal_id,token_hash,generation,status,expires_at,device_id,installation_id,config_json) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(principal_id) DO UPDATE SET token_hash=excluded.token_hash,generation=excluded.generation,status=excluded.status,expires_at=excluded.expires_at,device_id=excluded.device_id,installation_id=excluded.installation_id,config_json=excluded.config_json').run(config.principal_id,hash(token),generation,'active',config.expires_at??null,config.device_id,config.installation_id,canonicalJSON(config));this.db.prepare('DELETE FROM domain_snapshots WHERE principal_id=?').run(config.principal_id);return {principal_id:config.principal_id,token,generation};});
 }
 rotatePrincipal(principalId,options={}){this.ready();const row=this.db.prepare('SELECT config_json FROM domain_principals WHERE principal_id=?').get(principalId);if(!row)fail('not_found',404);return this.configurePrincipal(json(row.config_json),options);}
 revokePrincipal(principalId){this.ready();this.tx(()=>{this.db.prepare("UPDATE domain_principals SET status='revoked',generation=generation+1 WHERE principal_id=?").run(principalId);this.db.prepare('DELETE FROM domain_snapshots WHERE principal_id=?').run(principalId);});}
 authenticate(token){this.ready();if(typeof token!=='string')return null;const row=this.db.prepare("SELECT * FROM domain_principals WHERE token_hash=? AND status='active'").get(hash(token));if(!row||row.expires_at&&time(row.expires_at)<=this.now())return null;return {principal_id:row.principal_id,generation:row.generation,device_id:row.device_id,installation_id:row.installation_id};}
 auth(p){if(!p)fail('unauthenticated',401);const row=this.db.prepare('SELECT * FROM domain_principals WHERE principal_id=?').get(p.principal_id);if(!row||row.status!=='active'||row.generation!==p.generation||row.device_id!==p.device_id||row.installation_id!==p.installation_id)fail('unauthenticated',401);if(row.expires_at&&time(row.expires_at)<=this.now())fail('credential_expired',401);return {...json(row.config_json),generation:row.generation};}
 scope(p,d,a,ns){const needed=a==='adopt'?'adopt':ns==='shadow'?(a==='read'?'shadow_read':'shadow_write'):a;if(!p.scopes.includes(`${d.domain}:${needed}`))fail('scope_forbidden',403);}
 context(principal,domain,core,{read=false,operation=false}={}){this.ready();const p=this.auth(principal);if(core!==this.nodeId)fail('core_identity_mismatch',409);const d=this.domain(domain);this.hooks(d);const visible=d.mode==='frozen'?d.frozen_from:d.mode;const ns=visible==='shadow'?'shadow':'production';if(!operation&&d.mode==='off')fail('domain_off',503);if(read)this.scope(p,d,'read',ns);return {p,d,ns};}
 allowed(p,r){return (!p.record_ids||p.record_ids.includes(r.id))&&(!p.origins||p.origins.includes(r.origin?.principal_id))&&(!p.origin_device_only||r.origin?.device_id===p.device_id);}
 fieldAccess(p,d,fields){const allowed=p.fields?.[d.domain];if(allowed&&fields.some(f=>!allowed.includes(f)))fail('scope_forbidden',403);}
 actor(p,raw,targets,domain){if(!p.actors.includes(raw.actor))fail('actor_not_authorized',403);if(levels[raw.actor]===3){if(raw.actor==='user_direct'&&!p.trusted_interactive)fail('actor_not_authorized',403);if(!raw.authorization_ref||typeof raw.authorization_ref!=='string'||!this.verifyAuthorization||this.verifyAuthorization({principal:p,request:raw,targets,domain,authorizationRef:raw.authorization_ref})!==true)fail('actor_not_authorized',403);}if(raw.actor==='import'&&raw.kind==='create'&&(!p.import_sources||!p.import_sources.includes(raw.provenance?.source)))fail('actor_not_authorized',403);}
 load(ns,domain,id){const row=this.db.prepare('SELECT envelope_json,body_json FROM domain_records WHERE namespace=? AND domain=? AND id=?').get(ns,domain,id);if(!row)return null;return {...json(row.envelope_json),...(row.body_json?json(row.body_json):{})};}
 visible(p,r){if(!r||!this.allowed(p,r))fail('not_found',404);return r;}
 tomb(r){return Object.fromEntries(['domain','id','revision','deleted_at','merged_into','body_state','policy_version','core_instance_id'].map(k=>[k,r[k]]));}
 publicRecord(r){return r.deleted_at?this.tomb(r):clone(r);}
 canRead(p,d,ns,r){return p.scopes.includes(`${d.domain}:${ns==='shadow'?'shadow_read':'read'}`)&&this.allowed(p,r);}
 groups(schema,fields){const grouped=new Set();const out=[];for(const [name,fs] of Object.entries(schema.groups??{})){fs.forEach(f=>grouped.add(f));if(fs.some(f=>fields.includes(f)))out.push([name,fs]);}for(const f of fields)if(!grouped.has(f))out.push([f,[f]]);return out;}
 validateData(schema,data,{complete=false}={}){if(!plain(data))fail('invalid_request');for(const [f,v] of Object.entries(data)){const s=schema.fields[f];if(!s)fail('invalid_request');if(v===null){if(!s.nullable)fail('invalid_request');continue;}const valid=s.type==='array'?Array.isArray(v):s.type==='object'?plain(v):s.type==='integer'?Number.isSafeInteger(v):typeof v===s.type;if(!valid||(typeof v==='number'&&!Number.isFinite(v))||(s.enum&&!s.enum.some(x=>eq(x,v))))fail('invalid_request');}if(complete&&Object.entries(schema.fields).some(([f,s])=>s.required&&!Object.hasOwn(data,f)))fail('invalid_request');for(const [,fs] of this.groups(schema,Object.keys(data)))if(fs.some(f=>!Object.hasOwn(data,f)))fail('incomplete_field_group');}
 validate(raw,d){if(Array.isArray(raw))fail('batch_not_supported',413);if(bytes(raw)>DOMAIN_POLICY.maxOpBytes)fail('payload_too_large',413);if(!plain(raw)||!specific[raw.kind])fail('invalid_request');strict(raw,[...common,...specific[raw.kind]]);if(raw.domain_protocol_version!==1||raw.schema_version!==d.schema.version||!uuid(raw.op_id)||raw.op_id===raw.id||!identifier(raw.id)||!Number.isSafeInteger(raw.base_revision)||raw.base_revision<0||!levels[raw.actor])fail('invalid_request');if(raw.epoch!=null||raw.fencing_token!=null)fail('unsupported_authority_feature');const created=time(raw.created_at),expires=time(raw.expires_at);if(created>this.now()+DOMAIN_POLICY.futureSkew||expires<=created||expires-created>DOMAIN_POLICY.intentTtl)fail('invalid_request');
  if(raw.kind==='create'){if(!uuid(raw.id))fail('invalid_request');this.validateData(d.schema,raw.data,{complete:true});strict(raw.provenance,['source','source_refs','import_batch_id']);if(typeof raw.provenance.source!=='string'||!Array.isArray(raw.provenance.source_refs)||!Object.hasOwn(raw.provenance,'import_batch_id'))fail('invalid_request');}
  if(['patch','status'].includes(raw.kind)){this.validateData(d.schema,raw.patch);if(!Object.keys(raw.patch).length)fail('invalid_request');}
  if(raw.kind==='patch'&&raw.confirm_fields!==undefined){if(!Array.isArray(raw.confirm_fields)||levels[raw.actor]!==3||raw.confirm_fields.some(f=>!Object.hasOwn(raw.patch,f)))fail('invalid_request');}
  if(raw.kind==='delete'&&raw.permanent!==undefined&&typeof raw.permanent!=='boolean')fail('invalid_request');
  if(raw.kind==='merge'){if(!identifier(raw.target_id)||raw.target_id===raw.id||!Number.isSafeInteger(raw.target_base_revision)||!Array.isArray(raw.reference_updates))fail('invalid_request');this.validateData(d.schema,raw.target_data,{complete:true});const ids=new Set();for(const u of raw.reference_updates){strict(u,['id','base_revision','patch']);if(!identifier(u.id)||ids.has(u.id)||[raw.id,raw.target_id].includes(u.id)||!Number.isSafeInteger(u.base_revision))fail('invalid_request');ids.add(u.id);this.validateData(d.schema,u.patch);}}
 }
 patchFor(raw,d,p){if(raw.kind==='ack_capture'){if(p.processor!==raw.processor||!d.schema.processors?.[raw.processor]||!plain(raw.disposition))fail('scope_forbidden',403);this.validateData(d.schema,raw.disposition);if(!eq(Object.keys(raw.disposition).sort(),[...d.schema.processors[raw.processor]].sort()))fail('scope_forbidden',403);return raw.disposition;}return raw.patch??raw.data??raw.target_data??{};}
 checkPatch(p,d,r,patch,base,raw,derived=[]){const fields=Object.keys(patch);this.fieldAccess(p,d,fields.filter(f=>!derived.includes(f)));if(raw.kind==='status'&&fields.some(f=>!derived.includes(f)&&!d.schema.statusFields?.includes(f)))fail('scope_forbidden',403);const gs=this.groups(d.schema,fields);for(const [g] of gs){const m=r.field_meta?.[g];if(m&&levels[m.actor]===3&&levels[raw.actor]<3)fail('user_locked',409);}
  if(base<1||base>r.revision)fail('invalid_base');for(const [g] of gs){const m=r.field_meta?.[g];if(m&&m.rev>base){if(levels[raw.actor]===3&&levels[m.actor]===3)fail('user_conflict',409);if(levels[raw.actor]<levels[m.actor])fail('superseded',409);if(levels[raw.actor]===levels[m.actor])fail('stale_base',409);}}
  return gs;
 }
 changed(r,patch,raw){return Object.entries(patch).some(([f,v])=>!eq(r.data[f],v))||(raw.confirm_fields?.length??0)>0;}
 applyPatch(p,d,ns,r,patch,base,raw){
  const derived=raw.kind==='status'?this.derivedPatch(p,d,ns,raw,r):{};patch={...patch,...derived};
  const gs=this.checkPatch(p,d,r,patch,base,raw,Object.keys(derived));const changed=this.changed(r,patch,raw);const next=clone(r);
  if(changed){next.revision++;next.updated_at=this.iso();next.data={...next.data,...clone(patch)};for(const [g] of gs)next.field_meta[g]={rev:next.revision,actor:raw.actor,at:next.updated_at,op_id:raw.op_id};}
  if(raw.kind==='merge')this.pendingBusinessTransitions.push({current:clone(r),next});else this.validateBusiness(p,d,ns,raw,r,next);if(!changed)return false;
  for(const [group] of gs){const prior=r.field_meta?.[group];if(prior)this.pendingSupersedes?.push({id:r.id,group,op_id:prior.op_id,revision:prior.rev});}
  Object.assign(r,next);return true;
 }
 save(ns,d,r){if(bytes(r)>DOMAIN_POLICY.maxRecordBytes)fail('payload_too_large',413);const {data,field_meta,provenance,...envelope}=r;const body=r.body_state==='purged'?null:canonicalJSON({data,field_meta,provenance});this.db.prepare('INSERT INTO domain_records(namespace,domain,id,revision,envelope_json,body_json) VALUES(?,?,?,?,?,?) ON CONFLICT(namespace,domain,id) DO UPDATE SET revision=excluded.revision,envelope_json=excluded.envelope_json,body_json=excluded.body_json').run(ns,d.domain,r.id,r.revision,canonicalJSON(envelope),body);const total=this.db.prepare('SELECT COALESCE(SUM(length(CAST(body_json AS BLOB))),0) n FROM domain_records WHERE namespace=? AND domain=?').get(ns,d.domain).n;const payload=this.db.prepare('SELECT COALESCE(SUM(length(CAST(payload_json AS BLOB))),0) n FROM domain_op_payloads WHERE namespace=? AND domain=?').get(ns,d.domain).n;if(total+payload>DOMAIN_POLICY.bodyQuota)fail('domain_capacity_exceeded',429);const sequence=this.highWater(ns,d)+1;if(!Number.isSafeInteger(sequence))fail('domain_capacity_exceeded',429);this.db.prepare('INSERT INTO domain_changes(namespace,domain,id,revision,domain_sequence,changed_at) VALUES(?,?,?,?,?,?)').run(ns,d.domain,r.id,r.revision,sequence,this.iso());d.runtime.highwaters??={};d.runtime.highwaters[ns]=sequence;this.saveRuntime(d);return sequence;}
 highWater(ns,d){return Math.max(d.runtime.highwaters?.[ns]??0,d.runtime.watermarks[ns]??0,Number(this.db.prepare('SELECT COALESCE(MAX(domain_sequence),0) n FROM domain_changes WHERE namespace=? AND domain=?').get(ns,d.domain).n));}
 checkCapacity(ns,domain,additional=0){const used=['domain_records:body_json','domain_op_payloads:payload_json','domain_snapshots:snapshot_json'].reduce((sum,spec)=>{const [table,column]=spec.split(':');return sum+Number(this.db.prepare(`SELECT COALESCE(SUM(length(CAST(${column} AS BLOB))),0) n FROM ${table} WHERE namespace=? AND domain=?`).get(ns,domain).n);},0)+Number(this.db.prepare('SELECT length(CAST(schema_json AS BLOB)) n FROM domain_registry WHERE domain=?').get(domain)?.n??0);if(used+additional>DOMAIN_POLICY.bodyQuota)fail('domain_capacity_exceeded',429);}
 latestReceipt(ns,domain,id){for(const row of this.db.prepare('SELECT receipt_json FROM domain_receipts WHERE namespace=? AND domain=? ORDER BY rowid DESC').all(ns,domain)){const r=json(row.receipt_json);if(r.targets.some(t=>t.id===id))return r;}fail('history_unavailable',409);}
 duplicateReceipt(p,d,ns,id){const receipt=this.latestReceipt(ns, d.domain, id);if(receipt.targets.some(target=>{const record=this.load(ns,d.domain,target.id);return !record||!this.allowed(p,record);}))fail('duplicate_restricted',409);return receipt;}
 result(raw,d,outcome,reason,receipt=null,problem=null){return {domain_protocol_version:1,domain:d.domain,op_id:raw.op_id,outcome,reason,receipt,problem};}
 persist(ns,p,d,raw,result,status,targets=[],duplicateTargetId=null){const row=this.load(ns,d.domain,raw.id);if(!row?.deleted_at)this.checkCapacity(ns,d.domain,bytes(raw));const meta={kind:raw.kind,id:raw.id,base_revision:raw.base_revision,actor:raw.actor,at:this.iso(),policy_version:d.policy_version,outcome:result.outcome??'shadow_staged',scope:actions[raw.kind],required_scopes:raw.kind==='merge'?['read','patch','delete','merge']:raw.kind==='purge'?['delete','purge']:[actions[raw.kind]],target_fields:raw.kind==='merge'?[{id:raw.id,fields:[]},{id:raw.target_id,fields:Object.keys(raw.target_data)},...raw.reference_updates.map(update=>({id:update.id,fields:Object.keys(update.patch)}))]:[{id:raw.id,fields:Object.keys(raw.patch??raw.data??raw.disposition??{})}],targets,duplicate_target_id:duplicateTargetId,fields:Object.keys(raw.patch??raw.data??raw.target_data??raw.disposition??{}),source_hmac:raw.kind==='create'?this.mac(raw.provenance.source):row?.provenance?.source?this.mac(row.provenance.source):null,supersedes:result.outcome==='accepted'?this.pendingSupersedes??[]:[],field_value_hmacs:Object.fromEntries(Object.entries(raw.patch??raw.data??raw.disposition??{}).filter(([f])=>Array.isArray(d.schema.fields[f]?.enum)).map(([f,v])=>[f,this.mac(v)])),processor:raw.processor??null,derived_fields:result.outcome==='accepted'||result.transport_state==='shadow_staged'?this.pendingDerivedFields??[]:[],derived_hooks_version:d.requiredHooksVersion,derived_refs:result.outcome==='accepted'||result.transport_state==='shadow_staged'?this.pendingDerivedRefs??[]:[],cascade_pending:result.outcome==='accepted'||result.transport_state==='shadow_staged'?this.pendingCascadeRefs??[]:[],authorization_ref_hmac:raw.authorization_ref?this.mac(raw.authorization_ref):null};this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(ns,p.principal_id,d.domain,raw.op_id,this.mac(raw),canonicalJSON({status,body:result}),canonicalJSON(this.recoveryMetadata(ns,p.principal_id,d.domain,raw.op_id,this.mac(raw),{status,body:result},meta)));if(!row?.deleted_at)this.db.prepare('INSERT INTO domain_op_payloads(namespace,principal_id,domain,op_id,payload_json,expires_at) VALUES(?,?,?,?,?,?)').run(ns,p.principal_id,d.domain,raw.op_id,canonicalJSON(raw),result.outcome==='accepted'?null:this.iso(time(raw.expires_at)+DOMAIN_POLICY.terminalRetention));}
 sanitizeResult(p,d,ns,saved){const out=clone(saved);delete out.body.record;for(const key of ['possible_duplicate','duplicate_of']){const id=out.body[key];if(id){const target=this.load(ns,d.domain,id);if(!target||target.deleted_at||!this.allowed(p,target))delete out.body[key];}}const ids=out.body.receipt?.targets?.map(t=>t.id)??[];if(ids.some(id=>{const r=this.load(ns,d.domain,id);return r&&!this.allowed(p,r);}))fail('not_found',404);return out;}
 submit(principal,domain,raw){return response(()=>{if(Array.isArray(raw))fail('batch_not_supported',413);if(!plain(raw))fail('invalid_request');if(bytes(raw)>DOMAIN_POLICY.maxOpBytes)fail('payload_too_large',413);const {p,d,ns}=this.context(principal,domain,raw?.core_instance_id,{operation:true});this.validate(raw,d);this.scope(p,d,actions[raw.kind],ns);const patch=this.patchFor(raw,d,p);this.fieldAccess(p,d,Object.keys(patch));if(raw.kind==='status'&&Object.keys(patch).some(f=>!d.schema.statusFields?.includes(f)))fail('scope_forbidden',403);if(raw.kind==='purge')this.scope(p,d,'delete',ns);if(raw.kind==='merge'){for(const action of ['read','patch','delete','merge'])this.scope(p,d,action,ns);for(const update of raw.reference_updates)this.fieldAccess(p,d,Object.keys(update.patch));}if(['delete','restore','merge','purge'].includes(raw.kind)&&levels[raw.actor]!==3)fail('actor_not_authorized',403);const authTargets=[{id:raw.id,fields:Object.keys(patch)},...(raw.kind==='merge'?[{id:raw.target_id,fields:Object.keys(raw.target_data)},...raw.reference_updates.map(u=>({id:u.id,fields:Object.keys(u.patch)}))]:[])];this.actor(p,raw,authTargets,domain);this.authorizeBusiness(p,d,ns,raw,{phase:'preflight'});
  return this.tx(()=>{const r=this.load(ns,domain,raw.id);if(r){this.visible(p,r);if(raw.actor==='import'&&(!p.import_sources||!p.import_sources.includes(r.provenance?.source)))fail('actor_not_authorized',403);}this.authorizeBusiness(p,d,ns,raw,{current:r});const old=this.db.prepare('SELECT * FROM domain_ops WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').get(ns,p.principal_id,domain,raw.op_id);if(old){if(old.request_digest!==this.mac(raw))fail('idempotency_conflict',409);const priorMeta=json(old.op_meta_json);this.replayBusiness(p,d,ns,priorMeta);const duplicateTarget=priorMeta.duplicate_target_id?this.visible(p,this.load(ns,domain,priorMeta.duplicate_target_id)):null;if(duplicateTarget?.deleted_at)fail('deleted_target',410,this.canRead(p,d,ns,duplicateTarget)?{tombstone:this.tomb(duplicateTarget)}:{});if(r?.deleted_at&&!['delete','purge'].includes(raw.kind))fail('deleted_target',410,this.canRead(p,d,ns,r)?{tombstone:this.tomb(r)}:{});const result=this.sanitizeResult(p,d,ns,json(old.result_json));if(result.body.outcome==='accepted'){result.status=200;result.body.outcome='duplicate';result.body.reason='idempotent_replay';}return result;}
   if(d.mode==='off')fail('domain_off',503);if(d.mode==='frozen')fail('domain_frozen',503);
   this.fault?.('after_preflight');this.db.exec('SAVEPOINT domain_operation');
   try{if(time(raw.expires_at)<=this.now())fail('intent_expired',410);const outcome=this.execute(p,d,ns,raw,r,patch);this.fault?.('after_records');let body,status;
    if(ns==='shadow'){body={transport_state:'shadow_staged',shadow_result_id:randomUUID()};status=202;}
    else if(!outcome.changed){body={...this.result(raw,d,'duplicate',outcome.reason,outcome.receipt),...(outcome.duplicate_of?{duplicate_of:outcome.duplicate_of}:{})};status=200;}
    else{const receipt={receipt_id:randomUUID(),core_instance_id:this.nodeId,authority_mode:'single_host',epoch:null,domain,accepted_op_id:raw.op_id,principal_id:p.principal_id,accepted_at:this.iso(),policy_version:d.policy_version,targets:outcome.records.map(r=>({id:r.id,revision:r.revision})),change_sequences:outcome.sequences};receipt.receipt_auth=this.mac(receipt);this.db.prepare('INSERT INTO domain_receipts(receipt_id,namespace,domain,receipt_json) VALUES(?,?,?,?)').run(receipt.receipt_id,ns,domain,canonicalJSON(receipt));body=this.result(raw,d,'accepted',null,receipt);if(outcome.possible_duplicate)body.possible_duplicate=outcome.possible_duplicate;status=201;}
    this.persist(ns,p,d,raw,body,status,outcome.records?.map(r=>({id:r.id,revision:r.revision}))??(outcome.duplicate_target?[outcome.duplicate_target]:[]),outcome.duplicate_target?.id??null);this.fault?.('after_result');const shown=outcome.records?.find(x=>x.id===raw.id);if(ns!=='shadow'&&shown&&!shown.deleted_at&&this.canRead(p,d,ns,shown))body={...body,record:this.publicRecord(shown)};return {status,body};
   }catch(e){if(!(e instanceof DomainError)||[403,404,413,429,503].includes(e.status))throw e;this.db.exec('ROLLBACK TO domain_operation');const outcome=e.code==='intent_expired'?'expired':['user_conflict','stale_delete','duplicate_restricted','reference_conflict','merge_too_large'].includes(e.code)?'needs_resolution':'rejected';const problem={problem_id:randomUUID(),code:e.code,retryable:false,action:'new_intent'};const body=this.result(raw,d,outcome,e.code,null,problem);this.persist(ns,p,d,raw,body,e.status);return {status:e.status,body};}
  });
 });}
 execute(p,d,ns,raw,r,patch){this.pendingSupersedes=[];this.pendingDerivedFields=[];this.pendingDerivedRefs=[];this.pendingCascadeRefs=[];this.pendingBusinessTransitions=[];
  if(raw.kind==='create'){
   if(raw.base_revision!==0)fail('invalid_base');if(r)fail('id_exists',409);const fields=Object.keys(raw.data);const now=this.iso();r={domain:d.domain,schema_version:d.schema.version,id:raw.id,revision:1,data:clone(raw.data),field_meta:{},created_at:now,updated_at:now,deleted_at:null,deleted_by:null,merged_into:null,body_state:'present',purge_after:null,origin:{principal_id:p.principal_id,device_id:p.device_id,created_op_id:raw.op_id},provenance:clone(raw.provenance),policy_version:d.policy_version,core_instance_id:this.nodeId};if(!this.allowed(p,r))fail('not_found',404);for(const [g] of this.groups(d.schema,fields))r.field_meta[g]={rev:1,actor:raw.actor,at:now,op_id:raw.op_id};
   this.validateBusiness(p,d,ns,raw,null,r);
   let duplicate=null;const hook=this.dedupHooks[d.domain];if(hook||d.schema.dedupFields?.length){const candidates=this.db.prepare('SELECT id FROM domain_records WHERE namespace=? AND domain=?').all(ns,d.domain).map(row=>this.load(ns,d.domain,row.id)).filter(candidate=>!candidate.deleted_at&&this.allowed(p,candidate));
    if(hook){let selected;try{selected=hook({data:clone(raw.data),provenance:clone(raw.provenance),candidates:clone(candidates)});if(selected&&typeof selected.then==='function'){selected.then(()=>{},()=>{});fail('dedup_unavailable',503);}}catch{fail('dedup_unavailable',503);}if(selected!==null){duplicate=candidates.find(candidate=>candidate.id===selected);if(!duplicate)fail('duplicate_restricted',409);}}
    else duplicate=candidates.find(candidate=>d.schema.dedupFields.every(f=>eq(candidate.data[f],r.data[f])))??null;
   }
   if(duplicate&&raw.actor!=='user_direct')return {changed:false,reason:'semantic_duplicate',duplicate_of:duplicate.id,duplicate_target:{id:duplicate.id,revision:duplicate.revision},receipt:ns==='shadow'?null:this.duplicateReceipt(p,d,ns,duplicate.id)};
   return {changed:true,records:[r],sequences:[this.save(ns,d,r)],possible_duplicate:duplicate?.id};
  }
  if(!r)fail('not_found',404);if(r.deleted_at&&!['restore','purge'].includes(raw.kind))fail('deleted_target',410,{tombstone:this.tomb(r)});
  if(['patch','status','ack_capture'].includes(raw.kind)){if(!this.applyPatch(p,d,ns,r,patch,raw.base_revision,raw))return {changed:false,reason:'no_change',receipt:ns==='shadow'?null:this.duplicateReceipt(p,d,ns,r.id)};return {changed:true,records:[r],sequences:[this.save(ns,d,r)]};}
  const previous=clone(r);
  if(raw.base_revision<1||raw.base_revision>r.revision)fail('invalid_base');
  if(raw.kind==='merge')return this.merge(p,d,ns,raw,r);
  if(raw.kind==='delete'&&raw.base_revision!==r.revision){const history=this.db.prepare('SELECT op_meta_json FROM domain_ops WHERE namespace=? AND domain=?').all(ns,d.domain).map(row=>json(row.op_meta_json)).filter(m=>m.outcome==='accepted'&&m.targets.some(t=>t.id===r.id&&t.revision>raw.base_revision));const revisions=new Set(history.flatMap(m=>m.targets.filter(t=>t.id===r.id).map(t=>t.revision)));if(history.some(m=>m.kind!=='patch'||m.actor!=='agent_inferred')||revisions.size!==r.revision-raw.base_revision)fail('stale_delete',409);}
  else if(raw.base_revision!==r.revision)fail('stale_base',409);
  if(raw.kind==='purge'){
   if(!r.deleted_at)fail('purge_target_alive',409);if(r.body_state==='purged')return {changed:false,reason:'already_purged',receipt:ns==='shadow'?null:this.duplicateReceipt(p,d,ns,r.id)};r.revision++;r.updated_at=this.iso();r.body_state='purged';this.scrub(ns,d,r.id,raw.op_id);delete r.data;delete r.field_meta;delete r.provenance;
  }else if(raw.kind==='restore'){
   if(!r.deleted_at)fail('restore_target_alive',409);if(r.merged_into)fail('merge_restore_unsupported',409);if(r.body_state!=='recoverable'||this.now()>=time(r.purge_after))fail('restore_window_expired',410);r.revision++;r.updated_at=this.iso();r.deleted_at=null;r.deleted_by=null;r.merged_into=null;r.body_state='present';r.purge_after=null;
  }else if(raw.kind==='delete')this.markDeleted(p,d,ns,r,raw);
  if(raw.kind!=='delete')this.validateBusiness(p,d,ns,raw,previous,r);
  return {changed:true,records:[r],sequences:[this.save(ns,d,r)]};
 }
 markDeleted(p,d,ns,r,raw,mergedInto=null){const previous=clone(r);r.revision++;r.updated_at=this.iso();r.deleted_at=this.iso();r.deleted_by=p.principal_id;r.merged_into=mergedInto;r.purge_after=this.iso(this.now()+DOMAIN_POLICY.restoreWindow);const immediate=raw.permanent||(d.schema.immediateDeleteSources??[]).includes(r.provenance?.source);r.body_state=immediate?'purged':'recoverable';if(immediate){delete r.data;delete r.field_meta;delete r.provenance;}if(raw.kind==='merge')this.pendingBusinessTransitions.push({current:previous,next:clone(r)});else this.validateBusiness(p,d,ns,raw,previous,r);this.pendingCascadeRefs=this.historicalDerivedRefs(ns,d.domain,r.id);this.scrub(ns,d,r.id,raw.op_id);const job={id:r.id,delete_revision:r.revision,purge_after:r.purge_after,state:immediate?'complete':'pending',at:this.iso(),attempts:0};this.db.prepare('INSERT INTO domain_purge_jobs(job_id,namespace,domain,id,job_json) VALUES(?,?,?,?,?)').run(randomUUID(),ns,d.domain,r.id,canonicalJSON(job));}
 scrub(ns,d,id,cause){const rows=this.db.prepare('SELECT principal_id,op_id,op_meta_json FROM domain_ops WHERE namespace=? AND domain=?').all(ns,d.domain);for(const row of rows){const m=json(row.op_meta_json);if(m.id===id||m.targets?.some(t=>t.id===id))this.db.prepare('DELETE FROM domain_op_payloads WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').run(ns,row.principal_id,d.domain,row.op_id);}
  // Conflicts and reference intents may name this record without accepted targets.
  for(const row of this.db.prepare('SELECT principal_id,op_id,payload_json FROM domain_op_payloads WHERE namespace=? AND domain=?').all(ns,d.domain)){const x=json(row.payload_json);if(x.id===id||x.target_id===id||x.reference_updates?.some(u=>u.id===id))this.db.prepare('DELETE FROM domain_op_payloads WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').run(ns,row.principal_id,d.domain,row.op_id);}
  this.db.prepare('DELETE FROM domain_snapshots WHERE namespace=? AND domain=?').run(ns,d.domain);
  const event={event:'payload_purge',id,cause,at:this.iso(),outcome:'purged',targets:[]};this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(ns,'__maintenance__',d.domain,randomUUID(),this.mac(event),canonicalJSON({status:200,body:{purged:true}}),canonicalJSON(event));
 }
 merge(p,d,ns,raw,source){if(raw.base_revision!==source.revision)fail('stale_base',409);for(const action of ['read','patch','delete','merge'])this.scope(p,d,action,ns);const target=this.visible(p,this.load(ns,d.domain,raw.target_id));if(target.deleted_at)fail('deleted_target',410);if(target.revision!==raw.target_base_revision)fail('stale_base',409);
  // A complete replacement cannot silently erase registered optional fields.
  if(Object.keys(target.data).some(f=>!Object.hasOwn(raw.target_data,f)))fail('invalid_request');this.checkPatch(p,d,target,raw.target_data,target.revision,raw);
  const referenceFields=d.schema.referenceFields??[];const refs=[];for(const row of this.db.prepare('SELECT id FROM domain_records WHERE namespace=? AND domain=?').all(ns,d.domain)){const record=this.load(ns,d.domain,row.id);if(record.deleted_at||record.id===source.id)continue;if(referenceFields.some(f=>this.hasRef(record.data[f],source.id)))refs.push(record);}
  if(bytes({...raw,reference_updates:refs.map(r=>({id:r.id,base_revision:r.revision,patch:Object.fromEntries(referenceFields.filter(f=>this.hasRef(r.data[f],source.id)).map(f=>[f,this.replaceRef(r.data[f],source.id,target.id)]))}))})>DOMAIN_POLICY.maxOpBytes)fail('merge_too_large',409);if(refs.some(r=>r.id===target.id)||refs.length!==raw.reference_updates.length)fail('reference_conflict',409);const records=[];for(const reference of refs){const update=raw.reference_updates.find(u=>u.id===reference.id);if(!update||!this.allowed(p,reference)||update.base_revision!==reference.revision)fail('reference_conflict',409);try{this.fieldAccess(p,d,Object.keys(update.patch));for(const [field,value] of Object.entries(update.patch)){const required=referenceFields.filter(f=>this.hasRef(reference.data[f],source.id));const permitted=this.groups(d.schema,required).flatMap(([,fields])=>fields);if(!permitted.includes(field)||!eq(value,referenceFields.includes(field)?this.replaceRef(reference.data[field],source.id,target.id):reference.data[field]))fail('reference_conflict',409);}for(const field of referenceFields)if(this.hasRef(reference.data[field],source.id)&&!Object.hasOwn(update.patch,field))fail('reference_conflict',409);this.checkPatch(p,d,reference,update.patch,update.base_revision,raw);}catch{fail('reference_conflict',409);}this.applyPatch(p,d,ns,reference,update.patch,update.base_revision,raw);records.push(reference);}
  // Reject cycles in the resulting registered reference graph.
  const targetNext={...target,data:raw.target_data};const replacements=new Map([...records,targetNext].map(r=>[r.id,r]));const graph=new Map();for(const row of this.db.prepare('SELECT id FROM domain_records WHERE namespace=? AND domain=?').all(ns,d.domain)){const record=replacements.get(row.id)??this.load(ns,d.domain,row.id);if(record.deleted_at||record.id===source.id)continue;graph.set(record.id,referenceFields.flatMap(f=>Array.isArray(record.data[f])?record.data[f]:typeof record.data[f]==='string'?[record.data[f]]:[]));}const visiting=new Set(),visited=new Set();const walk=id=>{if(visiting.has(id))fail('reference_conflict',409);if(visited.has(id))return;visiting.add(id);for(const next of graph.get(id)??[])if(graph.has(next))walk(next);visiting.delete(id);visited.add(id);};for(const id of graph.keys())walk(id);
  if(this.applyPatch(p,d,ns,target,raw.target_data,target.revision,raw))records.unshift(target);this.markDeleted(p,d,ns,source,raw,target.id);records.push(source);
  this.businessView={namespace:ns,domain:d.domain,records:new Map(records.map(record=>[record.id,record]))};
  try{for(const transition of this.pendingBusinessTransitions)this.validateBusiness(p,d,ns,raw,transition.current,transition.next);}
  finally{this.businessView=null;this.pendingBusinessTransitions=[];}
  return {changed:true,records,sequences:records.map(r=>this.save(ns,d,r))};
 }
 hasRef(value,id){return value===id||Array.isArray(value)&&value.includes(id);}
 replaceRef(value,source,target){return Array.isArray(value)?value.map(v=>v===source?target:v):value===source?target:value;}
 getOperation(principal,domain,opId,coreInstanceId){return response(()=>{const {p,d,ns}=this.context(principal,domain,coreInstanceId,{operation:true});if(!identifier(opId))fail('invalid_request');if(!p.scopes.some(s=>s.startsWith(domain+':')))fail('scope_forbidden',403);const row=this.db.prepare('SELECT * FROM domain_ops WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').get(ns,p.principal_id,domain,opId);if(!row)fail('op_not_found',404);const meta=json(row.op_meta_json);this.replayBusiness(p,d,ns,meta);const required=meta.required_scopes??(meta.kind==='merge'?['read','patch','delete','merge']:meta.kind==='purge'?['delete','purge']:[meta.scope]);for(const action of required)this.scope(p,d,action,ns);if(!p.actors.includes(meta.actor))fail('actor_not_authorized',403);this.fieldAccess(p,d,meta.fields??[]);for(const target of meta.target_fields??[])this.fieldAccess(p,d,target.fields);if(meta.kind==='merge'&&!meta.target_fields)fail('scope_forbidden',403);if(meta.actor==='import'&&(!meta.source_hmac||!p.import_sources?.some(source=>this.mac(source)===meta.source_hmac)))fail('actor_not_authorized',403);for(const target of meta.target_fields??[]){const object=this.load(ns,domain,target.id);if(object)this.visible(p,object);}const r=this.load(ns,domain,meta.duplicate_target_id??meta.id);if(r)this.visible(p,r);const saved=this.sanitizeResult(p,d,ns,json(row.result_json));return {status:200,body:ns==='shadow'?saved.body:{found:true,result:saved.body,target_state:r?.deleted_at?'deleted':r?'present':'unknown'}};});}
 /** Local-only adoption. No HTTP kind, implicit file access, source discovery, or remote grant. */
 adoptLegacyRecord(principal,domain,record,options={}){return response(()=>{
  strict(record,['id','revision','deleted_at','origin','data','provenance']);
  strict(options,['dryRun','authorizationRef','sourceKind','sourceRecordId','sourceRevision','batchId','mappingVersion','opId','projectionProof']);
  if(bytes({record,options})>DOMAIN_POLICY.maxOpBytes)fail('payload_too_large',413);
  const dryRun=options.dryRun??true;if(typeof dryRun!=='boolean'||!identifier(record.id)||!Number.isSafeInteger(record.revision)||record.revision<1||record.deleted_at!==null&&typeof record.deleted_at!=='string')fail('invalid_request');
  if(record.deleted_at!==null)time(record.deleted_at);
  strict(record.origin,['principal_id','device_id']);if(!identifier(record.origin.principal_id)||!identifier(record.origin.device_id))fail('invalid_request');
  strict(record.provenance,['source','source_refs','import_batch_id']);if(!identifier(record.provenance.source)||!Array.isArray(record.provenance.source_refs)||!Object.hasOwn(record.provenance,'import_batch_id'))fail('invalid_request');
  for(const key of ['sourceKind','sourceRecordId','batchId','mappingVersion'])if(!identifier(options[key]))fail('invalid_request');
  if(options.projectionProof!==undefined){strict(options.projectionProof,['manifest_version','manifest_digest','consumer_binding_digest']);if(options.projectionProof.manifest_version!==1||![options.projectionProof.manifest_digest,options.projectionProof.consumer_binding_digest].every(value=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)))fail('invalid_request');}
  if(options.sourceRecordId!==record.id||options.sourceRevision!==record.revision||typeof options.authorizationRef!=='string'||!options.authorizationRef)fail('invalid_request');
  const {p,d,ns}=this.context(principal,domain,this.nodeId,{operation:true});
  // Local adoption never treats shadow_write or ordinary create as an adoption capability.
  if(!p.scopes.includes(`${domain}:adopt`))fail('scope_forbidden',403);
  if(!p.actors.includes('import')||!p.import_sources?.includes(record.provenance.source)||!p.import_sources.includes(options.sourceKind))fail('actor_not_authorized',403);
  const adoption={sourceKind:options.sourceKind,sourceRecordId:record.id,sourceRevision:record.revision,batchId:options.batchId,mappingVersion:options.mappingVersion,isTombstone:record.deleted_at!==null,originMappingVerified:true,userCorrectionMappingVerified:false,...(options.projectionProof===undefined?{}:{projectionProof:clone(options.projectionProof)})};
  const verified=this.callHost(this.verifyLegacyAdoption,frozenCopy({principal:p,domain,core_instance_id:this.nodeId,record,adoption:{...adoption,originMappingVerified:false},authorizationRef:options.authorizationRef,now:this.iso()}));
  if(verified===false)fail('actor_not_authorized',403);if(verified!==true)fail('schema_not_ready',503);
  const digest=this.mac({domain,record,sourceKind:options.sourceKind,sourceRecordId:options.sourceRecordId,sourceRevision:options.sourceRevision,batchId:options.batchId,mappingVersion:options.mappingVersion,...(options.projectionProof===undefined?{}:{projectionProof:options.projectionProof})});
  const adoptionRecordDigest=hash(record);const adoptionRecordAuth=this.mac({format:'domain-adoption-record-v1',record_digest:adoptionRecordDigest});const adoptionBindingDigest=this.mac({format:'domain-adoption-binding-v1',domain,record_digest:adoptionRecordDigest,adoption});
  const key=this.mac({domain,sourceKind:options.sourceKind,id:record.id,revision:record.revision,batchId:options.batchId,mappingVersion:options.mappingVersion});
  const opId=options.opId??`${key.slice(0,8)}-${key.slice(8,12)}-5${key.slice(13,16)}-a${key.slice(17,20)}-${key.slice(20,32)}`;
  if(!uuid(opId)||opId===record.id)fail('invalid_request');
  const raw={kind:'legacy_adopt',id:record.id,op_id:opId,actor:'import',base_revision:0};
  this.authorizeBusiness(p,d,ns,raw,{operationOrigin:'local_adoption',adoption});
  if(record.deleted_at===null){this.validateData(d.schema,record.data,{complete:true});this.fieldAccess(p,d,Object.keys(record.data));}
  else if(Object.hasOwn(record,'data'))fail('invalid_request');
  return this.tx(()=>{
   const current=this.load(ns,domain,record.id);if(current)this.visible(p,current);
   const old=this.db.prepare('SELECT * FROM domain_ops WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').get(ns,p.principal_id,domain,opId);
   if(old){if(old.request_digest!==digest)fail('idempotency_conflict',409);const meta=json(old.op_meta_json);if(meta.kind!=='legacy_adopt')fail('idempotency_conflict',409);this.replayBusiness(p,d,ns,meta);if(!current||current.revision!==meta.adoption.sourceRevision||current.origin?.created_op_id!==opId||current.body_state!==meta.adopted_body_state||current.deleted_at!==meta.adopted_deleted_at) return {status:409,body:{outcome:'needs_resolution',reason:'user_conflict'}};return {status:200,body:dryRun?{dry_run:true,outcome:'duplicate',id:record.id,revision:record.revision}:(ns==='shadow'?this.sanitizeResult(p,d,ns,json(old.result_json)).body:{...this.sanitizeResult(p,d,ns,json(old.result_json)).body,outcome:'duplicate'})};}
   if(current){
    const prior=this.db.prepare('SELECT op_meta_json,request_digest FROM domain_ops WHERE namespace=? AND domain=?').all(ns,domain).find(row=>{const m=json(row.op_meta_json);return m.kind==='legacy_adopt'&&m.id===record.id&&m.adoption?.sourceKind===options.sourceKind;});
    if(prior){const meta=json(prior.op_meta_json);if(meta.adoption.sourceRevision===record.revision&&prior.request_digest!==digest)fail('idempotency_conflict',409);}
    return {status:409,body:{outcome:'needs_resolution',reason:'user_conflict'}};
   }
   const now=this.iso();const next={domain,schema_version:d.schema.version,id:record.id,revision:record.revision,created_at:now,updated_at:now,deleted_at:record.deleted_at,deleted_by:record.deleted_at?p.principal_id:null,merged_into:null,body_state:record.deleted_at?'purged':'present',purge_after:record.deleted_at,origin:{...clone(record.origin),created_op_id:opId},policy_version:d.policy_version,core_instance_id:this.nodeId};
   if(record.deleted_at===null){next.data=clone(record.data);next.provenance=clone(record.provenance);next.field_meta={};for(const [g] of this.groups(d.schema,Object.keys(record.data)))next.field_meta[g]={rev:record.revision,actor:'import',at:now,op_id:opId};}
   if(!this.allowed(p,next))fail('not_found',404);
   this.pendingDerivedRefs=[];this.pendingDerivedFields=[];this.pendingCascadeRefs=[];
   this.validateBusiness(p,d,ns,raw,null,next,{operationOrigin:'local_adoption',adoption});
   if(dryRun)return {status:200,body:{dry_run:true,outcome:'ready',id:next.id,revision:next.revision,is_tombstone:!!next.deleted_at}};
   if(d.mode==='off')fail('domain_off',503);if(d.mode==='frozen')fail('domain_frozen',503);
   this.fault?.('adoption_after_preflight');this.checkCapacity(ns,domain,bytes(next)+(record.deleted_at===null?bytes(record):0));const sequence=this.save(ns,d,next);this.fault?.('adoption_after_record');
   let body,status;if(ns==='shadow'){body={transport_state:'shadow_staged',shadow_result_id:randomUUID()};status=202;}
   else{const receipt={receipt_id:randomUUID(),core_instance_id:this.nodeId,authority_mode:'single_host',epoch:null,domain,accepted_op_id:opId,principal_id:p.principal_id,accepted_at:now,policy_version:d.policy_version,targets:[{id:next.id,revision:next.revision}],change_sequences:[sequence],adoption_binding_digest:adoptionBindingDigest};receipt.receipt_auth=this.mac(receipt);this.db.prepare('INSERT INTO domain_receipts(receipt_id,namespace,domain,receipt_json) VALUES(?,?,?,?)').run(receipt.receipt_id,ns,domain,canonicalJSON(receipt));body=this.result(raw,d,'accepted',null,receipt);status=201;}
   const fields=Object.keys(record.data??{});const metadata={kind:'legacy_adopt',id:record.id,base_revision:0,actor:'import',at:now,policy_version:d.policy_version,outcome:ns==='shadow'?'shadow_staged':'accepted',scope:'adopt',required_scopes:['adopt'],fields,target_fields:[{id:record.id,fields}],source_hmac:this.mac(record.provenance.source),operation_origin:'local_adoption',adoption,adoption_record_auth:adoptionRecordAuth,adoption_binding_digest:adoptionBindingDigest,adopted_body_state:next.body_state,adopted_deleted_at:next.deleted_at,derived_refs:this.pendingDerivedRefs,authorization_ref_hmac:this.mac(options.authorizationRef),targets:[{id:next.id,revision:next.revision}]};
   this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(ns,p.principal_id,domain,opId,digest,canonicalJSON({status,body}),canonicalJSON(this.recoveryMetadata(ns,p.principal_id,domain,opId,digest,{status,body},metadata)));
   // No legacy plaintext in immutable metadata or a deleted-record payload.
   if(record.deleted_at===null)this.db.prepare('INSERT INTO domain_op_payloads(namespace,principal_id,domain,op_id,payload_json,expires_at) VALUES(?,?,?,?,?,?)').run(ns,p.principal_id,domain,opId,canonicalJSON(record),null);
   this.fault?.('adoption_after_result');return {status,body};
  });
 });}
 getRecord(principal,domain,id,coreInstanceId){return response(()=>{const {p,d,ns}=this.context(principal,domain,coreInstanceId,{read:true});if(!identifier(id))fail('invalid_request');const r=this.visible(p,this.load(ns,domain,id));if(r.deleted_at)fail('deleted_target',410,{tombstone:this.tomb(r)});return {status:200,body:{record:this.publicRecord(r),policy_version:d.policy_version}};});}
 binding(p,d,ns){return {core_instance_id:this.nodeId,domain:d.domain,principal_id:p.principal_id,credential_generation:p.generation,installation_id:p.installation_id,view_policy_version:d.policy_version,namespace:ns};}
 bound(x,p,d,ns){return Object.entries(this.binding(p,d,ns)).every(([k,v])=>x[k]===v);}
 consumerKey(p,ns){return `${ns}:${this.mac([p.principal_id,p.generation,p.installation_id])}`;}
 issue(p,d,ns,sequence,extra={}){const token=this.seal({...this.binding(p,d,ns),type:'cursor',sequence,...extra});const key=this.consumerKey(p,ns);d.runtime.issued[key]??=[];const digest=this.mac(token);if(!d.runtime.issued[key].some(x=>x.digest===digest))d.runtime.issued[key].push({digest,sequence,at:this.iso()});this.saveRuntime(d);return token;}
 cursor(p,d,ns,token){const x=this.unseal(token);if(x.type!=='cursor'||!this.bound(x,p,d,ns)||!Number.isSafeInteger(x.sequence)||x.sequence<0)fail('resync_required',409);const watermark=d.runtime.watermarks[ns]??0;if(x.sequence<watermark)fail('resync_required',409,{reason:'retention_gap',domain:d.domain,core_instance_id:this.nodeId,retained_watermark:watermark,snapshot:`/v1/core/domains/${d.domain}/snapshot`});return x;}
 limit(n){if(n===undefined)return DOMAIN_POLICY.pageLimit;if(!Number.isSafeInteger(n)||n<1||n>DOMAIN_POLICY.maxPageLimit)fail('invalid_request');return n;}
 changes(principal,domain,query){return response(()=>{strict(query,['core_instance_id','cursor','limit']);const {p,d,ns}=this.context(principal,domain,query.core_instance_id,{read:true});const limit=this.limit(query.limit);return this.tx(()=>{const cursor=this.cursor(p,d,ns,query.cursor);const cut=this.highWater(ns,d);const rows=this.db.prepare('SELECT id,MAX(domain_sequence) sequence FROM domain_changes WHERE namespace=? AND domain=? AND domain_sequence>? AND domain_sequence<=? GROUP BY id ORDER BY sequence').all(ns,domain,cursor.sequence,cut);const records=[];let position=cursor.sequence;let size=0;let hasMore=false;for(const row of rows){const r=this.load(ns,domain,row.id);if(!r||!this.allowed(p,r)){position=row.sequence;continue;}const out=this.publicRecord(r);if(records.length>=limit||size+bytes(out)>DOMAIN_POLICY.maxResponseBytes-16384){hasMore=true;break;}records.push(out);size+=bytes(out);position=row.sequence;}if(!hasMore)position=Math.max(position,cut);return {status:200,body:{records,next_cursor:this.issue(p,d,ns,position),has_more:hasMore,retained_watermark:d.runtime.watermarks[ns]??0,policy_version:d.policy_version}};});});}
 snapshot(principal,domain,query){return response(()=>{strict(query,['core_instance_id','snapshot_token','page_token','limit']);const {p,d,ns}=this.context(principal,domain,query.core_instance_id,{read:true});const limit=this.limit(query.limit);return this.tx(()=>{this.db.prepare('DELETE FROM domain_snapshots WHERE expires_at<=?').run(this.iso());let snapshot,offset=0;
   if(query.snapshot_token||query.page_token){const capability=this.unseal(query.snapshot_token??query.page_token);if(!this.bound(capability,p,d,ns)||!['snapshot','page'].includes(capability.type))fail('resync_required',409);const row=this.db.prepare('SELECT snapshot_json,expires_at FROM domain_snapshots WHERE snapshot_id=? AND namespace=? AND domain=? AND principal_id=? AND generation=? AND installation_id=? AND policy_version=?').get(capability.snapshot_id,ns,domain,p.principal_id,p.generation,p.installation_id,d.policy_version);if(!row||time(row.expires_at)<=this.now())fail('resync_required',409);snapshot=json(row.snapshot_json);if(query.page_token){const page=this.unseal(query.page_token);if(page.type!=='page'||!this.bound(page,p,d,ns)||page.snapshot_id!==snapshot.id||!Number.isSafeInteger(page.offset)||page.offset<0||page.offset>snapshot.records.length)fail('resync_required',409);offset=page.offset;}}
   else{const count=this.db.prepare('SELECT COUNT(*) n FROM domain_snapshots WHERE principal_id=?').get(p.principal_id).n;if(count>=DOMAIN_POLICY.snapshotQuota)fail('domain_capacity_exceeded',429);const records=this.db.prepare('SELECT id FROM domain_records WHERE namespace=? AND domain=? ORDER BY id').all(ns,domain).map(row=>this.load(ns,domain,row.id)).filter(r=>this.allowed(p,r)).map(r=>this.publicRecord(r));const cut=this.highWater(ns,d);snapshot={id:randomUUID(),records,cut,created:this.iso(),expires:this.iso(this.now()+DOMAIN_POLICY.snapshotTtl),digest:hash(records)};this.checkCapacity(ns,domain,bytes(snapshot));this.db.prepare('INSERT INTO domain_snapshots(snapshot_id,namespace,domain,principal_id,generation,installation_id,policy_version,cut_sequence,created_at,expires_at,snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(snapshot.id,ns,domain,p.principal_id,p.generation,p.installation_id,d.policy_version,cut,snapshot.created,snapshot.expires,canonicalJSON(snapshot));}
   const records=[];let size=0;for(const record of snapshot.records.slice(offset)){if(records.length>=limit||size+bytes(record)>DOMAIN_POLICY.maxResponseBytes-16384)break;records.push(record);size+=bytes(record);}const next=offset+records.length;const hasMore=next<snapshot.records.length;const manifest={...this.binding(p,d,ns),snapshot_id:snapshot.id,schema_version:d.schema.version,policy_version:d.policy_version,created_at:snapshot.created,expires_at:snapshot.expires,cut_sequence:snapshot.cut,collection_digest:snapshot.digest,base_watermark:d.runtime.watermarks[ns]??0,base_cursor:hasMore?null:this.issue(p,d,ns,snapshot.cut,{snapshot_id:snapshot.id})};manifest.manifest_auth=this.mac(manifest);return {status:200,body:{snapshot_id:snapshot.id,snapshot_token:this.seal({...this.binding(p,d,ns),type:'snapshot',snapshot_id:snapshot.id}),records,page_digest:hash(records),next_page_token:hasMore?this.seal({...this.binding(p,d,ns),type:'page',snapshot_id:snapshot.id,offset:next}):null,has_more:hasMore,manifest}};
  });});}
 acknowledge(principal,domain,raw){return response(()=>{strict(raw,['domain_protocol_version','core_instance_id','cursor','snapshot_id']);if(raw.domain_protocol_version!==1)fail('invalid_request');const {p,d,ns}=this.context(principal,domain,raw.core_instance_id,{read:true});return this.tx(()=>{const cursor=this.cursor(p,d,ns,raw.cursor);const key=this.consumerKey(p,ns);if(!(d.runtime.issued[key]??[]).some(x=>x.digest===this.mac(raw.cursor)&&x.sequence===cursor.sequence))fail('resync_required',409);if(raw.snapshot_id&&cursor.snapshot_id!==raw.snapshot_id)fail('resync_required',409);if(cursor.snapshot_id){const snap=this.db.prepare('SELECT expires_at FROM domain_snapshots WHERE snapshot_id=? AND principal_id=?').get(cursor.snapshot_id,p.principal_id);const completed=d.runtime.completed_snapshots?.[cursor.snapshot_id];if((!snap||time(snap.expires_at)<=this.now())&&!(completed?.key===key&&completed?.digest===this.mac(raw.cursor)))fail('resync_required',409);}const prior=this.db.prepare('SELECT cursor_sequence FROM domain_consumer_acks WHERE namespace=? AND domain=? AND principal_id=? AND generation=? AND installation_id=? AND policy_version=?').get(ns,domain,p.principal_id,p.generation,p.installation_id,d.policy_version);const position=Math.max(prior?.cursor_sequence??0,cursor.sequence);this.db.prepare('INSERT INTO domain_consumer_acks(namespace,domain,principal_id,generation,installation_id,policy_version,cursor_sequence) VALUES(?,?,?,?,?,?,?) ON CONFLICT(namespace,domain,principal_id,generation,installation_id,policy_version) DO UPDATE SET cursor_sequence=excluded.cursor_sequence').run(ns,domain,p.principal_id,p.generation,p.installation_id,d.policy_version,position);d.runtime.acks[key]={at:this.iso(),sequence:position};if(cursor.snapshot_id){d.runtime.completed_snapshots??={};d.runtime.completed_snapshots[cursor.snapshot_id]={key,digest:this.mac(raw.cursor),at:this.iso()};this.db.prepare('DELETE FROM domain_snapshots WHERE snapshot_id=? AND principal_id=?').run(cursor.snapshot_id,p.principal_id);}this.saveRuntime(d);return {status:200,body:{ack_cursor:this.issue(p,d,ns,position),advanced:!prior||position>prior.cursor_sequence}};});});}
 runRetention({domain}={}){return response(()=>{this.ready();return this.tx(()=>{let purged=0;const domains=domain?[this.domain(domain)]:this.db.prepare('SELECT domain FROM domain_registry').all().map(r=>this.domain(r.domain));for(const d of domains){this.pruneRuntime(d);for(const row of this.db.prepare('SELECT * FROM domain_purge_jobs WHERE domain=?').all(d.domain)){const job=json(row.job_json);if(job.state==='complete'||time(job.purge_after)>this.now())continue;const r=this.load(row.namespace,d.domain,row.id);if(!r?.deleted_at||r.revision!==job.delete_revision){job.state='complete';job.reason='superseded';}else if(r.body_state!=='purged'){r.revision++;r.updated_at=this.iso();r.body_state='purged';delete r.data;delete r.field_meta;delete r.provenance;this.scrub(row.namespace,d,r.id,row.job_id);const sequence=this.save(row.namespace,d,r);const receipt={receipt_id:randomUUID(),core_instance_id:this.nodeId,authority_mode:'single_host',epoch:null,domain:d.domain,accepted_op_id:row.job_id,principal_id:'__maintenance__',accepted_at:this.iso(),policy_version:d.policy_version,targets:[{id:r.id,revision:r.revision}],change_sequences:[sequence]};receipt.receipt_auth=this.mac(receipt);if(row.namespace==='production'){this.db.prepare('INSERT INTO domain_receipts(receipt_id,namespace,domain,receipt_json) VALUES(?,?,?,?)').run(receipt.receipt_id,row.namespace,d.domain,canonicalJSON(receipt));job.receipt_id=receipt.receipt_id;}else job.shadow_result_id=randomUUID();const recoveryMeta={kind:'retention_purge',outcome:'accepted',targets:[{id:r.id,revision:r.revision}]},recoveryResult={status:200,body:{purged:true}},recoveryDigest=this.mac(recoveryMeta);this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(row.namespace,'__maintenance__',d.domain,row.job_id,recoveryDigest,canonicalJSON(recoveryResult),canonicalJSON(this.recoveryMetadata(row.namespace,'__maintenance__',d.domain,row.job_id,recoveryDigest,recoveryResult,recoveryMeta)));job.state='complete';purged++;}else job.state='complete';job.at=this.iso();job.attempts++;this.db.prepare('UPDATE domain_purge_jobs SET job_json=? WHERE job_id=?').run(canonicalJSON(job),row.job_id);}
    for(const row of this.db.prepare('SELECT * FROM domain_op_payloads WHERE domain=? AND expires_at IS NOT NULL AND expires_at<=?').all(d.domain,this.iso())){this.db.prepare('DELETE FROM domain_op_payloads WHERE namespace=? AND principal_id=? AND domain=? AND op_id=?').run(row.namespace,row.principal_id,d.domain,row.op_id);const event={event:'terminal_payload_expired',op_id:row.op_id,at:this.iso(),targets:[],outcome:'purged'};this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(row.namespace,'__maintenance__',d.domain,randomUUID(),this.mac(event),'{}',canonicalJSON(event));}
    for(const ns of ['production','shadow']){const active=Object.entries(d.runtime.acks).filter(([k,v])=>k.startsWith(ns+':')&&time(v.at)>=this.now()-DOMAIN_POLICY.activeConsumer).map(([,v])=>v.sequence);let boundary=d.runtime.watermarks[ns]??0;for(const change of this.db.prepare('SELECT * FROM domain_changes WHERE namespace=? AND domain=? ORDER BY domain_sequence').all(ns,d.domain)){if(time(change.changed_at)>this.now()-DOMAIN_POLICY.feedRetention||active.some(s=>s<change.domain_sequence))break;boundary=change.domain_sequence;}if(boundary>(d.runtime.watermarks[ns]??0)){const previous=d.runtime.watermarks[ns]??0;d.runtime.watermarks[ns]=boundary;this.db.prepare('DELETE FROM domain_changes WHERE namespace=? AND domain=? AND domain_sequence<=?').run(ns,d.domain,boundary);const event={event:'retention_watermark',previous,current:boundary,policy_version:d.policy_version,at:this.iso(),targets:[]};this.db.prepare('INSERT INTO domain_ops(namespace,principal_id,domain,op_id,request_digest,result_json,op_meta_json) VALUES(?,?,?,?,?,?,?)').run(ns,'__maintenance__',d.domain,randomUUID(),this.mac(event),'{}',canonicalJSON(event));}}
    this.saveRuntime(d);
   }this.db.prepare('DELETE FROM domain_snapshots WHERE expires_at<=?').run(this.iso());return {status:200,body:{purged}};});});}
}
