import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes,createHash } from 'node:crypto';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,rmSync,existsSync,linkSync,unlinkSync,realpathSync,renameSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync,execFileSync,spawn } from 'node:child_process';
import { once } from 'node:events';
import { pathToFileURL } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import { DOMAIN_SCHEMA_SQL } from '../domain_schema.mjs';
import { ICoreStore } from '../i_core_store.mjs';
import { BACKUP_ROLES,createRuntimeBackup } from './backup_bundle.mjs';
import { wrapBackupKey,unwrapBackupKey,portableEnvelopeSha256,bindPortableArtifact,verifyPortableBinding,restorePortableBackupForInspection } from './portable_key_custody.mjs';
import { captureConsistentSqlite,captureOnlineRuntimeBackup,runDueAutomaticBackup } from './automatic_backup.mjs';
import { syntheticRoot,syntheticFixedNode } from '../test_fixtures/release_schema6/synthetic_paths.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(t,{schema6=false}={}){
 const root=syntheticRoot('portable-synthetic-');const closers=[];t.after(()=>{for(const close of closers)close();assert.equal(path.dirname(root),realpathSync.native(tmpdir()));assert.ok(path.basename(root).startsWith('portable-synthetic-'));rmSync(root,{recursive:true,force:true});});const sources=path.join(root,'sources'),release=path.join(sources,'release');mkdirSync(sources);mkdirSync(release);
 const database=path.join(sources,'core.sqlite');let db,node='synthetic-node';
 if(schema6){const store=new ICoreStore(database,{activityEnabled:false});store.close();db=new DatabaseSync(database);db.exec(DOMAIN_SCHEMA_SQL);db.exec("UPDATE core_metadata SET value='6' WHERE key='schema_version'");node=db.prepare("SELECT value FROM core_metadata WHERE key='node_id'").get().value;assert.equal(db.prepare("SELECT value FROM core_metadata WHERE key='schema_version'").get().value,'6');}
 else{db=new DatabaseSync(database);db.exec('CREATE TABLE core_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL)');for(const [k,v] of [['schema_version','4'],['node_id',node],['cursor_secret',randomBytes(32).toString('base64url')]])db.prepare('INSERT INTO core_metadata VALUES(?,?)').run(k,v);}
 db.exec('CREATE TABLE portable_test_payload(id INTEGER PRIMARY KEY,value TEXT)');db.prepare('INSERT INTO portable_test_payload VALUES(?,?)').run(1,'synthetic private row');db.close();
 const manifest=path.join(release,'manifest.json');writeFileSync(manifest,'{"synthetic":true}');const entries=[{role:'database',name:'core.sqlite',source_path:database,sha256:hash(readFileSync(database))},{role:'release',name:'manifest.json',source_path:manifest,sha256:hash(readFileSync(manifest))}];
 for(const role of BACKUP_ROLES.filter(r=>!['database','release'].includes(r))){const p=path.join(sources,role+'.json');writeFileSync(p,JSON.stringify(role==='recovery_custody'?{format:'i-core-recovery-custody-v1',mode:'initial_schema4',node_id:node,database_path:database}:{synthetic:true,role}));entries.push({role,name:role+'.json',source_path:p,sha256:hash(readFileSync(p))});}
 const key=randomBytes(32),password=randomBytes(32),backupSetId=randomBytes(32).toString('hex'),envelope=wrapBackupKey({key,password,backupSetId});t.after(()=>{key.fill(0);password.fill(0);});
 const spec={format:'i-core-runtime-backup-spec-v1',source_schema:schema6?6:4,node_id:node,canonical_database_path:database,old_release_root:release,old_release_manifest_sha256:entries[1].sha256,entries};
 const outputRoot=path.join(root,'daily'),mirrorRoot=path.join(root,'external-synthetic');mkdirSync(outputRoot);mkdirSync(mirrorRoot);const policy={format:'i-core-automatic-backup-v1',outputRoot,mirrorRoot,retentionDays:30,backupSetId};return{closers,root,sources,database,key,password,backupSetId,envelope,spec,policy};
}
test('scrypt envelope roundtrip, random salt/nonce, no key/password serialized',t=>{const f=fixture(t),key=unwrapBackupKey(f);assert.deepEqual(key,f.key);key.fill(0);const other=wrapBackupKey(f);assert.notEqual(other.salt,f.envelope.salt);assert.notEqual(other.nonce,f.envelope.nonce);assert.equal(JSON.stringify(f.envelope).includes(f.key.toString('base64url')),false);assert.equal(JSON.stringify(f.envelope).includes(f.password.toString('base64url')),false);});
test('wrong password, set, key purpose, tag, ciphertext, weak and costly KDF reject',t=>{const f=fixture(t);assert.throws(()=>unwrapBackupKey({...f,password:randomBytes(32)}));assert.throws(()=>unwrapBackupKey({...f,backupSetId:'0'.repeat(64)}));for(const mutate of [e=>e.purpose='recovery',e=>e.tag=Buffer.alloc(16).toString('base64url'),e=>e.ciphertext=Buffer.alloc(32).toString('base64url'),e=>e.kdf.N=2,e=>e.kdf.N=2**30,e=>e.kdf.p=1000000,e=>e.extra='unknown']){const e=structuredClone(f.envelope);mutate(e);assert.throws(()=>unwrapBackupKey({...f,envelope:e}));}assert.throws(()=>wrapBackupKey({...f,password:Buffer.alloc(15)}));assert.throws(()=>wrapBackupKey({...f,password:Buffer.alloc(1025)}));});
test('password-only restore in separate process uses real readonly Core, no DPAPI/key input',t=>{const f=fixture(t),r=createRuntimeBackup({spec:f.spec,key:f.key,outputDirectory:path.join(f.root,'backup')}),binding=bindPortableArtifact({...f,report:r});const module=pathToFileURL(path.resolve('tools/i_core/release_schema6/portable_key_custody.mjs')).href;const code=`import {restorePortableBackupForInspection} from ${JSON.stringify(module)};const chunks=[];for await(const c of process.stdin)chunks.push(c);const input=Buffer.concat(chunks);const n=input.readUInt32BE();const password=Buffer.from(input.subarray(4,4+n));const request=JSON.parse(input.subarray(4+n));try{const r=await restorePortableBackupForInspection({...request,password});process.stdout.write(JSON.stringify({verified:r.verified,passwordOnly:r.passwordOnly,dpapiUsed:r.dpapiUsed,denied:r.deniedRoutes.length,unchanged:r.databaseBytesUnchanged}));}finally{password.fill(0);input.fill(0);}`;const header=Buffer.alloc(4);header.writeUInt32BE(f.password.length);const input=Buffer.concat([header,f.password,Buffer.from(JSON.stringify({envelope:f.envelope,binding,artifactPath:r.artifactPath,outputDirectory:path.join(f.root,'restored')}))]);const child=spawnSync(process.execPath,['--input-type=module','-e',code],{input,encoding:'utf8',windowsHide:true,env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR},timeout:30000});input.fill(0);assert.equal(child.status,0,child.stderr);assert.deepEqual(JSON.parse(child.stdout),{verified:true,passwordOnly:true,dpapiUsed:false,denied:5,unchanged:true});});
test('portable artifact binding rejects artifact/fingerprint/envelope/key substitution',async t=>{const f=fixture(t),r=createRuntimeBackup({spec:f.spec,key:f.key,outputDirectory:path.join(f.root,'backup')}),b=bindPortableArtifact({...f,report:r});assert.equal(verifyPortableBinding({...f,binding:b}).artifactSha256,r.artifactSha256);for(const field of ['artifactSha256','inventorySha256','databaseFingerprintSha256','envelopeSha256','keyId'])assert.throws(()=>verifyPortableBinding({...f,binding:{...b,[field]:'0'.repeat(64)}}));await assert.rejects(restorePortableBackupForInspection({...f,binding:b,artifactPath:r.artifactPath,outputDirectory:f.sources}));});
test('online WAL snapshot includes committed changes without copying or deleting source sidecars',async t=>{const f=fixture(t),writer=new DatabaseSync(f.database);f.closers.push(()=>writer.close());writer.exec('PRAGMA journal_mode=WAL');writer.prepare('INSERT INTO portable_test_payload VALUES(?,?)').run(2,'committed WAL');assert.ok(existsSync(f.database+'-wal'));const target=path.join(f.root,'copy.sqlite');await captureConsistentSqlite({sourcePath:f.database,destinationPath:target});const copy=new DatabaseSync(target,{readOnly:true});assert.equal(copy.prepare('SELECT count(*) AS n FROM portable_test_payload').get().n,2);copy.close();assert.ok(existsSync(f.database+'-wal'));assert.equal(existsSync(target+'-wal'),false);await assert.rejects(captureConsistentSqlite({sourcePath:f.database,destinationPath:target}));});
test('online snapshot rejects source and sidecar hardlinks',async t=>{const f=fixture(t),hard=path.join(f.root,'hard');linkSync(f.database,hard);await assert.rejects(captureConsistentSqlite({sourcePath:f.database,destinationPath:path.join(f.root,'copy.sqlite')}));unlinkSync(hard);writeFileSync(f.database+'-wal','fake');linkSync(f.database+'-wal',hard);await assert.rejects(captureConsistentSqlite({sourcePath:f.database,destinationPath:path.join(f.root,'copy.sqlite')}));});
test('online schema6 archive retains original custody separately; password-only inspection succeeds',async t=>{const f=fixture(t,{schema6:true}),writer=new DatabaseSync(f.database);writer.exec('PRAGMA journal_mode=WAL');f.closers.push(()=>writer.close());const before=readFileSync(f.spec.entries.find(e=>e.role==='recovery_custody').source_path);const r=await captureOnlineRuntimeBackup({specTemplate:f.spec,key:f.key,outputDirectory:path.join(f.root,'online')});assert.equal(r.onlineSnapshot,true);assert.equal(r.captureWindow.crossComponentAtomic,false);assert.equal(existsSync(path.join(f.root,'online/capture')),false);assert.deepEqual(readFileSync(f.spec.entries.find(e=>e.role==='recovery_custody').source_path),before);const binding=bindPortableArtifact({...f,report:r});const inspected=await restorePortableBackupForInspection({...f,binding,artifactPath:r.artifactPath,outputDirectory:path.join(f.root,'inspection')});assert.equal(inspected.coreHealth.schema_version,6);assert.equal(inspected.dpapiUsed,false);});
test('daily due, default/configured retention and ciphertext mirror; unrelated files never deleted',async t=>{const f=fixture(t),now=1791234000000;const run=ms=>runDueAutomaticBackup({policy:f.policy,specTemplate:f.spec,key:f.key,envelope:f.envelope,nowMs:ms});const first=await run(now);assert.equal(first.status,'backed_up');assert.equal(first.mirrored,true);assert.equal((await run(now+1000)).status,'not_due');writeFileSync(path.join(f.policy.outputRoot,'unrelated'),'keep');await run(now+31*86400000);assert.equal(readdirSync(f.policy.outputRoot).filter(n=>n.startsWith('daily-')).length,1);assert.equal(readFileSync(path.join(f.policy.outputRoot,'unrelated'),'utf8'),'keep');const dirs=readdirSync(f.policy.mirrorRoot);assert.equal(dirs.length,1);assert.equal(readFileSync(path.join(f.policy.mirrorRoot,dirs[0],'artifact/runtime.aes256gcm')).includes(Buffer.from('synthetic private row')),false);});
test('scheduler rejects weak policy/key changes; same-process overlap rejects and stale lock pathname is harmless',async t=>{const f=fixture(t),opts={policy:f.policy,specTemplate:f.spec,key:f.key,envelope:f.envelope};for(const retentionDays of [0,-1,0.5,3651])await assert.rejects(runDueAutomaticBackup({...opts,policy:{...f.policy,retentionDays}}));await assert.rejects(runDueAutomaticBackup({...opts,key:randomBytes(32)}));writeFileSync(path.join(f.policy.outputRoot,'.automatic.lock'),'');const running=runDueAutomaticBackup(opts);await assert.rejects(runDueAutomaticBackup(opts),e=>e.code==='automatic_in_process_busy');assert.equal((await running).status,'backed_up');assert.ok(existsSync(path.join(f.policy.outputRoot,'.automatic.lock')));});
test('retention does not delete directories whose signed contents have extra files',async t=>{const f=fixture(t),now=1791234000000,opts={policy:f.policy,specTemplate:f.spec,key:f.key,envelope:f.envelope};await runDueAutomaticBackup({...opts,nowMs:now});const old=readdirSync(f.policy.outputRoot).find(n=>n.startsWith('daily-'));writeFileSync(path.join(f.policy.outputRoot,old,'user-file'),'keep');await assert.rejects(runDueAutomaticBackup({...opts,nowMs:now+31*86400000}));assert.equal(readFileSync(path.join(f.policy.outputRoot,old,'user-file'),'utf8'),'keep');});

test('auxiliary SQLite requires explicit consistent capture; raw config copying rejected',async t=>{const f=fixture(t),entry=f.spec.entries.find(e=>e.role==='configuration'),aux=path.join(f.sources,'aux.sqlite');const db=new DatabaseSync(aux);db.exec('CREATE TABLE items(id INTEGER); INSERT INTO items VALUES(1)');db.close();entry.source_path=aux;entry.sha256=hash(readFileSync(aux));await assert.rejects(captureOnlineRuntimeBackup({specTemplate:f.spec,key:f.key,outputDirectory:path.join(f.root,'bad')}),e=>e.code==='sqlite_source_requires_online_snapshot');const r=await captureOnlineRuntimeBackup({specTemplate:f.spec,sqliteEntryNames:[entry.name],key:f.key,outputDirectory:path.join(f.root,'good')});assert.equal(r.verified,true);});
test('clock rollback fails and no default mirror is written',async t=>{const f=fixture(t);delete f.policy.mirrorRoot;delete f.policy.retentionDays;const opts={policy:f.policy,specTemplate:f.spec,key:f.key,envelope:f.envelope};const r=await runDueAutomaticBackup({...opts,nowMs:1791234000000});assert.equal(r.retentionDays,30);assert.equal(r.mirrored,false);await assert.rejects(runDueAutomaticBackup({...opts,nowMs:1791233999999}),e=>e.code==='automatic_clock_rollback');});

test('offline mirror retains local success and reconnect copies without recapturing database',async t=>{const f=fixture(t);f.policy.mirrorRoot=path.join(f.root,'disconnected');const opts={policy:f.policy,specTemplate:f.spec,key:f.key,envelope:f.envelope};const first=await runDueAutomaticBackup({...opts,nowMs:1791234000000});assert.equal(first.status,'mirror_pending');assert.equal(first.localBackupCreated,true);const local=readdirSync(f.policy.outputRoot).filter(n=>n.startsWith('daily-'));assert.equal(local.length,1);const before=hash(readFileSync(path.join(f.policy.outputRoot,local[0],'artifact/runtime.aes256gcm')));mkdirSync(f.policy.mirrorRoot);const retry=await runDueAutomaticBackup({...opts,nowMs:1791234001000});assert.equal(retry.status,'not_due');assert.equal(retry.mirrored,true);assert.equal(readdirSync(f.policy.outputRoot).filter(n=>n.startsWith('daily-')).length,1);const target=readdirSync(f.policy.mirrorRoot)[0];assert.equal(hash(readFileSync(path.join(f.policy.mirrorRoot,target,'artifact/runtime.aes256gcm'))),before);});

test('Windows pinned wrappers setup portable key, automatic DPAPI job, then password-only restore without key directory',{skip:process.platform!=='win32'},async t=>{
 const f=fixture(t),{INVENTORY,cleanEnvironment,prepareRelease}=await import('./package.mjs');
 const repo=path.join(f.root,'synthetic-git'),release=path.join(f.root,'fixed-release');mkdirSync(repo);
 const gitPath=path.resolve(execFileSync('git',['--exec-path'],{encoding:'utf8',windowsHide:true}).trim(),'../../../bin/git.exe');
 const git=args=>execFileSync(gitPath,args,{encoding:'utf8',windowsHide:true,env:cleanEnvironment()}).trim();git(['init','-q',repo]);
 for(const n of INVENTORY.filter(n=>n!=='runtime/node.exe')){const target=path.join(repo,n);mkdirSync(path.dirname(target),{recursive:true});writeFileSync(target,readFileSync(path.resolve(n)));}
 git(['-C',repo,'-c','core.autocrlf=false','add','.']);git(['-C',repo,'-c','user.name=Synthetic','-c','user.email=synthetic@example.invalid','-c','commit.gpgsign=false','-c','core.hooksPath='+path.join(f.root,'no-hooks'),'commit','-qm','synthetic runtime']);
 const packaged=prepareRelease({repository:repo,output:release,nodePath:syntheticFixedNode(f.root),gitPath,sourceCommit:git(['-C',repo,'rev-parse','HEAD'])});
 const ps=path.join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe'),base=path.join(release,'tools/i_core/release_schema6'),keys=path.join(f.root,'dpapi-keys');
 execFileSync(ps,['-NoProfile','-NonInteractive','-File',path.join(base,'key_custody.ps1'),'-Action','Create','-KeyDirectory',keys],{windowsHide:true,stdio:['ignore','pipe','pipe']});
 // Synthetic UI substitute only. Random passphrase travels binary stdin; the
 // production wrapper still uses its actual SecureString conversion/frame.
 const driver=path.join(f.root,'synthetic-password-ui.ps1');writeFileSync(driver,`
$ErrorActionPreference='Stop'
$stream=[Console]::OpenStandardInput();$memory=New-Object IO.MemoryStream;$stream.CopyTo($memory);$bytes=$memory.ToArray();$memory.Dispose();$length=[int]$bytes[0]
$global:SyntheticSecure=New-Object Security.SecureString
for($i=1;$i -le $length;$i++){$global:SyntheticSecure.AppendChar([char]$bytes[$i])}
function global:Read-Host { param([string]$Prompt,[switch]$AsSecureString) return $global:SyntheticSecure.Copy() }
$request=[Text.Encoding]::UTF8.GetString($bytes,$length+1,$bytes.Length-$length-1)|ConvertFrom-Json
[Array]::Clear($bytes,0,$bytes.Length)
$arguments=@{};foreach($p in $request.args.PSObject.Properties){$arguments[$p.Name]=$p.Value}
& $request.wrapper @arguments
exit $LASTEXITCODE
`);
 const password=Buffer.from(randomBytes(32).toString('base64url'));t.after(()=>password.fill(0));
 const call=args=>{const input=Buffer.concat([Buffer.from([password.length]),password,Buffer.from(JSON.stringify({wrapper:path.join(base,'backup_bundle_schema6.ps1'),args:{ReleaseDirectory:release,ManifestSha256:packaged.manifest_sha256,...args}}))]);try{return JSON.parse(execFileSync(ps,['-NoProfile','-NonInteractive','-File',driver],{input,windowsHide:true,stdio:['pipe','pipe','pipe'],env:{...process.env,NODE_OPTIONS:'--require=missing-inherited.cjs'},maxBuffer:65536}));}finally{input.fill(0);}};
 const portable=path.join(f.root,'portable');assert.equal(call({Operation:'SetupPortable',KeyDirectory:keys,OutputDirectory:portable,BackupSetId:f.backupSetId}).status,'portable_key_created');
 const envelopePath=path.join(portable,'portable-key.json'),configPath=path.join(f.root,'automatic-config.json');
 writeFileSync(configPath,JSON.stringify({policy:f.policy,specTemplate:f.spec,sqliteEntryNames:[],envelopePath,envelopeSha256:hash(readFileSync(envelopePath))}));
 const aclScript=path.join(f.root,'protect-config.ps1');writeFileSync(aclScript,"param([string]$Helper,[string]$Target)\n. $Helper -Action Library\nSet-BackupPrivateAcl $Target $false\n");execFileSync(ps,['-NoProfile','-NonInteractive','-File',aclScript,'-Helper',path.join(base,'key_custody.ps1'),'-Target',configPath],{windowsHide:true,stdio:['ignore','pipe','pipe']});
 const auto=call({Operation:'Automatic',KeyDirectory:keys,ConfigPath:configPath,ConfigSha256:hash(readFileSync(configPath))});assert.equal(auto.status,'backed_up');assert.equal(auto.mirrored,true);
 const holderPath=path.join(f.root,'synthetic-lock-holder.ps1');writeFileSync(holderPath,"param([string]$Path)\n$h=New-Object IO.FileStream($Path,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)\n[Console]::Out.WriteLine('ready');[Console]::Out.Flush();[Console]::ReadLine()|Out-Null;$h.Dispose()\n");
 const lockPath=path.join(f.policy.outputRoot,'.automatic.lock');const holder=spawn(ps,['-NoProfile','-NonInteractive','-File',holderPath,'-Path',lockPath],{windowsHide:true,stdio:['pipe','pipe','pipe']});
 try{await Promise.race([once(holder.stdout,'data'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('synthetic_lock_timeout')),10000).unref())]);assert.throws(()=>call({Operation:'Automatic',KeyDirectory:keys,ConfigPath:configPath,ConfigSha256:hash(readFileSync(configPath))}));const exited=once(holder,'exit');holder.kill();await exited;assert.ok(existsSync(lockPath));assert.equal(call({Operation:'Automatic',KeyDirectory:keys,ConfigPath:configPath,ConfigSha256:hash(readFileSync(configPath))}).status,'not_due');}
 finally{if(holder.exitCode===null&&holder.signalCode===null){const exited=once(holder,'exit');holder.kill();await exited;}}
 const name=readdirSync(f.policy.outputRoot).find(n=>n.startsWith('daily-')),job=path.join(f.policy.outputRoot,name),bindingPath=path.join(job,'portable-binding.json');
 renameSync(keys,path.join(f.root,'unavailable-dpapi')); // Any old DPAPI path lookup now fails.
 const r=call({Operation:'RestorePortable',EnvelopePath:envelopePath,EnvelopeSha256:hash(readFileSync(envelopePath)),BindingPath:bindingPath,BindingSha256:hash(readFileSync(bindingPath)),ArtifactPath:path.join(job,'artifact/runtime.aes256gcm'),OutputDirectory:path.join(f.root,'portable-restored')});
 assert.equal(r.passwordOnly,true);assert.equal(r.dpapiUsed,false);assert.equal(r.deniedRoutes.length,5);assert.equal(r.databaseBytesUnchanged,true);
});
