import 'package:flutter_test/flutter_test.dart';
import 'package:memex/domain/whiteboard/video/video_domain.dart';

/// Fake transport: serves canned payloads per URL, or fails on demand.
class _FakeTransport implements TimedTextTransport {
  final Map<String, String> responses;
  final String? failure;
  int calls = 0;

  _FakeTransport({this.responses = const {}, this.failure});

  @override
  Future<String?> getText(String url, {Map<String, String>? headers}) async {
    calls++;
    if (failure != null) return null;
    return responses[url];
  }
}

/// A watch page with two caption tracks (zh manual + en asr).
const _watchPageWithCaptions = '''
<script>var ytInitialPlayerResponse = {
  "captions": {
    "playerCaptionsTracklistRenderer": {
      "captionTracks": [
        {
          "baseUrl": "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ\\u0026lang=zh-Hans\\u0026signature=abc123",
          "name": {"simpleText": "中文（简体）"},
          "languageCode": "zh-Hans",
          "trackName": ""
        },
        {
          "baseUrl": "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ\\u0026lang=en\\u0026signature=def456",
          "name": {"simpleText": "English"},
          "languageCode": "en",
          "kind": "asr",
          "trackName": ""
        }
      ]
    }
  }
};</script>
''';

/// A watch page without any captions (bot-blocked or no captions).
const _watchPageNoCaptions =
    '<script>var ytInitialPlayerResponse = {"playabilityStatus":{}};</script>';

/// A JSON3 payload with multi-segment lines and a missing duration.
const _json3Payload = '''
{"wireMagic":"pb3","events":[
  {"tStartMs":2000,"dDurationMs":3000,"segs":[{"utf8":"灯光切换，夜场开始"}]},
  {"tStartMs":6000,"dDurationMs":3500,"segs":[{"utf8":"舞台中央升起烟雾"}]},
  {"tStartMs":10000,"dDurationMs":4000,"segs":[{"utf8":"第一段副歌"},{"tOffsetMs":2000,"utf8":"灯光随节拍变化"}]},
  {"tStartMs":15000,"segs":[{"utf8":"鼓点加强"}]}
]}
''';

void main() {
  const watchUrl = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
  const embedUrl = 'https://www.youtube.com/embed/dQw4w9WgXcQ';

  group('YouTubeTimedTextService.extractVideoId', () {
    final service = YouTubeTimedTextService(transport: _FakeTransport());

    test('accepts a raw 11-char video id', () {
      expect(service.extractVideoId('dQw4w9WgXcQ'), equals('dQw4w9WgXcQ'));
    });

    test('extracts from watch URLs', () {
      expect(
          service.extractVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
          equals('dQw4w9WgXcQ'));
      expect(
          service.extractVideoId(
              'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=42'),
          equals('dQw4w9WgXcQ'));
    });

    test('extracts from youtu.be, embed, and shorts URLs', () {
      expect(service.extractVideoId('https://youtu.be/dQw4w9WgXcQ'),
          equals('dQw4w9WgXcQ'));
      expect(
          service.extractVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ'),
          equals('dQw4w9WgXcQ'));
      expect(
        service.extractVideoId(
          'https://www.youtube.com/shorts/dQw4w9WgXcQ?si=share',
        ),
        equals('dQw4w9WgXcQ'),
      );
    });

    test('rejects non-YouTube references', () {
      expect(service.extractVideoId('https://example.com/video/123'), isNull);
      expect(service.extractVideoId(null), isNull);
      expect(service.extractVideoId(''), isNull);
    });
  });

  group('parseTrackList', () {
    final service = YouTubeTimedTextService(transport: _FakeTransport());

    test('parses caption tracks from the watch page', () {
      final tracks = service.parseTrackList(_watchPageWithCaptions);
      expect(tracks, isNotNull);
      expect(tracks!.length, equals(2));
      expect(tracks[0].languageCode, equals('zh-Hans'));
      expect(tracks[0].displayName, equals('中文（简体）'));
      expect(tracks[0].baseUrl, contains('lang=zh-Hans'));
      expect(tracks[0].isAutoGenerated, isFalse);
      expect(tracks[1].languageCode, equals('en'));
      expect(tracks[1].isAutoGenerated, isTrue, reason: 'kind=asr');
    });

    test('returns null when the page has no captions', () {
      expect(service.parseTrackList(_watchPageNoCaptions), isNull);
    });

    test('returns null on non-HTML input', () {
      expect(service.parseTrackList(''), isNull);
    });
  });

  group('parseJson3', () {
    final service = YouTubeTimedTextService(transport: _FakeTransport());

    test('parses events into cues with durations', () {
      final cues = service.parseJson3(_json3Payload, language: 'zh');
      expect(cues.length, equals(4));
      expect(cues[0].cueId, equals('cue_zh_1'));
      expect(cues[0].startMs, equals(2000));
      expect(cues[0].endMs, equals(5000));
      expect(cues[0].text, equals('灯光切换，夜场开始'));
    });

    test('multi-segment cues join with a line break', () {
      final cues = service.parseJson3(_json3Payload, language: 'zh');
      expect(cues[2].text, equals('第一段副歌\n灯光随节拍变化'));
      expect(cues[2].endMs, equals(14000));
    });

    test('missing duration falls back to the next cue start', () {
      final cues = service.parseJson3(_json3Payload, language: 'zh');
      expect(cues[3].startMs, equals(15000));
      expect(cues[3].endMs, equals(17000),
          reason: 'next cue start; last cue +2s');
    });

    test('returns empty on malformed payload', () {
      expect(service.parseJson3('not json', language: 'en'), isEmpty);
      expect(service.parseJson3('{"events":42}', language: 'en'), isEmpty);
    });
  });

  group('fetchForVideo', () {
    test('loads a usable platform track for the preferred language', () async {
      final transport = _FakeTransport(responses: {
        watchUrl: _watchPageWithCaptions,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=zh-Hans&signature=abc123&fmt=json3': _json3Payload,
      });
      final service = YouTubeTimedTextService(
        transport: transport,
        preferredLanguage: 'zh',
      );
      final result = await service.fetchForVideo(
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
        sourceVersionId: 'ver_yt_v1',
      );
      expect(result.isSuccess, isTrue);
      expect(result.availableTracks, hasLength(2));
      expect(result.selectedTrack?.languageCode, 'zh-Hans');
      final track = result.track!;
      expect(track.sourceId, equals('src_yt_test'));
      expect(track.sourceKind, equals(TimedTextSourceKind.platform));
      expect(track.language, equals('zh-Hans'));
      expect(track.format, equals('json3'));
      expect(track.reliability, equals(TimedTextReliability.reliable),
          reason: 'manual captions are reliable; asr would be partial');
      expect(track.cues.length, equals(4));
      expect(track.cues.first.text, contains('灯光切换'));
    });

    test('picks English as fallback and marks ASR tracks partial', () async {
      final transport = _FakeTransport(responses: {
        watchUrl: _watchPageWithCaptions,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=en&signature=def456&fmt=json3': _json3Payload,
      });
      final service = YouTubeTimedTextService(
        transport: transport,
        preferredLanguage: 'ja', // not available → English fallback
      );
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isTrue);
      expect(result.track!.language, equals('en'));
      expect(result.track!.reliability, equals(TimedTextReliability.partial));
    });

    test('falls back to the embed page when the watch page is blocked',
        () async {
      final transport = _FakeTransport(responses: {
        watchUrl: '', // bot-block: empty body
        embedUrl: _watchPageWithCaptions,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=zh-Hans&signature=abc123&fmt=json3': _json3Payload,
      });
      final service = YouTubeTimedTextService(transport: transport);
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isTrue);
      expect(transport.calls, greaterThanOrEqualTo(2));
    });

    test('honest failure: no captions → error, no fabricated track', () async {
      final transport = _FakeTransport(responses: {
        watchUrl: _watchPageNoCaptions,
        embedUrl: _watchPageNoCaptions,
      });
      final service = YouTubeTimedTextService(transport: transport);
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isFalse);
      expect(result.track, isNull);
      expect(result.failureKind, YouTubeTimedTextFailureKind.noTrack);
      expect(result.error, contains('无字幕轨'));
    });

    test('honest failure: transport blocked (network / CORS) → error result',
        () async {
      final service = YouTubeTimedTextService(
        transport: _FakeTransport(failure: 'network down'),
      );
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isFalse);
      expect(result.track, isNull);
      expect(result.failureKind, YouTubeTimedTextFailureKind.network);
      expect(result.error, contains('网络失败'));
    });

    test('honest failure: unrecognizable video reference', () async {
      final service = YouTubeTimedTextService(transport: _FakeTransport());
      final result = await service.fetchForVideo(
        'https://example.com/x',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isFalse);
      expect(result.error, contains('无法识别'));
      expect(result.failureKind, YouTubeTimedTextFailureKind.invalidVideo);
    });

    test('honest failure: empty track content', () async {
      final transport = _FakeTransport(responses: {
        watchUrl: _watchPageWithCaptions,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=zh-Hans&signature=abc123&fmt=json3': '{"events":[]}',
      });
      final service = YouTubeTimedTextService(transport: transport);
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(result.isSuccess, isFalse);
      expect(result.track, isNull);
      expect(result.failureKind, YouTubeTimedTextFailureKind.parserFailure);
      expect(result.error, contains('解析器失效'));
    });

    test('discovers multiple CC tracks and loads an explicit selection',
        () async {
      final transport = _FakeTransport(responses: {
        watchUrl: _watchPageWithCaptions,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=zh-Hans&signature=abc123&fmt=json3': _json3Payload,
        'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ'
            '&lang=en&signature=def456&fmt=json3': _json3Payload,
      });
      final service = YouTubeTimedTextService(transport: transport);
      final initial = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(initial.availableTracks.map((track) => track.languageCode),
          ['zh-Hans', 'en']);

      final english = initial.availableTracks.last;
      final switched = await service.fetchTrack(
        english,
        sourceId: 'src_yt_test',
        availableTracks: initial.availableTracks,
      );
      expect(switched.isSuccess, isTrue);
      expect(switched.track!.language, 'en');
      expect(switched.track!.reliability, TimedTextReliability.partial);
      expect(switched.selectedTrack, same(english));
    });

    test('classifies region or permission restrictions separately', () async {
      const restricted = '''
        <script>var ytInitialPlayerResponse = {
          "playabilityStatus":{"status":"LOGIN_REQUIRED",
          "reason":"Sign in to confirm your age"}
        };</script>
      ''';
      final service = YouTubeTimedTextService(
        transport: _FakeTransport(responses: {
          watchUrl: restricted,
          embedUrl: restricted,
        }),
      );
      final result = await service.fetchForVideo(
        'dQw4w9WgXcQ',
        sourceId: 'src_yt_test',
      );
      expect(
        result.failureKind,
        YouTubeTimedTextFailureKind.accessRestricted,
      );
      expect(result.error, contains('地区或权限限制'));
    });
  });

  group('HttpTimedTextTransport', () {
    test('returns null on non-200 without throwing', () async {
      final transport = HttpTimedTextTransport(
        timeout: const Duration(milliseconds: 200),
      );
      final text = await transport.getText('http://127.0.0.1:1/nope');
      expect(text, isNull);
      transport.dispose();
    });
  });
}
